### ISSUE TITLE
Experiments folder

### ISSUE THREAD

**Issue by mkocabas** [xingyizhou/CenterNet#1]
Hi,

Thanks for the excellent paper and the code.

It seems you omit to upload the `experiments` folder indicated in [readme](https://github.com/xingyizhou/CenterNet#benchmark-evaluation-and-training). Could you upload it?

As a minor correction, the `multi_hp` argument in [this section](https://github.com/xingyizhou/CenterNet#use-centernet) of the readme should be corrected as `multi_pose`.

Best,

**Comment by xingyizhou** [comment]
Thanks! I have uploaded the folder and fixed the typo. Sorry for the inconvenience.

**Comment by mkocabas** [comment]
Great!
