### ISSUE TITLE
Google drive link for pretrained models

### ISSUE THREAD

**Issue by changkk** [xingyizhou/CenterNet#1014]
Hi team, thanks for the awesome work!

Just trying to get pretrained models to run and test the model, but seems like the Google Drive link is not available anymore. Do you guys still provide the pretrained models? If you do, can I get the new link to the models?

Thanks in advance!

**Comment by xingyizhou** [comment]
Hi,

  Sorry for the inconvenience. I updated the model links and they should be working now.

Best,
Xingyi

**Comment by changkk** [comment]
Confirmed it's working. Thank you!
