### ISSUE TITLE
test error on my own dataset 

### ISSUE THREAD

**Issue by shenghsiaowong** [xingyizhou/CenterNet#102]
my dataset is pascal voc format,but when i finish training and test my testdataset,in same testdataset  and i got different result ,sometime map is 0.8 ,sometime map is0.00,when i changeed overthresh ,and the map is same.

**Comment by xingyizhou** [comment]
You can visualize your output by `--debug 2`. I am not able to debug without more detailed information.

**Comment by shenghsiaowong** [comment]
thank  you i have already solved it

**Comment by yudehai1** [comment]
How do you train？I don't understand what he wrote.

**Comment by Eyren** [comment]
> thank you i have already solved it

Hi,may i ask what did you do to solve it?I've met the same issue.Thanks.
