### ISSUE TITLE
It seems that in DLA-34 implementation, the feature map of stride 32 is not used for directly upsampling to stride 4 as stated in paper?

### ISSUE THREAD

**Issue by kalyo-zjl** [xingyizhou/CenterNet#103]
Hi, thanks for sharing the code.
I have a little confused about the implementation of DLA-34 network.
In file pose_dla_dcn.py line 488-490
        for i in range(self.last_level - self.first_level):
            y.append(x[i].clone())
        self.ida_up(y, 0, len(y))
since last_level is 5 and first_level is 2, len(y) is 3 rather than 4.
Is there anything wrong?

**Comment by xingyizhou** [comment]
@DequanWang can you check this?

**Comment by djshen** [comment]
According to Figure 6 (d) in your paper, there should be 9 `ConvTranspose2d` (upsampling) in the model.
But after running the demo code with this command
```
python demo.py ctdet --demo ../images/ --load_model ../../test/convert_model/centernet/ctdet_coco_dla_2x.pth
```
, I only got 8 `ConvTranspose2d`.

**Comment by xingyizhou** [comment]
Thanks for pointing out the issue. You are right, the figure is indeed wrong. We will revise the figure in the revision.
