### ISSUE TITLE
download_pascal_voc.sh

### ISSUE THREAD

**Issue by zhangxydlut** [xingyizhou/CenterNet#111]
I don't find download_pascal_voc.sh. In fact, there is no folder named 'tools'.

**Comment by zhangxydlut** [comment]
Sorry, it's my fault

**Comment by arlensung** [comment]
> Sorry, it's my fault

Could you tell me where is the folder 'tools'

**Comment by chensonglu** [comment]
@arlensung src/tools/get_pascal_voc.sh
