### ISSUE TITLE
ConvTranspose2d to coreml

### ISSUE THREAD

**Issue by cwjhx** [xingyizhou/CenterNet#113]
使用https://github.com/xxradon/PytorchToCaffe把centernet模型转换成caffe，再把caffe模型转换成coreml时反卷积出错：
 File "/home/../coremltools/converters/caffe/_caffe_converter.py", line 255, in _export
    predicted_feature_name)
RuntimeError: Caffe model error in layer 'conv_transpose1' of type 'Deconvolution': 'num_output' (256) divided by groups (1does not match the first dimension of weights (1).

**Comment by xingyizhou** [comment]
I am not able to provide help on other frameworks.

**Comment by zoufangyu1987** [comment]
@cwjhx 我和你一样的错，你找到解决办法了吗？
I'm as wrong as you are. Have you found a solution?

**Comment by zoufangyu1987** [comment]
@cwjhx 
我已经解决这个问题，把https://github.com/xxradon/PytorchToCaffe里的pytorch_to_caffe.py的121行：
pad=_pair(padding),dilation=_pair(dilation),bias_term=bias is not None)
修改为：
pad=_pair(padding),dilation=_pair(dilation),bias_term=bias is not None,groups=groups)
反卷积层转的时候少了groups参数
