### ISSUE TITLE
RuntimeError: start (0) + length (15) exceeds dimension size (4)

### ISSUE THREAD

**Issue by jerrynije** [xingyizhou/CenterNet#115]
description:
When i run the command below,the problems occur if i use multi-gpus.However,if i run on 1 gpu,it works fine.
dataset:2types('hard','simple')
Command Run:
python main.py ctdet --exp_id coco_dla --batch_size 4 --master_batch 15 --lr 1.25e-4  --gpus 0,7
Problem:
Multi-GPUs:bad result
/home/jie/local/anaconda/lib/python3.5/site-packages/numba/errors.py:102: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
Fix size testing.
training chunk_sizes: [15, -11]
The output will be saved to  /home/jie/temp/CenterNet/src/lib/../../exp/ctdet/coco_dla
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
good
Setting up data...
==> initializing coco 2017 val data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded val 912 samples
==> initializing coco 2017 train data.
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
Loaded train 8207 samples
Starting training...
ctdet/coco_dlaTraceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/jie/temp/CenterNet/src/lib/trains/base_trainer.py", line 121, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/jie/temp/CenterNet/src/lib/trains/base_trainer.py", line 70, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/home/jie/local/anaconda/lib/python3.5/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jie/temp/CenterNet/src/lib/models/data_parallel.py", line 67, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids, self.chunk_sizes)
  File "/home/jie/temp/CenterNet/src/lib/models/data_parallel.py", line 78, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim, chunk_sizes=self.chunk_sizes)
  File "/home/jie/temp/CenterNet/src/lib/models/scatter_gather.py", line 30, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim, chunk_sizes) if inputs else []
  File "/home/jie/temp/CenterNet/src/lib/models/scatter_gather.py", line 25, in scatter
    return scatter_map(inputs)
  File "/home/jie/temp/CenterNet/src/lib/models/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/jie/temp/CenterNet/src/lib/models/scatter_gather.py", line 22, in scatter_map
    return list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/home/jie/temp/CenterNet/src/lib/models/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/jie/temp/CenterNet/src/lib/models/scatter_gather.py", line 15, in scatter_map
    return Scatter.apply(target_gpus, chunk_sizes, dim, obj)
  File "/home/jie/local/anaconda/lib/python3.5/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/jie/local/anaconda/lib/python3.5/site-packages/torch/cuda/comm.py", line 147, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: start (0) + length (15) exceeds dimension size (4). (narrow at /pytorch/aten/src/ATen/native/TensorShape.cpp:375)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f0efc94b441 in /home/jie/local/anaconda/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f0efc94ad7a in /home/jie/local/anaconda/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #2: at::native::narrow(at::Tensor const&, long, long, long) + 0x1d1 (0x7f0e5c6b6b21 in /home/jie/local/anaconda/lib/python3.5/site-packages/torch/lib/libcaffe2.so)
frame #3: at::TypeDefault::narrow(at::Tensor const&, long, long, long) const + 0x15 (0x7f0e5c9155e5 in /home/lijie/local/anaconda/lib/python3.5/site-packages/torch/lib/libcaffe2.so)
frame #4: torch::autograd::VariableType::narrow(at::Tensor const&, long, long, long) const + 0x2b8 (0x7f0e5aa970c8 in /home/lijie/local/anaconda/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #5: torch::cuda::scatter(at::Tensor const&, c10::ArrayRef<long>, c10::optional<std::vector<long, std::allocator<long> > > const&, long, c10::optional<std::vector<c10::optional<c10::cuda::CUDAStream>, std::allocator<c10::optional<c10::cuda::CUDAStream> > > > const&) + 0x14b (0x7f0e5b264d9b in /home/jie/local/anaconda/lib/python3.5/site-packages/torch/lib/libtorch.so.1)
frame #6: <unknown function> + 0x5a28ef (0x7f0efd31d8ef in /home/jie/local/anaconda/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x130d0c (0x7f0efceabd0c in /home/jie/local/anaconda/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #15: THPFunction_apply(_object*, _object*) + 0x6b1 (0x7f0efd12e491 in /home/jie/local/anaconda/lib/python3.5/site-packages/torch/lib/libtorch_python.so)

Single-GPU:works fine
ctdet/coco_resdcn18 |#####################           | train: [6][171/256]|Tot: 0:07:09 |ETA: 0:03:34 |loss 1.4366 |hm_loss 0.7522 |wh_loss 4.4351 |off_loss 0.2409 |Data 0ctdet/coco_resdcn18 |#####################           | train: [6][172/256]|Tot: 0:07:13 |ETA: 0:03:31 |loss 1.4373 |hm_loss 0.7527 |wh_loss 4.4351 |off_loss 0.2411 |Data 0ctdet/coco_resdcn18 |#####################           | train: [6][173/256]|Tot: 0:07:14 |ETA: 0:03:34 |loss 1.4360 |hm_loss 0.7519 |wh_loss 4.4308 |off_loss 0.2410 |Data 0ctdet/coco_resdcn18 |#####################           | train: [6][174/256]|Tot: 0:07:19 |ETA: 0:03:31 |loss 1.4364 |hm_loss 0.7514 |wh_loss 4.4392 |off_loss 0.2411 |Data 0ctdet/coco_resdcn18 |######################          | train: [6][175/256]|Tot: 0:07:19 |ETA: 0:03:28 |loss 1.4350 |hm_loss 0.7507 |wh_loss 4.4351 |off_loss 0.2408 |Data 0ctdet/coco_resdcn18 |######################          | train: [6][176/256]|Tot: 0:07:24 |ETA: 0:03:26 |loss 1.4372 |hm_loss 0.7528 |wh_loss 4.4381 |off_loss 0.2407 |Data 0ctdet/coco_resdcn18 |######################          | train: [6][177/256]|Tot: 0:07:25 |ETA: 0:03:24 |loss 1.4363 |hm_loss 0.7523 |wh_loss 4.4353 |off_loss 0.2405 |Data 0
ctdet/coco_resdcn18 |######################          | train: [6][178/256]|Tot: 0:07:29 |ETA: 0:03:21 |loss 1.4361 |hm_loss 0.7520 |wh_loss 4.4376 |off_loss 0.2404 |Data 0
ctdet/coco_resdcn18 |######################          | train: [6][179/256]|Tot: 0:07:30 |ETA: 0:03:22 |loss 1.4345 |hm_loss 0.7509 |wh_loss 4.4335 |off_loss 0.2402 |Data 0
ctdet/coco_resdcn18 |######################          | train: [6][180/256]|Tot: 0:07:34 |ETA: 0:03:19 |loss 1.4325 |hm_loss 0.7489 |wh_loss 4.4334 |off_loss 0.2403 |Data 0
ctdet/coco_resdcn18 |######################          | train: [6][181/256]|Tot: 0:07:35 |ETA: 0:03:17 |loss 1.4305 |hm_loss 0.7471 |wh_loss 4.4310 |off_loss 0.2403 |Data 0
ctdet/coco_resdcn18 |######################          | train: [6][182/256]|Tot: 0:07:40 |ETA: 0:03:15 |loss 1.4307 |hm_loss 0.7472 |wh_loss 4.4323 |off_loss 0.2402 |Data 0
ctdet/coco_resdcn18 |#######################         | train: [6][183/256]|Tot: 0:07:40 |ETA: 0:03:12 |loss 1.4301 |hm_loss 0.7469 |wh_loss 4.4307 |off_loss 0.2402 |Data 0
ctdet/coco_resdcn18 |#######################         | train: [6][184/256]|Tot: 0:07:45 |ETA: 0:03:10 |loss 1.4298 |hm_loss 0.7467 |wh_loss 4.4307 |off_loss 0.2401 |Data 0
ctdet/coco_resdcn18 |#######################         | train: [6][185/256]|Tot: 0:07:46 |ETA: 0:03:07 |loss 1.4300 |hm_loss 0.7469 |wh_loss 4.4296 |off_loss 0.2402 |Data 0
ctdet/coco_resdcn18 |#######################         | train: [6][186/256]|Tot: 0:07:50 |ETA: 0:03:04 |loss 1.4299 |hm_loss 0.7464 |wh_loss 4.4337 |off_loss 0.2401 |Data 0
ctdet/coco_resdcn18 |#######################         | train: [6][187/256]|Tot: 0:07:51 |ETA: 0:03:01 |loss 1.4289 |hm_loss 0.7458 |wh_loss 4.4313 |off_loss 0.2400 |Data 0
ctdet/coco_resdcn18 |#######################         | train: [6][188/256]|Tot: 0:07:55 |ETA: 0:02:59 |loss 1.4291 |hm_loss 0.7460 |wh_loss 4.4309 |off_loss 0.2400 |Data 0
ctdet/coco_resdcn18 |#######################         | train: [6][189/256]|Tot: 0:07:56 |ETA: 0:02:57 |loss 1.4280 |hm_loss 0.7458 |wh_loss 4.4238 |off_loss 0.2399 |Data 0
ctdet/coco_resdcn18 |#######################         | train: [6][190/256]|Tot: 0:08:01 |ETA: 0:02:54 |loss 1.4282 |hm_loss 0.7458 |wh_loss 4.4257 |off_loss 0.2398 |Data 0
ctdet/coco_resdcn18 |########################        | train: [6][191/256]|Tot: 0:08:01 |ETA: 0:02:52 |loss 1.4269 |hm_loss 0.7444 |wh_loss 4.4264 |off_loss 0.2398 |Data 0
ctdet/coco_resdcn18 |########################        | train: [6][192/256]|Tot: 0:08:06 |ETA: 0:02:49 |loss 1.4272 |hm_loss 0.7445 |wh_loss 4.4274 |off_loss 0.2399 |Data 0
ctdet/coco_resdcn18 |########################        | train: [6][193/256]|Tot: 0:08:07 |ETA: 0:02:46 |loss 1.4296 |hm_loss 0.7468 |wh_loss 4.4291 |off_loss 0.2399 |Data 0
ctdet/coco_resdcn18 |########################        | train: [6][194/256]|Tot: 0:08:07 |ETA: 0:02:44 |loss 1.4288 |hm_loss 0.7457 |wh_loss 4.4317 |off_loss 0.2399 |Data 0
ctdet/coco_resdcn18 |########################        | train: [6][195/256]|Tot: 0:08:11 |ETA: 0:02:17 |loss 1.4278 |hm_loss 0.7447 |wh_loss 4.4324 |off_loss 0.2398 |Data 0
ctdet/coco_resdcn18 |########################        | train: [6][196/256]|Tot: 0:08:12 |ETA: 0:02:36 |loss 1.4274 |hm_loss 0.7444 |wh_loss 4.4316 |off_loss 0.2399 |Data 0
ctdet/coco_resdcn18 |########################        | train: [6][197/256]|Tot: 0:08:13 |ETA: 0:02:33 |loss 1.4276 |hm_loss 0.7440 |wh_loss 4.4386 |off_loss 0.2398 |Data 0
ctdet/coco_resdcn18 |########################        | train: [6][198/256]|Tot: 0:08:17 |ETA: 0:02:08 |loss 1.4295 |hm_loss 0.7452 |wh_loss 4.4452 |off_loss 0.2398 |Data 0
ctdet/coco_resdcn18 |#########################       | train: [6][199/256]|Tot: 0:08:17 |ETA: 0:02:02 |loss 1.4292 |hm_loss 0.7446 |wh_loss 4.4461 |off_loss 0.2400 |Data 0
ctdet/coco_resdcn18 |#########################       | train: [6][200/256]|Tot: 0:08:22 |ETA: 0:02:00 |loss 1.4291 |hm_loss 0.7442 |wh_loss 4.4492 |off_loss 0.2399 |Data 0
ctdet/coco_resdcn18 |#########################       | train: [6][201/256]|Tot: 0:08:23 |ETA: 0:01:58 |loss 1.4286 |hm_loss 0.7436 |wh_loss 4.4488 |off_loss 0.2401 |Data 0
ctdet/coco_resdcn18 |#########################       | train: [6][202/256]|Tot: 0:08:23 |ETA: 0:01:56 |loss 1.4300 |hm_loss 0.7445 |wh_loss 4.4529 |off_loss 0.2402 |Data 0
ctdet/coco_resdcn18 |#########################       | train: [6][203/256]|Tot: 0:08:27 |ETA: 0:01:32 |loss 1.4294 |hm_loss 0.7439 |wh_loss 4.4532 |off_loss 0.2402 |Data 0

**Comment by xingyizhou** [comment]
`master_batch` is the batch size in the first GPU, it should be less than the total batch size.

**Comment by qiuhaining** [comment]
> `master_batch` is the batch size in the first GPU, it should be less than the total batch size.

where is the 'master_batch', i just found the “master_batch_size”
