### ISSUE TITLE
a coding mistake

### ISSUE THREAD

**Issue by fenglv12345** [xingyizhou/CenterNet#116]
mistake as below
https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/image.py
def gaussian_radius(det_size, min_overlap=0.7):

  height, width = det_size

  a1  = 1

  b1  = (height + width)

  c1  = width * height * (1 - min_overlap) / (1 + min_overlap)

  sq1 = np.sqrt(b1 ** 2 - 4 * a1 * c1)

  r1  = (b1 + sq1) / 2

  a2  = 4

  b2  = 2 * (height + width)

  c2  = (1 - min_overlap) * width * height

  sq2 = np.sqrt(b2 ** 2 - 4 * a2 * c2)

  r2  = (b2 + sq2) / 2

  a3  = 4 * min_overlap

  b3  = -2 * min_overlap * (height + width)

  c3  = (min_overlap - 1) * width * height

  sq3 = np.sqrt(b3 ** 2 - 4 * a3 * c3)

  r3  = (b3 + sq3) / 2

  return min(r1, r2, r3)

And the correct one
please reference to the
https://github.com/princeton-vl/CornerNet/blob/master/sample/utils.py
like this
def gaussian_radius(det_size, min_overlap):
height, width = det_size

a1  = 1

b1  = (height + width)

c1  = width * height * (1 - min_overlap) / (1 + min_overlap)

sq1 = np.sqrt(b1 ** 2 - 4 * a1 * c1)

r1  = (b1 - sq1) / (2 * a1)

a2  = 4

b2  = 2 * (height + width)

c2  = (1 - min_overlap) * width * height

sq2 = np.sqrt(b2 ** 2 - 4 * a2 * c2)

r2  = (b2 - sq2) / (2 * a2)

a3  = 4 * min_overlap

b3  = -2 * min_overlap * (height + width)

c3  = (min_overlap - 1) * width * height

sq3 = np.sqrt(b3 ** 2 - 4 * a3 * c3)

r3  = (b3 + sq3) / (2 * a3)

return min(r1, r2, r3)
so i hope you can give you Mathematical formula derivation in the readme.md
because which is not same with mine

**Comment by fenglv12345** [comment]
my mathmatical formulas as below
https://github.com/princeton-vl/CornerNet/issues/110

**Comment by xingyizhou** [comment]
Thanks, we will try this in the future.
