### ISSUE TITLE
Difference between main.py --test and test.py

### ISSUE THREAD

**Issue by bsvineethiitg** [xingyizhou/CenterNet#117]
Hi. What is the fundamental difference between running test through 

main.py --test

versus 

test.py with/without _not_prefetch_test flag?

Thanks!

**Comment by xingyizhou** [comment]
No difference. But main.py does not support `--flip_test`, `--keep_res` or `--test_scale`.

**Comment by sisrfeng** [comment]
main.py --test:
can only run on 'val' split.

 test.py:
run on 'val' or 'test' split.

**Comment by sisrfeng** [comment]
On my dataset, the AP50 is 68 using `main.py --test`
but 80 `using test.py `of the same model (dla_2x)
