### ISSUE TITLE
When I train my own dataset，map@0.5 and map@0.75 makes me confused

### ISSUE THREAD

**Issue by shenghsiaowong** [xingyizhou/CenterNet#123]
hi ，xingyi，sorry to bother you，When I train my own dataset（class_num=1），i use different backbones,the result as follows
 (1)hourglass get map@0.5=90.7%,map@0.75=73%,
 (2)DLA get map@0.5=90.5%,map@0.75=72%,
 (3)resnet-101 map@0.5=88.7%，map@0.75=33.1%,
 (4)resnet-18 map@0.5 =89.9%.map@0.75=34.2%,
Q1: why when i use resnet ,the map@0.75 drop so much(the hg and dla is almost 73%,but resnet is only 33%)?
Q2:why resnet18 performed excellent than resnet-101？
best wishes to you@xingyizhou

**Comment by shenghsiaowong** [comment]
@xingyizhou

**Comment by xingyizhou** [comment]
1. I have no idea about this. You can try resdcn to see if deformable layers are the major cause. 
2. Possibly due to your dataset is small or due to randomness in training.

**Comment by shenghsiaowong** [comment]
@xingyizhou  thank you for your answer!!

**Comment by leavewave** [comment]
hello, when you use the resnet as the backbone, what you change in the code? i only change the --arch for resnet18,it tested as ap=0, could you help me ,thanks....
