### ISSUE TITLE
WHY the performance of the model you provided is not equal to the value in the table

### ISSUE THREAD

**Issue by 20143698lhy** [xingyizhou/CenterNet#128]
the map is 77.1% the the table 
but 
the map is 0.7537 I use 'ctdet_pascal_resdcn101_384.pth' and your test.py you provided .
Plus, the map is 75.38% when I trained myself if the random_seed is the default 317. 
I changed the seed and the answer is far from 77.
77 is a random answer ? Thanks

**Comment by xingyizhou** [comment]
Because you haven't added `--flip_test` when running your test.
