### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by westpilgrim** [xingyizhou/CenterNet#129]
I have successfully trained 5 epochs, but at the end of the 5th epoch, I got the following error:

File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

the error is the same with the issue:https://github.com/xingyizhou/CenterNet/issues/70, but that happened at the inference time.

how can I solve this?

**Comment by xingyizhou** [comment]
You can set `--val_intervals 100000` to skip validation ...

**Comment by Ridhwanluthra** [comment]
It's probably due to change in memory requirements or some other program using the memory. It is most probably not a bug with either centernet or pytorch

**Comment by westpilgrim** [comment]
> You can set `--val_intervals 100000` to skip validation ...

thank you !I successfully trained the model according to your method. but I still cannot test my model, my test batch shape is (1,3,512,512),but the same error occurs when forwarding

**Comment by xingyizhou** [comment]
I haven't met that. Can you provide a minimal script that can reproduce this?

**Comment by westpilgrim** [comment]
solved this simply by adding gpu memory to 8g
