### ISSUE TITLE
why the draw_umich_gaussian return heaymap whic is all zeros.

### ISSUE THREAD

**Issue by VCBE123** [xingyizhou/CenterNet#130]
https://github.com/xingyizhou/CenterNet/blob/b328816ecf16c65ee43ba14c6edd2a6e8dcdacff/src/lib/utils/image.py#L126:L141

**Comment by xingyizhou** [comment]
It is not. You can visualize it by `--debug 2`.

**Comment by allenfutaki** [comment]
https://github.com/xingyizhou/CenterNet/blob/b328816ecf16c65ee43ba14c6edd2a6e8dcdacff/src/lib/datasets/sample/ctdet.py#L117

According the usage of draw_gaussian, the parameter is the selection of heatmap which is the copy of heatmap then it does not make any change in place. 

Therefore, nothing change in heatmap .............

**Comment by Shawnnnnn** [comment]
@allenfutaki hello, I print hm and find it always zeros. I'm confused how them to train and calculate loss. But it works and can detect objects...

**Comment by allenfutaki** [comment]
@Shawnnnnn , the comment i made is wrong, it does run correctly.

**Comment by Shawnnnnn** [comment]
@allenfutaki can you tell me how it process heatmap and where is that in code? thank u very much!

**Comment by allenfutaki** [comment]
@Shawnnnnn maybe you can trace the code from this 
https://github.com/xingyizhou/CenterNet/blob/master/src/lib/trains/ctdet.py#L49

**Comment by Shawnnnnn** [comment]
@allenfutaki I found batch[‘hm’] is not all zeros, but in src/lib/datasets/sample/ctdet.py I didn't find heatmap changed since it defined...

**Comment by Shawnnnnn** [comment]
@allenfutaki ok, I found that code to change heatmap：
`if min(masked_gaussian.shape) > 0 and min(masked_heatmap.shape) > 0: # TODO debug
     np.maximum(masked_heatmap, masked_gaussian * k, out=masked_heatmap)`
thank you!

**Comment by Man-go008** [comment]
@Shawnnnnn excuse me ,If I want to output a heatmap after Gaussian function，where can I change the code?

**Comment by NinelM** [comment]
I also have this problem, and I think that's the problem，`hmap = np.zeros((self.num_classes, self.fmap_size['h'], self.fmap_size['w']), dtype=np.float32)  # heatmap` ，Hmap is a three-dimensional array，` draw_umich_gaussian(hmap[label], obj_c_int, radius)` ，In this case, Heatmap will extract a two-dimensional array of labels from the first dimension。`def draw_umich_gaussian(heatmap, center, radius, k=1):
  diameter = 2 * radius + 1
  gaussian = gaussian2D((diameter, diameter), sigma=diameter / 6)

  x, y = int(center[0]), int(center[1])

  height, width = heatmap.shape[0:2]

  left, right = min(x, radius), min(width - x, radius + 1)
  top, bottom = min(y, radius), min(height - y, radius + 1)

  masked_heatmap = heatmap[y - top:y + bottom, x - left:x + right]
  masked_gaussian = gaussian[radius - top:radius + bottom, radius - left:radius + right]
  if min(masked_gaussian.shape) > 0 and min(masked_heatmap.shape) > 0:  # TODO debug
    np.maximum(masked_heatmap, masked_gaussian * k, out=masked_heatmap)
  return heatmap`  When the code jumps here, Heatmap should also be a two-dimensional array, but what I get here is a three-dimensional array, so the subsequent slicing operation fails and masked is obtained_ Heatmap is empty。

**Comment by Juphex** [comment]
> @allenfutaki ok, I found that code to change heatmap： `if min(masked_gaussian.shape) > 0 and min(masked_heatmap.shape) > 0: # TODO debug np.maximum(masked_heatmap, masked_gaussian * k, out=masked_heatmap)` thank you!

This code should work. However, call-by-reference doesn't work in my case.
Python 3.8.10 and numpy                          1.22.0 .
Just in case anyone encounters the problem that the heatmap is all zero, I assigned the heatmap like this:
`hm[cls_id] = draw_gaussian(hm[cls_id], ct_int, radius)`
