### ISSUE TITLE
change Installation process and versions

### ISSUE THREAD

**Issue by Ridhwanluthra** [xingyizhou/CenterNet#132]
I setup the package with PyTorch 1.1.0 and the only thing that I needed to do to get it working is get the latest version of DCNv2 from their repo.

I did not test multi-scale and extremenet yet but everything else seems to work fine with no challenges, there was just 1 warning about a function which will soon be deprecated. 
Maybe it would be a good idea to convert DCNv2 into a submodule and that way we would let them deal with issues in that and switch to PyTorch 1.1.0?

**Comment by xingyizhou** [comment]
Thanks for the suggestion. Testing works for pytorch v1.1 for sure. According to my experiments, training ctdet_1x on COCO is 0.4 AP lower than 0.4.1. I don't want to hear complains about that so I decided to release in 0.4.1. It is easy for the users to switch to 1.1 themselves.
