### ISSUE TITLE
Why mask the invisible keypoint when apply the method to human pose estimation?

### ISSUE THREAD

**Issue by USTClj** [xingyizhou/CenterNet#134]
Hi, congratulations on your new great work! But the COCO evaluation will take  into account the invisible keypoints. Is there some consideration for making them?
PS: I have known you for your work for a long time :). Happy to see your new work again.

My respect.

**Comment by xingyizhou** [comment]
Thanks for your interests. I don't think I have masked invisible keypoints (i.e., visible = 1) in training [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/sample/multi_pose.py#L137). `pts[j, 2] = 0` is for not annotated points.

**Comment by USTClj** [comment]
Thank you for your reply. In Chapter 4.2 of your paper, there goes:

> We ignore the invisible keypoints by masking the loss
