### ISSUE TITLE
problem in height of 2d bbox

### ISSUE THREAD

**Issue by 123alaa** [xingyizhou/CenterNet#135]
Hi @xingyizhou ,

I have new 3d data set (like kitti), i made all the transformation to convert to kitti format, trained a model, but i have problem in height of the 2d box:
1. My images shape is w = 1280 h = 720, and gt build based on that, but your network can get only 1280,384. (i update this in the code)
 So sure will be problem with the height output in this. how can i fix the output to be good.
I tried to multiply with some factors like 384/720, but it not work.

Can you help? the center_y is perfect although it fed to the network in relation to 720.

Suggestion: If i change the gt to 384, and the image will 1280,720, is enough?

Thank's

**Comment by xingyizhou** [comment]
Do you plan to re-train your network? If so, create a new dataset file like [this](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/dataset/kitti.py) and change [this line](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/dataset/kitti.py#L19) to your image shape. If not, I won't expect KITTI trained model can generalize well to other datasets. If you use `test.py` to run your own image, you can `--keep_res` so it will not resize to kitti size.

**Comment by 123alaa** [comment]
Hi @xingyizhou , yes i want to retrain, but if i change this line it will fed to the network images with 1280,720, right? That it is very big on our gpu. So to fed to the network the labels and images with 1280,720. and resize it in the code (i.e for the netwrok it will be on 1280,384). Did you understand?
