### ISSUE TITLE
questions about data preprocessing code

### ISSUE THREAD

**Issue by zzzxxxttt** [xingyizhou/CenterNet#138]
First of all, thank you for this great implementation! 
I have several questions when I'm reading the source code, especially in the data preprocessing part, such as this function:
``` 
def _get_border(self, border, size):
    i = 1
    while size - border // i <= border // i:
      i *= 2
    return border // i
```
could you tell me what is _get_border() used for? 
Another question is about this:
```  
if self.opt.keep_res:
      input_h = (height | self.opt.pad) + 1
      input_w = (width | self.opt.pad) + 1
      scale = np.array([input_w, input_h], dtype=np.float32)
```
I never figure out the usage of "|" here, could you give some explainations? Thanks very much!

**Comment by xingyizhou** [comment]
Hi, the code is copied from the CornerNet implementation and I am not sure about its exact purpose. You can switch to a naive scale/ shift augmentation [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/sample/ctdet.py#L57) by `--not_rand_crop` and set the augmentation parameters by `--scale 0.x --shift 0.x` if you feel uncomfortable about the augmentation. `|` is bit operation. `y = (x | 31) + 1` makes sure y is divisible by 32.
