### ISSUE TITLE
how to train you own model?

### ISSUE THREAD

**Issue by toplinuxsir** [xingyizhou/CenterNet#14]
how to train you own model?

**Comment by xingyizhou** [comment]
Please check [GETTING_STARTED.md](https://github.com/xingyizhou/CenterNet/blob/master/readme/GETTING_STARTED.md) or ask a more specific question.

**Comment by deandiakov** [comment]
> Please check [GETTING_STARTED.md](https://github.com/xingyizhou/CenterNet/blob/master/readme/GETTING_STARTED.md) or ask a more specific question.

For a more specific question: How should our images and respective annotations be organized if we wish to train our own classes using your models as the base model; the goal being to take advantage of transfer learning versus training a model completely from scratch.

**Comment by shenghsiaowong** [comment]
can we train voc datasets on centerNet?
