### ISSUE TITLE
Change the class_name

### ISSUE THREAD

**Issue by taqikoma** [xingyizhou/CenterNet#140]
Hi, I changed the class_name according to my own dataset in pascal.py, and used test.py to calculate AP.
But the result is:
Evaluating detections
VOC07 metric? Yes
AP for aeroplane = 0.0000
AP for bicycle = 0.0000
AP for bird = 0.0000
AP for boat = 0.0000
AP for bottle = 0.0000
AP for bus = 0.0000
AP for car = 0.0000
AP for cat = 0.0000
AP for chair = 0.0000
AP for cow = 0.0000
AP for diningtable = 0.0000
AP for dog = 0.0000
AP for horse = 0.0000
AP for motorbike = 0.0000
AP for person = 0.0000
AP for pottedplant = 0.0000
AP for sheep = 0.0000
AP for sofa = 0.0000
AP for train = 0.0000
AP for tvmonitor = 0.0000
Mean AP = 0.0000
~~~~~~~~
What else should I do？ Thank you!

**Comment by xingyizhou** [comment]
We don't support evaluation on custom datasets. You will need to look into the pascal evaluation code from faster rcnn and modify accordingly. I haven't looked into this.
