### ISSUE TITLE
Doubt in how to run demo.py for 1 class trained model

### ISSUE THREAD

**Issue by nanditam1** [xingyizhou/CenterNet#141]
Hi, I have trained the model with 1 class (fine-tuned from coco model) , for my own dataset , and have made changes in code as per instructions, i made the changes in coco.py itself:
1. in 'dataset/coco.py' : num_classes = 1,     self.class_name = ['__background__', 'car'],   self._valid_ids = [1]
2. in debugger.py , coco_class_name = ['car']

I understand I have skipped some steps, eg: adding to dataset_factory. But would it impact the training?

However when i run demo.py, with newly trained model, I get boxes always at the top of image randomly. 
And after loading it says:
Skip loading parameter hm.2.weight, required shapetorch.Size([80, 256, 1, 1]), loaded shapetorch.Size([1, 256, 1, 1]).
Skip loading parameter hm.2.bias, required shapetorch.Size([80]), loaded shapetorch.Size([1]).

Do you find any errors in my training approach and demo.py? Is the code still expecting 80 classes somewhere when im trying to load 1 class model?

Thanks!!

**Comment by xingyizhou** [comment]
You will need to change the default dataset information [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/opts.py#L337). Or you can try `--num_classes 1`, not sure if this works. The reason is that `create_model` will take `opt.num_classes` as the number of channels for its last layer.

**Comment by lih627** [comment]
@nanditam1 I have the same question, how to train a model for 1 class in my own dataset. I want to detect some makers in image.
Do the changes you listed before can make the code performs well?
