### ISSUE TITLE
Question about multi_pose_decode

### ISSUE THREAD

**Issue by YLRong** [xingyizhou/CenterNet#143]
Great work.

When decoding the outputs from multi_pose network, the author snaps the initial predictions to the closest detected keypoint on the joint heatmap, which is introduced as refining process in the paper. 

I have a question: multi_pose_decode extracts 100 peaks from joint heatmap output['hm_hp'] with shape (1, 17, 128, 128), and then adds respective value from the offset map output['hp_offset'] with shape (1, 2, 128, 128). Does it mean that all kind of joints share the offsets from coordinates of joint heatmap peaks? Or should the offset map be shaped (1, 34, 128, 128) or (1, 17, 2, 128, 128)? 

Looking forward to a reply.
^_^

**Comment by xingyizhou** [comment]
Hi,
  All joints share the offset map. I haven't tried the other option.
