### ISSUE TITLE
Model without DCN

### ISSUE THREAD

**Issue by Maplernothaxor** [xingyizhou/CenterNet#144]
Hey,

Is the only GPU dependency the dcn implementation? If so, is it possible to train the model without dcn (thus making it cpu compatible)? Are there any pre-trained models without dcn?

Thanks!

**Comment by sebamenabar** [comment]
hey, did you find an answer for this? could you make it work without CUDA? I want to make some tests before sending to GPU

**Comment by macqueen09** [comment]
same question . No answers yet . Also want get a model train in GPU , inference in CPU .

**Comment by mengzhi2** [comment]
If you want to train a model without DCN, use --arch res_18 or dlav0_34.
