### ISSUE TITLE
To train my own data

### ISSUE THREAD

**Issue by hheavenknowss** [xingyizhou/CenterNet#145]
Hello there, I want to train my own data, and I read the document, but  I still have some questions. my data is coco  format, and I wonder where should I put my images and annotations , should I make a new directory? like src/lib/datasets/trains/ or something, thank you for your time

**Comment by xingyizhou** [comment]
You will need to create the image folders, create a new python file,  and specify the data path like [this](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/dataset/coco.py#L24). You are expected to read some code if you want to train on a new dataset.

**Comment by hheavenknowss** [comment]
I tried  as your document again and thanks to your advisee it worked this time, and I want to see the  result of training, I set debug=2 is enough ? And I don't konw where it save the model and training result, I don't see any parameters like savepath, could you tell me about it? Thank you!

**Comment by hheavenknowss** [comment]
> 
> 
> You will need to create the image folders, create a new python file, and specify the data path like [this](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/dataset/coco.py#L24). You are expected to read some code if you want to train on a new dataset.

I followed the document and solved my problem above, but I stil have some issues, I want to see the decetion result,and I set the debugger=1, I run the code on serves, so it can not show the images, what should I do to save the result so I can check them?Thank you for your patience.

**Comment by XiaoJiNu** [comment]
@hheavenknowss you should modify code in test.py,  but now I don't have spare time to do it, sorry

**Comment by xingyizhou** [comment]
`--debug 4` will dump the results to disk. See [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/opts.py#L24). You are expected to read the code if you want to do something beyond demo.

**Comment by thinkyang88** [comment]
self.class_name and self._valid_ids should modify correspond  to new dataset?

**Comment by zjp99** [comment]
更换数据集后，test时候需要更改什么东西，我的出不来，测试标签仍使用的voc不是我的类别
