### ISSUE TITLE
ModuleNotFoundError: No module named 'external.nms'

### ISSUE THREAD

**Issue by leiyaohui** [xingyizhou/CenterNet#146]
Hello, this error occurred when I ran demo.py. I look forward to your reply.

**Comment by xingyizhou** [comment]
~~~
cd src/lib/external
make
~~~

**Comment by joyyang1215** [comment]
Thanks, it works.

**Comment by NathanWendt** [comment]
@xingyizhou Hey, I tried this and got "-bash: cd: src/lib/external: No such file or directory", am noobish. Please help :)
