### ISSUE TITLE
模型下载问题

### ISSUE THREAD

**Issue by zqnnn** [xingyizhou/CenterNet#149]
请问有没有检测模型的百度云资源，google下不了模型

**Comment by heartInsert** [comment]
+1

**Comment by AmieeZhou** [comment]
+1

**Comment by AmieeZhou** [comment]
pre-trained weights 'ctdet_coco_dla_2x.pth'
link：https://pan.baidu.com/s/1XfGUh8uvKPrQ_gbzifWaPg 
password：jkvy

**Comment by heartInsert** [comment]
> pre-trained weights 'ctdet_coco_dla_2x.pth'
> link：https://pan.baidu.com/s/1XfGUh8uvKPrQ_gbzifWaPg
> password：jkvy

3Q
