### ISSUE TITLE
training 3d model in different resolution

### ISSUE THREAD

**Issue by 123alaa** [xingyizhou/CenterNet#150]
Hi @xingyizhou ,

Can i train 3d model in 320,320 image resolution? i.e Is your architecture work, with any size, if change the size in the opts and change the image size?.

This will help me a lot. 

Best,
Alaa

**Comment by xingyizhou** [comment]
You can have a try by changing [this line](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/dataset/kitti.py#L19), but usually a small input resolution will give a performance drop. You can visualize the training image by `--debug 2` to see if it is reasonable.
