### ISSUE TITLE
Performance Issue with Heat-map : Msra-Gaussian Artifacts.

### ISSUE THREAD

**Issue by PetreanuAndi** [xingyizhou/CenterNet#151]
Hello :D 

Has anyone ever plotted / drawn the "hm" heat map that is outputted from the draw_gaussian(...) function? If there are many close objects, the heat map displays severe artifacts, and this will surely affect the network. I have attached an example here (with a scaling factor of 30, otherwise you could not "see" the values)

Please let me know what you think, i'm pretty sure this is a bug and is affecting your performance too :) I'm testing the "draw_msra_gaussian(...)", with values scaled by 30 and a symmetric radius of 3. 

Original segmented GT : 
![2019-04-02 11 37 32_vis](https://user-images.githubusercontent.com/19908335/59693601-de0b3b00-91ef-11e9-892d-fca4869333ee.png)

Gaussian HM GT created in sample/ctdet.py : 

![2019-04-02 11 37 32_gauss](https://user-images.githubusercontent.com/19908335/59693725-07c46200-91f0-11e9-8575-0f7e8bdb9f39.jpg)

**Comment by xingyizhou** [comment]
You can `--debug 2` to visualize the rendered gaussian map. The plot you have shown is not likely to be generated by the code. MSRA style gaussian is never used in this project.

**Comment by PetreanuAndi** [comment]
The artifacts were a bug of mine, so this thread can be closed.
I modified the MSRA Gaussian technique such that it produces rotated and elongated shapes, and it looks good now. 

However, you mentioned you do not use the MSRA (although it is in your code) 
Can you also say why? Or what's the main difference between MSRA and UMICH?
Why do you prefer the Umich?

Is it not important to have a gaussian that stretches all the way to the boundaries of the object?
I see that you only create symmetrical gaussians, with no AspectRatio to them. It's counter intuitive that this works (especially for elongated objects)

**Comment by xingyizhou** [comment]
Because I haven't made it work. They are from the corresponding code and I haven't look into them.

**Comment by lih627** [comment]
Hello, @PetreanuAndi 
> The artifacts were a bug of mine, so this thread can be closed.
I modified the MSRA Gaussian technique such that it produces rotated and elongated shapes, and it looks good now.
I meet the same problem. I want to draw a gaussian map with different w/h and rotation. Your diagram looks very good. Could you tell me how to achieve that?

thanks a lot
