### ISSUE TITLE
Question about losses of size and local offset

### ISSUE THREAD

**Issue by Newcomer520** [xingyizhou/CenterNet#153]
Thank you @xingyizhou for this great work, really appreciated.

I have two questions about two loss terms.

1. Since the size is always greater than 0, should we map the size into log-domain and then calculate the loss for size?

2. Similar to 1., local offset should be between 0 and 1 but it seems no activation(sigmoid) function to the prediction of local offset. Does it have better prediction without any activation?

Thanks a lot!

**Comment by xingyizhou** [comment]
We haven't tried both. 1 looks reasonable but 2 looks unnecessary. Feel free to have a tried yourself, we are happy to discuss if you have the results.

**Comment by Newcomer520** [comment]
Thank you for the reply!

**Comment by jixiaonanzhuaizhuai** [comment]
@Newcomer520 do you try about loss for size?

**Comment by Newcomer520** [comment]
Hello @jixiaonanzhuaizhuai I didn't try the different loss calculation yet. Currently I only use the same loss mentioned in the paper
