### ISSUE TITLE
cat_spec_wh in ctdet_decode

### ISSUE THREAD

**Issue by fw509** [xingyizhou/CenterNet#154]
It seems that `dets = ctdet_decode(hm, wh, reg=reg, K=self.opt.K)` does not include 'cat_spec_wh' as an argument? [https://github.com/xingyizhou/CenterNet/blob/819e0d0dde02f7b8cb0644987a8d3a370aa8206a/src/lib/detectors/ctdet.py#L36](url)
Thanks.

**Comment by xingyizhou** [comment]
We never used `cat_spec_wh` is the experiments. I have tried once this on Pascal VOC but it doesn't give improvement. Feel free to try it on COCO yourself.
