### ISSUE TITLE
Training VOC, No param ....

### ISSUE THREAD

**Issue by ZLeopard** [xingyizhou/CenterNet#155]
I train the VOC dataset following your command, also eval the dataset with your published model. your model is fine, but i trained by myself, the AP is zero. maybe the json file problem???
**here is my result.json, a lot of [][][]**
[[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [],

**and the AP**

Evaluating detections
VOC07 metric? Yes
AP for aeroplane = 0.0000
AP for bicycle = 0.0000
AP for bird = 0.0000
AP for boat = 0.0000
AP for bottle = 0.0000
AP for bus = 0.0000
AP for car = 0.0000
AP for cat = 0.0000
AP for chair = 0.0000
AP for cow = 0.0000
AP for diningtable = 0.0000
AP for dog = 0.0000
AP for horse = 0.0000
AP for motorbike = 0.0000
AP for person = 0.0000
AP for pottedplant = 0.0000
AP for sheep = 0.0000
AP for sofa = 0.0000
AP for train = 0.0000
AP for tvmonitor = 0.0000
Mean AP = 0.0000
~~~~~~~~

**and the infomation about NO PARAM .........**

No param dla_up.ida_2.proj_3.conv.conv_offset_mask.bias.
No param dla_up.ida_2.up_3.weight.
No param dla_up.ida_2.node_3.actf.0.weight.
No param dla_up.ida_2.node_3.actf.0.bias.
No param dla_up.ida_2.node_3.actf.0.running_mean.
No param dla_up.ida_2.node_3.actf.0.running_var.
No param dla_up.ida_2.node_3.actf.0.num_batches_tracked.
No param dla_up.ida_2.node_3.conv.weight.
No param dla_up.ida_2.node_3.conv.bias.
No param dla_up.ida_2.node_3.conv.conv_offset_mask.weight.
No param dla_up.ida_2.node_3.conv.conv_offset_mask.bias.
No param ida_up.proj_1.actf.0.weight.
No param ida_up.proj_1.actf.0.bias.
No param ida_up.proj_1.actf.0.running_mean.
No param ida_up.proj_1.actf.0.running_var.
No param ida_up.proj_1.actf.0.num_batches_tracked.
No param ida_up.proj_1.conv.weight.
No param ida_up.proj_1.conv.bias.
No param ida_up.proj_1.conv.conv_offset_mask.weight.
No param ida_up.proj_1.conv.conv_offset_mask.bias.
No param ida_up.up_1.weight.
No param ida_up.node_1.actf.0.weight.
No param ida_up.node_1.actf.0.bias.
No param ida_up.node_1.actf.0.running_mean.
No param ida_up.node_1.actf.0.running_var.
No param ida_up.node_1.actf.0.num_batches_tracked.
No param ida_up.node_1.conv.weight.
No param ida_up.node_1.conv.bias.
No param ida_up.node_1.conv.conv_offset_mask.weight.
No param ida_up.node_1.conv.conv_offset_mask.bias.
No param ida_up.proj_2.actf.0.weight.
No param ida_up.proj_2.actf.0.bias.
No param ida_up.proj_2.actf.0.running_mean.
No param ida_up.proj_2.actf.0.running_var.
No param ida_up.proj_2.actf.0.num_batches_tracked.
No param ida_up.proj_2.conv.weight.
No param ida_up.proj_2.conv.bias.
No param ida_up.proj_2.conv.conv_offset_mask.weight.
No param ida_up.proj_2.conv.conv_offset_mask.bias.
No param ida_up.up_2.weight.
No param ida_up.node_2.actf.0.weight.
No param ida_up.node_2.actf.0.bias.
No param ida_up.node_2.actf.0.running_mean.
No param ida_up.node_2.actf.0.running_var.
No param ida_up.node_2.actf.0.num_batches_tracked.
No param ida_up.node_2.conv.weight.
No param ida_up.node_2.conv.bias.
No param ida_up.node_2.conv.conv_offset_mask.weight.
No param ida_up.node_2.conv.conv_offset_mask.bias.

**I train the net with your script in experiment fold. Please help me to config what happened. Thanks a lot!!!!**

**Comment by xingyizhou** [comment]
It says the network does not find the corresponding parameters from your trained .pth model. Please make sure your `--arch` is the same as the model you load.
