### ISSUE TITLE
Train on my own dataset, RuntimeError

### ISSUE THREAD

**Issue by lih627** [xingyizhou/CenterNet#157]
Thanks for your work.
I create a  small dataset(about 300 images) for CenterNet to detect markers in image. And I convert voc format annotations to coco format. The image I use is `1280x720` and I change  
 some code in `coco.py` and `opts.py`, because I only have one style marker. 

When I train `resdcn_18`, the error raise, I use one GPU and here is the opts:
```
Fix size testing.
training chunk_sizes: [4]
The output will be saved to  /home/lih/project/CenterNet/src/lib/../../exp/ctdet/coco_resdcn18
heads {'hm': 1, 'wh': 2, 'reg': 2, 'hp_offset': 2}
Namespace(K=100, aggr_weight=0.0, agnostic_ex=False, arch='resdcn_18', aug_ddd=0.5, aug_rot=0, batch_size=4, cat_spec_wh=False, center_thresh=0.1, chunk_sizes=[4], data_dir='/home/lih/project/CenterNet/src/lib/../../data', dataset='coco', debug=0, debug_dir='/home/lih/project/CenterNet/src/lib/../../exp/ctdet/coco_resdcn18/debug', debugger_theme='white', demo='', dense_hp=False, dense_wh=False, dep_weight=1, dim_weight=1, down_ratio=4, eval_oracle_dep=False, eval_oracle_hm=False, eval_oracle_hmhp=False, eval_oracle_hp_offset=False, eval_oracle_kps=False, eval_oracle_offset=False, eval_oracle_wh=False, exp_dir='/home/lih/project/CenterNet/src/lib/../../exp/ctdet', exp_id='coco_resdcn18', fix_res=True, flip=0.5, flip_test=False, gpus=[0], gpus_str='0', head_conv=64, heads={'hm': 1, 'wh': 2, 'reg': 2, 'hp_offset': 2}, hide_data_time=False, hm_hp=True, hm_hp_weight=1, hm_weight=1, hp_weight=1, input_h=720, input_res=1280, input_w=1280, keep_res=False, kitti_split='3dop', load_model='', lr=0.000125, lr_step=[90, 120], master_batch_size=4, mean=array([[[0.40789655, 0.44719303, 0.47026116]]], dtype=float32), metric='loss', mse_loss=False, nms=False, no_color_aug=False, norm_wh=False, not_cuda_benchmark=False, not_hm_hp=False, not_prefetch_test=False, not_rand_crop=False, not_reg_bbox=False, not_reg_hp_offset=False, not_reg_offset=False, num_classes=1, num_epochs=140, num_iters=-1, num_stacks=1, num_workers=4, off_weight=1, output_h=180, output_res=320, output_w=320, pad=31, peak_thresh=0.2, print_iter=0, rect_mask=False, reg_bbox=True, reg_hp_offset=True, reg_loss='l1', reg_offset=True, resume=False, root_dir='/home/lih/project/CenterNet/src/lib/../..', rot_weight=1, rotate=0, save_all=False, save_dir='/home/lih/project/CenterNet/src/lib/../../exp/ctdet/coco_resdcn18', scale=0.4, scores_thresh=0.1, seed=317, shift=0.1, std=array([[[0.2886383 , 0.27408165, 0.27809834]]], dtype=float32), task='ctdet', test=False, test_scales=[1.0], trainval=False, val_intervals=100000000, vis_thresh=0.3, wh_weight=0.1)
Creating model...
=> loading pretrained model https://download.pytorch.org/models/resnet18-5c106cde.pth
=> init deconv weights from normal distribution
Setting up data...
==> initializing coco 2017 val data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded val 250 samples
==> initializing coco 2017 train data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded train 250 samples
Starting training...
Traceback (most recent call last):
  File "/home/lih/project/CenterNet/src/main.py", line 102, in <module>
    main(opt)
  File "/home/lih/project/CenterNet/src/main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/lih/project/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/lih/project/CenterNet/src/lib/trains/base_trainer.py", line 69, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/home/lih/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lih/project/CenterNet/src/lib/trains/base_trainer.py", line 20, in forward
    loss, loss_stats = self.loss(outputs, batch)
  File "/home/lih/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lih/project/CenterNet/src/lib/trains/ctdet.py", line 49, in forward
    hm_loss += self.crit(output['hm'], batch['hm']) / opt.num_stacks
  File "/home/lih/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lih/project/CenterNet/src/lib/models/losses.py", line 121, in forward
    return self.neg_loss(out, target)
  File "/home/lih/project/CenterNet/src/lib/models/losses.py", line 56, in _neg_loss
    pos_loss = torch.log(pred) * torch.pow(1 - pred, 2) * pos_inds
RuntimeError: The size of tensor a (184) must match the size of tensor b (180) at non-singleton dimension 2
```
I want to know what caused the error...
Thanks a lot

**Comment by lih627** [comment]
`keep_res = True` then the error will not raise.
But why `keep_res = False` causes this error...

**Comment by PetreanuAndi** [comment]
I'm getting the same error with or without res. In any case, i see the 'ddd' task does not use square resolution, so i'm pretty sure that the default square resolution (512,512) is not mandatory.

I'm using my own dataset and i need the original aspect ratio. Square res. would imply smthng like FPN which is probably not the case. Still, i get this : 

pos_loss = torch.log(pred) * torch.pow(1 - pred, 2) * pos_inds
RuntimeError: The size of tensor a (200) must match the size of tensor b (3) at non-singleton dimension 3

**Comment by lih627** [comment]
@PetreanuAndi 
If you don't care the inference speed, maybe you can avoid this error by `keep_res = True` while training. It worked in ctdet model. And I change some parameters in opts, for example:
```
  input_h: 720
  input_res: 1280
  input_w: 1280
  keep_res: True
```
Then the inference speed can't reach real-time in test `total time =0.103s`. Because the image size is lager than default.
I want to train and inference in resized images, and it occurs the error. If you find the way to train in resized images, please tell me... Thanks a lot.

**Comment by PetreanuAndi** [comment]
Hey @lih627 

You can close this issue. This is the fix : 

180 comes from your input height resolution / output_stride_ratio (720 / 4)
However, the "self.opt.keep_res" will pad your input (and consequently also enlarge your Gaussian Heatmap "hm") such that your input height will become 184.

If you pre-compile your heatmaps, as i did to optimise train speed, make sure those heatmaps are scaled down with output_stride_ratio (default 4) and also make sure you pad them when reading such that they match with the output resolution of the input.

Hope this helps. :)

**Comment by lih627** [comment]
@PetreanuAndi  Sorry to reply late.  
Is that from `base_detector,py` at [line37](https://github.com/xingyizhou/CenterNet/blob/a5a0483beb0f9e8705f6dc67d8817275369cfa7e/src/lib/detectors/base_detector.py#L37)?

I don't have time to speed up the algorithm, because I meet another error about data loader when I use lager dataset(about 20,000 images), and it's hard to reproduce the error.... When I fix this error, I will try to speed up the model.

**Comment by xingyizhou** [comment]
The input size should be dividable by 32 for resnet/ dla (and 128 for hourglass). 720 does not meet this.

**Comment by CompliceU** [comment]
@lih627  Hello, I don't know if you are training. I also want to do this work, but the data that I have transferred is always a problem. I don't know if I can guide you. Thank you.

**Comment by lih627** [comment]
@CompliceU  I already trained the model in my dataset. 

I use labelImg to create pascal voc format xml annotations from images. And then convert voc to coco format(a json file).  You can use [These utils](https://github.com/lih627/Dataset-Utils) to create json annotations from xml annotations.  It works well
