### ISSUE TITLE
What are the usages of 'count_iou', 'count_anchor', 'count'?

### ISSUE THREAD

**Issue by SkeletonOne** [xingyizhou/CenterNet#159]
@xingyizhou  Thanks for your beautiful work first.

I'm currently trying to read your code, since I would like to know how you extract the center in each object for label in train. While in calc_coco_overlap.py I saw you defined four functions, while you only use 'count_size' at last. Are the extraction operation done in this py? And could you explain what are these functions used for? Thanks!

**Comment by xingyizhou** [comment]
They are used to produce different numbers in appendix C. Please refer to appendix C or ask a more specific question.

**Comment by SkeletonOne** [comment]
@xingyizhou  Thanks! I understand now!
