### ISSUE TITLE
have you tried HRNet as backbone?

### ISSUE THREAD

**Issue by bailvwangzi** [xingyizhou/CenterNet#164]
dla and hourglass result is good, but maybe hrnet is better for pose/keypoint? do you have this experiment? i will try it @xingyizhou

**Comment by xingyizhou** [comment]
I have tried it for one day, but I haven't made it work on PascalVOC with the same hyperparameter. It also runs considerably slower than DLA so we decide to stick to DLA.

**Comment by Epiphqny** [comment]
> dla and hourglass result is good, but maybe hrnet is better for pose/keypoint? do you have this experiment? i will try it @xingyizhou

Have you tried the hrnet? i train the model from scratch for object detection, but it can not converge.
