### ISSUE TITLE
issues of Train

### ISSUE THREAD

**Issue by lkllk** [xingyizhou/CenterNet#166]
hello,when I train a model using "sh ctdet_coco_dla_1x.sh",it doesn't work. Details are as follows:

ctdet/coco_dla_1x---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000057870.jpg
---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000122688.jpg
---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000392136.jpg
ctdet/coco_dla_1x |#####                           | val: [125][0/6]|Tot: 0:00:00 |ETA: 0:00:00 |loss 92.2464 |hm_loss 89.5612 |wh_loss 21.9291 |off_loss 0.4923 |Data 0.125s(0.125s) |Net 0.203s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000398494.jpg
ctdet/coco_dla_1x |##########                      | val: [125][1/6]|Tot: 0:00:00 |ETA: 0:00:02 |loss 102.2282 |hm_loss 99.6916 |wh_loss 20.2657 |off_loss 0.5100 |Data 0.001s(0.063s) |Net 0.140s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000090570.jpg
ctdet/coco_dla_1x |################                | val: [125][2/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 116.4594 |hm_loss 113.8563 |wh_loss 20.7146 |off_loss 0.5317 |Data 0.001s(0.042s) |Net 0.119s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000504616.jpg
ctdet/coco_dla_1x |#####################           | val: [125][3/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 113.3300 |hm_loss 110.9208 |wh_loss 18.8662 |off_loss 0.5226 |Data 0.004s(0ctdet/coco_dla_1x |##########################      | val: [125][4/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 131.6531 |hm_loss 129.2190 |wh_loss 18.9063 |off_loss 0.5435 |Data 0.001s(0ctdet/coco_dla_1x |################################| val: [125][5/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 129.9010 |hm_loss 127.4887 |wh_loss 18.6448 |off_loss 0.5478 |Data 0.001s(0.022s) |Net 0.100s
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000057870.jpg
---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000122688.jpg
---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000392136.jpg
ctdet/coco_dla_1x |#####                           | val: [130][0/6]|Tot: 0:00:00 |ETA: 0:00:00 |loss 92.2464 |hm_loss 89.5612 |wh_loss 21.9291 |off_loss 0.4923 |Data 0.131s(0.131s) |Net 0.209s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000398494.jpg
ctdet/coco_dla_1x |##########                      | val: [130][1/6]|Tot: 0:00:00 |ETA: 0:00:02 |loss 102.2282 |hm_loss 99.6916 |wh_loss 20.2657 |off_loss 0.5100 |Data 0.001s(0.066s) |Net 0.143s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000090570.jpg
ctdet/coco_dla_1x |################                | val: [130][2/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 116.4594 |hm_loss 113.8563 |wh_loss 20.7146 |off_loss 0.5317 |Data 0.001s(0.044s) |Net 0.122s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000504616.jpg
ctdet/coco_dla_1x |#####################           | val: [130][3/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 113.3300 |hm_loss 110.9208 |wh_loss 18.8662 |off_loss 0.5226 |Data 0.001s(0ctdet/coco_dla_1x |##########################      | val: [130][4/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 131.6531 |hm_loss 129.2190 |wh_loss 18.9063 |off_loss 0.5435 |Data 0.001s(0ctdet/coco_dla_1x |################################| val: [130][5/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 129.9010 |hm_loss 127.4887 |wh_loss 18.6448 |off_loss 0.5478 |Data 0.001s(0.022s) |Net 0.100s
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000057870.jpg
---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000122688.jpg
---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000392136.jpg
ctdet/coco_dla_1x |#####                           | val: [135][0/6]|Tot: 0:00:00 |ETA: 0:00:00 |loss 92.2464 |hm_loss 89.5612 |wh_loss 21.9291 |off_loss 0.4923 |Data 0.130s(0.130s) |Net 0.208s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000398494.jpg
ctdet/coco_dla_1x |##########                      | val: [135][1/6]|Tot: 0:00:00 |ETA: 0:00:02 |loss 102.2282 |hm_loss 99.6916 |wh_loss 20.2657 |off_loss 0.5100 |Data 0.002s(0.066s) |Net 0.147s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000090570.jpg
ctdet/coco_dla_1x |################                | val: [135][2/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 116.4594 |hm_loss 113.8563 |wh_loss 20.7146 |off_loss 0.5317 |Data 0.002s(0.045s) |Net 0.126s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000504616.jpg
ctdet/coco_dla_1x |#####################           | val: [135][3/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 113.3300 |hm_loss 110.9208 |wh_loss 18.8662 |off_loss 0.5226 |Data 0.001s(0ctdet/coco_dla_1x |##########################      | val: [135][4/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 131.6531 |hm_loss 129.2190 |wh_loss 18.9063 |off_loss 0.5435 |Data 0.001s(0ctdet/coco_dla_1x |################################| val: [135][5/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 129.9010 |hm_loss 127.4887 |wh_loss 18.6448 |off_loss 0.5478 |Data 0.001s(0.023s) |Net 0.102s
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x
ctdet/coco_dla_1x---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000057870.jpg
---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000122688.jpg
---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000392136.jpg
ctdet/coco_dla_1x |#####                           | val: [140][0/6]|Tot: 0:00:00 |ETA: 0:00:00 |loss 92.2464 |hm_loss 89.5612 |wh_loss 21.9291 |off_loss 0.4923 |Data 0.121s(0.121s) |Net 0.199s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000398494.jpg
ctdet/coco_dla_1x |##########                      | val: [140][1/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 102.2282 |hm_loss 99.6916 |wh_loss 20.2657 |off_loss 0.5100 |Data 0.001s(0.061s) |Net 0.141s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000090570.jpg
ctdet/coco_dla_1x |################                | val: [140][2/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 116.4594 |hm_loss 113.8563 |wh_loss 20.7146 |off_loss 0.5317 |Data 0.001s(0.041s) |Net 0.120s---------------------img_path------------------- /home/aicrobo/CenterNet/src/lib/../../data/coco/val2017/COCO_train2014_000000504616.jpg
ctdet/coco_dla_1x |#####################           | val: [140][3/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 113.3300 |hm_loss 110.9208 |wh_loss 18.8662 |off_loss 0.5226 |Data 0.001s(0ctdet/coco_dla_1x |##########################      | val: [140][4/6]|Tot: 0:00:00 |ETA: 0:00:01 |loss 131.6531 |hm_loss 129.2190 |wh_loss 18.9063 |off_loss 0.5435 |Data 0.002s(0ctdet/coco_dla_1x |##

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

**Comment by xingyizhou** [comment]
Please make sure you haven't modified the code. It shows your validation set only contains 6 samples.
