### ISSUE TITLE
train coco use  ctdet_coco_resdcn18

### ISSUE THREAD

**Issue by zhangtiantian12311** [xingyizhou/CenterNet#168]
when i use ''python demo.py ctdet --exp_id coco_resdcn18 --arch resdcn_18 --demo ../images/1.mp4  --load_model ../exp/ctdet/coco_resdcn18/model_last.pth '',it no problem, but has no detection result in the video.
thank you very much

**Comment by xingyizhou** [comment]
I am not able to help unless more details are provided. Can you try the res18 model in our model zoo?

**Comment by zhangtiantian12311** [comment]
yes, but when i test the model that i trained ,it has no result, and i try the res18 in model zoo,it has detection-result
![image](https://user-images.githubusercontent.com/43676340/60245183-9de24180-98ee-11e9-808c-c2b1bed9a7b3.png)

**Comment by xingyizhou** [comment]
Please make sure you haven't made any changes to the code. You can first test the model on COCO validation set to see if everything goes well. You can also `--debug 2` to visualize the predicted heatmaps.
