### ISSUE TITLE
pose_dla_dcn.py DLA-34 not match model-diagrams in paper

### ISSUE THREAD

**Issue by Sxs7513** [xingyizhou/CenterNet#169]
the forward function of modle DLASeg in pose_dla_dcn.py is

```
y = []
        for i in range(self.last_level - self.first_level):
            y.append(x[i].clone())
        self.ida_up(y, 0, len(y))
```

but self.last_level(5) - self.first_level(2) = 3 in normal, so the box with blue circle will not be calculated,  is there somotheing i miss ?

![image](https://user-images.githubusercontent.com/29081463/60187011-6d9f9200-985f-11e9-8e15-087ba652b95b.png)

**Comment by xingyizhou** [comment]
@DequanWang Can you check this?

**Comment by djshen** [comment]
same problem here #103

**Comment by xingyizhou** [comment]
Thanks for pointing out the issue. You are right, the figure is indeed wrong. We will revise the figure in the revision.

**Comment by windyrobin** [comment]
@DequanWang  @xingyizhou 
```
for i in range(self.last_level - self.first_level):
            y.append(x[i].clone())
        self.ida_up(y, 0, len(y))
```
is  `clone`  really necessary?
it seems ida_up doesn't change the content:
```
def forward(self, layers, startp, endp):
        for i in range(startp + 1, endp):
            upsample = getattr(self, 'up_' + str(i - startp))
            project = getattr(self, 'proj_' + str(i - startp))
            layers[i] = upsample(project(layers[i]))
            node = getattr(self, 'node_' + str(i - startp))
            layers[i] = node(layers[i] + layers[i - 1])
```

**Comment by hheavenknowss** [comment]
hai there, I wonder if this issue get fixed? And how much it could influnce the train, thank u
