### ISSUE TITLE
a Question about the local offset image in your paper.

### ISSUE THREAD

**Issue by ZhenLiuBuaa** [xingyizhou/CenterNet#170]
![offset](https://user-images.githubusercontent.com/45850504/60245750-ca4a8d80-98ef-11e9-86d8-b32077c40140.PNG)

the image data is begin in top-left corner,and offset value is between 0 and 1,why your local off-set vector  points at top-right corner.

**Comment by xingyizhou** [comment]
Thanks! You are correct. It should be bottom-right ...

**Comment by ZhenLiuBuaa** [comment]
Thanks for your reply.and i also have a question. how can i test the model with the eval_oracle_hm parameter. i find in test process ,the eval_oracle_hm parameter has no effect on the test result.

**Comment by coderKyf** [comment]
@ZhenLiuBuaa 
Hi,
I have some questions about the local offset.
You said "offset value is between 0 and 1".  Why?  Isn't offset value pixel?
Thanks a lot.

**Comment by ZhenLiuBuaa** [comment]
in the code, author set offset value between 0 and 1 .I think the reason maybe is  the offset value is of  the feature map and model can learn it more accurately. @xingyizhou

**Comment by ash2703** [comment]
Can someone explain where the offsets are calculated? @ZhenLiuBuaa @xingyizhou
