### ISSUE TITLE
Cannot move to target thread (0x731d870), Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hktxt** [xingyizhou/CenterNet#172]
`python demo.py ctdet --demo ../images/16004479832_a748d55f21_k.jpg --load_model ../models/ctdet_coco_dla_2x.pth`

Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /media/e/hktxt/CV/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
QObject::moveToThread: Current thread (0x731d870) is not the object's thread (0x752caa0).
Cannot move to target thread (0x731d870)

Segmentation fault (core dumped)

I run the demo.py and got this issues. I use pytorch 0.4, cuda 8.0, ubuntu and gcc 4.9.3.

can anyone help?

**Comment by xingyizhou** [comment]
Can you try rebooting?

**Comment by hktxt** [comment]
@xingyizhou 
I tried. but reboot did not work.
I think missing '--' here in: https://github.com/xingyizhou/CenterNet/blob/master/src/lib/opts.py#L13
It will cause problem when run demo under pycharm.
I tired to debug and found that error showed up at this line： https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/debugger.py#L218. But，I don't know why...

**Comment by XiaoJiNu** [comment]
@hktxt @ xingyizhou I met the same problem and I tried rebooting, but it didn't work, what should i do ...

**Comment by hktxt** [comment]
@XiaoJiNu  there is nothing we can do. I got stuck on this issue for some days. Find out the problem on our own is the only way to go.

**Comment by hktxt** [comment]
@xingyizhou @XiaoJiNu 
I might find out what's the problem.
It's kind of opencv bug, as I said before error came when call cv2.imshow().
I fixed this by uninstall and then reinstall opencv.

**Comment by XiaoJiNu** [comment]
@hktxt thank you very much, i will try it

**Comment by XiaoJiNu** [comment]
hi @hktxt I did as you say but came out the same problem, I use pip 'install opencv-python' to install opencv whose version is  4.1.0.25,  what's the version of your opencv?

**Comment by hktxt** [comment]
It's 4.1.
basically, I use 'conda install -c conda-forge opencv'.
I use a canda virtual env on ubuntu.

**Comment by XiaoJiNu** [comment]
@hktxt Thank you very much, it works!

**Comment by priteshgohil** [comment]
I had the similar error. I guess it was caused by wrong compiler.
After updating  gcc compiler to latest https://github.com/xingyizhou/CenterNet/issues/29#issuecomment-487438162, I have followed following steps.

1.  cd $CenterNet_ROOT/src/lib/models/networks/DCNv2
2. python setup.py clean --all
3.  ./make.sh

This worked for me and may solve the problem.
