### ISSUE TITLE
How  to enhance  bbox  accuracy  ?

### ISSUE THREAD

**Issue by heartInsert** [xingyizhou/CenterNet#174]
I'm  doing   a   project    which  the   number  of  object    is  always  the  same.  So  I  need  to enhance  the  BBoxes  accuracy  even  0.1% .  I've   figure  out  a  way  about  solution.

1: I've  notice  the   'wh_weight'  is  assigned to  0.1  , So  is  it  worked  that  I  make  like below?
` wh_weight=(epoch/100).clamp(0.1,1) `  
So  it  is  slightly increased.

Is  there   any    good   advice    in   your   head ?
Hope  for  your   rely.

**Comment by xingyizhou** [comment]
That's a good thing to try and I am curious how it works. Actually `--wh_weight 0.05` will give a slight improvement on COCO with DLA model.
