### ISSUE TITLE
Using rotation_y and locaation in training 3d model

### ISSUE THREAD

**Issue by 123alaa** [xingyizhou/CenterNet#176]
Hi @xingyizhou ,

I have a simple question, I read your code for training 3d model on kitti, and i see that you did not use rotation_y and location of object in training, instead of this you calculate them from predicted alpha, 2d_box, depth? Is this correct? If this correct, so i can remove them from json file and i will got the same results, right?

Best,
Alaa

**Comment by xingyizhou** [comment]
Yes; Right.
