### ISSUE TITLE
a question about the eval_oracle_hm parameter 

### ISSUE THREAD

**Issue by ZhenLiuBuaa** [xingyizhou/CenterNet#177]
![image](https://user-images.githubusercontent.com/45850504/60478789-42c99980-9cb6-11e9-9dcc-b89df702b2b4.png)

how can i test the model with the eval_oracle_hm parameter and  get the result like above picture. i find in test process ,the eval_oracle_hm parameter has no effect on the test result.

**Comment by xingyizhou** [comment]
You will need to use main.py for that. e.g., `main.py ctdet xxxxxxx --test --eval_oracle_hm`. `test.py` does not have access to the ground truth data.

**Comment by ZhenLiuBuaa** [comment]
thank you very much!
