### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by sidney001** [xingyizhou/CenterNet#182]
python demo.py ctdet --demo ../images/ --load_model ../models/ctdet_coco_dla_2x.pth
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/caffe/CenterNet/src/lib/../../exp/ctdet/default
Traceback (most recent call last):
  File "demo.py", line 57, in <module>
    opt = opts().init()
  File "/home/caffe/CenterNet/src/lib/opts.py", line 359, in init
    dataset = Struct(default_dataset_info[opt.task])
  File "/home/caffe/CenterNet/src/lib/opts.py", line 357, in __init__
    self.__setattr__(k, v)
AttributeError: Struct instance has no attribute '__setattr__'

How can I solve this problem? Thanks

**Comment by xingyizhou** [comment]
Please make sure you have the correct python version and haven't modified the code.
