### ISSUE TITLE
about draw_umich_gaussian

### ISSUE THREAD

**Issue by moondaiy** [xingyizhou/CenterNet#185]
Hi  Thanks to your work .
Could you tell me , if i used focal loss , that draw_umich_gaussian  function will used in your code  , but in your paper , i think draw_msra_gaussian function may be better.

thanks for your reply.

**Comment by xingyizhou** [comment]
I haven't tried msra_gaussian for focal loss. I can't see why it can be better. Feel free to have a try if you are curious about that.

**Comment by zzl-997** [comment]
the parameter opt.hm_gauss isn't defined in opts.py, but it is used if I want to use draw_msra_gaussian function when opt.mse_loss is True
