### ISSUE TITLE
: cannot connect to X server

### ISSUE THREAD

**Issue by moranxiachong** [xingyizhou/CenterNet#186]
hi, when i run demo.py on an offline computer, got this error
": cannot connect to X server"

how to fix this?

thanks!

**Comment by xingyizhou** [comment]
You will need a screen if you want to visualize the output with opencv. Or you can `--debug 4` to dump the prediction to the disk.

**Comment by ViswanathaReddyGajjala** [comment]
I have tried --debug 4, but it is not working.

**Comment by wanghao14** [comment]
@xingyizhou I have tried --debug 4, but the error ":cannot connect to X server" still exists. I find the problem is in the [base_detector.py](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/detectors/base_detector.py#L139), where the results will always be output to the screen even though the value of debug is 4. The related codes should be modified, for example, I add a function named save_results in [ctdet.py](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/detectors/ctdet.py) to call the function used to save results in [debugger.py](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/debugger.py#L239).

**Comment by DrPeryCox** [comment]
> @xingyizhou I have tried --debug 4, but the error ":cannot connect to X server" still exists. I find the problem is in the [base_detector.py](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/detectors/base_detector.py#L139), where the results will always be output to the screen even though the value of debug is 4. The related codes should be modified, for example, I add a function named save_results in [ctdet.py](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/detectors/ctdet.py) to call the function used to save results in [debugger.py](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/debugger.py#L239).

could you please provide code of this function?

**Comment by pingnuttakrid** [comment]
> @xingyizhou I have tried --debug 4, but the error ":cannot connect to X server" still exists. I find the problem is in the [base_detector.py](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/detectors/base_detector.py#L139), where the results will always be output to the screen even though the value of debug is 4. The related codes should be modified, for example, I add a function named save_results in [ctdet.py](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/detectors/ctdet.py) to call the function used to save results in [debugger.py](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/debugger.py#L239).

Can you show me your code what you did? about function named save_results ,I need a lot of help

**Comment by zhongtao93** [comment]
Just commit line 139-140 and work without screen.
`    #if self.opt.debug >= 1:`
`    #  self.show_results(debugger, image, results)`

**Comment by sisrfeng** [comment]
> Just commit line 139-140 in the https://github.com/xingyizhou/CenterNet/blob/master/src/lib/detectors/base_detector.py and work without screen.
> ` #if self.opt.debug >= 1:`
> ` # self.show_results(debugger, image, results)`

After doing that, I get:
The output will be saved to  /root/c/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
tot 0.277s |load 0.012s |pre 0.183s |net 0.026s |dec 0.002s |post 0.055s |merge 0.001s |

but no img in exp/ctdet/default.

**Comment by priteshgohil** [comment]
Unfortunately this repo do not support saving images with result. This line `/root/c/src/lib/../../exp/ctdet/default` that author prints must be fixed if no images are provided for remote usage.

Read this https://github.com/xingyizhou/CenterNet/issues/500#issuecomment-572862510
