### ISSUE TITLE
关于bbox的gt生成

### ISSUE THREAD

**Issue by shuoshuoa** [xingyizhou/CenterNet#187]
作者你好，在生成gt时，我不太理解bbox的处理方式，bbox的gt也会随着特征图缩小4倍而缩小4倍吗？为什么bbox没有和image同时做数据增强处理？

**Comment by xingyizhou** [comment]
1. Yes. 
2. It is [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/sample/ctdet.py#L105).
