### ISSUE TITLE
损失值下不去

### ISSUE THREAD

**Issue by huang229** [xingyizhou/CenterNet#188]
这是一个新颖的目标检测理念， 非常感谢作者的开源共享。但我遇到一些问题，训练了pascalvoc2007目标检测数据，类别数目=20， batch_size = 8, 特征图尺寸128*128， 训练了20多个epoch，损失下不去，请问为什么？
total_loss:42.2115 cls_loss:40.0113 offset_loss:0.6196 size_loss:15.8061 learning_rate:0.000081000
total_loss:13.9295 cls_loss:11.4873 offset_loss:0.5177 size_loss:19.2449 learning_rate:0.000081000
total_loss:10.6922 cls_loss:8.3126 offset_loss:0.4995 size_loss:18.8012 learning_rate:0.000081000
total_loss:10.6922 cls_loss:8.3126 offset_loss:0.4995 size_loss:18.8012 learning_rate:0.000081000
total_loss:19.9303 cls_loss:17.2530 offset_loss:0.4911 size_loss:21.8619 learning_rate:0.000081000
total_loss:20.5976 cls_loss:17.9423 offset_loss:0.5158 size_loss:21.3951 learning_rate:0.000081000

**Comment by xingyizhou** [comment]
Hi, I am not able to provide help unless more information is provided. And usually not able to help debug if you have modified the code. You can `--debug 2` to visualize your training data.
