### ISSUE TITLE
更换其它基模型，是否任然有效？

### ISSUE THREAD

**Issue by huang229** [xingyizhou/CenterNet#189]
非常感谢您提供的开源共享，这是一个非常棒的idear。我训练中遇到一些困惑，我使用的pascalvoc2007数据，我更换了基础网络，使用了yolo3和yolo2的darknet53和darknet19，网络中没有deformable convolution和deformable RoI pooling层，你认为这能训练成功不，为什么？

**Comment by ImMrMa** [comment]
你换了为什么不直接看看训练结果？在这问作者这个有意思吗？

**Comment by xingyizhou** [comment]
I have no idea. Feel free to have a try.

**Comment by huang229** [comment]
我换了yolo系列的几个模型，训练pascalvoc2007数据，损失一直下不去，batchsize=8

**Comment by yutliu** [comment]
> 我换了yolo系列的几个模型，训练pascalvoc2007数据，损失一直下不去，batchsize=8

请问你解决了这个问题吗？我有类似的问题
