### ISSUE TITLE
main.py: error: the following arguments are required: task

### ISSUE THREAD

**Issue by YangYangGirl** [xingyizhou/CenterNet#192]
when I run the main.py：
cd src
python main.py ctdet --exp_id coco_dla_2x --batch_size 128 --master_batch 9 --lr 5e-4 --gpus 0,1,2,3,4,5,6,7 --num_workers 16 --num_epochs 230 lr_step 180,210

I met this error：
main.py: error: the following arguments are required: task

**Comment by YangYangGirl** [comment]
> when I run the main.py：
> cd src
> python main.py ctdet --exp_id coco_dla_2x --batch_size 128 --master_batch 9 --lr 5e-4 --gpus 0,1,2,3,4,5,6,7 --num_workers 16 --num_epochs 230 lr_step 180,210
> 
> I met this error：
> main.py: error: the following arguments are required: task

**Comment by YangYangGirl** [comment]
![image](https://user-images.githubusercontent.com/32426369/61055543-50082600-a424-11e9-9aec-4c9521a7b4c4.png)

**Comment by VRCMF** [comment]
You should give the parameters @YangYangGirl

**Comment by YangYangGirl** [comment]
Can you give me an example?The "ctdet"  which I add after "main.py" isn't the task parameter?

**Comment by VRCMF** [comment]
@YangYangGirl  The parameters are in the list on your console, u can check it out

**Comment by 201814476285951** [comment]
I have the same problem,if you can tell me how you solve it?

**Comment by 201814476285951** [comment]
> Can you give me an example?The "ctdet" which I added after "main.py" wasn't the task parameter?

I have the same problem,if you can tell me how you solve it?
