### ISSUE TITLE
Provide ONNX models where possible

### ISSUE THREAD

**Issue by gyenesvi** [xingyizhou/CenterNet#193]
Can you please provide ONNX models of those network that are possible to export to ONNX? It seems to me that at least some variants of CenterNet for object detection should not contain any special operations that could not be exported to ONNX, so it seems doable. However, it seems that multiple people (including myself) have tried to load the models available here and export them to ONNX and failed.

My attempts failed at loading models due to unwanted dependencies in the code base. I tried to import a single detector (CtdetDetector) but failed because importing that model depends on all other models in the code, which require cuda (I don't even have cuda GPU) and external nms op to be compiled, which is not required for this detector network as far as I understand.

**Comment by xingyizhou** [comment]
I honestly don't know what ONNX is and don't have a good motivation to learn this ...

**Comment by gyenesvi** [comment]
ONNX is a format for exporting your models so that others can use it outside of PyTorch as well. I believe that should be a good enough motivation, you probably want your research to be accessible to others as well. In the present format, your models cannot even easily be loaded in PyTorch as I explained above.

**Comment by Markusgami** [comment]
Just change the ouput of the network from dict to list, then it will work(without deformable conv)

**Comment by jinfagang** [comment]
@Markusgami  How do u remove these deformable conv?

**Comment by sezan92** [comment]
``` 
don't have a good motivation to learn this ..

```
making an open neural network model which can be used across all frameworks is enough of a motivation

**Comment by jinfagang** [comment]
I found there were people already done this, by exporting centernet to onnx

**Comment by sezan92** [comment]
> I found there were people already done this, by exporting centernet to onnx

can you give the link?

**Comment by jinfagang** [comment]
http://manaai.cn/aicodes_detail3.html?id=49 They have also accelerated centernet using TensorRT

**Comment by PankajJ08** [comment]
> http://manaai.cn/aicodes_detail3.html?id=49 They have also accelerated centernet using TensorRT

How to access mana ai code outside china?

**Comment by ckcraig01** [comment]
There will be always engineering people in the industrial society do the onnx converting, I agree to have the author focus on the research that he is good at (and that's reason why pytorch exists)

**Comment by EnricoBeltramo** [comment]
Here a example of conversion of CenterNet in ONNX:
https://github.com/CaoWGG/TensorRT-CenterNet
