### ISSUE TITLE
Train the model on my own data set

### ISSUE THREAD

**Issue by superjiajia26** [xingyizhou/CenterNet#197]
Hi,Sorry to bother you, when I use your own dataset to train the model,the following problem occurred. Pull loss、push loss and regr loss are zero.
training loss at iteration 7760: 5.049665927886963
focal loss at iteration 7760: 4.9249396324157715
pull loss at iteration 7760: 1.7944596493180143e-06
push loss at iteration 7760: 0.050008296966552734
regr loss at iteration 7760: 0.07471586763858795
training loss at iteration 7765: 0.38687416911125183
focal loss at iteration 7765: 0.38687416911125183
pull loss at iteration 7765: 0.0
push loss at iteration 7765: 0.0
regr loss at iteration 7765: 0.0
training loss at iteration 7770: 0.46406546235084534
focal loss at iteration 7770: 0.46406546235084534
pull loss at iteration 7770: 0.0
push loss at iteration 7770: 0.0
regr loss at iteration 7770: 0.0
training loss at iteration 7775: 0.2653082013130188
focal loss at iteration 7775: 0.2653082013130188
pull loss at iteration 7775: 0.0
push loss at iteration 7775: 0.0
regr loss at iteration 7775: 0.0
I am very confused, Is this reasonable?
Thanks,I look forward to hearing from you.

**Comment by xingyizhou** [comment]
I didn't use pull or push loss. You came to the wrong repo.
