### ISSUE TITLE
Flip augmentation in ddd model

### ISSUE THREAD

**Issue by 123alaa** [xingyizhou/CenterNet#198]
Hi @xingyizhou ,

You comment out the flip augmentation in ddd model, Did you try it, and it affect the performance? i want to add some augmentations to make the model better. So if you tried something that did not work, good to know.

See this line:
https://github.com/xingyizhou/CenterNet/blob/a5a0483beb0f9e8705f6dc67d8817275369cfa7e/src/lib/datasets/sample/ddd.py#L92

**Comment by xingyizhou** [comment]
Hi, this is a good question. The main reason is that we are not sure how the orientation annotation will change when the image flipped. I have tried changing `alpha` to `np.pi - alpha if alpha > 0 else - np.pi - alpha` and applying the flip augmentation. The performance is not being improved or hurt. Not sure if this is correct, will need to take a closer look at kitti.
