### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by 201814476285951** [xingyizhou/CenterNet#199]
python demo.py ctdet --demo /path/to/image/or/folder/or/video --load_model ../models/ctdet_coco_dla_2x.pth
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/ying/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 49, in demo
    ret = detector.run(image_name)
  File "/home/ying/CenterNet/src/lib/detectors/base_detector.py", line 105, in run
    images, meta = self.pre_process(image, scale, meta)
  File "/home/ying/CenterNet/src/lib/detectors/base_detector.py", line 38, in pre_process
    height, width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by PRYUS** [comment]
/path/to/image/or/folder/or/video 
You have to replace the above argument with the path to your image (or video) file (or folder)

**Comment by 201814476285951** [comment]
> /path/to/image/or/folder/or/video
> You have to replace the above argument with the path to your image (or video) file (or folder)

Thanks a lot.
