### ISSUE TITLE
DataLoader worker (pid 8107) is killed by signal: Killed. Details are lost due to multip│ rocessing. Rerunning with num_workers=0 may give better error trace

### ISSUE THREAD

**Issue by buaaJeremyduan** [xingyizhou/CenterNet#20]
When I ran the command " python main.py ctdet --exp_id coco_dla --batch_size 32 --master_batch 15 --lr 1.25e-4  --gpus 0,1", this error pop up after about half an hour. It may be related to opencv(getAffineTransfrom and warpAffine) in the dataloader, I think.

**Comment by xingyizhou** [comment]
I haven't met this before. It seems that people have this [issue](https://github.com/facebookresearch/maskrcnn-benchmark/issues/195) in maskrcnn-benchmark too, which does not use cv2.warpAffine. Did you install opencv via `conda install opencv` or `pip install opencv-python`? I observed conda gives a slow version and might be related to this issue.

**Comment by buaaJeremyduan** [comment]
Thanks for replay. Actually I follow the instructions in the INSTALL.MD ( pip install -r requirements.txt), My setting is Ubuntu16.06, cuda 8.0. In my opinion, the warpaffine part is to about to resized the img to fix size(512) since the rot angle is always 0, is that right? I am trying to replace that part to find out the bug.

**Comment by xingyizhou** [comment]
Yes, you can reimplement this. Although I still thought it is not the problem ...

**Comment by qingnanli** [comment]
@buaaJeremyduan Hi, have you sovled this problem? I met the same problem....https://github.com/xingyizhou/CenterNet/issues/566
