### ISSUE TITLE
Batch Inference

### ISSUE THREAD

**Issue by aj-ames** [xingyizhou/CenterNet#204]
How do I perform batch inference? I have a Titan RTX 24GB and I want to run at maximum FPS at inference by utilizing the entire GPU memory.

**Comment by xingyizhou** [comment]
Unfortunately, this is not supported in this repo.

**Comment by aj-ames** [comment]
Thank you for your reply @xingyizhou 
However, how would it be possible to go about it? I changed a bit of code in ctdet.py and basedetector.py and it worked. However, I'm able to only pass a batch of size 14 and got fps of 126. The memory utilised was about 3GB.

**Comment by elepherai** [comment]
@aj-ames Hi, have you solved this problem?

**Comment by hyperparameters** [comment]
Hello @aj-ames I also tried implementation for batch inference but there are some random incorrect predictions in the batch, what can cause this problem can you share your implementation
