### ISSUE TITLE
ctdet_post_process()

### ISSUE THREAD

**Issue by XiaoJiNu** [xingyizhou/CenterNet#206]
Could you please explain how does ctdet_post_process(dets, c, s, h, w, num_classes), transform_preds,  get_affine_transform and affine_transform  work?  I‘m confused about it

**Comment by xingyizhou** [comment]
Basically, `post process` converts the coordinate in the output heatmap (4x downsampled, in some case crop-and-resized) to the original image. The code is from MSRA human pose simple baseline repo. I haven't read them line-by-line.
