### ISSUE TITLE
make.sh

### ISSUE THREAD

**Issue by qh332612340** [xingyizhou/CenterNet#207]
hi 
when I run the make.sh, had no input files error as below:

 qiuhan@qiuhan-MS-7A75:~/PycharmProjects/untitled/CenterNet-3-153/src/lib/models/networks/DCNv2$ source make.sh
: 没有那个文件或目录
：未找到命令
gcc-5: error: dcn_v2_im2col_cuda.cu: 没有那个文件或目录
gcc-5: warning: ‘-x c++’ after last input file has no effect
’
gcc-5: fatal error: no input files
compilation terminated.
gcc-5: error: dcn_v2_im2col_cuda_double.cu: 没有那个文件或目录
gcc-5: warning: ‘-x c++’ after last input file has no effect
’
gcc-5: fatal error: no input files
compilation terminated.
：未找到命令
gcc-5: error: dcn_v2_psroi_pooling_cuda.cu: 没有那个文件或目录
gcc-5: warning: ‘-x c++’ after last input file has no effect
’
gcc-5: fatal error: no input files
compilation terminated.
gcc-5: error: dcn_v2_psroi_pooling_cuda_double.cu: 没有那个文件或目录
gcc-5: warning: ‘-x c++’ after last input file has no effect
’
gcc-5: fatal error: no input files
compilation terminated.
：未找到命令
: 无效选项-
cd: 用法: cd [-L|[-P [-e]] [-@]] [dir]
': [Errno 2] No such file or directory
': [Errno 2] No such file or directorypy

how can I solve this error?

**Comment by leon1581** [comment]
试试看装一下Cython

**Comment by qh332612340** [comment]
装过Cython了 ， nms.pyx已经编译过了
我试了下不用make.sh     直接在终端执行make.sh里的代码，能运行
但是还是不知道什么原因，直接执行make.sh就报错

**Comment by xingyizhou** [comment]
I have no idea. Can you check if there is a difference between `source make.sh` and `./make.sh` or `bash make.sh`?

**Comment by qh332612340** [comment]
I checked it， but I got the same error

**Comment by ayuanjng** [comment]
> hi
> when I run the make.sh, had no input files error as below:
> 
> qiuhan@qiuhan-MS-7A75:~/PycharmProjects/untitled/CenterNet-3-153/src/lib/models/networks/DCNv2$ source make.sh
> : 没有那个文件或目录
> ：未找到命令
> gcc-5: error: dcn_v2_im2col_cuda.cu: 没有那个文件或目录
> gcc-5: warning: ‘-x c++’ after last input file has no effect
> ’
> gcc-5: fatal error: no input files
> compilation terminated.
> gcc-5: error: dcn_v2_im2col_cuda_double.cu: 没有那个文件或目录
> gcc-5: warning: ‘-x c++’ after last input file has no effect
> ’
> gcc-5: fatal error: no input files
> compilation terminated.
> ：未找到命令
> gcc-5: error: dcn_v2_psroi_pooling_cuda.cu: 没有那个文件或目录
> gcc-5: warning: ‘-x c++’ after last input file has no effect
> ’
> gcc-5: fatal error: no input files
> compilation terminated.
> gcc-5: error: dcn_v2_psroi_pooling_cuda_double.cu: 没有那个文件或目录
> gcc-5: warning: ‘-x c++’ after last input file has no effect
> ’
> gcc-5: fatal error: no input files
> compilation terminated.
> ：未找到命令
> : 无效选项-
> cd: 用法: cd [-L|[-P [-e]] [-@]] [dir]
> ': [Errno 2] No such file or directory
> ': [Errno 2] No such file or directorypy
> 
> how can I solve this error?

> 装过Cython了 ， nms.pyx已经编译过了
> 我试了下不用make.sh 直接在终端执行make.sh里的代码，能运行
> 但是还是不知道什么原因，直接执行make.sh就报错

我解决这个问题了，把仓库删掉，然后重新git，一步一步编译，就好了。我也觉得很莫名其妙

**Comment by TheProjectM** [comment]
> > hi
> > when I run the make.sh, had no input files error as below:
> > qiuhan@qiuhan-MS-7A75:~/PycharmProjects/untitled/CenterNet-3-153/src/lib/models/networks/DCNv2$ source make.sh
> > : 没有那个文件或目录
> > ：未找到命令
> > gcc-5: error: dcn_v2_im2col_cuda.cu: 没有那个文件或目录
> > gcc-5: warning: ‘-x c++’ after last input file has no effect
> > ’
> > gcc-5: fatal error: no input files
> > compilation terminated.
> > gcc-5: error: dcn_v2_im2col_cuda_double.cu: 没有那个文件或目录
> > gcc-5: warning: ‘-x c++’ after last input file has no effect
> > ’
> > gcc-5: fatal error: no input files
> > compilation terminated.
> > ：未找到命令
> > gcc-5: error: dcn_v2_psroi_pooling_cuda.cu: 没有那个文件或目录
> > gcc-5: warning: ‘-x c++’ after last input file has no effect
> > ’
> > gcc-5: fatal error: no input files
> > compilation terminated.
> > gcc-5: error: dcn_v2_psroi_pooling_cuda_double.cu: 没有那个文件或目录
> > gcc-5: warning: ‘-x c++’ after last input file has no effect
> > ’
> > gcc-5: fatal error: no input files
> > compilation terminated.
> > ：未找到命令
> > : 无效选项-
> > cd: 用法: cd [-L|[-P [-e]] [-@]] [dir]
> > ': [Errno 2] No such file or directory
> > ': [Errno 2] No such file or directorypy
> > how can I solve this error?
> 
> > 装过Cython了 ， nms.pyx已经编译过了
> > 我试了下不用make.sh 直接在终端执行make.sh里的代码，能运行
> > 但是还是不知道什么原因，直接执行make.sh就报错
> 
> 我解决这个问题了，把仓库删掉，然后重新git，一步一步编译，就好了。我也觉得很莫名其妙

我遇到了相同的问题，我这边的原因是因为我实在window下clone的，然后同步到linux下，因此导致了一些编码的问题。  后面删除掉重新在linux下clone然后make.sh就好了。
