### ISSUE TITLE
ASSERT: "false" in file qasciikey.cpp, line 501

### ISSUE THREAD

**Issue by leon1581** [xingyizhou/CenterNet#208]
when run the demo for the video in the Ubuntu server:
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/gongliang/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
ASSERT: "false" in file qasciikey.cpp, line 501
已放弃 (核心已转储)

how to deal with it?

**Comment by xingyizhou** [comment]
I have no idea. I don't think the `quasciikey.cpp` is from this repo.

**Comment by lan786** [comment]
@leon1581  It worked for me 
pip install qtconsole

**Comment by lsccccc** [comment]
For me, this error happens when I try to  simultaneously show the original video and the processed video.
`cv2.imshow('input', img) # line 29 in demo.py
self.show_results(debugger, image, results) # line 140 in base_detector.py
` 
I can solve the problem by comment line 29 in demo.py

**Comment by xizaoqu** [comment]
https://blog.csdn.net/qxqxqzzz/article/details/104942021

maybe this will help
