### ISSUE TITLE
What's the meaning of "agnex"?

### ISSUE THREAD

**Issue by Epiphqny** [xingyizhou/CenterNet#209]

**Comment by xingyizhou** [comment]
Where is it from?

**Comment by Epiphqny** [comment]
> Where is it from?

https://github.com/xingyizhou/CenterNet/issues/209#issuecomment-511980080

**Comment by Epiphqny** [comment]
> Where is it from?

https://github.com/xingyizhou/CenterNet/blob/819e0d0dde02f7b8cb0644987a8d3a370aa8206a/src/lib/trains/exdet.py#L13

**Comment by xingyizhou** [comment]
Oh it is short for `category-agnostic extreme points`. This is never used in this repo.
