### ISSUE TITLE
Possible BUG when evaluating PASCAL format mAP?

### ISSUE THREAD

**Issue by liuchang8am** [xingyizhou/CenterNet#21]
Following experiments script, test.py for pretrained model pascal_resdcn18_384, the evaluation result is as shown in the figure:

![image](https://user-images.githubusercontent.com/1009550/56549975-eb70c400-65b6-11e9-8ed3-c390b4241b6c.png)

`python3 test.py ctdet --exp_id pascal_resdcn18_384 --arch resdcn_18 --dataset pascal --load_model ~/data/models/pytorch/CenterNet/ctdet_pascal_resdcn18_384.pth`

where "ctdet_pascal_resdcn18_384.pth" is provided in ModelZoo.

Anyone else has the same issue? Is this a bug or my incorrect configuration (following DATA.md PASCAL VOC)

**Comment by xingyizhou** [comment]
It works fine in my machine. Do you see some abnormal logs when loading the model? Can you add `--debug 2` to your command to visualize the heatmap outputs?

**Comment by liuchang8am** [comment]
> It works fine in my machine. Do you see some abnormal logs when loading the model? Can you add `--debug 2` to your command to visualize the heatmap outputs?

No abnormal logs are observed. with `--debug 2` the visualizations are correct. Output log is attached, bar processing is not shown in the log.

[resdcn_18_test.log](https://github.com/xingyizhou/CenterNet/files/3105618/resdcn_18_test.log)

**Comment by xingyizhou** [comment]
I have fixed a pickle version bug. Can you remove `data/voc/VOCdevkit/VOC2007/ImageSets/Main/test.txt_annots.pkl` and try the current version?

**Comment by liuchang8am** [comment]
> I have fixed a pickle version bug. Can you remove `data/voc/VOCdevkit/VOC2007/ImageSets/Main/test.txt_annots.pkl` and try the current version?

I've updated the code as https://github.com/xingyizhou/CenterNet/blob/d56bfd94cfe8c4697ebca8829a2c18a637480a7d/src/tools/voc_eval_lib/datasets/voc_eval.py#L122
and remove the cachefile` test.txt_annots.pkl`, but the eval results seems unchanged. I've uploaded the generated `test.txt_annots.pkl` and bboxes results for reference:
https://drive.google.com/file/d/1mxQsu0vUsoVUw2H5FokQwynsw_ndMikr/view?usp=sharing
https://drive.google.com/file/d/1XO14VNnqQzjjouhRSbiMbClCrohJ3QN6/view?usp=sharing

**Comment by moothes** [comment]
I have the same problem. I find that maybe it's cause by the image orders in Dataset. 
I modify the test.py :
  ```
class PrefetchDataset(torch.utils.data.Dataset):
    def __init__(self, opt, dataset, pre_process_func):
    self.images = dataset.images
    print(self.images[:20])
    self.load_image_func = dataset.coco.loadImgs
    self.img_dir = dataset.img_dir
    self.pre_proces
    ...
```
It print:
![捕获](https://user-images.githubusercontent.com/17693547/56574940-124eea80-65f7-11e9-974f-026fd058bb18.JPG)

And I modify src/tools/voc_eval_lib/datasets/pascal_voc.py：
```
  def _write_voc_results_file(self, all_boxes):
    print(self.image_index[:20])
    ...
```
It print:
![捕获](https://user-images.githubusercontent.com/17693547/56575230-d10b0a80-65f7-11e9-91da-d146d876f08c.JPG)

I think this is the reason. So I add `sort()` in test.py :
  ```
class PrefetchDataset(torch.utils.data.Dataset):
    def __init__(self, opt, dataset, pre_process_func):
    self.images = dataset.images
    self.images.sort()
    self.load_image_func = dataset.coco.loadImgs
    self.img_dir = dataset.img_dir
    self.pre_proces
    ...
```
I get an acceptable results with flip test:
![捕获](https://user-images.githubusercontent.com/17693547/56575444-4971cb80-65f8-11e9-8b02-6ee92034c172.JPG)
Hope this can help you fix this bug.
@xingyizhou

**Comment by moothes** [comment]
Since add `sort()` in test.py maybe not suitable for coco dataset, I move the `sort()` function to src/lib/datasets/dataset/pascal.py:
```
def __init__(self, opt, split):
    ...
    self.images = self.coco.getImgIds()       \\ line 49
    self.images.sort()
    ...
```
The results are the same.

**Comment by xingyizhou** [comment]
Hi, 
  Thanks for pointing it out! There is indeed a bug in converting the evaluation format. However in my machine, the image ids are sorted itself. I have [fixed](https://github.com/xingyizhou/CenterNet/commit/a412990c06c3a3e3e77e9605d90deb0523090f37) this by fixing the image id when saving them to the disk.

**Comment by liuchang8am** [comment]
> Since adds `sort()` in test.py maybe not suitable for coco dataset, I move the `sort()` function to src/lib/datasets/dataset/pascal.py:
> 
> ```
> def __init__(self, opt, split):
>     ...
>     self.images = self.coco.getImgIds()       \\ line 49
>     self.images.sort()
>     ...
> ```
> The results are the same.

This is indeed the cause. I can get proper mAP after adding sort(). Thanks a lot! Closing the issue.
