### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'  when  evaluating the pascal model

### ISSUE THREAD

**Issue by studyharderer** [xingyizhou/CenterNet#212]
first of all , thank you for sharing your wonderful work!!!

when i am using your code to evaluating  the AP of the pascal voc model , i meet this error
'python test.py ctdet --exp_id dla --dataset pascal --load_model ../models/ctdet_pascal_dla.pth --flip_test' 

/home/zhengyu/anaconda3/envs/CenterNet/bin/python3.6 /home/zhengyu/CenterNet/CenterNet/src/test.py ctdet --exp_id dla --dataset pascal --load_model ../models/ctdet_pascal_dla_384.pth --flip_test
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/zhengyu/CenterNet/CenterNet/src/lib/../../exp/ctdet/dla
heads {'hm': 20, 'wh': 2, 'reg': 2}
Namespace(K=100, aggr_weight=0.0, agnostic_ex=False, arch='dla_34', aug_ddd=0.5, aug_rot=0, batch_size=32, cat_spec_wh=False, center_thresh=0.1, chunk_sizes=[32], data_dir='/home/zhengyu/CenterNet/CenterNet/src/lib/../../data', dataset='pascal', debug=0, debug_dir='/home/zhengyu/CenterNet/CenterNet/src/lib/../../exp/ctdet/dla/debug', debugger_theme='white', demo='', dense_hp=False, dense_wh=False, dep_weight=1, dim_weight=1, down_ratio=4, eval_oracle_dep=False, eval_oracle_hm=False, eval_oracle_hmhp=False, eval_oracle_hp_offset=False, eval_oracle_kps=False, eval_oracle_offset=False, eval_oracle_wh=False, exp_dir='/home/zhengyu/CenterNet/CenterNet/src/lib/../../exp/ctdet', exp_id='dla', fix_res=True, flip=0.5, flip_test=True, gpus=[0], gpus_str='0', head_conv=256, heads={'hm': 20, 'wh': 2, 'reg': 2}, hide_data_time=False, hm_hp=True, hm_hp_weight=1, hm_weight=1, hp_weight=1, input_h=384, input_res=384, input_w=384, keep_res=False, kitti_split='3dop', load_model='../models/ctdet_pascal_dla_384.pth', lr=0.000125, lr_step=[90, 120], master_batch_size=32, mean=array([[[0.485, 0.456, 0.406]]], dtype=float32), metric='loss', mse_loss=False, nms=False, no_color_aug=False, norm_wh=False, not_cuda_benchmark=False, not_hm_hp=False, not_prefetch_test=False, not_rand_crop=False, not_reg_bbox=False, not_reg_hp_offset=False, not_reg_offset=False, num_classes=20, num_epochs=140, num_iters=-1, num_stacks=1, num_workers=4, off_weight=1, output_h=96, output_res=96, output_w=96, pad=31, peak_thresh=0.2, print_iter=0, rect_mask=False, reg_bbox=True, reg_hp_offset=True, reg_loss='l1', reg_offset=True, resume=False, root_dir='/home/zhengyu/CenterNet/CenterNet/src/lib/../..', rot_weight=1, rotate=0, save_all=False, save_dir='/home/zhengyu/CenterNet/CenterNet/src/lib/../../exp/ctdet/dla', scale=0.4, scores_thresh=0.1, seed=317, shift=0.1, std=array([[[0.229, 0.224, 0.225]]], dtype=float32), task='ctdet', test=False, test_scales=[1.0], trainval=False, val_intervals=5, vis_thresh=0.3, wh_weight=0.1)
==> initializing pascal test2007 data.
loading annotations into memory...
Done (t=0.09s)
creating index...
index created!
Loaded val 4952 samples
Creating model...
loaded ../models/ctdet_pascal_dla_384.pth, epoch 70
Drop parameter base.fc.weight.
Drop parameter base.fc.bias.
Traceback (most recent call last):
  File "tools/reval.py", line 19, in <module>
    from src.tools.voc_eval_lib.model.test import apply_nms
  File "/home/zhengyu/CenterNet/CenterNet/src/tools/voc_eval_lib/model/test.py", line 24, in <module>
    from ..utils.blob import im_list_to_blob
  File "/home/zhengyu/CenterNet/CenterNet/src/tools/voc_eval_lib/utils/blob.py", line 14, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

The result.json file has been generated, but the error is that the cv2 module could not be found.
But I am sure that cv2 is indeed installed . In pycharm I can click cv2 to enter the inside of the module .

what‘s more In the place where the error is reported , it also shows that this module cannot be found if I import progress or easydict .
how can i solve it? thanks!!!!

**Comment by xingyizhou** [comment]
Please make sure you are running in the same conda environment between your pycharm and command line (`conda activate CenterNet`).

**Comment by studyharderer** [comment]
I found that using the command line directly will not encounter this error, it may be caused by my pycharm environment settings ! thank you !
