### ISSUE TITLE
Request of some details

### ISSUE THREAD

**Issue by Gouiaa** [xingyizhou/CenterNet#214]
I am implementing CenterNet from scratch using tensorflow. At the beginning, I am really interested in pose estimation part. Thanks in advance for your time.

Here are my questions.
 1) I implemented DLA34, without Deformable convolution, because it costs a lot of time using high level tensorflow? Did you try DLA34 with traditional conv2d?
2) My big question is about how to generate the ground truth to calculate the losses in the case of object detection and pose estimation

    a-1) Heat map in object detection (bounding box):  Generate the gaussian heatmap which indicates a gaussian radius around the bounding box center for each object in the image (section 3) ?

   a-2) Heatmap in pose estimation: Generate the gaussian heatmap which indicates a gaussian radius around every joint (17 joints)  (section 4.2)?
This is used to calculate the L_k loss in both cases ?

    b-1) Local offset  (boundingbox): for every bounding box center point, we calculate the offset as indicated in equation 2) L_off
    b-2)    Local offset (pose estimation) : for every joint (17 joints), we calculate its offset to the center of the bounding box ?

c-1) L_size (bbox): for every bounding box center, we save the height and the width of the bbox in the S_k map , for all objects in the image (equation) ?
c-2) This is used in both cases(pose estimation and object detection)?
Now suppose that I want to use Coco dataset to do pose person detection and pose estimation, Should I consider two branches ?

I have also a confusion in figure 4 between joint locations[kx2] (which described by J and called joint offsets in section 4.2) and joint offset[2](I don't know what is this!)

**Comment by xingyizhou** [comment]
1. https://github.com/xingyizhou/CenterNet/issues/109#issuecomment-502427224
2. All cases look reasonable, feel free to have a try.
3. Joint offset[2] is should be joint local offset. It is similar to the center point local offset. It is used to recover the 4x downsampling for the human keypoint heatmap.
