### ISSUE TITLE
dist must be a Distribution instance

### ISSUE THREAD

**Issue by lbq779660843** [xingyizhou/CenterNet#22]
Hi,

I ran 'make.sh' in windows and met the problem in line 39 of 'build.py', how can i fix it?

Thanks!

**Comment by cclauss** [comment]
https://github.com/xingyizhou/CenterNet/blob/master/src/lib/models/networks/DCNv2/build.py#L39

**Comment by xingyizhou** [comment]
Hi,
  I haven't tried windows. Can you check [this](https://github.com/xingyizhou/CenterNet/issues/7)?

**Comment by ausk** [comment]
I commented the line: `extra_compile_args=extra_compile_args,`

**Comment by ThreeChen** [comment]
i solved this issue by install DCNv2 from the origin repo. maybe you should git clone the DCNv2 origin, place it in the same place , and change to the 0.40(or 0.41) pytorch version branch. Then install it.

**Comment by mk123qwe** [comment]
> i solved this issue by install DCNv2 from the origin repo. maybe you should git clone the DCNv2 origin, place it in the same place , and change to the 0.40(or 0.41) pytorch version branch. Then install it.

I can not git clone DCNv2 origin 0.41) pytorch version branch.Links do not exist.

**Comment by ThreeChen** [comment]
just follow the instructions here:
https://github.com/CharlesShang/DCNv2

git checkout pytorch_0.4
