### ISSUE TITLE
test error on my voc-style dataset

### ISSUE THREAD

**Issue by kknoob** [xingyizhou/CenterNet#221]
When I use the following code to test on pascal voc 2007 dataset:

`python test.py ctdet --not_prefetch_test --dataset detection --exp_id det2  --load_model F:\kuyanfeng\CenterNet\exp\ctdet\det2\model_best.pth  --gpus 0 --num_workers 0 --flip_test`

I encountered an error:

`det2 |################################| [356/357]|Tot: 0:00:35 |ETA: 0:00:01 |tot 0.097 |load 0.004 |pre 0.026 |net 0.059 |dec 0.005 |post 0.003 |merge 0.000
Evaluating detections
VOC07 metric? Yes
Traceback (most recent call last):
  File "tools/reval.py", line 78, in <module>
    from_dets(imdb_name, args.detection_file, args)
  File "tools/reval.py", line 71, in from_dets
    imdb.evaluate_detections(nms_dets)
  File "tools\voc_eval_lib\datasets\pascal_voc.py", line 284, in evaluate_detections
    self._do_python_eval(output_dir)
  File "tools\voc_eval_lib\datasets\pascal_voc.py", line 244, in _do_python_eval
    use_07_metric=use_07_metric, use_diff=self.config['use_diff'])
  File "tools\voc_eval_lib\datasets\voc_eval.py", line 116, in voc_eval
    recs[imagename] = parse_rec(annopath.format(imagename))
  File "tools\voc_eval_lib\datasets\voc_eval.py", line 17, in parse_rec
    tree = ET.parse(filename)
  File "E:\Anaconda\envs\pytorch\lib\xml\etree\ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "E:\Anaconda\envs\pytorch\lib\xml\etree\ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '10015_AB0821_aug_4.xml'`

How to solve it? Where should the XML file be placed? Thanks a lot

**Comment by xingyizhou** [comment]
Hi, if you follow the [pascal setup code](https://github.com/xingyizhou/CenterNet/blob/master/src/tools/get_pascal_voc.sh), they should be properly placed automatically. If this is not the case, it is also possible that the issue is from the path format of windows. E.g,. I am aware (but not sure) that `os.path.join` does not work well for windows. You can check this by print the corresponding paths in the evaluation script. Or just try changing every os.path.join in the script to something like `path = path1 + path2`.

**Comment by kknoob** [comment]
> Hi, if you follow the [pascal setup code](https://github.com/xingyizhou/CenterNet/blob/master/src/tools/get_pascal_voc.sh), they should be properly placed automatically. If this is not the case, it is also possible that the issue is from the path format of windows. E.g,. I am aware (but not sure) that `os.path.join` does not work well for windows. You can check this by print the corresponding paths in the evaluation script. Or just try changing every os.path.join in the script to something like `path = path1 + path2`.

Thanks a lot ! I find the problem.
It occurs 
` annopath = os.path.join(self._devkit_path,
      'VOC' + self._year,
      'Annotations'),'{:s}.xml')`
in `def  _do_python_eval` in `pascal_voc.py`
os.path.join() can't stitch this path,so annopath is '{:s}.xml' after this code.

I modified function interface in `def voc_eval` in `voc_eval.py` .
Added `annodir` to  pass parameters ‘annodir = os.path.join(self._devkit_path,'VOC' + self._year,'Annotations')’
