### ISSUE TITLE
cuda runtime error in training

### ISSUE THREAD

**Issue by se7enXF** [xingyizhou/CenterNet#226]
## environment
* OS: Ubuntu 16.04  
* GPU: 4*RTX2080ti
* Python: 3.6  
* Pytorch: 0.4.1  
* CUDA&cuDNN: 9.1&7.0, 10.1&7.6  
## Why two CUDA    
The CUDA9.1 was installed before for using tensorflow. I directly clone your repo and want to 
train my own data but failed. I check the issues and find that RTX20** GPU works well with 
CUDA10, so I install the last. But it seems like no effect cause the same error arise.   
## About Opts
I check the issues list and find some samiliar problems.   
* One like mult threads dataloader may cause the porblem. It still not work if I set  'num_workers=0'.   
* One like GPU overflow. It still not work if I set 'batch_size' very small.   
* One like mult GPU cause some problems. It still not work if I only use GPU0.  
* I also try different choice of 'head_conv' and still not work.  
## Here is the outputs of command line
```python
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /data/cver1/CenterNet/src/lib/../../exp/ctdet/thz_1
heads {'hm': 20, 'wh': 2, 'reg': 2}
Namespace(K=100, aggr_weight=0.0, agnostic_ex=False, arch='res_101', aug_ddd=0.5, aug_rot=0, batch_size=32, cat_spec_wh=False, center_thresh=0.1, chunk_sizes=[32], data_dir='/data/cver1/CenterNet/src/lib/../../data', dataset='pascal', debug=0, debug_dir='/data/cver1/CenterNet/src/lib/../../exp/ctdet/thz_1/debug', debugger_theme='white', demo='', dense_hp=False, dense_wh=False, dep_weight=1, dim_weight=1, down_ratio=4, eval_oracle_dep=False, eval_oracle_hm=False, eval_oracle_hmhp=False, eval_oracle_hp_offset=False, eval_oracle_kps=False, eval_oracle_offset=False, eval_oracle_wh=False, exp_dir='/data/cver1/CenterNet/src/lib/../../exp/ctdet', exp_id='thz_1', fix_res=True, flip=0.5, flip_test=False, gpus=[0], gpus_str='0', head_conv=64, heads={'hm': 20, 'wh': 2, 'reg': 2}, hide_data_time=False, hm_hp=True, hm_hp_weight=1, hm_weight=1, hp_weight=1, input_h=384, input_res=384, input_w=384, keep_res=False, kitti_split='3dop', load_model='', lr=0.000125, lr_step=[90, 120], master_batch_size=32, mean=array([[[0.485, 0.456, 0.406]]], dtype=float32), metric='loss', mse_loss=False, nms=False, no_color_aug=False, norm_wh=False, not_cuda_benchmark=False, not_hm_hp=False, not_prefetch_test=False, not_rand_crop=False, not_reg_bbox=False, not_reg_hp_offset=False, not_reg_offset=False, num_classes=20, num_epochs=140, num_iters=-1, num_stacks=1, num_workers=4, off_weight=1, output_h=96, output_res=96, output_w=96, pad=31, peak_thresh=0.2, print_iter=0, rect_mask=False, reg_bbox=True, reg_hp_offset=True, reg_loss='l1', reg_offset=True, resume=False, root_dir='/data/cver1/CenterNet/src/lib/../..', rot_weight=1, rotate=0, save_all=False, save_dir='/data/cver1/CenterNet/src/lib/../../exp/ctdet/thz_1', scale=0.4, scores_thresh=0.1, seed=317, shift=0.1, std=array([[[0.229, 0.224, 0.225]]], dtype=float32), task='ctdet', test=False, test_scales=[1.0], trainval=False, val_intervals=5, vis_thresh=0.3, wh_weight=0.1)
Creating model...
=> loading pretrained model https://download.pytorch.org/models/resnet101-5d3b4d8f.pth
Setting up data...
==> initializing pascal train data.
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Loaded train 1845 samples
==> initializing pascal train data.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loaded train 1845 samples
Starting training...
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "/data/cver1/CenterNet/src/main.py", line 102, in <module>
    main(opt)
  File "/data/cver1/CenterNet/src/main.py", line 69, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/data/cver1/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/data/cver1/CenterNet/src/lib/trains/base_trainer.py", line 69, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/usr/local/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cver1/CenterNet/src/lib/trains/base_trainer.py", line 19, in forward
    outputs = self.model(batch['input'])
  File "/usr/local/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/cver1/CenterNet/src/lib/models/networks/msra_resnet.py", line 212, in forward
    x = self.conv1(x)
  File "/usr/local/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663
```

**Comment by xingyizhou** [comment]
Thanks for providing the very detailed information. It might be a pytorch installation issue (THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
T). check [here](https://github.com/pytorch/pytorch/issues/15797).

**Comment by se7enXF** [comment]
Thank you for reply. I follow your advice and finally the code works. Here are the details may help other people. This issue may solve the ***problems in using RTX2xxx GPUs***.  
1. Install cuda10,  cudaa7.6  
2. Install pytorch1.0  
3. Follow [this issue](https://github.com/xingyizhou/CenterNet/issues/3) replace the DCN for building  
4. Follow [INSTALL.md](https://github.com/xingyizhou/CenterNet/blob/master/readme/INSTALL.md) do what necessary  
---  
Thanks CenterNet!

**Comment by JaneHJ** [comment]
I happened to find that this error only raise once, so there is a crazy way to solve this problem...
1- First add the following scripts at the beginning. then the error 'THCudaCheck FAIL file=.../src/THC/THCGeneral.cpp line=663 error=11 : invalid argument'.
```
try:
    from torchvision.models import vgg16
    model = vgg16().cuda()
    x = torch.zeros((32, 3, 227, 227)).cuda()
    model(x)
except:
    pass
```
2- Just ignore it and continue to run.
3-  It works!

Crazy...but it works, again!

**Comment by YuhaoYeSteve** [comment]
> I happened to find that this error only raise once, so there is a crazy way to solve this problem...
> 1- First add the following scripts at the beginning. then the error 'THCudaCheck FAIL file=.../src/THC/THCGeneral.cpp line=663 error=11 : invalid argument'.
> 
> ```
> try:
>     from torchvision.models import vgg16
>     model = vgg16().cuda()
>     x = torch.zeros((32, 3, 227, 227)).cuda()
>     model(x)
> except:
>     pass
> ```
> 
> 2- Just ignore it and continue to run.
> 3- It works!
> 
> Crazy...but it works, again!

Does not work for me
