### ISSUE TITLE
When training , we still have the bug: "NoneType" object has no attribute 'shape'

### ISSUE THREAD

**Issue by DD0922** [xingyizhou/CenterNet#228]
We run the code with the command:

`python main.py ctdet --exp_id coco_dla_2x --batch_size 1 --master_batch 9 --lr 5e-4 --gpus 0,1 --num_workers 2 --num_epochs 230`

**To debug , we print the image path before the 'img = cv2.imread(path)'.**

Unfortunately ,  we meet the problem:
`Starting training...
ctdet/coco_dla_2xctdet:path
/home/fc10382/CenterNet/src/lib/../../data/coco/train2017/000000550133.jpg
ctdet:path
/home/fc10382/CenterNet/src/lib/../../data/coco/train2017/000000392793.jpg
ctdet:path
/home/fc10382/CenterNet/src/lib/../../data/coco/train2017/000000107628.jpg
ctdet:path
/home/fc10382/CenterNet/src/lib/../../data/coco/train2017/000000154931.jpg
Traceback (most recent call last):
  File "main.py", line 102, in <module>
ctdet:path
/home/fc10382/CenterNet/src/lib/../../data/coco/train2017/000000215889.jpg
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/fc10382/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/fc10382/CenterNet/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/fc10382/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/fc10382/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/fc10382/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/fc10382/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/fc10382/CenterNet/src/lib/datasets/sample/ctdet.py", line 40, in __getitem__
    height, width = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'`

Could you help me?
Thanks!

**Comment by DD0922** [comment]
Is the problem related with the dataset named COCO???

**Comment by DD0922** [comment]
Some images can be trained , most images can't.
And the number of images which can be trained  is  related with the batch_size and  num_workers.

**Comment by xingyizhou** [comment]
Can you check if the files in your printed path actually exist?

**Comment by Gaochunyang1314** [comment]
you can read these images by cv2 with the path you printed and check if the same question occur

**Comment by DD0922** [comment]
Thanks.

But we meet another problem:
we print the path and insert the code in  **ctdet.py**:
`
print(self.img_dir)
print(os.path.exists(self.img_dir)
print('img_path')  #we change to the absolute path before
                            #/home/fc10382/CenterNet/src/lib/../../data/coco/images/train2017
print(os.path.exists(img_path))
  `
And the bug is :

`ctdet/coco_dla_2x/home/fc10382/CenterNet/src/lib/../../data/coco/train2017
False
img_path
True
`
We don't know the reason why self.img_dir begins with 'cedet/coco_dla_2x' and the 'images/' vanishes?

**Comment by VRCMF** [comment]
@xingyizhou  The problem is the dataset path that u give us. You could check my issue #190

**Comment by DD0922** [comment]
3Q very much!
We found the error:  we created the directory:images uncorrectly.
We put the train2017,val2017,test2017 in the 'coco' directory and it ran well.

**Comment by omeralierdemir** [comment]
Can you write your directories path ? I want to check my paths
