### ISSUE TITLE
Undefined name 'dla' in dlav0.py

### ISSUE THREAD

**Issue by cclauss** [xingyizhou/CenterNet#23]
[flake8](http://flake8.pycqa.org) testing of https://github.com/xingyizhou/CenterNet on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./src/lib/models/networks/dlav0.py:417:5: F821 undefined name 'dla'
    dla.BatchNorm = bn
    ^
1     F821 undefined name 'dla'
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by xingyizhou** [comment]
This line is never used.

**Comment by cclauss** [comment]
Agreed because if it was the program would halt on the user.  That is why flake8 is flagging it as dangerous.
