### ISSUE TITLE
[question] Have you experimented with multiscale training?

### ISSUE THREAD

**Issue by HamsterHuey** [xingyizhou/CenterNet#230]
I noticed that while you implemented multi-scale testing + NMS for better performance at slower inference speeds, there is no mention of doing multi-scale training as was popularized with YOLO (where after every 10 batches, a new input resolution was selected for the batches). 

I understand that the network architectures used here have more connections across the various internal layers which might make them less sensitive to the scale of input images, but I was still curious if you think that multi-scale training could provide benefit and also if you had tried anything like that in your experimentation? Clearly it does provide benefit on the inference side so perhaps it should help some if implemented on the training side?

**Comment by xingyizhou** [comment]
I haven't tried. It looks like a promising thing to try.

**Comment by HamsterHuey** [comment]
Thanks for the reply. I'll close this for now and report back if I end up implementing this and trying to train on COCO.

**Comment by lyumazi** [comment]
> 
> 
> Thanks for the reply. I'll close this for now and report back if I end up implementing this and trying to train on COCO.

have you done that？how does it work？

**Comment by Cindy0725** [comment]
Hi @HamsterHuey  have you tried the multi-scale training? Does it improve the model? Thanks!

**Comment by HamsterHuey** [comment]
@Cindy0725 - I never retrained Centernet on COCO so I don't know if it would help there. It is relatively easy to use an augmentation library to at least use Affine transforms for zoom-in/out augmentation with padding to achieve some level of multi-scale augmentation. Depending on the problem space, it can certainly help.
