### ISSUE TITLE
convert kitti to coco

### ISSUE THREAD

**Issue by chensonglu** [xingyizhou/CenterNet#235]
@xingyizhou Hello, why do you add "pt_3d[1] += dim[0] / 2" in the line 139 of /src/tools/convert_kitti_to_coco.py. It is right numerically, but i don't understand why. Could you explain that for me. Thank you very much.

**Comment by xingyizhou** [comment]
Hi, this is because the `position` of KITTI is defined as the center of the bottom face.

**Comment by chensonglu** [comment]
@xingyizhou thanks
