### ISSUE TITLE
Center point collision解决方案

### ISSUE THREAD

**Issue by jnulzl** [xingyizhou/CenterNet#236]
你好，@xingyizhou 
首先，您的工作确实不错。
但是，正如您在文中说的那样。该方法有个问题就是：Center point collision！

我有个疑问，您在文中说了为了节省计算开销，对于所有类别的输出
heatmap Y（W_hat x H_hat x C ）共用了
R(W_hat x H_hat x 2)和S(W_hat x H_hat x 2)，
其中W_hat=W/R, H_hat =H/R。
那么假如对于每个类别，在计算损失时用不同的R和S是否可以解决Center point collision问题？？
也就是说R和S尺寸变为：
R：W_hat x H_hat x 2C 
S：W_hat x H_hat x 2C
您有没有这样尝试过？？？

**Comment by xingyizhou** [comment]
I have tried and it is supported in this codebase. You can turn on `--cat_spec_wh`. It doesn't improve the performance on both pascal and COCO.

**Comment by jnulzl** [comment]
Ok!Thank you so much !

**Comment by jnulzl** [comment]
@xingyizhou Ok!Thank you so much !

**Comment by henbucuoshanghai** [comment]
我有个疑问，您在文中说了为了节省计算开销，对于所有类别的输出
heatmap Y（W_hat x H_hat x C ）共用了
R(W_hat x H_hat x 2)和S(W_hat x H_hat x 2)，
其中W_hat=W/R, H_hat =H/R。

但是如果二个物体的中心center完全重合，请问此时预测出二个物体呢？
