### ISSUE TITLE
Pretrained model for arch dlav0_34

### ISSUE THREAD

**Issue by tmac1997** [xingyizhou/CenterNet#237]
Thanks for your great work. I want to know that how I can use non-deform arch `dlav0_34`. Setting the flag `--arch dlav0_34` with pretrained model `ctdet_coco_dla_2x.pth` could not work but I didn't found any pretrained model listed in README corresponding to `dlav0_34`. Any advice or suggestions would be appreciated.

**Comment by xingyizhou** [comment]
I have uploaded the model mentioned [here](https://github.com/xingyizhou/CenterNet/issues/109#issuecomment-502427224) to the [google drive](https://drive.google.com/open?id=18yBxWOlhTo32_swSug_HM4q3BeWgxp_N). It is not recommended to use dla without dcn though.

**Comment by tmac1997** [comment]
Much thanks!
