### ISSUE TITLE
top K

### ISSUE THREAD

**Issue by bruceyang2012** [xingyizhou/CenterNet#24]
Why do you use topK instead of a fixed threshold for output? Wouldn't it make a big error if there were only a few or a lot of targets in the image?

**Comment by xingyizhou** [comment]
I use top 100 detections for COCO dataset. The COCO evaluation metric does not give any penalty for low confident false prediction. In a real application, you can set a hard threshold, e.g., 0.3. It will kill most false positives. I haven't tried set hard thresholds for COCO evaluation, it is for sure lower AP than top 100. It is easy to try it yourself.

**Comment by bruceyang2012** [comment]
@xingyizhou I see, thank you.
