### ISSUE TITLE
confuse with loss

### ISSUE THREAD

**Issue by realwill** [xingyizhou/CenterNet#245]
why heatmap loss is computed with many pixels around center but height and width loss are computed with the center?
中文：heatmap的损失是计算中心点周边的损失之和，而宽高的损失仅仅计算了中心点宽高的损失？这样设计的理念是什么？是否会导致inference的时候，中心点有偏差，导致宽高的预测非常不准？

**Comment by xingyizhou** [comment]
Yes. It follows the associative embedding paper. We do have an option in this repo to enable adding losses to points near the center `--dense_wh`. But I haven't made it work.
