### ISSUE TITLE
FPS for ctdet_coco_resdcn18 

### ISSUE THREAD

**Issue by twangnh** [xingyizhou/CenterNet#249]
Hi! @xingyizhou, Thanks for sharing your great work. I tried run the fastest ctdet_coco_resdcn18 model with 
`python test.py ctdet --arch resdcn_18 --keep_res --resume --load_model ../pretrained/ctdet_coco_resdcn18.pth`
however, I have confusion about the fps of 142 for this model, below is bar after the evaluation complete:
`|Tot: 0:15:45 |ETA: 0:00:01 |dec 0.001s (0.003s) |post 0.124s (0.122s) |tot 0.135s (0.189s) |load 0.000s (0.000s) |pre 0.000s (0.000s) |net 0.008s (0.063s) |merge 0.000s (0.000s)`

I assume for fps, you mean the `net` time (i.e.,  net 0.008s (0.063s)), are your reporting on the 0.008s? but should it be the avg time of 0.063s?

**Comment by xingyizhou** [comment]
The paper fps include average net + dec time on our machine with Titan-Xp. The time varies across different machines and environments. I am not able to point out the problem unless more environment details are provided. Please refer to other issues for references.
