### ISSUE TITLE
About draw_umich_gaussian and draw_msra_gaussian

### ISSUE THREAD

**Issue by DeeperDeeper** [xingyizhou/CenterNet#251]
https://github.com/xingyizhou/CenterNet/blob/a5a0483beb0f9e8705f6dc67d8817275369cfa7e/src/lib/utils/image.py#L126
What is the difference, brielfly,  between draw_umich_gaussian and draw_msra_gaussian ?  Did you use constant radius or dynamic radius ?

https://github.com/xingyizhou/CenterNet/blob/a5a0483beb0f9e8705f6dc67d8817275369cfa7e/src/lib/utils/image.py#L140-L142

I think this instruction `np.maximum(masked_heatmap, masked_gaussian * k, out=masked_heatmap)` should contains heatmap variable. I remark that heatmap does not changed

**Comment by xingyizhou** [comment]
They are copied from the umich repo and the msra repo, respectively. I haven't looked into the details. You can run this line in your machine to see if the heatmap changes.
