### ISSUE TITLE
The AP is not the same as the paper provide

### ISSUE THREAD

**Issue by hheavenknowss** [xingyizhou/CenterNet#256]
hi there, I've download the coco testdev-2017 dataset and run test, then I upload the result.json to coco's website, and I got APs  are all a little lower than  you provide, here are the result I get:
AP: 0.366
AP_50: 0.545
AP_75: 0.393
AP_small: 0.155
AP_medium: 0.389
AP_large: 0.521
AR_max_1: 0.316
AR_max_10: 0.508
AR_max_100: 0.535
AR_small: 0.286
AR_medium: 0.572
AR_large: 0.744

I used the model named ctdet_coco_dla_2x.pth which I download from model_zoo,I checked the result pictures and it seems like need nms,but in paper you said "Inference is a single network forward-pass, without non-maximal suppression for post-processing." so I wonder is there something I missing or maybe it need nms when inference.

**Comment by xingyizhou** [comment]
Can you show your commend for testing and make sure the code is unchanged? Also please check other issues related to the performance. The visualization problem is most likely due to you haven't loaded the trained parameters.

**Comment by hheavenknowss** [comment]
my testing commend,with nms:
['main.py', 'ctdet', '--test', '--nms', '--exp_id', 'test_nms', '--load', '../models/ctdet_coco_dla_2x.pth', '--debug=4']
without nms :
['main.py', 'ctdet', '--test', '--load', '../models/ctdet_coco_dla_2x.pth', '--exp_id', 'test_no_nms', '--debug=4']
as you can see, I loaded the model you provide,and I think commend is right, and I found out that both commend's visualize result look the same, I didn't change the code,

**Comment by hheavenknowss** [comment]
I've found where I was wrong, I didn't use --keep_res in my commend, after added that,performence is very close to you provide,but visualization issue still there.
![图片](https://user-images.githubusercontent.com/35052711/62767870-2ba57500-bac8-11e9-9b8f-3da9f313c6d3.png)
like picture above,is that normal?
my commed:
['main.py', 'ctdet', '--test', '--load', '../models/ctdet_coco_dla_2x.pth', '--exp_id', 'test_keep_res_with_nms', '--keep_res', '--debug=4', '--nms']
I add --nms try to fix situation like this,but it's seems not work

**Comment by yelingyunlmm** [comment]
Have you changed the '--vis_thresh'?

**Comment by yelingyunlmm** [comment]
Did you change the value of '--vis_thresh'? there are many values below 0.3 in your image.

**Comment by hheavenknowss** [comment]
No I don't ,do you get the normal results in visualization?

**Comment by yelingyunlmm** [comment]
yes. I think you should check your default vis_thresh in 'src/lib/opts.py' whether it is '0.3'

**Comment by hheavenknowss** [comment]
I just checked this file,and it's '0.3',any where may goes wrong??

**Comment by yelingyunlmm** [comment]
I have no idea...normally, if the bbox[4] below opt.vis_thresh won't be added...you can analyze the function in 'lib/detectors/base_detector.py' and 'lib/detectors/ctdet.py' by tracking the order of execution:
1. run() in 'lib/detectors/base_detector.py': check if the function 'self.show_results()' is executed. my code is as following:
'''
if self.opt.debug >= 1:
    self.show_results(debugger, image, results, image_or_path_or_tensor)
    print("self.show_results")
'''
2.show_results() in 'lib/detectors/ctdet.py': check if the bboxes is added conditionally.
'''
for j in range(1, self.num_classes + 1):
    for bbox in results[j]:
        if bbox[4] > self.opt.vis_thresh:
            debugger.add_coco_bbox(bbox[:4], j - 1, bbox[4], img_id='ctdet')
'''
maybe that will help you...if also doesn't work , god bless you....

**Comment by hheavenknowss** [comment]
I see,did you run test.py?I run the train.py with --test,I guess that the problem

**Comment by xingyizhou** [comment]
Please always use `test.py` to test a pretrained model. `main.py` does not include test time augmentations.

**Comment by hheavenknowss** [comment]
I see,but test.pt it will show the image and I didn't find the save image code, and I use linux,so I guess I have to change some code,could you help me out?

  def show_results(self, debugger, image, results):
    debugger.add_img(image, img_id='ctdet')
    for j in range(1, self.num_classes + 1):
      for bbox in results[j]:
        if bbox[4] > self.opt.vis_thresh:
          debugger.add_coco_bbox(bbox[:4], j - 1, bbox[4], img_id='ctdet')
    debugger.show_all_imgs(pause=self.pause)
I think maybe I can change show to save,but the I can't give the augmentations that save image need.

**Comment by yelingyunlmm** [comment]
vim lib/utils/debugger.py

<img width="574" alt="捕获" src="https://user-images.githubusercontent.com/26156986/62992195-1ee89e80-be85-11e9-9f79-432ad99456d3.PNG">

**Comment by yelingyunlmm** [comment]
but....my test  mAP on coco is very low.....
>python test.py ctdet --dataset coco --exp_id coco_dla --keep_res --load_model ../models/ctdet_coco_dla_2x.pth
'''
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.093
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.185
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.084
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.097
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.106
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.113
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.139
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.267
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.294
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.232
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.299
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.382
'''
could you help me?

**Comment by yelingyunlmm** [comment]
it‘s my fault. I rebuild the project，now it works well. thanks.
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.374
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.551
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.408
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.206
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.420
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.506
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.317
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.521
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.551
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.336
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.594
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.737

**Comment by hheavenknowss** [comment]
> 
> 
> it‘s my fault. I rebuild the project，now it works well. thanks.
> Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.374
> Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.551
> Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.408
> Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.206
> Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.420
> Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.506
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 1 ] = 0.317
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets= 10 ] = 0.521
> Average Recall (AR) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.551
> Average Recall (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.336
> Average Recall (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.594
> Average Recall (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.737

:)

**Comment by yelingyunlmm** [comment]
do you know what 'coco_hp' is? no information about it in data.md

**Comment by hheavenknowss** [comment]
> 
> 
> do you know what 'coco_hp' is? no information about it in data.md

I guess it's some datasets, I don't really know, but it's looks like coco.py

**Comment by yelingyunlmm** [comment]
emmm.... I forget to add ''--dataset coco_hp'  in my command line for the task of  'mulit-pose'

**Comment by hheavenknowss** [comment]
> 
> 
> emmm.... I forget to add ''--dataset coco_hp' in my command line for the task of 'mulit-po

> 
> 
> emmm.... I forget to add ''--dataset coco_hp' in my command line for the task of 'mulit-pose'

so mulit-pose need to use coco_hp？

**Comment by yelingyunlmm** [comment]
yes, there is something about 'coco_hp' in 'lib/utils/debugger.py'

**Comment by yelingyunlmm** [comment]
> > emmm.... I forget to add ''--dataset coco_hp' in my command line for the task of 'mulit-po
> 
> > emmm.... I forget to add ''--dataset coco_hp' in my command line for the task of 'mulit-pose'
> 
> so mulit-pose need to use coco_hp？

yes, there is something about 'coco_hp' in 'lib/utils/debugger.py'
