### ISSUE TITLE
RGB/BGR mixup

### ISSUE THREAD

**Issue by bsvineethiitg** [xingyizhou/CenterNet#262]
> Yes.

> _Originally posted by @xingyizhou in https://github.com/xingyizhou/CenterNet/issues/229#issuecomment-514787498_

The DLA model seems to be trained using torchvision dataset loader that loads images in RGB order. (Check https://github.com/ucbdrive/dla/issues/12)

So, the pretrained models should be expecting RGB as opposed to BGR. 

Could you clarify @xingyizhou? Thanks.

**Comment by bsvineethiitg** [comment]
Not only for DLA, but also for the ResNet pretrained models (Official PyTorch ones), the expected inputs are in RGB.

**Comment by xingyizhou** [comment]
Thanks for reporting the problem. We will investigate this later.

**Comment by bsvineethiitg** [comment]
Thank you.

**Comment by BenjaminGit001** [comment]
@bsvineethiitg  @xingyizhou 
it seems use BGR in torch dataloader, but use RGB in test data loader.
https://github.com/xingyizhou/CenterNet/blob/a5a0483beb0f9e8705f6dc67d8817275369cfa7e/src/lib/detectors/base_detector.py#L58

**Comment by liangxiao05** [comment]
@BenjaminGit001 ，
inp_image.transpose(2, 0, 1)  convert HWC to CHW ,not BGR to RGB

**Comment by xingyizhou** [comment]
I tried RGB and observed it not help.
