### ISSUE TITLE
train loss drops in second epoch

### ISSUE THREAD

**Issue by thinkyang88** [xingyizhou/CenterNet#268]
I train the net in my dataset, why the train loss drops from 23 to 2  at the beginning of second epoch？

**Comment by xingyizhou** [comment]
We show the average loss in the epoch instead of per-iteration loss.

**Comment by thinkyang88** [comment]
thanks，I firstly trained 10 epochs，but it seems that the trainning is false.My
 dataset has 15 classes and resolution 1024×1024, and  I set self.class_name = [
      '__background__', 'plane', 'baseball-diamond', 'bridge', 'ground-track-field', 
      'small-vehicle', 'large-vehicle', 'ship','tennis-court', 'basketball-court', 'storage-tank',
      'soccer-ball-field', 'roundabout', 'harbor', 'swimming-pool', 'helicopter']
    self._valid_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15]  is that right？

**Comment by thinkyang88** [comment]
I detect one picture， but only harbor is detected and mischecked.

**Comment by xingyizhou** [comment]
Closing this now as we found a bug in your implementation in your other issue.
