### ISSUE TITLE
L1 loss is different from the paper

### ISSUE THREAD

**Issue by DeeperDeeper** [xingyizhou/CenterNet#272]
Hi @xingyizhou, 
https://github.com/xingyizhou/CenterNet/blob/a5a0483beb0f9e8705f6dc67d8817275369cfa7e/src/lib/models/losses.py#L184

I think this is different from the paper. You average on the whole pixel (128^2)! but in the paper we average only on the non-zeros pixels

**Comment by xingyizhou** [comment]
[L1Loss()](https://github.com/xingyizhou/CenterNet/blob/a5a0483beb0f9e8705f6dc67d8817275369cfa7e/src/lib/models/losses.py#L177) is not used for learning the bounding size. [RegL1Loss()](https://github.com/xingyizhou/CenterNet/blob/a5a0483beb0f9e8705f6dc67d8817275369cfa7e/src/lib/models/losses.py#L139) is used, which uses `size_average=False`.
