### ISSUE TITLE
strange FPS

### ISSUE THREAD

**Issue by CPFLAME** [xingyizhou/CenterNet#284]
I just run this command 
`python src/demo.py ctdet --arch resdcn_18 --demo images/ --load_model ctdet_coco_resdcn18.pth`
but the inference time of net forward costs 0.095s in my V100 GPU, it's about 10FPS. any help?
![image](https://user-images.githubusercontent.com/13843079/63396050-5eb90400-c3f8-11e9-8149-bdf6b7bd3d36.png)

**Comment by wangg12** [comment]
On my 1070 card, I got about 26 fps.
```
python test.py ctdet --load_model ./models/ctdet_coco_resdcn18.pth --keep_res
[2630/5000]|Tot:0:01:46|ETA:0:01:32|tot 0.037s(0.038s)|load 0.000s(0.000s)|pre 0.001s(0.001s)|net 0.033s(0.034s)|dec 0.001s(0.001s)|post 0.002s(0.002s)|merge 0.000s(0.000s)
```

**Comment by xingyizhou** [comment]
We also observed a slow down on Titan V. It seems related to `.cuda(non_blocking=True)` or `pin_memory=True`. Check [this](https://github.com/xingyizhou/CenterNet/issues/247).

**Comment by CPFLAME** [comment]
@wangg12 @xingyizhou  Thanks for your apply, but where should I modify the `.cuda(non_blocking=True)`?   The `pin_memory=True` seems related to dataloader(which affects pre_process time), but my net forward time is very slow.

**Comment by CPFLAME** [comment]
@wangg12  @xingyizhou  Hi~ I think  maybe  I know  the reason:
When I run `python src/demo.py ctdet --arch hourglass --demo images/ --load_model ctdet_coco_hg.pth`
the net forward cost 70 ms,which is similar to your report.
![image](https://user-images.githubusercontent.com/13843079/63501390-1a179080-c4fe-11e9-91f1-0af21ca902f0.png)
but  when I use  resnet18 and resnet101. resnet18 cost 95ms and resnet101 cost 96~97ms,while DLA34 cost 246ms.
Hourglass without DCN is faster than other methods. Maybe  the  DCN cost too much time?

**Comment by CPFLAME** [comment]
OK, me again. 
I have just run some experiments, I modified demo.py to test net forward time with random tensor.
![image](https://user-images.githubusercontent.com/13843079/63507595-a9c33c00-c50a-11e9-9c84-4ee53669b895.png)
And I run `python src/demo.py ctdet --arch resdcn_18 --demo images/ --load_model ctdet_coco_resdcn18.pth`. I found the real net forward time only cost 5ms in my V100 GPU.
 
![image](https://user-images.githubusercontent.com/13843079/63507659-cc555500-c50a-11e9-9d06-d37af98c92c2.png)
Why it is 95ms in the original code?  May it be the reason of random tensor?

**Comment by wangg12** [comment]
What is your `pin_memory`? And what is your pytorch, cuda, driver version? Are you solely running this test without any other computation-expensive programs?

**Comment by CPFLAME** [comment]
@wangg12 
1. The `pin_memory` is in src/test.py,  but I ran the src/demo.py.  By the way， what I care about is **net forward time**, I don't think `pin_memory` makes a difference in net forward time, It is for speeding up pre-process time.
2. pytorch 0.4.1 , cuda 9.0 , nvidia driver  410.79 ,  CPU  E5-2650 v4, GPU v100
3. I shut down all other program for running this code.  I'm pretty sure that  I run this code without any other computation-expensive programs.
4. Strangely，after I command `torch.cuda.synchronize()` in src/lib/detectors/ctdet.py and src/lib/detectors/base_detector.py,  which is for synchronizing GPU-CPU time.  The net forward time of resnet18, resnet101 and dla34 are 7ms,23ms, 20ms. it's very similar to the report result. Is it a 
coincidence？
5. I can  just Reproduce the  result of hourglass（net forward 70ms） with `torch.cuda.synchronize()` on. When I command 'torch.cuda.synchronize()', hourglass run 35ms for net forward. It's strange.
6. I don't know why I can reach the report result with different synchronize setting(hourglass with synchronize and [resnet18,resnet101,dla34] without synchronize), any help for me?
7. Any other setting question?

**Comment by wangg12** [comment]
With `demo.py`, nothing changed, I got the following result with resnet_dcn18.
(pytorch version 1.2, cuda-10, driver 430)
```
tot 0.060s |load 0.027s |pre 0.020s |net 0.009s |dec 0.001s |post 0.003s |merge 0.000s |
tot 0.083s |load 0.047s |pre 0.022s |net 0.009s |dec 0.001s |post 0.003s |merge 0.000s |
tot 0.074s |load 0.038s |pre 0.023s |net 0.009s |dec 0.001s |post 0.003s |merge 0.000s |
tot 0.066s |load 0.033s |pre 0.019s |net 0.009s |dec 0.001s |post 0.003s |merge 0.000s |
```

**Comment by CPFLAME** [comment]
@wangg12 
Thx !
I just use pytorch 1.2, cuda-10 , driver 410 , GPU V100
And I use https://github.com/CharlesShang/DCNv2.git
with demo.py , I got this result.
![image](https://user-images.githubusercontent.com/13843079/63569476-13dfed80-c5ac-11e9-9f42-65fe53bbf3da.png)
It's wierd that pytorch, cuda vision  and DCNv2  make such a big difference.

**Comment by wangg12** [comment]
My DCNv2 is comed from [https://github.com/open-mmlab/mmdetection/tree/master/mmdet/ops/dcn](https://github.com/open-mmlab/mmdetection/tree/master/mmdet/ops/dcn), FYI.

**Comment by JOSHUAWENJZ** [comment]
@wangg12 @CPFLAME Thamk you for all of your advice! You may not believe that I reduced the detection time cost from **0.18 seconds** to **0.014 seconds** on  **GTX1660S GPU**！
