### ISSUE TITLE
How did you sovel this problem from "error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2" , for the DCNv2 ? 

### ISSUE THREAD

**Issue by Beam-wi** [xingyizhou/CenterNet#288]
external is failed
(CenterNet) D:\research\CenterNet-master\src\lib\external>python setup.py install
running install
running build
running build_ext
building 'nms' extension
D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -ID:\Anaconda3\envs\CenterNet\lib\site-packages\numpy\core\include -ID:\Anaconda3\envs\CenterNet\include -ID:\Anaconda3\envs\CenterNet\include "-ID:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /Tcnms.c /Fobuild\temp.win-amd64-3.6\Release\nms.obj -Wno-cpp -Wno-unused-function
cl : Command line error D8021 : invalid numeric argument '/Wno-cpp'
error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

_Originally posted by @mk123qwe in https://github.com/xingyizhou/CenterNet/issues/7#issuecomment-486653333_

**Comment by xingyizhou** [comment]
Can you check [this](https://github.com/xingyizhou/CenterNet/issues/7)?

**Comment by Beam-wi** [comment]
> Can you check [this](https://github.com/xingyizhou/CenterNet/issues/7)?

I have solved this problem, thank you very much!

**Comment by deep-practice** [comment]
@Beam-wi Can you share your solution?

**Comment by jizefeng0810** [comment]
@Beam-wi Can you share your solution?

**Comment by LikaiLiu-lh** [comment]
@Beam-wi Can you share your solution?

**Comment by Fansgithub2019** [comment]
@Beam-wi Can you share your solution?

**Comment by coctel99** [comment]
@Beam-wi Can you share your solution?

**Comment by LikaiLiu-lh** [comment]
Sorry i just check my email , it was too long to remember the details of the problem. But it is not hard to sovel it ,may be you could upgrade you cuda version ,try cuda-10.2 to compile.
Here are some logs when i tried to sovle it ,hope this helps :
error detected in the compilation of "C:/Users/ADMINI~1/AppData/Local/Temp/2/t
mpxft_00001ac8_00000000-10_deform_conv_cuda.cpp1.ii".
error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin
\nvcc.exe' failed with exit status 1
Solution：
several files must be changed by manually.
file1:
{your evn path}\Lib\site-packages\torch\include\torch\csrc\jit\argument_spec.h
example:
{C:\Miniconda3\envs\py36}\Lib\site-packages\torch\include\torch\csrc\jit\argument_spec.h(190)
static constexpr size_t DEPTH_LIMIT = 128;
change to -->
static const size_t DEPTH_LIMIT = 128;
file2:
{your evn path}\Lib\site-packages\torch\include\pybind11\cast.h
example:
{C:\Miniconda3\envs\py36}\Lib\site-packages\torch\include\pybind11\cast.h(1449)
explicit operator type&() { return *(this->value); }
change to -->
explicit operator type&() { return ((type)this->value); }



在 2022-05-25 04:59:29，"Barabanov Alexander" ***@***.***> 写道：

@Beam-wi Can you share your solution?
