### ISSUE TITLE
Training on pascal dataset

### ISSUE THREAD

**Issue by DeeperDeeper** [xingyizhou/CenterNet#289]
Hello @xingyizhou 
You mentioned in the paper that you train the DLA on pascal dataset using 1 GPU for 70 epochs and it takes 10 hours. Did you use any pretrained model or the training is done from scratch. Based on my experiments (my implementation), 70 epochs is not enough to train the DLA. Thanks to clarify this point

**Comment by xingyizhou** [comment]
It trains from scratch. You can run this implementation to see if it converges. I have repeated the pascal experiments for >20 times and I am pretty sure it will.

**Comment by DeeperDeeper** [comment]
@xingyizhou I used only the VOC 2012 data (11540 images) and I think this is why 70 epochs was not enough in my case (also the batch size is 12 in my case).

**Comment by niaoyu** [comment]
> It trains from scratch. You can run this implementation to see if it converges. I have repeated the pascal experiments for >20 times and I am pretty sure it will.

Hi, I just test the model for VOC dataset. The "ctdet_pascal_dla_384" score is 79.3. However it is the only one that match the paper.Could you just explain the point?
