### ISSUE TITLE
Fail to run camera demo on pytorch1.0+ + CUDA10 + Ubuntu 16.04 + cudnn7.4

### ISSUE THREAD

**Issue by mbufi** [xingyizhou/CenterNet#29]
`$ python demo.py ctdet --demo webcam --load_model ../models/ctdet_coco_dla_2x.pth`

> Fix size testing.
> training chunk_sizes: [32]
> heads {'hm': 80, 'reg': 2, 'wh': 2}
> Creating model...
> loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
> Segmentation fault (core dumped)

Anyone getting the same issue? I have followed the steps of changing `dcn_v2_cuda` and also recompiling DCNv2 for pytorch1.0

**Comment by xingyizhou** [comment]
I honestly have no idea about this...

**Comment by mbufi** [comment]
:disappointed:

**Comment by ThreeChen** [comment]
got the same issue, i fixed it by updating my gcc to 4.9.2.
when your gcc version is lesser than 4.9, you should get a WARNING saying that gcc version is not compatible with Pytorch on ABI.
so as i upgraded my gcc, the WARNING disappear and the segment fault bug got fixed.

**Comment by DeniJsonC** [comment]
> `$ python demo.py ctdet --demo webcam --load_model ../models/ctdet_coco_dla_2x.pth`
> 
> > Fix size testing.
> > training chunk_sizes: [32]
> > heads {'hm': 80, 'reg': 2, 'wh': 2}
> > Creating model...
> > loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
> > Segmentation fault (core dumped)
> 
> Anyone getting the same issue? I have followed the steps of changing `dcn_v2_cuda` and also recompiling DCNv2 for pytorch1.0

hi~ could tell me what need to  change to run in cuda 10+pytorch1.0 environment.because , I have met something wrong when ran "demo.py",the console error shows " torch.utils.ffi was deprecated"  then I replace it to
"torch.utils.cpp_extension" but I do not know what to use to relpace the function "_wrap_function()"
it is a hard choice for me to downgrade CUDA 9 and pytorch 0.4.1

**Comment by ualiawan** [comment]
> hi~ could tell me what need to change to run in cuda 10+pytorch1.0 environment.because , I have met something wrong when ran "demo.py",the console error shows " torch.utils.ffi was deprecated" then I replace it to
> "torch.utils.cpp_extension" but I do not know what to use to relpace the function "_wrap_function()"
> it is a hard choice for me to downgrade CUDA 9 and pytorch 0.4.1

You can have a look at this:
https://www.gitmemory.com/issue/xingyizhou/CenterNet/7/486653333

**Comment by Kenneth-X** [comment]
> got the same issue, i fixed it by updating my gcc to 4.9.2.
> when your gcc version is lower than 4.9, you should get a WARNING saying that gcc version is not compatible with Pytorch on ABI as you were trying to compile DCNv2.
> so as i upgraded my gcc, the WARNING disappeared and the segment fault bug got fixed.
> 
> howerver, you won't get this WARNING when your pytorch version is 0.4.1.

still come out this Segmentation fault problem after fixing into  gcc 4.9
this log is followed:

$python demo.py ctdet --demo ../images/17790319373_bd19b24cfc_k.jpg --load_model ../models/ctdet_coco_dla_2x.pth --debug 2
Fix size testing.
training chunk_sizes: [1]
The output will be saved to  /home/yuxi.xt/experinment/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
Segmentation fault

**Comment by twangnh** [comment]
same problem

**Comment by twangnh** [comment]
use higher version gcc and recompile solve the problem

**Comment by Ai-is-light** [comment]
aftre updating the gcc I got @twangnh 
CenterNet_point_pytorch/src/lib/external]# make
python setup.py build_ext --inplace
Warning: Extension name 'nms' does not match fully qualified name 'external.nms' of 'nms.pyx'
running build_ext
rm -rf build

have you met it?

python demo.py --task ctdet --demo ../images/16004479832_a748d55f21_k.jpg --load_mode ../models/ctdet_coco_dla_2x.pth
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/data2/yonasyu/project_pose/CenterNet_point_pytorch/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/data2/yonasyu/project_pose/CenterNet_point_pytorch/src/lib/detectors/exdet.py", line 11, in <module>
    from progress.bar import Bar
ModuleNotFoundError: No module named 'progress'

**Comment by Ai-is-light** [comment]
my system is fucking centos7

**Comment by Ai-is-light** [comment]
@twangnh what's version of your gcc?

gcc --version
gcc (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by yuanshengyu** [comment]
> 
> 
> got the same issue, i fixed it by updating my gcc to 4.9.2.
> when your gcc version is lower than 4.9, you should get a WARNING saying that gcc version is not compatible with Pytorch on ABI as you were trying to compile DCNv2.
> so as i upgraded my gcc, the WARNING disappeared and the segment fault bug got fixed.
> 
> howerver, you won't get this WARNING when your pytorch version is 0.4.1.

thanks!
1 remove DCNv2
2 git clone https://github.com/CharlesShang/DCNv2.git
3 cd DCNv2
4 ./make.sh

update gcc:
https://stackoverflow.com/questions/36327805/how-to-install-gcc-5-3-with-yum-on-centos-7-2
