### ISSUE TITLE
invalid argument 0: Sizes of tensors must match except in dimension 0. Got 2 and 1 in dimension 1 at /opt/conda/conda-bld/pytorch_1532579805626/work/aten/src/TH/generic/THTensorMath.cpp:3616

### ISSUE THREAD

**Issue by chumengdd** [xingyizhou/CenterNet#290]
I met this error：
...
index created!
Loaded gisdata2 16684 samples
Starting training...
ctdet/coco_resdcn101Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/haha/PROJECT_TRAFFIC/CenterNet-master/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/haha/PROJECT_TRAFFIC/CenterNet-master/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 184, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 184, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 184, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 184, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 173, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 2 and 1 in dimension 1 at /opt/conda/conda-bld/pytorch_1532579805626/work/aten/src/TH/generic/THTensorMath.cpp:3616
I have set all the input images size is 512*512, and check the image channel is 3. I don't know how to solve this error !

**Comment by BMG-JTIAN** [comment]
In the data generator, the size of gt_det may vary between different input, you need to use zero-padding to make the gt_det tensor shape to be the same. 
They probably changed the data-loader class since pytorch 1.0.. All items in the dictionary are treated as tensors and forced to have the same shape if they have the same key value.

**Comment by chumengdd** [comment]
thank you for your advice , i find the reason and solve it !

**Comment by WZHsmile** [comment]
> thank you for your advice , i find the reason and solve it !

could  you tell me how to solve this proplem ?THX

**Comment by chumengdd** [comment]
when I trained my own data,I changed the folder name, I didn't notice that some operations connect to the folder name , so the image miss some processes,  you can check your codes if you met some reason with me. good luck!

**Comment by YilanWang** [comment]
> In the data generator, the size of gt_det may vary between different input, you need to use zero-padding to make the gt_det tensor shape to be the same.
> They probably changed the data-loader class since pytorch 1.0.. All items in the dictionary are treated as tensors and forced to have the same shape if they have the same key value.

thx for your advices, and you mean although the codes "sample/ctdet.py" has trans the input tensor to a fixed scale(like 512x512x3), I have to change the coco dataset to the same scale (like 1280x720)?
