### ISSUE TITLE
DCNv2 can not built on pytorch1.0

### ISSUE THREAD

**Issue by jinfagang** [xingyizhou/CenterNet#3]
```
    from ._ext import dcn_v2 as _backend
ModuleNotFoundError: No module named 'models.networks.DCNv2._ext'
```

the DCNv2 can not be built on pytorch 1.0.

```
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

```

Any fix on  this?

**Comment by xingyizhou** [comment]
Hi, 
  Thanks for your interests again. You can check the Pytorch1.0 DCNv2 from the original repo https://github.com/CharlesShang/DCNv2 . Remember also to disable cudnn BN for pytorch 1.0. Our preliminary result on pytorch 1.0 is about 0.4 AP lower than pytorch 0.4.1 (for ctdet_coco_dla_1x). Not sure if this is due to randomness or internal difference between the two versions. Other experiments are not fully tested in pytorch 1.0. You can still test with our pretrained model on pytorch 1.0.

**Comment by jinfagang** [comment]
@xingyizhou  I already update DCNv2 to pytorch 1.0 now. It works fine, thanks for your reply.

BTW, how to disable cudnn BN in pytorch?

**Comment by DequanWang** [comment]
You do not need to do that after pytorch 1.0.

**Comment by xingyizhou** [comment]
Actually you still need to, according to my observation.
You can
`vim ~/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py`
or `vim ~/anaconda3/envs/ENV_NAME/lib/python3.6/site-packages/torch/nn/functional.py` (if you use 
conda environment)
And change `torch.backend.cudnn.enabled` to `False` in line `1623`.

**Comment by azhaoaigaga** [comment]
> @xingyizhou I already update DCNv2 to pytorch 1.0 now. It works fine, thanks for your reply.
> 
> BTW, how to disable cudnn BN in pytorch?

@jinfagang  How would you update DCNv2 to pytorch 1.0

**Comment by VRCMF** [comment]
> > @xingyizhou I already update DCNv2 to pytorch 1.0 now. It works fine, thanks for your reply.
> > BTW, how to disable cudnn BN in pytorch?
> 
> @jinfagang How would you update DCNv2 to pytorch 1.0

Download the new code from the original repo and replace them

**Comment by clemente620** [comment]
> > > @xingyizhou I already update DCNv2 to pytorch 1.0 now. It works fine, thanks for your reply.
> > > BTW, how to disable cudnn BN in pytorch?
> > 
> > 
> > @jinfagang How would you update DCNv2 to pytorch 1.0
> 
> Download the new code from the original repo and replace them

TKS  IT WORKS WELL

**Comment by clemente620** [comment]
I just  git clone https://github.com/CharlesShang/DCNv2.git  to my repo 
and change my pytorch==1.0 for cuda 10
solve the problem
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by VRCMF** [comment]
@clemente620  Please refer the question #7

**Comment by SurPer-Y** [comment]
> Hi,
> Thanks for your interests again. You can check the Pytorch1.0 DCNv2 from the original repo https://github.com/CharlesShang/DCNv2 . Remember also to disable cudnn BN for pytorch 1.0. Our preliminary result on pytorch 1.0 is about 0.4 AP lower than pytorch 0.4.1 (for ctdet_coco_dla_1x). Not sure if this is due to randomness or internal difference between the two versions. Other experiments are not fully tested in pytorch 1.0. You can still test with our pretrained model on pytorch 1.0.

Can this method solve his first question？`from ._ext import dcn_v2 as _backend
ModuleNotFoundError: No module named 'models.networks.DCNv2._ext'`

**Comment by dankydev** [comment]
> > Hi,
> > Thanks for your interests again. You can check the Pytorch1.0 DCNv2 from the original repo https://github.com/CharlesShang/DCNv2 . Remember also to disable cudnn BN for pytorch 1.0. Our preliminary result on pytorch 1.0 is about 0.4 AP lower than pytorch 0.4.1 (for ctdet_coco_dla_1x). Not sure if this is due to randomness or internal difference between the two versions. Other experiments are not fully tested in pytorch 1.0. You can still test with our pretrained model on pytorch 1.0.
> 
> Can this method solve his first question？`from ._ext import dcn_v2 as _backend ModuleNotFoundError: No module named 'models.networks.DCNv2._ext'`

I'm afraid the answer is no. The _ext module should be built when DCNv2 is compiled, and it seems not to work even when the script says everything gone as predicted.
@xingyizhou Do you know something about this? I've been googling the whole day, but this problem seems almost unsolved. Thank you in advance
