### ISSUE TITLE
Bug in training?

### ISSUE THREAD

**Issue by moothes** [xingyizhou/CenterNet#30]
Training the network sometimes reports a strange issue. However, if I run the code again, everything is fine, this bug is missing. It seems to be a probability event.
```
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/media/data2/zhouhj/centernet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/media/data2/zhouhj/centernet/src/lib/trains/base_trainer.py", line 74, in run_epoch
    self.optimizer.step()
  File "/home/zhouhj/.local/lib/python3.5/site-packages/torch/optim/adam.py", line 92, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: The expanded size of the tensor (2) must match the existing size (20) at non-singleton dimension 0
```

**Comment by xingyizhou** [comment]
I haven't met this. You can check if the error is from resuming from a wrong checkpoint.

**Comment by PetreanuAndi** [comment]
@moothes , why did you close did? how did you fix it? I'm getting something similar (from the loss function) : 
pos_loss = torch.log(pred) * torch.pow(1 - pred, 2) * pos_inds
RuntimeError: The size of tensor a (200) must match the size of tensor b (3) at non-singleton dimension 3

**Comment by moothes** [comment]
Well, I thought it only happens on my machine, so I close it. I find it is cause by the order of dictionary keys.
For example, the 155 line  in the resnet_dcn.py file:    
`
for head in self.heads:
`
I change it to:
```
        keys = list(self.heads.keys())
        keys.sort()
        
        for head in keys:
```

And then I never met that issue again. The order of `self.heads.keys()` needs Manual Sorting.
Your can try to print(self.heads.keys()), maybe you will find the order of each running is different.

**Comment by moothes** [comment]
> 
> 
> @moothes , why did you close did? how did you fix it? I'm getting something similar (from the loss function) :
> pos_loss = torch.log(pred) * torch.pow(1 - pred, 2) * pos_inds
> RuntimeError: The size of tensor a (200) must match the size of tensor b (3) at non-singleton dimension 3

Since your error get two number: 200 and 3. You can check whether the heads in configure file is 200 and 3 too. If it is, you should meet the same problem as me.
