### ISSUE TITLE
use get_pascal_voc.sh download voc dataset, but when testing, It loads images that are not in the folder？

### ISSUE THREAD

**Issue by zhen8838** [xingyizhou/CenterNet#300]
##### Download dataset :

```sh
./get_pascal_voc.sh
mv voc ../../data
```
##### Testing model:

```sh
test.py ctdet --exp_id pascal_resdcn18_384 --arch resdcn_18 --dataset pascal --load_model ../models/ctdet_pascal_resdcn18_384.pth --resume --flip_test
```

##### Got error `AttributeError: 'NoneType' object has no attribute 'shape'`

I print the path of the images which will be loads:
```sh
/home/zqh/Documents/CenterNet/src/lib/../../data/voc/images/000001.jpg
/home/zqh/Documents/CenterNet/src/lib/../../data/voc/images/000002.jpg
/home/zqh/Documents/CenterNet/src/lib/../../data/voc/images/000003.jpg
```
But in my voc folder:

exec : 
```sh
ls /home/zqh/Documents/CenterNet/src/lib/../../data/voc/images/ | grep 000001 
```

get :
~~~
2009_000001.jpg 
2010_000001.jpg
~~~
exec : 
```sh
ls /home/zqh/Documents/CenterNet/src/lib/../../data/voc/images/ | grep 000002
```
get : 
~~~
2008_000002.jpg
2009_000002.jpg
2010_000002.jpg
2011_000002.jpg
~~~

**Comment by xingyizhou** [comment]
The `provided get_pascal_voc.sh` involves some move file commends. Make sure they are executed correctly.

**Comment by zhen8838** [comment]
OK, I add `sync` after `tar` command, Now I can training on voc dataset.

**Comment by LinqingZhu** [comment]
> OK, I add sync after tar command, Now I can training on voc dataset.

Hi, I met the same problem. But I am not very clear about this solution. Could you please tell me how to add sync after tar command?

**Comment by zhen8838** [comment]
use `sync` command after `tar`
```sh
tar 1.tar.gz
sync
tar 2.tar.gz
sync
```
