### ISSUE TITLE
Why do predict bboxes have negative values？

### ISSUE THREAD

**Issue by ymmshi** [xingyizhou/CenterNet#301]
I train the model on my own dataset. When testing, the results are pretty good, but there are some obvious mistakes. such as negative coordinates in the generated boxes, x1>x2 or y1>y2, [x1,y1,x2,y2] is the coordinates of the boxes. I can't find the reason for the mistakes and look forward to your help，thank you!

**Comment by evitself** [comment]
Hi, @ymmshi , It seems you have got negative w/h values, I think it's normal case (as for wh regression, there is actually no constrains to keep those values keep in positive) you just need to ignore those negative values. And then try to evaluate the results see if the metrics are reasonable.

**Comment by ymmshi** [comment]
> Hi, @ymmshi , It seems you have got negative w/h values, I think it's normal case (as for wh regression, there is actually no constrains to keep those values keep in positive) you just need to ignore those negative values. And then try to evaluate the results see if the metrics are reasonable.

Thank you! I know what you mean now. Maybe you can add this constrains to the post_process function.
