### ISSUE TITLE
to() got an unexpected keyword argument 'non_blocking'

### ISSUE THREAD

**Issue by Ranchentx** [xingyizhou/CenterNet#31]
When I try to run main.py. It seems has some problem: 

Starting training...
Traceback (most recent call last):
  File "/home/jin/Documents/fairy/CenterNet/src/main.py", line 103, in <module>
    main(opt)
  File "/home/jin/Documents/fairy/CenterNet/src/main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/jin/Documents/fairy/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/jin/Documents/fairy/CenterNet/src/lib/trains/base_trainer.py", line 68, in run_epoch
    batch[k] = batch[k].to(device=opt.device, non_blocking=True)    
TypeError: to() got an unexpected keyword argument 'non_blocking'

**Comment by moothes** [comment]
Maybe your Pytorch version is 0.4.0.
Your can update your Pytorch to 0.4.1 or remove `non_blocking` parameter.

**Comment by Ranchentx** [comment]
@moothes Thanks for your reply. But when I run with Pytorch 0.4.1 or  I remove non_blocking parameter Pytorch 0.4.0 . The training seems stuck as below:


![Screenshot from 2019-04-25 14-29-22](https://user-images.githubusercontent.com/25639421/56729786-23b70480-6767-11e9-879e-32a3836fb298.png)

**Comment by moothes** [comment]
Well, this work for me. I just test it on pascal voc dataset.

**Comment by PRYUS** [comment]
> Maybe your Pytorch version is 0.4.0.
> You can update your Pytorch to 0.4.1 or remove `non_blocking` parameter.

Yes, this solved the issue for me.
