### ISSUE TITLE
将骨干网络换成resnet18，测试时没有参数

### ISSUE THREAD

**Issue by leavewave** [xingyizhou/CenterNet#316]
只是改了--arch命令行参数为res_18，别的没有改，是不是还得改其他地方？训练的时候可以进行下去，测试的时候ap=0，完全加载不上参数
![image](https://user-images.githubusercontent.com/41049484/64305523-3ddcdb00-cfc2-11e9-895a-1de3c05171bd.png)

**Comment by HHusers** [comment]
请问，您解决了吗，我也遇到了类似的问题

**Comment by xls888** [comment]
请问你解决了吗，我也遇到同样的问题
