### ISSUE TITLE
About "draw_dense_reg"

### ISSUE THREAD

**Issue by seekFire** [xingyizhou/CenterNet#318]
The function "draw_dense_reg" in src/lib/utils/image.py is shown as follows:

def draw_dense_reg(regmap, heatmap, center, value, radius, is_offset=False):
        diameter = 2 * radius + 1
        gaussian = gaussian2D((diameter, diameter), sigma=diameter / 6)
        value = np.array(value, dtype=np.float32).reshape(-1, 1, 1)
        dim = value.shape[0]
        reg = np.ones((dim, diameter*2+1, diameter*2+1), dtype=np.float32) * value
        if is_offset and dim == 2:
            delta = np.arange(diameter*2+1) - radius
            reg[0] = reg[0] - delta.reshape(1, -1)
            reg[1] = reg[1] - delta.reshape(-1, 1)
            ...

Questions: 
- Why "reg" is initialized by 1 ? Why not use 0 ?
- Why "reg" has size:  "diameter*2+1"?
- What does "delta" mean ?

**Comment by xingyizhou** [comment]
This is never used in the paper and never worked. I didn't remembered the details. Feel free to ignore it.

**Comment by seekFire** [comment]
> This is never used in the paper and never worked. I didn't remembered the details. Feel free to ignore it.
But in sample/ctdet.py, the class "CTDetDataset" used this function, I think it may be used for generating offset heatmap of center point detection...

**Comment by seekFire** [comment]
@xingyizhou 
But in sample/ctdet.py, the class "CTDetDataset" used this function, I think it may be used for generating offset heatmap of center point detection...

**Comment by JuvenileInWind** [comment]
Do you know how to generating offset heatmaps?
Are all the value of the offset heatmap the same?

**Comment by TangShengqin** [comment]
> Do you know how to generating offset heatmaps?
> Are all the value of the offset heatmap the same?

just look src/lib/datasets/sample/ctdet.py, you can get the answer !
