### ISSUE TITLE
Possible typo in get_pose_net for dlav0.py

### ISSUE THREAD

**Issue by dvbvr** [xingyizhou/CenterNet#321]
In line 642 in `src/lib/models/networks/dlav0.py` it says:
`def get_pose_net(num_layers, heads, add_conv=256, down_ratio=4):`
But we believe you meant:
`def get_pose_net(num_layers, heads, head_conv=256, down_ratio=4):`

**Comment by xingyizhou** [comment]
Thanks! It is a typo.
