### ISSUE TITLE
run test.py with an error of importing dataset_factory & detector_factory

### ISSUE THREAD

**Issue by liudanyang** [xingyizhou/CenterNet#325]
**the command is:**
python test.py ctdet --exp_id coco_dla --keep_res --load_model ../models/ctdet_coco_dla_2x.pth

**while an error occurs:**
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    from datasets.dataset_factory import dataset_factory
ImportError: No module named datasets.dataset_factory

When importing detector_factory, the same thing happens.
Please help me to fix it! Many thanks!

**Comment by xingyizhou** [comment]
Please make sure you are using python3.

**Comment by liudanyang** [comment]
> Please make sure you are using python3.

thanks a lot! solved

**Comment by engrjav** [comment]
@liudanyang  i am using python 3 still not solved. can you guide
