### ISSUE TITLE
Training: stuck

### ISSUE THREAD

**Issue by Ranchentx** [xingyizhou/CenterNet#33]
When I try to train on coco dataset, it is stuck as below: 

![Screenshot from 2019-04-25 14-29-22](https://user-images.githubusercontent.com/25639421/56735404-692efe00-6776-11e9-8083-627f2638251c.png)

My environment is : CUDA9.0 pytorch0.4.1, python3.6

**Comment by xingyizhou** [comment]
Hi,
  If you list `nvidia-smi` and the GPU usage looks good, then it might just due to the print function (progress) not working well (if you are using slurm). You can run `python -m xxxx --print_iter 1` to switch to standard screen print.

**Comment by sicarioakki** [comment]
I am stuck at the same problem. @xingyizhou what is 'xxxx' is your suggestion command?

**Comment by jaehyunshinML** [comment]
I am stuck at the same problem @Ranchentx have you found a solution ?
