### ISSUE TITLE
During the traing, I found that the log.txt is empty. Is this normal?

### ISSUE THREAD

**Issue by a954217436** [xingyizhou/CenterNet#338]
And do we have a visual tool to draw loss curve? 
Thanks for reading my question.
Wish you have a good day~

**Comment by ggsggs** [comment]
If you install tensorboardX you can see the curves using TensorFlow's TensorBoard, they are saved in exp/YOUR_TASK/YOUR_EXPERIMENT/log_DATE/.

**Comment by a954217436** [comment]
> If you install tensorboardX you can see the curves using TensorFlow's TensorBoard, they are saved in exp/YOUR_TASK/YOUR_EXPERIMENT/log_DATE/.

Thanks a lot, I will try it

**Comment by Jucjiaswiss** [comment]
my log.txt is empty too, have you solved it? @a954217436

**Comment by czc00125** [comment]
Hello，I followed the instructions presented on the website for training KITTI，but the log.txt is all none, have you solved it ?
