### ISSUE TITLE
Could you show you training log?

### ISSUE THREAD

**Issue by Fighting-JJ** [xingyizhou/CenterNet#34]
I tried the Experienment CTDET-DLA-PASCAL ,the train loss log ：
![图片](https://user-images.githubusercontent.com/17001854/56776560-95429180-67ff-11e9-9411-142430894c1b.png)

the loss of val (every five epoch)do not converge along with the epoches:
![图片](https://user-images.githubusercontent.com/17001854/56776600-dc308700-67ff-11e9-940e-8c7628d43050.png)

I do not change the BN to cpu.
Can you show your training log?
Thanks a lot.
@xingyizhou

**Comment by Fighting-JJ** [comment]
AP that I got:
![图片](https://user-images.githubusercontent.com/17001854/56776759-93c59900-6800-11e9-9bbc-232d743ed844.png)

**Comment by xingyizhou** [comment]
My log looks similar. The result is correct.

**Comment by Fighting-JJ** [comment]
Thanks for your reply.
