### ISSUE TITLE
How can I use tensorboardx?

### ISSUE THREAD

**Issue by sidney001** [xingyizhou/CenterNet#345]
I am using
'tensorboard --logdir exp/ctdet/coco_dla_1x/logs_2019-09-11-18-01/' . But it gots "No dashboards are active for the current data set."

**Comment by xingyizhou** [comment]
I haven't included tensorboard in install.md. But if you have installed it before launching training, it should work. You can check if tensorboard is successfully imported in `lib/logger.py` and the log files are created in the corresponding folder.

**Comment by zjp99** [comment]
@sidney001 您好，不知道你会使用log文件可视化了吗？
