### ISSUE TITLE
Training from nuScenes data advise

### ISSUE THREAD

**Issue by jinfagang** [xingyizhou/CenterNet#35]
Hi, I have managed training CenterNet 3d on kitti, it pretty nice on predicting 3d box using kitti format labeling. I wanna training it on nuScences now. I want get some advise from here:

1. nuScences has more classes then kitti, very pedestrian were classified into more detailed classes, should I treat them as single classes when training? (the people in wheelchairs is also labeled, the trash can and traffic cone were also elaborately labeled) Does so many classes can be trained on CenterNet? (in other words, how to choose reasonable classes to get a good performance?)

2. About the training input data and output data, input data is image of course, but how to prepared output data? (in kitti, it's object x,y,z hwl, r_y in 3D according to camera view, and in kitti the y axis is on the height side. But it seems not labeled like this. Will it effect the final result?)

thanks in advance.

**Comment by jinfagang** [comment]
Here is the nuScenes link for reference: https://www.nuscenes.org/download

**Comment by xingyizhou** [comment]
I can not give any advice at this point. We are also interested in unScenes and will work on it in the near future. But we don't plan to share this before we finish.

**Comment by jinfagang** [comment]
@xingyizhou  Aha! Hope you guys finish it as quick as possible, I am working on it too :）
