### ISSUE TITLE
during training,wh_loss and off_loss identically zero

### ISSUE THREAD

**Issue by keithyh** [xingyizhou/CenterNet#353]
![Screenshot from 2019-09-13 12-51-53](https://user-images.githubusercontent.com/14086114/64838416-a4e33b00-d625-11e9-8a50-a164f398531b.png)

By follow steps provided by the following link,I was able to train my own data now.However,as shown in the pic above,the wh_loss and off_loss are always zero,which is not the case in the link below.

https://blog.csdn.net/weixin_41765699/article/details/100118353

Can you explain what these two losses mean.

**Comment by xingyizhou** [comment]
Thanks for pointing out the blog. It is helpful for new users. You can use `--debug 2` to visualize your ground truth data. It is likely your training data is not in the correct format.

**Comment by mrkind** [comment]
I will have a try ,thank you author!

**Comment by mrkind** [comment]
Thank you author!I have solved this issue.You are correct,this issue is due to a bug in trainning data preprocessing.
