### ISSUE TITLE
Have you tried deeper DLA models? 

### ISSUE THREAD

**Issue by Epiphqny** [xingyizhou/CenterNet#364]
such as dla-60,dla-102? Why did you choose the dla network?

**Comment by evitself** [comment]
@Epiphqny Well I think the author have evaluated through a bunch of backbones (please read the paper), and it seems that dla34 has the best trade-off between accuracy and speed. And one more thing, if you read the paper carefully, you must have noticed that the second author of this paper is also the author of dla paper. So, I guess this must be one of the reason for choosing dla. ;)

**Comment by Epiphqny** [comment]
Ok, thanks for your reply.

**Comment by Epiphqny** [comment]
> @Epiphqny Well I think the author have evaluated through a bunch of backbones (please read the paper), and it seems that dla34 has the best trade-off between accuracy and speed. And one more thing, if you read the paper carefully, you must have noticed that the second author of this paper is also the author of dla paper. So, I guess this must be one of the reason for choosing dla. ;)

Ok, thanks for your reply!

**Comment by Epiphqny** [comment]
> @Epiphqny Well I think the author have evaluated through a bunch of backbones (please read the paper), and it seems that dla34 has the best trade-off between accuracy and speed. And one more thing, if you read the paper carefully, you must have noticed that the second author of this paper is also the author of dla paper. So, I guess this must be one of the reason for choosing dla. ;)

Ok, thanks for your reply!
