### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'hm_gauss'

### ISSUE THREAD

**Issue by David-19940718** [xingyizhou/CenterNet#366]
I add --mse_loss when i run main.py. it raise:
```
 File "/home/*/Project/CenterNet-master/src/lib/datasets/sample/ctdet.py", line 113, in __getitem__
    radius = self.opt.hm_gauss if self.opt.mse_loss else radius
AttributeError: 'Namespace' object has no attribute 'hm_gauss'

```
i found there is no hm_gauss parameter in your project.
Please tell me how to fixed it, tks. @xingyizhou

**Comment by xingyizhou** [comment]
You can add a `hm_gauss` in `opt.py`. I used 3 for input_res 384 and 4 for input_res 512. I didn't make mse loss work anyway.

**Comment by DangerousY** [comment]
> You can add a hm_gauss in opt.py. I used 3 for input_res 384 and 4 for input_res 512. I didn't make mse loss work anyway.

I want to how to add them, please. Thanks!
