### ISSUE TITLE
How to interpret the results of testing?

### ISSUE THREAD

**Issue by mrkind** [xingyizhou/CenterNet#368]
Dear author,After running test.py I obtained a result giving many APs and ARs.Can you provide a detailed explanation and interpretations of these results.Thank you!

![APAR](https://user-images.githubusercontent.com/14086114/65227058-8e902000-dafa-11e9-94c5-22eb1fc54e9c.jpg)

**Comment by evitself** [comment]
hi, @mrkind Let me answer your question, this is mscoco standard metrics, for example, first line is mAP@IOU[0.5:0.05:0.05], that is the mean value of every calculated mAP on IOU from 0.5 to 0.95 step 0.05. For details, please see official description. http://cocodataset.org/#detection-eval

**Comment by mrkind** [comment]
@evitself Thank you!I am almost clear now.What not mentioned in the official description is the meaning of maxDets. This quantity seems only relavent with AR.What does it mean?

**Comment by evitself** [comment]
@mrkind That means max detections per image. Basically, it is top K results of sorted detections by score desc.

**Comment by mrkind** [comment]
That makes sense!The bigger max detections is,the more likely  centernet will find all objects in the picture,so the larger AR is.

**Comment by xingyizhou** [comment]
Thanks @evitself . Closing this as the question is resolved.
