### ISSUE TITLE
use model 'ctdet_coco_resdcn18.pth' error

### ISSUE THREAD

**Issue by murdockhou** [xingyizhou/CenterNet#38]
Thanks for your work. 

I run `python demo.py ctdet --load_model ../models/ctdet_coco_dla_2x.pth  --demo ../images` successfully, but when i change the pre-trained model into `ctdet_coco_resdcn18.pth`, there some information such as ` No param reg_r.0.bias` and there is no correct result shown in picture. 

How i should do to solve this? Thanks~

**Comment by xingyizhou** [comment]
`reg_r` is from `exdet`. Can you show your command and the complete output log?

**Comment by murdockhou** [comment]
![Selection_072](https://user-images.githubusercontent.com/18358653/56875775-751c0800-6a75-11e9-866a-c49126f16624.png)
![Selection_073](https://user-images.githubusercontent.com/18358653/56875798-91b84000-6a75-11e9-82ca-4dc44af507ee.png)

this is mine conmand and part of output log, and there is nothing shown in output picture.
![Selection_074](https://user-images.githubusercontent.com/18358653/56875813-abf21e00-6a75-11e9-8951-7a00c007afbf.png)

**Comment by xingyizhou** [comment]
`--arch resdcn_18`

**Comment by murdockhou** [comment]
It's work, thanks a lot!
