### ISSUE TITLE
COCO Detector HG Training Command Typo

### ISSUE THREAD

**Issue by bsvineethiitg** [xingyizhou/CenterNet#384]
Hi. You mentioned in the paper and in another issue that you trained HG on COCO by finetuning on ExtremeNet (100 epochs) for 50 epochs with a decay at 40th epoch.

But your training command under experiments directory is as follows:

"python main.py ctdet --exp_id coco_hg --arch hourglass --batch_size 24 --master_batch 4 --lr 2.5e-4 --load_model ../models/ExtremeNet_500000.pth --gpus 0,1,2,3,4"

Shouldn't this be:

"python main.py ctdet --exp_id coco_hg --arch hourglass --batch_size 24 --master_batch 4 --lr 2.5e-4 --load_model ../models/ExtremeNet_500000.pth --gpus 0,1,2,3,4 --num_epochs 50 --lr_step 40"?

Thanks.

**Comment by xingyizhou** [comment]
Thanks for pointing it out! You are correct. It should be `--num_epochs 50 --lr_step 40`.
