### ISSUE TITLE
Trouble with demo.py

### ISSUE THREAD

**Issue by kunsung** [xingyizhou/CenterNet#385]
Hello, author. As shown in the picture, it got stuck when running the demo.py. May I ask how to solve it？
![demoWrong](https://user-images.githubusercontent.com/38248825/65824540-58dafc00-e29d-11e9-8282-538d11bf4b23.png)

**Comment by xingyizhou** [comment]
Our demo script uses `cv2.imshow` to visualize the output by default. If you are using ssh, it is likely the image is displayed on the server's screen. You can use `--debug 4` to dump the output to disk.

**Comment by kunsung** [comment]
> Our demo script uses `cv2.imshow` to visualize the output by default. If you are using ssh, it is likely the image is displayed on the server's screen. You can use `--debug 4` to dump the output to disk.

Thank you for your reply. But you seem to misunderstand me, I did not use ssh, imshow is normal.The problem is that the picture can also run out, but it will not save.

**Comment by kunsung** [comment]
> Our demo script uses `cv2.imshow` to visualize the output by default. If you are using ssh, it is likely the image is displayed on the server's screen. You can use `--debug 4` to dump the output to disk.
Thank you. I have solved this problem.

**Comment by zhiqwang** [comment]
Hi, @xingyizhou 
Add  `--debug 4` does not resolved this question
