### ISSUE TITLE
如果二个物体的中心center完全重合，请问此时预测出二个物体呢？

### ISSUE THREAD

**Issue by henbucuoshanghai** [xingyizhou/CenterNet#394]
和yolo1一样？？
如果二个物体center完全重合，就只预测出一个物体？舍弃另一个？

**Comment by jamie0618** [comment]
+1
Interested in the same question.

**Comment by lxtGH** [comment]
+2
Interested in the same question.

**Comment by ManiaaJia** [comment]
+3
Interested in the same question.

**Comment by zhly0** [comment]
个人觉得：如果是相同物体。会取概率最大的（只能够检测到一个）。如果是不同物体，不会互相影响。

**Comment by henbucuoshanghai** [comment]
同一类的话，只预测一个？

**Comment by kernel-Peanut** [comment]
同一类的话就只剩置信度最大的那个了

**Comment by henbucuoshanghai** [comment]
明白，那不同类呢？

**Comment by kernel-Peanut** [comment]
不同类不会有影响，就是在heatmap上的不同channel预测了同一个center，这样是可行的

**Comment by henbucuoshanghai** [comment]
我明白，heatmap是多类的，不同类分开。但是hw呢，一个center对应2个数值hw。   hw维度是多少呢，类别数乘以2？

**Comment by dl8207531** [comment]
默认参数不同类也只能检测出一个，因为宽高只有一个，除非使用dense_wh，但是听作者说使用dense_wh也提高不了多少点数

**Comment by henbucuoshanghai** [comment]
是的，算法有不足的

**Comment by henbucuoshanghai** [comment]
算法是有问题的对吧、、
