### ISSUE TITLE
gaussian kernal problem

### ISSUE THREAD

**Issue by qh332612340** [xingyizhou/CenterNet#395]
hello! 
thanks for your great work
but i have same problem in gaussian kernal
In you paper you said you used the gaussian kernal, but in code I can not find it 
can you tall me which the script do you use it ?

**Comment by jamie0618** [comment]
@qh332612340 
I think it's in /src/lib/utils/image.py 
There is a gaussian2D function.

**Comment by qh332612340** [comment]
@jamie0618 
Thanks a lot

**Comment by xingyizhou** [comment]
@jamie0618 is correct. Closing this.
