### ISSUE TITLE
Classwise MAP

### ISSUE THREAD

**Issue by abhigoku10** [xingyizhou/CenterNet#399]
@xingyizhou  hi thanks for teh wonderful code , how can i get the class wise ap , precision and recal values for the MSCOCO validation set ! can you share some pointers

**Comment by xingyizhou** [comment]
You will need to modify the COCO API for that. You can refer to the issues in the COCO API repo.

**Comment by abhigoku10** [comment]
@xingyizhou yup done with this activity thanks for the pointers
