### ISSUE TITLE
Not an issue - question on perspective detection

### ISSUE THREAD

**Issue by johndpope** [xingyizhou/CenterNet#4]
Could the training be easily configured to find corners of rooms / buildings / perspective?

![download](https://user-images.githubusercontent.com/289994/56337760-31f6a500-61ea-11e9-8ac8-93589e7692f6.jpeg)

**Comment by xingyizhou** [comment]
If you have such training data, yes. You will need to [add a new task](https://github.com/xingyizhou/CenterNet/blob/master/readme/DEVELOP.md). You can refer to our [StarMap](https://github.com/xingyizhou/StarMap) project about how to train a general keypoint detector. If you don't have such data annotation, no.

**Comment by johndpope** [comment]
thanks for quick response
