### ISSUE TITLE
how to shown model structure?

### ISSUE THREAD

**Issue by murdockhou** [xingyizhou/CenterNet#40]
Hi, i have meet some problems in looking at model structure part. I tried `tensorboardX` but it seems like need `torch version >= 1.0` where this repository needs 0.4. I also tried `pytorchviz` but i can not find suitable location to insert it. 

It's a little difficult for me to make it work. Could you please give me more instruction about this and help me out. Thanks a lot. I only want to look the different model structure more carefully. Thanks again.

**Comment by xingyizhou** [comment]
Hi,
  I am sure there is a 0.4 compatible tensorboardX version. But my code doesn't include the tensorboardX visualization part, and I haven't tried to visualize the architecture. As far as I can understand, [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/models/model.py#L28) should be a good place to insert `pytorchviz`.

**Comment by murdockhou** [comment]
Hi, 
tensorboardX=1.4 version can compatible with pytorch 0.4.1, [position](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/models/model.py#L28) that you provided is not work with tensorboardX either `pytorchviz`. So I changed to [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/detectors/base_detector.py#L115) based my knowledge but still caused error when running `tensorboardX` or `pytorchviz`. I have tried many ways to used `self.model` but can not get correct result. So hopefully that you can give more detailed information about this.

Sorry for trouble you with this, thanks a lot and best wishes for you.
