### ISSUE TITLE
use v100 ,model cost 500ms,but in titan xp ,cost 15ms,have some adapt?

### ISSUE THREAD

**Issue by mathpopo** [xingyizhou/CenterNet#402]

**Comment by mathpopo** [comment]
author,can tell me your env hardware of graphics card?

**Comment by xingyizhou** [comment]
Hi, we are aware of this issue but haven't looked into it in detail. Can you check [this](https://github.com/xingyizhou/CenterNet/issues/247)?

**Comment by mathpopo** [comment]
And I use https://github.com/CharlesShang/DCNv2.git  replace your code
pytorch1.2 cuda10.0 

is ok!!!!!!!!!!!!!!!!!!!
