### ISSUE TITLE
dla34 v0(没有deform conv) 版本的ctdet权重 可以下载吗？

### ISSUE THREAD

**Issue by CaoWGG** [xingyizhou/CenterNet#408]
dla34 v0(没有deform conv) 版本的ctdet权重 可以下载吗？

**Comment by ZhWL123456** [comment]
可以的，运行的时候会自动下载~

**Comment by ZhWL123456** [comment]
运行的时候代码会自动下载网络匹配的权重

**Comment by CaoWGG** [comment]
> 运行的时候代码会自动下载网络匹配的权重

预训练权重会自动下载，  训练好的权重也会自动下载吗？
