### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by DangerousY** [xingyizhou/CenterNet#412]
I use this to train pascal data in just one class.
python main.py ctdet --exp_id pascal_dla_384 --dataset pascal --num_epochs 70 --lr_step 45,60 --gpus 5,6

then I have those problems:

Creating model...
Setting up data...
==> initializing pascal test2007 data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded val 33 samples
==> initializing pascal trainval0712 data.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loaded train 131 samples
Starting training...
ctdet/pascal_dla_384Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/CenterNet/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/CenterNet/src/lib/datasets/sample/ctdet.py", line 39, in __getitem__
    height, width = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

I want to ask why I meet with this problem? Thanks!

**Comment by DangerousY** [comment]
my data just like this 

${CenterNet_ROOT}
|-- data
`-- |-- voc
    `-- |-- annotations
        |   |-- pascal_trainval0712.json
        |   |-- pascal_test2017.json
        |-- images
        |   |-- 000001.jpg
        |   ......
        `-- VOCdevkit

**Comment by DangerousY** [comment]
> my data just like this
> 
> ${CenterNet_ROOT}
> |-- data
> `-- |-- voc `-- |-- annotations
> | |-- pascal_trainval0712.json
> | |-- pascal_test2017.json
> |-- images
> | |-- 000001.jpg
> | ......
> `-- VOCdevkit

same with the guide

**Comment by AsharFatmi** [comment]
@DangerousY 

Going through the console output, I believe the problem is with the image is not being read by the program.

The issue is generated by the line in `ctdet.py` at `/home/CenterNet/src/lib/datasets/sample/ctdet.py `which means that the image is not being read by the line `img = cv2.imread(img_path)`, which may be caused by two issues:-
- The images are corrupted.
- The images are not at the specified location.

Make sure that the images are not corrupted and the dataset is located at the correct directory as specified in DATA.md  read me file : [https://github.com/xingyizhou/CenterNet/blob/master/readme/DATA.md](https://github.com/xingyizhou/CenterNet/blob/master/readme/DATA.md)

**Comment by DangerousY** [comment]
@AsharFatmi 
Yes, I find the problem, which is my wrong location. Thank you!
