### ISSUE TITLE
how did you implement jd in pose estimation

### ISSUE THREAD

**Issue by leonzgtee** [xingyizhou/CenterNet#416]
could you tell me how did you implement matching regression to the closest joint detection in table 5
DLA-reg 51.7 81.4 55.2 44.6 63.0
HG-reg 55.0 83.5 59.7 49.4 64.0
DLA-jd 57.9 84.7 63.1 52.5 67.4
HG-jd 63.0 86.8 69.6 58.9 70.4

**Comment by xingyizhou** [comment]
You can use `--not_hm_hp --not_reg_hp_offset`.

**Comment by leonzgtee** [comment]
@xingyizhou thank you
