### ISSUE TITLE
Do I need to reset the gaussian parameter if i want to modify the network input resolution?

### ISSUE THREAD

**Issue by Epiphqny** [xingyizhou/CenterNet#420]
For example, set 512 to 768, or 384, have you tried larger size? thanks!

**Comment by xingyizhou** [comment]
Usually no, the gaussian radius is adaptive to the actual pixel size. However I haven't tried modifying these parameters.

**Comment by Epiphqny** [comment]
> Usually no, the gaussian radius is adaptive to the actual pixel size. However I haven't tried modifying these parameters.

Ok, i will have a try.

**Comment by Bluswy** [comment]
could you tell me which parameters you change when you are going to change the default size?
Can I train the model with the nonsquare
