### ISSUE TITLE
About ground truth validation parsers meaning: such as eval_oracle_hm

### ISSUE THREAD

**Issue by ZhWL123456** [xingyizhou/CenterNet#431]
In the opts.py， there are some parsers listed as following:
    # ground truth validation
    self.parser.add_argument('--eval_oracle_hm', action='store_true', 
                             help='use ground center heatmap.')
    self.parser.add_argument('--eval_oracle_wh', action='store_true', 
                             help='use ground truth bounding box size.')
    self.parser.add_argument('--eval_oracle_offset', action='store_true', 
                             help='use ground truth local heatmap offset.')
    self.parser.add_argument('--eval_oracle_kps', action='store_true', 
                             help='use ground truth human pose offset.')
    self.parser.add_argument('--eval_oracle_hmhp', action='store_true', 
                             help='use ground truth human joint heatmaps.')
    self.parser.add_argument('--eval_oracle_hp_offset', action='store_true', 
                             help='use ground truth human joint local offset.')
    self.parser.add_argument('--eval_oracle_dep', action='store_true', 
                             help='use ground truth depth.')
Can somebody can explain their functions? I notice there are useful in loss function.
Thanks very much🌹

**Comment by xingyizhou** [comment]
They are used to produce Table. 7 in the supplementary material.

**Comment by ZhWL123456** [comment]
> They are used to produce Table. 7 in the supplementary material.

Thank u~
