### ISSUE TITLE
About the parameters "eig_val" and "eig_vec"

### ISSUE THREAD

**Issue by ZhWL123456** [xingyizhou/CenterNet#437]
In the file "./src/lib/datasets/dataset/coco.py", there are parameters "self.eig_val" and eig_vec, I know they mean eigenvalue and eigenvector. But i dont know how they work in this network, and how they count in our own dataset. 
Thanks for helping🌹

**Comment by DHU-th** [comment]
I have the same question with you ,looking for the answer

**Comment by ZhWL123456** [comment]
> I have the same question with you ,looking for the answer

I find it is used for data_aug(color aug). But I think it is difficult to count their value.

**Comment by xingyizhou** [comment]
They are from CornerNet code for color augmentation. I will suggest using the same values for your custom dataset.

**Comment by ZhWL123456** [comment]
Thanks for replying!
But Can I count the values of my dataset?





------------------ Original ------------------

**Comment by xingyizhou** [comment]
I have no idea. You can ask this in the CornerNet repo.

**Comment by javierlorenzod** [comment]
@ZhWL123456 I do not know if you found the answer. I also searched for it and in issue #280 you have the source of this transformation. Also, I have found that, among albumentations transforms, there is one called [**fancyPCA**](https://github.com/albumentations-team/albumentations/blob/2e48ce926973ab1ca492b98953740b9e12f92481/albumentations/augmentations/functional.py#L1949) which corresponds to the same transformation but using eigenvectors and eigenvalues from the PCA of one image. I think that the precomputed values from `coco.py`corresponds to the mean values between all dataset, similar to the ones from ImageNet:
```python
    'eigval': torch.Tensor([0.2175, 0.0188, 0.0045]),
    'eigvec': torch.Tensor([
        [-0.5675,  0.7192,  0.4009],
        [-0.5808, -0.0045, -0.8140],
        [-0.5836, -0.6948,  0.4203],
    ])
```

More info: https://machinelearning.wtf/terms/pca-color-augmentation/

**Comment by ZhWL123456** [comment]
> @ZhWL123456 I do not know if you found the answer. I also searched for it and in issue #280 you have the source of this transformation. Also, I have found that, among albumentations transforms, there is one called [**fancyPCA**](https://github.com/albumentations-team/albumentations/blob/2e48ce926973ab1ca492b98953740b9e12f92481/albumentations/augmentations/functional.py#L1949) which corresponds to the same transformation but using eigenvectors and eigenvalues from the PCA of one image. I think that the precomputed values from `coco.py`corresponds to the mean values between all dataset, similar to the ones from ImageNet:
> 
> ```python
>     'eigval': torch.Tensor([0.2175, 0.0188, 0.0045]),
>     'eigvec': torch.Tensor([
>         [-0.5675,  0.7192,  0.4009],
>         [-0.5808, -0.0045, -0.8140],
>         [-0.5836, -0.6948,  0.4203],
>     ])
> ```
> 
> More info: https://machinelearning.wtf/terms/pca-color-augmentation/
thank u very much~
