### ISSUE TITLE
test on  voc

### ISSUE THREAD

**Issue by zjp99** [xingyizhou/CenterNet#444]
voc07  test,4952samples,map==77.64,use the model -----ctdet_pascal_dla_384.pth,what should i do for map 79.3?

**Comment by xingyizhou** [comment]
Can you specify your command? Make sure you have included `--flip_test`.

**Comment by zjp99** [comment]
> 
> 
> Can you specify your command? Make sure you have included `--flip_test`.

that's ok,add --flip_test

**Comment by zjp99** [comment]
> 
> 
> Can you specify your command? Make sure you have included `--flip_test`.

I have another question。test on coco17,the result AP=-1
python test.py ctdet --exp_id coco_dla --trainval --keep_res --resume --load_model ../models/ctdet_coco_dla_2x.pth

**Comment by zjp99** [comment]
> 
> 
> Can you specify your command? Make sure you have included `--flip_test`.

![0EBAFD8564F37FA1739DC1348B63026B](https://user-images.githubusercontent.com/38965650/68267583-e0324100-008d-11ea-8063-ed7b3504ea1a.jpeg)

**Comment by zjp99** [comment]
![IMG_20191104_215118](https://user-images.githubusercontent.com/38965650/68267620-fe983c80-008d-11ea-90ff-4ac51e2be2a5.jpg)

**Comment by xingyizhou** [comment]
You will need to submit to COCO test server for the results on test-dev. The label is not publicly available.

**Comment by zjp99** [comment]
How can I submit it in your code?

**Comment by zjp99** [comment]
How can I save the results to submit？I use your model and code

**Comment by xingyizhou** [comment]
In general, you should not submit to the test server unless it is your original and final model. I will discourage it by not telling you how to do this, although it is easy to figure it out yourself by reading the code.

**Comment by DanZhang123** [comment]
Hi I have the same problem ，but I sure I have included --flip_test vo
 test,4952samples,map==79.3,use the model -----ctdet_pascal_dla_384.pth,;     but use the model ------ctdet_pascal_dla_512.pth,  the map == 78.62 , what should i do for map 80.7?
