### ISSUE TITLE
Can I do multi classification training when I do multi-pose

### ISSUE THREAD

**Issue by bleakie** [xingyizhou/CenterNet#445]
Can I do multi classification training when I do attitude estimation？

**Comment by xingyizhou** [comment]
We are working on this. However we observed dropped performance for both tasks.

**Comment by bleakie** [comment]
For example, I want to identify car and human body posture, which is a parallel task. Why is it worse

**Comment by xingyizhou** [comment]
We just observed it in experiments. Explaining it is nontrivial. Feel free to have a try yourself.
