### ISSUE TITLE
你好，请教下，Image在送入网络前做warpAffine的目的是什么，为什么不直接用resize实现呢，哪怕是直接resize为512*512？

### ISSUE THREAD

**Issue by xiaoxinggui** [xingyizhou/CenterNet#448]

**Comment by zhiqwang** [comment]
Just for data augmentation, I guess.

**Comment by fafancier** [comment]
using warpAffine can implement rotational augmentation, maybe it's more powerful than resize function, I guess.

**Comment by zhiqwang** [comment]
I write a small snippet to show the data augmentation result. Maybe you can use it to take a look of the `warpAffine` result.

```python
from datasets.dataset_factory import get_dataset

Dataset = get_dataset(opt.dataset, opt.task)
train_dataset = Dataset(opt, 'train')


def decode(sample):
    image = sample['input']
    image = image * 0.2726 + 0.2668  # mean and std
    image = image.transpose(1, 2, 0)
    # image = np.clip(image, 0, 1)

    num_objs = 0
    for i in sample['reg_mask']:
        if i == 1:
            num_objs += 1
        else:
            break

    bbox = np.zeros((num_objs, 4))
    for i in range(num_objs):
        x = sample['ind'][i] % 64  # 64 represent for the size of the last feature map
        y = sample['ind'][i] // 64
        x = sample['reg'][i][0] + x
        y = sample['reg'][i][1] + y
        w, h = sample['wh'][i]
        bbox[i] = [x - w / 2, y - h / 2, x + w / 2, y + h / 2]
    return image, bbox, num_objs


train_data_sample = next(iter(train_dataset))
train_img, train_bbox, train_num_objs = decode(train_data_sample)

for i in range(train_num_objs):
    color = [0, 0, 0]

    bbox = train_bbox[i]
    bbox = [int(j * 4) for j in bbox]
    color[i % 3] = 1
    cv2.rectangle(train_img, (bbox[0], bbox[1]), (bbox[2], bbox[3]), color, 2)

plt.imshow(train_img[:,:,::-1])
```

**Comment by xingyizhou** [comment]
Yes the major reason I use affine transform is for rotation augmentation in training. However it is never used in the current version. You are free to replace it with a simpler crop and resize.

**Comment by xiaoxinggui** [comment]
> Yes the major reason I use affine transform is for rotation augmentation in training. However it is never used in the current version. You are free to replace it with a simpler crop and resize.
谢谢您的回复，我们暂时才用resize实现了能正常使用。顺便再请教下，你们在用的当前版本没有开源？跟github上的版本差异不大吧？

**Comment by zhiqwang** [comment]
Hi @xiaoxinggui , the parameter 0 in the following line represents that there is no rotation augmentation, I guess.
https://github.com/xingyizhou/CenterNet/blob/9efed05d531922b001b101c648c7ac5af3a9dafb/src/lib/datasets/sample/ctdet.py#L84

**Comment by xiaoxinggui** [comment]
> trans_output = get_affine_transform(c, s, 0, [output_w, output_h])

谢谢！
