### ISSUE TITLE
ModuleNotFoundError: No module named '_ext'

### ISSUE THREAD

**Issue by ssshcj** [xingyizhou/CenterNet#454]
Linux QT C++ use demo.py，get an error:
from .DCNv2.dcn_v2 import DCN
File "/home/hhh/Downloads/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 13, in <module>
import _ext as _backend
ModuleNotFoundError: No module named '_ext'
Can someone help me? Thanks!

**Comment by inspiros** [comment]
Change directory to `src/models/networks/DCNv2` and run `sh make.sh`

**Comment by maoxx97** [comment]
when you run `./make.sh` in dir DCNv2.
maybe you should also change `sudo python setup.py build develop` into `sudo /your/path/to/python setup.py build develop`, when you have multiple env of python

**Comment by hello-worldmaker** [comment]
1.rename DCNv2-master as DCNv2
2.remove DCNv2 to path( 'D:\anaconda\envs\CenterNet\Lib\site-packages' ) 
3.In cmd(windows):D:\anaconda\envs\CenterNet\Lib\site-packages\DCNv2>D:\anaconda\envs\CenterNet\python setup.py build develop
4.this file(_ext.cp36-win_amd64.pyd) aslo in D:\anaconda\envs\CenterNet\Lib\site-packages\DCNv2\_ext.cp36-win_amd64.pyd and D:\anaconda\envs\CenterNet\Lib\site-packages\DCNv2\build\lib.win-amd64-3.6\_ext.cp36-win_amd64.pyd.
I would suggest 
rename `D:\anaconda\envs\CenterNet\Lib\site-packages\DCNv2\_ext.cp36-win_amd64.pyd` as `D:\anaconda\envs\CenterNet\Lib\site-packages\DCNv2\_ext.pyd`
rename`D:\anaconda\envs\CenterNet\Lib\site-packages\DCNv2\build\lib.win-amd64-3.6\_ext.cp36-win_amd64.pyd` as `D:\anaconda\envs\CenterNet\Lib\site-packages\DCNv2\build\lib\_ext.pyd`
4.Successfully solved problem No module '_ext' in windows10

**Comment by whzz101** [comment]
> Change directory to `src/models/networks/DCNv2` and run `sh make.sh`

yes, don't use sudo ./make.sh

**Comment by mryoungci** [comment]
when you had _ext.cpython-37m-x86_64-linux-gnu.so
copy it to "_ext.so"  and add following code in  dcn_v2.py
import sys
sys.path.append(r'Yourpath/CenterTrack-master/src/lib/model/networks/DCNv2/')
