### ISSUE TITLE
ResNet non DCN pretrained weight

### ISSUE THREAD

**Issue by wuhy08** [xingyizhou/CenterNet#458]
Hi,

I noticed that for your resnet backbone models, they all have DCN in it. Do you have any non-DCN model?

Thank you!

**Comment by xingyizhou** [comment]
Our model does not work well without DCN so we don't provide this model and don't encourage people to use it. You can train the model yourself if you really want.

**Comment by wuhy08** [comment]
Thank you @xingyizhou !
