### ISSUE TITLE
error when  train with my own pascal datasets error: AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by pingnuttakrid** [xingyizhou/CenterNet#459]
the error is 

AttributeError: 'NoneType' object has no attribute 'shape'

in other issue say the error is from wrong images directory in coco.py 
but i think i do correctly  because i  do follow data.md in readme 

my directoy

![image](https://user-images.githubusercontent.com/42993287/68546791-026ceb80-040d-11ea-942c-9a8bb7737b66.png)

directory code in pascal.py

![image](https://user-images.githubusercontent.com/42993287/68546804-2af4e580-040d-11ea-8c2e-a2cc0cdf7a62.png)

format in data.md

![image](https://user-images.githubusercontent.com/42993287/68546813-511a8580-040d-11ea-83e7-e7471200ee9d.png)

how can i solve it

**Comment by xingyizhou** [comment]
You can try printing out the path in cv2.imread and check if it exists.
