### ISSUE TITLE
Extracting meaningful pose information from model output

### ISSUE THREAD

**Issue by stbjelcevic** [xingyizhou/CenterNet#46]
Is there a straightforward way to parse the output from the pose model? For example, if I wanted just the coordinates of all of the detected foot keypoints, how would I obtain those from looking at 'ret' with the following line:

`ret = centernet_detector.run(img)['results']`

Where centernet_detector was initialized with the following model:

```
MODEL_PATH = "../models/multi_pose_dla_3x.pth"
TASK = 'multi_pose' 
opt = opts().init('{} --load_model {}'.format(TASK, MODEL_PATH).split(' '))
centernet_detector = detector_factory[opt.task](opt)
```

Not really an issue - just trying to understand if there's an easy way to parse the output that I've overlooked because at the moment, ret is returned as a massive dictionary with 1 key value that looks like this (and this is just a small chunk of it):

{1: [[431.6806335449219, 374.5654296875, 798.3137817382812, 806.46533203125, 0.9136448502540588, 596.3617553710938, 451.5331115722656, 574.0827026367188, 441.81072998046875, 598.2064819335938, 444.61395263671875, 521.5050048828125, 435.496337890625, 592.1182250976562, 452.6651306152344, 465.6389465332031, 520.5789184570312, 612.9014892578125, 522.172607421875, 444.38726806640625, 601.4559936523438, 692.7471923828125, 614.8954467773438, 520.7488403320312, 474.4514465332031, 700.9055786132812, 577.1103515625, 532.8385009765625, 736.5150146484375, 634.1228637695312, 736.1271362304688, 623.9586181640625, 757.8681640625, 748.8753051757812, 693.3152465820312, 627.692626953125, 819.211669921875, 763.8153686523438, 810.7884521484375], [1150.5811767578125, 243.87657165527344, 1309.4493408203125, 445.14276123046875, 0.8061871528625488, 1273.1363525390625, 298.8131408691406, 1272.9134521484375, 288.4426574707031, 1268.0367431640625, 295.4898376464844, 1242.2972412109375, 281.63641357421875, 1233.7552490234375, 296.6488952636719, 1197.0325927734375, 321.2576599121094, 1218.05224609375, 341.2820739746094, 1256.329833984375, 355.447998046875, 1230.5333251953125, 421.34320068359375, 1274.132080078125, 307.4358825683594, 1275.4371337890625, 431.8289489746094, 1185.95556640625, 444.4655456542969, 1200.3651123046875, 460.19976806640625, 1249.952880859375, 467.85028076171875, 1283.1112060546875, 476.4889831542969, 1236.3939208984375, 513.936767578125, 1261.282958984375, 516.7928466796875], ... ]]}

In addition to this, where is the code that outputs the skeleton drawing for the demo? I presume the answer to my initial question may lie there, but I can't find that either.

Thanks!

**Comment by xingyizhou** [comment]
Hi,
  Thanks for your interests. The output is a `4 + 1 + 17 x 2` d list, where the first `4` dimensions are the bounding box, the `5`th dimension is the score, and the rest `17 x 2` dimensions are the 17 human joints in the image coordinate. The visualization code is [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/debugger.py#L191) and is invoked [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/detectors/multi_pose.py#L93). 
  Thanks for bringing this up, we will make the output more readable in the next code revision.

**Comment by stbjelcevic** [comment]
Thanks again for the quick response!
