### ISSUE TITLE
inference on Jetson nano

### ISSUE THREAD

**Issue by hyperparameters** [xingyizhou/CenterNet#461]
I am trying to run the model on my Jetson Nano 
it gives the following error 

`error in modulated_deformable_im2col_cuda : too many resources requested for launch`

how to control the resources???

**Comment by faheuer** [comment]
If this is still open: You need to modify code in the cuda file (Should be src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu), correct:

const int CUDA_NUM_THREADS = 512; 


Then compile again. For some reason Aarch64 cannot handle 1024.

**Comment by hyperparameters** [comment]
Yes I did the same modification and it worked.
Thankyou

**Comment by abedMeto** [comment]
I did the same fix and compiled DCNv2 successfully
but when running test_cuda.py I get:

RuntimeError: Backward is not reentrant, i.e., running backward with same input and grad_output multiple times gives different values, although analytical gradient matches numerical gradient. The tolerance for nondeterminism was 0.0.
Segmentation fault (core dumped)

any advice?

**Comment by abedMeto** [comment]
> Yes I did the same modification and it worked.
> Thankyou

hyperparameters! did you managed to run center net on jetson nano?

**Comment by hyperparameters** [comment]
@abedMeto yes i did run it but with pytorch only, i was trying to write it with tensort but was unsuccessful

**Comment by WhaSukGO** [comment]
@hyperparameters Could you tell us about the performance? I'm planning to experiment with it on Jetson Nano in real time. Also, how's TensorRT going on?

**Comment by hyperparameters** [comment]
@WhaSukGO I was unable to compile the deformable conv layers on TensorRT. with pytorch the performance is not realtime don't remember the exact inference time now.

**Comment by abedMeto** [comment]
I got about 4 HZ using pytorch

**Comment by Mehdi0xC** [comment]
@abedMeto can you please provide the steps for reproducing the result you've got?

**Comment by abedMeto** [comment]
> @abedMeto can you please provide the steps for reproducing the result you've got?

1. first you must have a python 3.6 distribution that is NOT Anaconda 
2. Make and install pytorch 1.3.0 from source. This take a long time on Jetson nano
3. Remove the folder DCNv2 from CenterNet and the latest DCNv2 from github
4. follow the instruction for CenterNet setup
note: I am not sure about other issues of dependencies packages that is not compatible with ARM. If there is then should be build locally from source
