### ISSUE TITLE
Is it possible that model predict two center points for one object? 

### ISSUE THREAD

**Issue by aboutx** [xingyizhou/CenterNet#462]
It seems that you take the top 100 peak points as center point. So is it possible that model predict two center points for one object? If possible, how do you deal with it? If not, how do you avoid it? Thank you very much!

**Comment by xingyizhou** [comment]
It is possible. The mAP metric does not penalize low-confident predictions. If you want to avoid it, you can set a output_threshold to filter out the low confident prediction.

**Comment by aboutx** [comment]
Okay, thanks again!
