### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

### ISSUE THREAD

**Issue by Yuki-TU** [xingyizhou/CenterNet#463]
When I run the following code:
`python test.py ddd --exp_id 3dop --dataset kitti --kitti_split 3dop --load_model ../models/ddd_3dop.pth`

I got the following error:

> Traceback (most recent call last):
  File "test.py", line 15, in <module>
    from external.nms import soft_nms
  File "__init__.pxd", line 918, in init nms
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

What should I do?
thank you for reading it until the very end.

**Comment by xingyizhou** [comment]
You can compile nms following readme or comment out the import soft_nms line.

**Comment by Yuki-TU** [comment]
It worked fine when I cloned the repository to a new directory and recreated it.
Thank you.
