### ISSUE TITLE
Install COCOAPI error: _mask.c: No such file or directory

### ISSUE THREAD

**Issue by slzhly** [xingyizhou/CenterNet#464]
when i Install COCOAPI with the following step:
COCOAPI=/path/to/clone/cocoapi
git clone https://github.com/cocodataset/cocoapi.git $COCOAPI
cd $COCOAPI/PythonAPI
make

print the follow error:
gcc -pthread -B /home/yun/anaconda3/envs/python3.6_pytorch0.4.1/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yun/anaconda3/envs/python3.6_pytorch0.4.1/lib/python3.6/site-packages/numpy/core/include -I../common -I/home/yun/anaconda3/envs/python3.6_pytorch0.4.1/include/python3.6m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.6/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
gcc: error: pycocotools/_mask.c: No such file or directory
error: command 'gcc' failed with exit status 1
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1

my gcc is 5.4 cuda=9.0

**Comment by AlexandrWh** [comment]
The same error. What should I do?

**Comment by li-source** [comment]
you can try "pip install cython"
