### ISSUE TITLE
error when run test.py "list index out of range' with my custom voc datasets

### ISSUE THREAD

**Issue by pingnuttakrid** [xingyizhou/CenterNet#466]
![image](https://user-images.githubusercontent.com/42993287/68732638-bc7b7780-0606-11ea-905a-ee44bf014372.png)

this is error when i run test.py with my custom pascal_voc datasets

**Comment by xingyizhou** [comment]
I have no idea. Can you print `all_bboxes`, `cls_ind`, and `im_ind` before this line?

**Comment by moyans** [comment]
> I have no idea. Can you print `all_bboxes`, `cls_ind`, and `im_ind` before this line?

i convert my data to coco format, my data class only one, so i change `self.class_name = [
      '__background__', 'person']` and `self._valid_ids = [1,]` in lib/dataset/coco.py, when i use test.py eval mAP, in this `category_id = self._valid_ids[cls_ind - 1]` lines get "list index out of range' erro too, can you help me.

**Comment by TWDH** [comment]
@pingnuttakrid  Have you solved the problem? I met the same issue, and the mAp output all goes to 0. Thanks!
