### ISSUE TITLE
使用resnet101 训练multipose任务时，模型收敛效果差

### ISSUE THREAD

**Issue by grainw** [xingyizhou/CenterNet#467]
resnet系列效果都比较差，同样的数据用dla，hourglass 都收敛特别好

**Comment by grainw** [comment]
验证模型时，没有任何结果输出

**Comment by fafancier** [comment]
resnet收敛都很差是吗？我也小试了一下，后面还要在这个基础上试试，你是从头训练的吗

**Comment by grainw** [comment]
有预加载的模型，hm_loss 到2.3就不下降了

**Comment by grainw** [comment]
@xingyizhou 能否给解答下啊
