### ISSUE TITLE
question about architecture of CenterNet

### ISSUE THREAD

**Issue by chaos0625** [xingyizhou/CenterNet#469]
As we know, FPN is a very useful part for object detection because it can fuse features of mulity layers. 
Why CenterNet didn't use FPN just like other neural networks?
If I add FPN to CenterNet, does it useful for improve performance？

**Comment by xingyizhou** [comment]
The simple reason is I didn't find time to try. I believe it will be helpful.

**Comment by chaos0625** [comment]
@xingyizhou Thanks for your reply

**Comment by yarkable** [comment]
@chaos1992 you mean feature fusion or multi-level feature prediction ?

**Comment by goldentimecoolk** [comment]
@chaos1992 Hi, have you tried this solution? I experimented it but got poor performance. I don't know where is wrong.
