### ISSUE TITLE
ddd.py problem

### ISSUE THREAD

**Issue by GuoChuan1314** [xingyizhou/CenterNet#472]
CenterNet_ROOT/src/lib/detectors/ddd.py", line 62, in process
    output['dep'] = 1. / (output['dep'].sigmoid() + 1e-6) - 1.

KeyError: 'dep'

**Comment by xingyizhou** [comment]
Can you show your commend? Please make sure you haven't modified the code.

**Comment by GuoChuan1314** [comment]
hello author.I've implemented this program.Thank you for your help.Then I will do my work on your basis.Thank you very much for your guidance.The best wish to you.
