### ISSUE TITLE
how can i evaluate mAP result of each class when run test.py

### ISSUE THREAD

**Issue by pingnuttakrid** [xingyizhou/CenterNet#474]
when i run test.py with my own coco custom datasets 

i can evaluate only AP (Average Precision)

how can i evaluate mAP of each class

![image](https://user-images.githubusercontent.com/42993287/69036324-3735ff80-0a18-11ea-97d0-2ff02c19a551.png)

**Comment by pingnuttakrid** [comment]
![image](https://user-images.githubusercontent.com/42993287/69036324-3735ff80-0a18-11ea-97d0-2ff02c19a551.png)

**Comment by pingnuttakrid** [comment]
i want something looklike this 

![image](https://user-images.githubusercontent.com/42993287/69051444-ea155600-0a36-11ea-9839-ffe0253fcd88.png)
 
but with my custom coco datasets

**Comment by LaCandela** [comment]
You can try this approach:
[https://stackoverflow.com/questions/56247323/coco-api-evaluation-for-subset-of-classes](url)

**Comment by pingnuttakrid** [comment]
@LaCandela thank you

**Comment by xingyizhou** [comment]
For COCO stype per-class AP, you will need to modify the COCO API. See the issues in the COCO API repo for reference.
