### ISSUE TITLE
how to obtain more accurate confidence values?

### ISSUE THREAD

**Issue by mrkind** [xingyizhou/CenterNet#475]
In object detection task,I found that the confidence values on the bounding boxes possesses only one digit precision,like 0.9,0.8,1.0,...etc.

How to obtain more accurate confidence values like 0.989,0.879,...etc.

Thanks

**Comment by xingyizhou** [comment]
https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/debugger.py#L179

**Comment by mrkind** [comment]
Thanks! Got it
