### ISSUE TITLE
Very poor performance using provided pretrained model(KITTI, 3DOP)

### ISSUE THREAD

**Issue by yzheng97** [xingyizhou/CenterNet#48]
Thanks for your nice work. I download your pretrained model for 3DOP split and follow the instruction in GETTING_STARTED.md. Here is the kitti evaluation result: 

car_detection AP: 96.919403 87.846443 79.191116
car_orientation AP: 93.916435 84.285149 75.674400
pedestrian_detection AP: 69.930481 60.852219 52.161320
pedestrian_orientation AP: 52.551113 45.630672 39.154442
cyclist_detection AP: 73.306274 48.693352 41.659622
cyclist_orientation AP: 63.731075 41.754368 36.320240
car_detection_ground AP: 3.543346 4.392704 3.567544
pedestrian_detection_ground AP: 5.368695 5.038685 4.873090
cyclist_detection_ground AP: 4.042099 3.308401 3.359062
car_detection_3d AP: 0.890253 1.148476 1.380574
pedestrian_detection_3d AP: 4.984490 4.746258 3.636364
cyclist_detection_3d AP: 3.657130 3.113063 3.147585

Compared with your paper, the 2D detection and AOS result of car category is fairly normal, while the result of 3D detection and BEV detection is extremely low. I wonder if I made any mistake.

**Comment by xingyizhou** [comment]
Hi,
  The evaluation works well in my machine. Can you show your commond and specify the modification you have made to the code? The most possible reason is that the camera calibration is not correctly provided. Please check `img_info['calib']` is correct [here](https://github.com/xingyizhou/CenterNet/blob/master/src/test.py#L39).

**Comment by yzheng97** [comment]
> Hi,
> The evaluation works well in my machine. Can you show your commond and specify the modification you have made to the code? The most possible reason is that the camera calibration is not correctly provided. Please check `img_info['calib']` is correct [here](https://github.com/xingyizhou/CenterNet/blob/master/src/test.py#L39).

I haven't made any modification yet. I went through the `convert_kitti_to_coco.py` and make sure that `img_info['calib']` comes from `P2` matrix in `calib` text file. Maybe the raw calib file is different? Below is part of the `kitti_3dop_val.json`.

> "file_name": "000001.png", "id": 1, "calib": [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257]]

> "file_name": "000002.png", "id": 2, "calib": [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257]]

> "file_name": "000004.png", "id": 4, "calib": [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257]]

> "file_name": "000005.png", "id": 5, "calib": [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257]]

> file_name": "000006.png", "id": 6, "calib": [[718.3350830078125, 0.0, 600.3890991210938, 44.50381851196289], [0.0, 718.3350830078125, 181.51220703125, -0.5951107144355774], [0.0, 0.0, 1.0, 0.0026163149159401655]]

> file_name": "000008.png", "id": 8, "calib": [[721.5377197265625, 0.0, 609.559326171875, 44.85728073120117], [0.0, 721.5377197265625, 172.85400390625, 0.2163791060447693], [0.0, 0.0, 1.0, 0.0027458840049803257]]}

**Comment by xingyizhou** [comment]
Hi,
  Thanks for bringing up the problem. I found it is because that the default kitti_eval script use `0.7` IoU threshold, and the numbers we referred are evaluated using `0.5` IoU threshold, as is specified in the paper and is consistent with the compared methods (also see [here](http://openaccess.thecvf.com/content_cvpr_2018/papers/Xu_Multi-Level_Fusion_Based_CVPR_2018_paper.pdf)). You will need to change the IoU threshold in the evaluation script [here](https://github.com/prclibo/kitti_eval/blob/master/evaluate_object_3d_offline.cpp#L54). We will update GETTING_STARTED.md.

**Comment by yzheng97** [comment]
Thanks for your reply! 
Besides, it seems that the predicted results is saved in $ROOT/exp/ddd/3dop/results, but the default kitti_eval script reads them in $ROOT/exp/ddd/3dop/results/data.

**Comment by xingyizhou** [comment]
I also fixed this in the new commit.
