### ISSUE TITLE
Run Demo error

### ISSUE THREAD

**Issue by forevergogi** [xingyizhou/CenterNet#481]
Current Env:torch 1.2.0 py 3.6 CentOs
I have built the DCN part successfully! However, when I run the demo file.It goes wrong and reminders that Drop parameter base.fc.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
And my command is `python demo.py ctdet --demo ../images/16004479832_a748d55f21_k.jpg --load_model ../models/ctdet_coco_dla_2x.pth`

**Comment by xingyizhou** [comment]
The command looks good to me, can you make sure you haven't changed any code?

**Comment by forevergogi** [comment]
No, I only replace the DCNv2 code from the original repo since I failed to compile the code with torch 0.4.1.

**Comment by xingyizhou** [comment]
Can you show the full output log?

**Comment by forevergogi** [comment]
And I compared the pretrained model and the model defined in the code. I found that two parameters in the pretrained model are not defined in the code. They are fc.weight and fc.bias.

**Comment by forevergogi** [comment]
> Can you show the full output log?

`ssh://qqiao@10.82.0.153:32876/home/qqiao/anaconda3/envs/CenterNet/bin/python3.6 -u /home/qqiao/codes/CenterNet-master/src/demo.py ctdet --demo ../images/16004479832_a748d55f21_k.jpg --load_model ../models/ctdet_coco_dla_2x.pth
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/qqiao/codes/CenterNet-master/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
Drop parameter base.fc.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Drop parameter base.fc.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
`

**Comment by xingyizhou** [comment]
`base.fc.*` should be there, but they are never used. One possible reason is pytorch 1.2 automatically trims the un-used layers. You should still be able to run the demo anyway.

**Comment by forevergogi** [comment]
Yes, it can run with no error. Previously, I thought the output log is error info.
