### ISSUE TITLE
Does object detection benefit from pose estimation?

### ISSUE THREAD

**Issue by WangChen100** [xingyizhou/CenterNet#487]
Hi, Zhou. In the pose estimation task, CenterNet detects objects and joints in the meantime.
Do you think object detection benefits from pose estimation?

**Comment by xingyizhou** [comment]
I have tried setting `wh_weight` to 0 in `multi_pose`, the results are similar or worse.

**Comment by zyc4me** [comment]
hi,zhou, will the key point result be worse if i do not use the hm_hp predict and just pred a offset of key point？

**Comment by WangChen100** [comment]
Thank you for your reply. I agree with you. 

In my opinion, if we set `wh_weight=0` in multi_pose, it means that NN doesn't have to learn the size of those bounding boxes. 

In the worst case, there are no bounding boxes so that all joints are predicted by `kps`, as shown in the following codes. Unfortunately, `kps` seems not as accurate as `hm_hps` so that the results become worse.

```
mask = (hm_kps[..., 0:1] < l) + (hm_kps[..., 0:1] > r) + \
             (hm_kps[..., 1:2] < t) + (hm_kps[..., 1:2] > b) + \
             (hm_score < thresh) + (min_dist > (torch.max(b - t, r - l) * 0.3))
mask = (mask > 0).float().expand(batch, num_joints, K, 2)
kps = (1 - mask) * hm_kps + mask * kps 
```

**Comment by xingyizhou** [comment]
Thank you for the discussion.
