### ISSUE TITLE
ctdet: How can i change the number of max detected object, i only find it's default 100 

### ISSUE THREAD

**Issue by sailyung** [xingyizhou/CenterNet#492]

**Comment by sailyung** [comment]
I do face detaction, but i find the max result detected face in a image is 100. I want change it

**Comment by zry12321** [comment]
you can just change "default=100" to "default=the number you want". or you can add "opt.K=the number you want" in demo.py

**Comment by sailyung** [comment]
> you can just change "default=100" to "default=the number you want". or you can add "opt.K=the number you want" in demo.py

oh, i tried it. but the K value only wored in test debug, dont infect the result image of tiltle ctdet

**Comment by zry12321** [comment]
in fact, i don't really understand what you mean. maybe you can debug the code and make sure the “K“ has really been changed.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sailyung"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 下午4:23
收件人:&nbsp;"xingyizhou/CenterNet"<CenterNet@noreply.github.com&gt;;
抄送:&nbsp;"周如月"<1270646439@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xingyizhou/CenterNet] ctdet: How can i change the number of max detected object, i only find it's default 100  (#492)



 
you can just change "default=100" to "default=the number you want". or you can add "opt.K=the number you want" in demo.py
  
oh, i tried it. but the K value only wored in test debug, dont infect the result image of tiltle ctdet

**Comment by sailyung** [comment]
I find it in base_detector.py
self.max_per_image = 100

**Comment by Man-go008** [comment]
> I find it in base_detector.py
> self.max_per_image = 100
do you solve it? I meet the same question.
