### ISSUE TITLE
help: the nano system cannot be accessed.

### ISSUE THREAD

**Issue by kiwifruit-guo** [xingyizhou/CenterNet#497]
The nano board says that the power is on, the light is on, but the display is not responding, and the nano system cannot be accessed. The wireless network card can be connected to wifi. Whether it is a circular hole or a usb power supply, the nano system cannot be accessed. thanks so much.

**Comment by xingyizhou** [comment]
I think you have pasted the question to a wrong repo. The only suggestion I have is to reboot.
