### ISSUE TITLE
Error when convert pytorch to onnx. "RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict."

### ISSUE THREAD

**Issue by zhangxilun** [xingyizhou/CenterNet#502]
I trained CenterNet on my own dataset, and finally I got the model called "model_best.pth". I would like to convert the pytorch model to onnx model.  However, I met a problem called "RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict."

 Here is my pytorch2onnx.py code:
`from models.model import create_model, load_model, save_model
import torch.onnx
from torch.autograd import Variable
from opts import opts
import torch
import os
from datasets.dataset_factory import get_dataset

def pytorch2onnx(opt):
    Dataset = get_dataset(opt.dataset, opt.task)
    opt = opts().update_dataset_info_and_set_heads(opt, Dataset)
    print(opt)

    os.environ['CUDA_VISIBLE_DEVICES'] = opt.gpus_str
    opt.device = torch.device('cuda' if opt.gpus[0] >= 0 else 'cpu')

    print('Creating model...')
    model = create_model(opt.arch, opt.heads, opt.head_conv)
    
    print("Loading model...")
    model = load_model(model, opt.load_model).cuda()

    print("convert pytorch to onnx...")
    image_input = Variable(torch.randn(1, 3, opt.input_h, opt.input_w)).cuda()
    print(image_input.size())
    torch.onnx.export(model, image_input, "model_onnx_best.proto", verbose = True)

if __name__ == '__main__':
  opt = opts().parse()
  pytorch2onnx(opt)`

And the arch of model is dlav0_34, and my task is ctdet. 
pytorch = 0.4.1

How can I solve this problem?

**Comment by xingyizhou** [comment]
You can refer to (this)[https://github.com/xingyizhou/CenterNet/issues/77#issuecomment-503443329].

**Comment by zhangxilun** [comment]
Thank you! The problem has been solved!

**Comment by xiaoheizi123** [comment]
I meet the same problem, and change the msra_resnet.py with the ret to list like  this,
`ret = []
for head in self.heads:
  ret.append(self.__getattr__(head)(x))
return [ret]`
It doesnot work, and could you tell how to solve this?
