### ISSUE TITLE
Error when video detect finished

### ISSUE THREAD

**Issue by lsccccc** [xingyizhou/CenterNet#503]
Hi,
Thanks a lot of your open source code. 
When I run the demo of video detect, it seems run OK with good performence. But when the video is finished, an error arises like this.
`Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 30, in demo
    ret = detector.run(img)
  File "/home/lsc/CenterNet/CenterNet/src/lib/detectors/base_detector.py", line 95, in run
    image = image_or_path_or_tensor['image'][0].numpy()
TypeError: 'NoneType' object is not subscriptable
`
So how to exit without this error when the video is finished?
Thanks.

**Comment by xingyizhou** [comment]
Thank you for raising this issue. A naive fix will be adding a shape check when reading the frame from the video [here](https://github.com/xingyizhou/CenterNet/blob/master/src/demo.py#L28).

**Comment by lsccccc** [comment]
> Thank you for raising this issue. A naive fix will be adding a shape check when reading the frame from the video [here](https://github.com/xingyizhou/CenterNet/blob/master/src/demo.py#L28).

Thank you for your reply. I works when I add a shape check before `ret = detector.run(img)`.
Thanks again.

**Comment by almpantoja** [comment]
How do you write the shape check?
