### ISSUE TITLE
about result.json

### ISSUE THREAD

**Issue by DangerousY** [xingyizhou/CenterNet#506]
I use VOC format to train this network, and I don't know why I don't have the seperate result.json about my 6 classes.

**Comment by xingyizhou** [comment]
I didn't understand the question. You will need to manually convert the prediction to the required evaluation format like [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/dataset/pascal.py#L57).

**Comment by DangerousY** [comment]
I have solved it . Thanks!
