### ISSUE TITLE
Error while visualizing the bounding box detected by CenterNet

### ISSUE THREAD

**Issue by ljjyxz123** [xingyizhou/CenterNet#508]
@xingyizhou 
Hello, XingYi Zhou, 
I am running CenterNet, and wanted to draw bounding box on the image, and save it as a jpg picture.
But when I save the picture, I got this result:

![image](https://user-images.githubusercontent.com/2631417/70222424-05959600-1785-11ea-951c-f07c7a6b1372.png)

The white parts are the bounding boxes.

I will post my code below.
Do you know what I did wrong? Thank you very much!

**Comment by ljjyxz123** [comment]
In the base_trainer.py file:

      output, loss, loss_stats = model_with_loss(batch)

      dets = ctdet_decode(output['hm'], output['wh'])
      dets_bbox  = []
      for nIdx in range(len(dets)):
        dets_bbox.append(dets[nIdx][:, 0:4].double())

      save_im_b = np.float32(batch['input'][0][0].cpu())

      tmp_mean = 0.40789655 # [0.40789655, 0.44719303, 0.47026116]
      tmp_std = 0.2886383 # [0.2886383, 0.27408165, 0.27809834]
      #for idx in range(3):
      #  save_im_b[idx] = (save_im_b[idx] * tmp_std[idx] + tmp_mean[idx]) * 255.0
      save_im_b = (save_im_b * tmp_std + tmp_mean) * 255.0

      for bbox_idx in range(dets_bbox[0].size()[0]):
        tmp_x1 = dets_bbox[0][bbox_idx][0]
        tmp_y1 = dets_bbox[0][bbox_idx][1]
        tmp_x2 = dets_bbox[0][bbox_idx][2]
        tmp_y2 = dets_bbox[0][bbox_idx][3]
        print('x1, y1, x2, y2: ', tmp_x1, tmp_y1, tmp_x2, tmp_y2)

        cv2.imwrite('./centernet_orig_' + str(1) + '_' + str(0) + '.jpg', save_im_b)
        cv2.rectangle(save_im_b, (tmp_x1, tmp_y1), (tmp_x2, tmp_y2), (255), 2)
        cv2.imwrite('./centernet_' + str(1) + '_' + str(0) + '.jpg', save_im_b)

**Comment by ljjyxz123** [comment]
This is the bounding box detected and decoded by CenterNet:

![image](https://user-images.githubusercontent.com/2631417/70223106-185c9a80-1786-11ea-9723-5d6069a81536.png)

I found the bounding boxes are not normal.

**Comment by xingyizhou** [comment]
The bbox after decode is in the output heatmap coordinate, which is in a 4x stride. You will need to call `*_post_process` to convert it back to the image coordinate. You use our visualization code by calling `--debug 2` or refer to our code.

**Comment by ljjyxz123** [comment]
> The bbox after decode is in the output heatmap coordinate, which is in a 4x stride. You will need to call `*_post_process` to convert it back to the image coordinate. You use our visualization code by calling `--debug 2` or refer to our code.

@xingyizhou 
Thank you very much!
I will take a look at your code, and apply it to my purpose.

**Comment by pipi2020** [comment]
@ljjyxz123 Hi，my friends ，could you tell me how to solve this problem?
I also meet this problem,Thank U @xingyizhou

**Comment by vivcheng01** [comment]
Hi, I have the same problem; please advise.
Should we be multiplying the bounding box by 4, or some other value?
I see that the values of `wh` are very small (e.g. 0.22), so when generating predicted bounding box even after multiplying by four it is very small.
