### ISSUE TITLE
issue about fps

### ISSUE THREAD

**Issue by DangerousY** [xingyizhou/CenterNet#509]
I want to know how to get my fps when I train my data using dla network. Thanks! There are sevral detecting time, and I don't know use which one.

**Comment by xingyizhou** [comment]
We report network time + decode time.

**Comment by Edwardmark** [comment]
@xingyizhou not including nms?

**Comment by xingyizhou** [comment]
The multi-scale setting includes NMS time. We don't have nms in other settings.
