### ISSUE TITLE
Not use Corner Pooling

### ISSUE THREAD

**Issue by autocyz** [xingyizhou/CenterNet#51]
In the paper, center pooling module and cascade corner pooling module consist of corner pooling layers. But in the code, I don't find a corner pooling layer.

**Comment by liquor233** [comment]
Hi, I just have the same puzzle as you, could you please tell me why this lib do not use corner pooling?

**Comment by autocyz** [comment]
This repo is implement of "Objects as Points"
https://github.com/Duankaiwen/CenterNet is repo for “CenterNet: Keypoint Triplets for Object Detection”
