### ISSUE TITLE
No module named 'external.nms'

### ISSUE THREAD

**Issue by Man-go008** [xingyizhou/CenterNet#513]
I have trained my own dataset, but when i run test.py , it has an error. can you give me some tips?
I run 
cd src/lib/external
make
but no work.

**Comment by xingyizhou** [comment]
You can just comment out the import nms line. It is not used.

**Comment by howdidthatwork** [comment]
Hi, I commented out the import nms line but got an error saying there was no module named pycocotools. 

I'm quite perplexed because of this. Can you please help me?

**Comment by BJLZ123** [comment]
> Hi, I commented out the import nms line but got an error saying there was no module named pycocotools.
> 
> I'm quite perplexed because of this. Can you please help me?

pip is a 好东西
