### ISSUE TITLE
Arguments of L1Loss?

### ISSUE THREAD

**Issue by askarbozcan** [xingyizhou/CenterNet#514]
Hello,
I'd like to understand the way regression loss works in the code however I'm somewhat struggling to connect it to the way it's presented in paper.

These are the arguments: output, mask, ind, target

OK, output is the regression predictions of network. Target is the regression ground truth with regression values at center points and 0 everywhere else. ind I assume is the 1d indices of predicted keypoints. What about mask though?

Thanks.

**Comment by xingyizhou** [comment]
See [here](https://github.com/xingyizhou/CenterNet/issues/511#issuecomment-562763210).

**Comment by askarbozcan** [comment]
Thanks a lot! The encoding of regressions makes a lot more sense now.
