### ISSUE TITLE
 No module named 'external.nms'

### ISSUE THREAD

**Issue by haoopan** [xingyizhou/CenterNet#52]
When run demo.py, it got the above error, from "from external.nms import soft_nms". So ,how to use nms.pyx in external folder.Thx!

**Comment by wangyihuan123** [comment]
Changing "from external.nms import soft_nms" to "**lib.**from external.nms import soft_nms" works for me.

**Comment by wilxy** [comment]
> Changing "from external.nms import soft_nms" to "lib.from external.nms import soft_nms" works for me.

Hi, is there any error in "lib.from external.nms import soft_nms"?

**Comment by lhyfst** [comment]
> Changing "from external.nms import soft_nms" to "lib.from external.nms import soft_nms" works for me.

I encounter 'SyntaxError: invalid syntax'
