### ISSUE TITLE
when test,i can not understand your pro_precess methord? I need your help.

### ISSUE THREAD

**Issue by tieguanyin803** [xingyizhou/CenterNet#521]
when test,if opt.keep_res==true,i see you use the next two lines
inp_height = (new_height | self.opt.pad) + 1
inp_width = (new_width | self.opt.pad) + 1
to change the input width and height,self.opt.pad=127,but i can not understand why you do it.
can you explain it for me?thank you for your help

**Comment by ljjyxz123** [comment]
I have the same question here. :)

**Comment by xingyizhou** [comment]
This follows the CornerNet code. I didn't understand the intuition behind this but basically it makes sure the new height/ with are divisible by 128.

**Comment by ljjyxz123** [comment]
> This follows the CornerNet code. I didn't understand the intuition behind this but basically it makes sure the new height/ with are divisible by 128.

Making sure the new height and width are divisible by 32 or 128 sounds making sense.

**Comment by sisrfeng** [comment]
> This follows the CornerNet code. I didn't understand the intuition behind this but basically it makes sure the new height/ with are divisible by 128.
Why should them be divisible by 128? 
Any similar usage of the "|" ?


![image](https://user-images.githubusercontent.com/53520949/88059265-33eea700-cb97-11ea-890b-b81d0bb9e077.png)
