### ISSUE TITLE
typo(?) on arXiv paper

### ISSUE THREAD

**Issue by YusukeSuzuki** [xingyizhou/CenterNet#523]
I read arXiv paper of CenterNet ( https://arxiv.org/abs/1904.07850 ).
In Table 2, AP_M of YoLo v3 is 25.4.

![Screenshot from 2019-12-12 12-36-50](https://user-images.githubusercontent.com/657060/70680863-d038fd00-1cdc-11ea-80ce-65f56c04d49d.png)

In YoLo v3 arXiv paper ( https://arxiv.org/abs/1804.02767 ) Table 3, AP_M of YoLo v3 is 35.4.

![Screenshot from 2019-12-12 12-32-25](https://user-images.githubusercontent.com/657060/70680553-0033d080-1cdc-11ea-8534-aa49271d32ab.png)

Is it typo?

**Comment by ljjyxz123** [comment]
@YusukeSuzuki

You are so careful.

**Comment by xingyizhou** [comment]
Thanks for pointing this out! We will fix.
