### ISSUE TITLE
Question about function get_affine_transform()

### ISSUE THREAD

**Issue by ljjyxz123** [xingyizhou/CenterNet#524]
@xingyizhou 
Hello Xingyi,

In this file, https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/image.py
For the function def get_affine_transform():

I have three questions,
1. Are you calculating the Affine matrix between src and dst?

2. How are the three points in src corresponding to the three points in dst? 

3. In the function,

`
scale_tmp = scale

    src_w = scale_tmp[0]

    dst_w = output_size[0]

    dst_h = output_size[1]

`
I can understand dst_w and dst_h are the output_size of dst,
but why src_w is assigned with scale? I thought src_w should be the original width of src.

Thank you very much!

**Comment by xingyizhou** [comment]
I haven't carefully looked into this file. It is from the [MSRA human pose repo](https://github.com/Microsoft/human-pose-estimation.pytorch). You can ask this in their repo.

**Comment by ljjyxz123** [comment]
> I haven't carefully looked into this file. It is from the [MSRA human pose repo](https://github.com/Microsoft/human-pose-estimation.pytorch). You can ask this in their repo.

@xingyizhou 
Got it, thank you very much!
