### ISSUE TITLE
How can I run test on testing set without annotations?

### ISSUE THREAD

**Issue by Alien1007** [xingyizhou/CenterNet#525]
I want to run test.py to get results.json for submission. But I don't have annotations now. Is it possible to reuse your code in an efficient way? Or it is supposed to re-implement test method for this case?

**Comment by xingyizhou** [comment]
I didn't understand the question. If you mean testing in COCO-style format, you will need to provide an `image_info_xxx.json`, which contains the images and their paths. Our code will generate a result json file in the experiment folder.

**Comment by Alien1007** [comment]
I have solved it by generate an annotation file without bbox information. Now I can run test.py as usual. Thanks for your reply.

**Comment by wwq98** [comment]
@Alien1007 i have the same problem. Could you share your code with me? Thanks!

**Comment by Alien1007** [comment]
Sry, it is not available for me now. You can just generate an COCO-format annotation JSON file with empty 'annotations' item. Then it can be loaded by cocotools in CenterNet. Finally, skip local evaluation method in your_dataset.py.
