### ISSUE TITLE
model DLA-34 run very slow on tesla T4 

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [xingyizhou/CenterNet#526]
![Screenshot from 2019-12-12 22-38-22](https://user-images.githubusercontent.com/35255081/70726122-28e5b580-1d30-11ea-9bbf-7885fdda872e.png)

I followed the install instruction and successfully run model in my PC with GTX 950m(~6 FPS) but when I test on Tesla T4 the speed is very bad. 
The logs showed st like this : "THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument" 
![Screenshot from 2019-12-12 22-45-26](https://user-images.githubusercontent.com/35255081/70726707-1a4bce00-1d31-11ea-90d9-f001810cc50c.png)

the Tesla T4 run with 100% and cpu was not runing model.
I've spend my whole day to to fix this but I failed. I hope that someones have solved this and give me some instruction!
Many thanks! 

P/S: Tesla T4 run on Ubuntu 18.04 cuda 10 cudnn 7.6.4 I tried use another version of CUDA like 9.0, 9.2 but it's still not work.

**Comment by nguyenhoangthuan99** [comment]
I've figure out my fault. The error is my tesla T4 system is incompatitive with pytorch 0.4.1, when I convert code to pytorch 1.2 and cuda 10.0 my model works perfectly and achive 25 FPS!

**Comment by funkyyyyyy** [comment]
> I've figure out my fault. The error is my tesla T4 system is incompatitive with pytorch 0.4.1, when I convert code to pytorch 1.2 and cuda 10.0 my model works perfectly and achive 25 FPS!

Hi @nguyenhoangthuan99,

Would you mind sharing your converted code?

**Comment by nguyenhoangthuan99** [comment]
@funkyyyyyy it's very simple. You just remove DCNv2 in src/lib/models/network/ and then clone the DCNv2 repo with compatitive with torch 1.0 and rebuild. The left works well.

**Comment by funkyyyyyy** [comment]
Thank you! @nguyenhoangthuan99
