### ISSUE TITLE
Is there a pretrained model for dlav0?

### ISSUE THREAD

**Issue by lsccccc** [xingyizhou/CenterNet#527]
Hi xingyi, 
I've tried to transform the dla34 based model to ONNX, however the DCNv2 function is [not supported](https://pytorch.org/docs/stable/onnx.html#supported-operators) in the current ONNX version. I got that the dlav0 based model doesn't contain DCNv2 function, so is there a pretrained model for dlav0? 
Thanks.

**Comment by nguyenhoangthuan99** [comment]
you can check this gg drive: https://drive.google.com/drive/folders/1px-Xg7jXSC79QqgsD1AAGJQkuf5m0zh_

**Comment by lsccccc** [comment]
> https://drive.google.com

Thanks a lot but I got a 404, could you please check if this address is correct?

> you can check this gg drive: "https://drive.google.com/open?id=1px-Xg7jXSC79QqgsD1AAGJQkuf5m0zh_"

Thanks a lot but I got a 404 error, could you please check if this address is correct?

**Comment by nguyenhoangthuan99** [comment]
you should copy all link include the last character of the link "_"

**Comment by lsccccc** [comment]
> you should copy all link include the last character of the link "_"

I successfully entered this model zoo, and found the model I wanted. Thanks again.
