### ISSUE TITLE
self.max_objs =128

### ISSUE THREAD

**Issue by zgsxwsdxg** [xingyizhou/CenterNet#529]
for file 'src/lib/datasets/dataset/coco.py', 
self.max_objs =128,what does it mean?

**Comment by xingyizhou** [comment]
It is the maximum number of objects in an image. We need this because we need a constant shape to form a batch. See a similar issue [here](https://github.com/xingyizhou/CenterNet/issues/511).

**Comment by zgsxwsdxg** [comment]
> It is the maximum number of objects in an image. We need this because we need a constant shape to form a batch. See a similar issue here.

您好！谢谢您回复！我还想请教您，比如我的训练任务中，每张图像中的目标数可能大于128，我需要修改那些地方才能训练？

**Comment by xingyizhou** [comment]
Answered in the other issue.
