### ISSUE TITLE
down ratio

### ISSUE THREAD

**Issue by bruceyang2012** [xingyizhou/CenterNet#53]
If I want to change the down ratio from 4 to 1, where should I change the code?

**Comment by xingyizhou** [comment]
You will need to modify the [network](https://github.com/xingyizhou/CenterNet/tree/master/src/lib/models/networks) files. Currently, DLA supports down ratio [2, 4, 8, 16] and other networks only support 4. You will need to design how to do upsample yourself. I haven't tried down ratio 1 for any networks, but have tried down ratio 2 for dla on pascal once. The result becomes worse (-2 mAP) than downsample 4, if not changing any other hyper-parameters. You are welcomed to share/ discuss your results for changing down ratio.

**Comment by bruceyang2012** [comment]
@xingyizhou Thanks for your help, i'll try it later.

**Comment by azhao25** [comment]
Is there any update on this thread for trying down ratio of 1?
