### ISSUE TITLE
Convert dlav0_34 based model to caffe model

### ISSUE THREAD

**Issue by lsccccc** [xingyizhou/CenterNet#530]
hi, I convert dlav0_34 based model to caffe model by [PytorchToCaffe](https://github.com/xxradon/PytorchToCaffe), then visualize the network structure by [netscope](http://ethereon.github.io/netscope/#/editor).
So why these two BN layers doesn't connect with anywhere?
![image](https://user-images.githubusercontent.com/43127532/71050985-b63a6700-2181-11ea-9fab-999ed4997256.png)
![image](https://user-images.githubusercontent.com/43127532/71051002-c3efec80-2181-11ea-8dd5-dd69ea775138.png)

Also mentioned in https://github.com/xingyizhou/CenterNet/issues/43#issuecomment-566839558_

**Comment by lsccccc** [comment]
Here is the script I used to transform pytorch to caffe model.
```
import sys
sys.path.append("/home/lsc/PytorchToCaffe/")
import pytorch_to_caffe

from lib.models.networks.dlav0 import get_pose_net
from lib.models.model import load_model
import torch
from types import MethodType

def forward(self, x):
    x = self.base(x)
    x = self.dla_up(x[self.first_level:])
    ret = []
    for head in self.heads:
        ret.append(self.__getattr__(head)(x))
    return ret

net = get_pose_net(34, {'hm':80, 'reg':2, 'wh':2})
net.forward = MethodType(forward, net)
load_model(net, '../models/ctdet_coco_dlav0_1x.pth')
net.eval()

name = 'ctdet_coco_dlav0_1x'
input = torch.zeros([1, 3, 512, 512])
pytorch_to_caffe.trans_net(net, input, name)
pytorch_to_caffe.save_prototxt('../models/{}.prototxt'.format(name))
pytorch_to_caffe.save_caffemodel('../models/{}.caffemodel'.format(name))
```
Any wrong?

**Comment by xingyizhou** [comment]
It is unintended. However since it does not course any issues we don't have a plan to fix it.

**Comment by Dantju** [comment]
i met the same problem,have u solver it?

**Comment by lsccccc** [comment]
@xingyizhou thank you

**Comment by lsccccc** [comment]
@Dantju This issue might arise during transformation. Although I don't know the specific reason, but you can fix it by removing these layers. BTW, I have visualize the dlav0 based ONNX model with [netron](https://github.com/lutzroeder/netron), and you can modify the caffe model by referring to this.
![ctdet_coco_dlav0_1x onnx](https://user-images.githubusercontent.com/43127532/71396022-72e56a00-2653-11ea-849f-e859ef637d9e.png)

**Comment by Qingfeng0623** [comment]
> @Dantju This issue might arise during transformation. Although I don't know the specific reason, but you can fix it by removing these layers. BTW, I have visualize the dlav0 based ONNX model with [netron](https://github.com/lutzroeder/netron), and you can modify the caffe model by referring to this.
> ![ctdet_coco_dlav0_1x onnx](https://user-images.githubusercontent.com/43127532/71396022-72e56a00-2653-11ea-849f-e859ef637d9e.png)

This is the network struction of dlav0_34?

**Comment by lsccccc** [comment]
@Qingfeng0623 yes

**Comment by Qingfeng0623** [comment]
@lsccccc Do you have the network struction of dla_34?

**Comment by lsccccc** [comment]
@Qingfeng0623 Sorry, I don't have, but you can refer to [this](https://github.com/xingyizhou/CenterNet/issues/43#issuecomment-505363493)

**Comment by Qingfeng0623** [comment]
@lsccccc What's the mean of node named P_weight*?

**Comment by lsccccc** [comment]
@Qingfeng0623 Not sure, maybe parameter of DCNv2

**Comment by Qingfeng0623** [comment]
@lsccccc Thank you!
