### ISSUE TITLE
Why python demo.py need download pretrain weights?

### ISSUE THREAD

**Issue by ujsyehao** [xingyizhou/CenterNet#532]
Hi, When I use you provided model to test, I type 
`python3 demo.py  cadet --arch resdcn_18 --demo 1.jpg --load_model *.model`
It starts to download resnet18-5c106cde.pth.

**It is necessary?**
-----------------------------
I modify models/networks/resnet_dcn.py line266, 
`if 1: ` -> `if 0:`

**Comment by xingyizhou** [comment]
It is not necessary in testing/ demo, but required for training.
