### ISSUE TITLE
为什么检测出的目标只有一百个？？？

### ISSUE THREAD

**Issue by zgsxwsdxg** [xingyizhou/CenterNet#534]
您好！ 首先谢谢您的工作！我基于您的代码训练了检测模型，每次输出只有100个框，哪里可以修改这个参数？为什么要设置这个参数为100？谢谢！

**Comment by xingyizhou** [comment]
You can change it by `--K xxx` (see [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/opts.py#L108)). We need this because we used `torch.topK()` to find the peaks.

**Comment by zgsxwsdxg** [comment]
> You can change it by --K xxx (see here). We need this because we used torch.topK() to find the peaks.

您好！我还想问下您，这个K值，训练的时候就必须设置，还是在推理时修改为自己的值就可以了？

**Comment by xingyizhou** [comment]
That's correct.
