### ISSUE TITLE
Issues about the not implemented functions

### ISSUE THREAD

**Issue by DemonsRhythm** [xingyizhou/CenterNet#536]
I have found that in large_hourglass.py, the function `make_pool_layer` return an empty sequence of layers, while the correct implementation was commented.
![image](https://user-images.githubusercontent.com/18750094/71305494-2a8a3a00-2410-11ea-8f59-f0c72e3fcdd7.png)

Another issue is that some functions in base_trainer.py still return Exception of NotImplementedError.
![image](https://user-images.githubusercontent.com/18750094/71305524-91a7ee80-2410-11ea-9f51-565b9b3dd9b0.png)

Could you please explain this?

**Comment by xingyizhou** [comment]
Thanks for reading the code. 
  1. it follows the original CornerNet code. 
  2. BaseTrainter is a base class. It is always inherited by a specific trainer with the corresponding implementation.

**Comment by DemonsRhythm** [comment]
> Thanks for reading the code.
> 
> 1. it follows the original CornerNet code.
> 2. BaseTrainter is a base class. It is always inherited by a specific trainer with the corresponding implementation.

Thanks for your reply.
For the 2nd issue, I understand. But for the 1st, I find that the `make_pool_layer` function of CornerNet and Hourglass both use nn.MaxPool2d. When I use nn.MaxPool2d in CenterNet, it will show a RuntimeError:  Given input size: (384x1x1). Calculated output size: (384x0x0). Output size is too small. (Input size is 3x800x800). When I use `nn.Sequential()` it will work. I can't understand as `nn.Sequential()` should mean the `make_pool_layer` function will not be effectual. It will be very helpful to explain this. Thank you.

**Comment by xingyizhou** [comment]
There are some unused confusing functions in the CornerNet code. The code in this repo should reflect the actual running version of CornerNet hourglass.
