### ISSUE TITLE
> It is the maximum number of objects in an image. We need this because we need a constant shape to form a batch. See a similar issue here.

### ISSUE THREAD

**Issue by zgsxwsdxg** [xingyizhou/CenterNet#537]
> It is the maximum number of objects in an image. We need this because we need a constant shape to form a batch. See a similar issue here.

您好！谢谢您回复！我还想请教您，比如我的训练任务中，每张图像中的目标数可能大于128，我需要修改那些地方才能训练？

_Originally posted by @zgsxwsdxg in https://github.com/xingyizhou/CenterNet/issues/529#issuecomment-568325042_

**Comment by xingyizhou** [comment]
Simply change this to a larger number would work.

**Comment by zgsxwsdxg** [comment]
> Simply change this to a larger number would work.

谢谢
