### ISSUE TITLE
> You can change it by --K xxx (see here). We need this because we used torch.topK() to find the peaks.

### ISSUE THREAD

**Issue by zgsxwsdxg** [xingyizhou/CenterNet#538]
> You can change it by --K xxx (see here). We need this because we used torch.topK() to find the peaks.

您好！我还想问下您，这个K值，训练的时候就必须设置，还是在推理时修改为自己的值就可以了？

_Originally posted by @zgsxwsdxg in https://github.com/xingyizhou/CenterNet/issues/534#issuecomment-568322892_

**Comment by xingyizhou** [comment]
`K` is only used in testing.

**Comment by zgsxwsdxg** [comment]
> `K` is only used in testing.

谢谢
