### ISSUE TITLE
train main.py

### ISSUE THREAD

**Issue by lihua-hua** [xingyizhou/CenterNet#539]
Change the Deform layer in the dla34 network to ordinary Conv, train the coco dataset, and the task is human pose estimation. Trained 30 epochs in five days. Is this speed normal? Can it be faster?

**Comment by xingyizhou** [comment]
How many GPUs are you using? It is definitely abnormal for 8 GPUs, but possible for one.

**Comment by lihua-hua** [comment]
Thank you for your reply. I did use 1 gpu. I haven't found a way to make it train faster. Do you have any suggestions

**Comment by xingyizhou** [comment]
I would suggest working on Pascal VOC for 1 gpu users.

**Comment by lihua-hua** [comment]
Thanks  I will try
