### ISSUE TITLE
How to generate the image dir in kitti?

### ISSUE THREAD

**Issue by lhyfst** [xingyizhou/CenterNet#54]
Thanks for your work! I am a bit confused that how to use `convert_kitti_to_coco.py` to generate the `images` dir in kitti?

Here are my dirs in kitti.
```
heyuan@lambda-quad:~/Research/CenterNet/data/kitti$ tree -L 2
.
├── ImageSets_3dop
│   ├── test.txt
│   ├── train.txt
│   ├── trainval.txt
│   └── val.txt
├── ImageSets_subcnn
│   ├── test.txt
│   ├── train.txt
│   ├── trainval.txt
│   └── val.txt
└── training
    ├── calib
    ├── image_2
    └── label_2
```

When I tried to run `python convert_kitti_to_coco.py`. It returned an error.
```
(CenterNet) heyuan@lambda-quad:~/Research/CenterNet/src/tools$ python convert_kitti_to_coco.py 
# images:  3712
# annotations:  25099
Traceback (most recent call last):
  File "convert_kitti_to_coco.py", line 151, in <module>
    json.dump(ret, open(out_path, 'w'))
FileNotFoundError: [Errno 2] No such file or directory: '../../data/kitti//annotations/kitti_3dop_train.json'
```

Then, I created `annotations` manually, and run the command again.
```
heyuan@lambda-quad:~/Research/CenterNet/data/kitti$ tree -L 2
.
├── annotations
│   ├── kitti_3dop_train.json
│   ├── kitti_3dop_val.json
│   ├── kitti_subcnn_train.json
│   └── kitti_subcnn_val.json
├── ImageSets_3dop
│   ├── test.txt
│   ├── train.txt
│   ├── trainval.txt
│   └── val.txt
├── ImageSets_subcnn
│   ├── test.txt
│   ├── train.txt
│   ├── trainval.txt
│   └── val.txt
└── training
    ├── calib
    ├── image_2
    └── label_2

```

Now the files in `annotations` are generated, but I still cannot find `images` dir as your description in DATA.md

By the way, when I run the command with `DEBUG = True`, it returns an error because there is no image in the image path.
```
(CenterNet) heyuan@lambda-quad:~/Research/CenterNet/src/tools$ python convert_kitti_to_coco.py 
pt_3d [[1.8127272]
 [1.4814587]
 [8.405019 ]]
location [1.84, 1.47, 8.41]
Traceback (most recent call last):
  File "convert_kitti_to_coco.py", line 143, in <module>
    cv2.imshow('image', image)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
```

**Comment by xingyizhou** [comment]
Sorry, you will need to manually link the image folder
~~~
cd $CENTERNET_ROOT/data/kitti/
mkdir images
ln -s training/image_2 images/trainval
~~~
I will update DATA.md.

**Comment by lhyfst** [comment]
Thanks for your quick response! It works.

**Comment by qhykwsw** [comment]
> Thanks for your work! I am a bit confused that how to use `convert_kitti_to_coco.py` to generate the `images` dir in kitti?
> 
> Here are my dirs in kitti.
> 
> ```
> heyuan@lambda-quad:~/Research/CenterNet/data/kitti$ tree -L 2
> .
> ├── ImageSets_3dop
> │   ├── test.txt
> │   ├── train.txt
> │   ├── trainval.txt
> │   └── val.txt
> ├── ImageSets_subcnn
> │   ├── test.txt
> │   ├── train.txt
> │   ├── trainval.txt
> │   └── val.txt
> └── training
>     ├── calib
>     ├── image_2
>     └── label_2
> ```
> 
> When I tried to run `python convert_kitti_to_coco.py`. It returned an error.
> 
> ```
> (CenterNet) heyuan@lambda-quad:~/Research/CenterNet/src/tools$ python convert_kitti_to_coco.py 
> # images:  3712
> # annotations:  25099
> Traceback (most recent call last):
>   File "convert_kitti_to_coco.py", line 151, in <module>
>     json.dump(ret, open(out_path, 'w'))
> FileNotFoundError: [Errno 2] No such file or directory: '../../data/kitti//annotations/kitti_3dop_train.json'
> ```
> 
> Then, I created `annotations` manually, and run the command again.
> 
> ```
> heyuan@lambda-quad:~/Research/CenterNet/data/kitti$ tree -L 2
> .
> ├── annotations
> │   ├── kitti_3dop_train.json
> │   ├── kitti_3dop_val.json
> │   ├── kitti_subcnn_train.json
> │   └── kitti_subcnn_val.json
> ├── ImageSets_3dop
> │   ├── test.txt
> │   ├── train.txt
> │   ├── trainval.txt
> │   └── val.txt
> ├── ImageSets_subcnn
> │   ├── test.txt
> │   ├── train.txt
> │   ├── trainval.txt
> │   └── val.txt
> └── training
>     ├── calib
>     ├── image_2
>     └── label_2
> ```
> 
> Now the files in `annotations` are generated, but I still cannot find `images` dir as your description in DATA.md
> 
> By the way, when I run the command with `DEBUG = True`, it returns an error because there is no image in the image path.
> 
> ```
> (CenterNet) heyuan@lambda-quad:~/Research/CenterNet/src/tools$ python convert_kitti_to_coco.py 
> pt_3d [[1.8127272]
>  [1.4814587]
>  [8.405019 ]]
> location [1.84, 1.47, 8.41]
> Traceback (most recent call last):
>   File "convert_kitti_to_coco.py", line 143, in <module>
>     cv2.imshow('image', image)
> cv2.error: OpenCV(4.1.0) /io/opencv/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
> ```
Hi, I meet the problem same as you.
FileNotFoundError: [Errno 2] No such file or directory: '../../data/kitti//annotations/kitti_3dop_train.json'
Can you share your 4 json file to me? Thank you very much.

**Comment by ZiyuBao** [comment]
> Sorry, you will need to manually link the image folder
> 
> ```
> cd $CENTERNET_ROOT/data/kitti/
> mkdir images
> ln -s training/image_2 images/trainval
> ```
> 
> I will update DATA.md.

What is the test folder in [CenterNet Data](https://github.com/ZiyuBao/CenterNet/blob/5c941d455c88bbda8972bbe6cd615b58153accbf/readme/DATA.md)?
