### ISSUE TITLE
when test on COCO test-dev,the result is -1  

### ISSUE THREAD

**Issue by Dantju** [xingyizhou/CenterNet#541]
the default code is test on val ，when  i change to test on COCO test-dev，the result is -1，do u know how to fix it

**Comment by timelesszxl** [comment]
the same problem

**Comment by timelesszxl** [comment]
and the coco2017 val result is right.
the model ctdet_coco_dla_2x' result:
[IoU=0.50:0.95] = 0.374

**Comment by Dantju** [comment]
if u fix it，please tell me

**Comment by Dantju** [comment]
@xingyizhou Results on COCO test-dev can be found in the paper or add --trainval for test.py. i also try this but the result still is -1，

**Comment by Dantju** [comment]
@xingyizhou   i find there is not bbox in image_info_test-dev2017.json ,is this the reson？can u show me the way u test on test-dev

**Comment by xingyizhou** [comment]
You will need to submit the json file to COCO test server. Remark that it is strongly discouraged to submit other people's method to the test server. The test server is used for the final evaluation of your own method only. All other evaluations should be done in the validation set.
