### ISSUE TITLE
the detection box is always shift in the upper left corner

### ISSUE THREAD

**Issue by YuzaChongyi** [xingyizhou/CenterNet#543]
I have trained a one class detection model with EfficientNet+Deconv，but I find  the detection box is always shift in the upper left corner, what could be the reason？

**Comment by YuzaChongyi** [comment]
I think the reg is not accurate, can I increase the reg loss weight?

**Comment by xingyizhou** [comment]
That's interesting. Can you be more specific? Which code have you changed and what datasets are you using?

**Comment by YuzaChongyi** [comment]
> That's interesting. Can you be more specific? Which code have you changed and what datasets are you using?

I only replace Res18 with EfficientNet-b0, and the dataset is a synthesized QRcode detection dataset. The loss and weights as follows: 
- "hm" loss: FocalLoss, weights: 1
- "wh" loss: RegL1Loss, weights: 0.1
- "reg" loss: RegL1Loss, weights: 1

The reg loss can converge to about 0.5，so I think the inaccurate regression causes the box shift. Then I find if I change the function ctdet_decode() [https://github.com/xingyizhou/CenterNet/blob/master/src/lib/models/decode.py#L464](url) to
```
 if reg is not None:
      reg = _transpose_and_gather_feat(reg, inds)`
      reg = reg.view(batch, K, 2)
      xs = xs.view(batch, K, 1) + reg[:, :, 0:1] + 0.5
      ys = ys.view(batch, K, 1) + reg[:, :, 1:2] + 0.5
```
 the result would be better.

**Comment by xingyizhou** [comment]
In this case it might be possible that your annotation is shifted. You can visualize the annotation by `--debug 2` in training.
