### ISSUE TITLE
 the confidence is very low,why?

### ISSUE THREAD

**Issue by wang7393** [xingyizhou/CenterNet#544]
the object detection's confidence is very low(0.1,0.2)，why?

**Comment by xingyizhou** [comment]
It is not observed in my experiments. Can you be more specific? What dataset/ models are you using? Also make sure you haven't changed any code.

**Comment by tingnit** [comment]
I had the same problem, I trained centernet with Resnet backbone(18, 50, 101) on my own dataset, when finished training, I noticed that the results seem to be well, but confidence rarely greater than 0.3. When i analyze the results, also find that the FPR curve not smooth. Could you @xingyizhou please help me find where might cause this problem.

**Comment by wang7393** [comment]
@xingyizhou I experiment on my own dataset(one class, the background is simple and fixed) , and finetuned on the model of ctdet_pascal_dla_384 and ctdet_pascal_dla_512,both the results of the prediction confidence is very low. do you have any good ideas to solver the problem?

**Comment by xingyizhou** [comment]
I don't have good suggestions on custom datasets. Usually you can try a longer schedule or different input resolutions.

**Comment by wang7393** [comment]
Thanks.
