### ISSUE TITLE
 Where did you generate the taget label?

### ISSUE THREAD

**Issue by wen0618** [xingyizhou/CenterNet#548]
Hi,I want to try label smoothing method in CenterNet.But I can not find the code you set the target label.I want to try set target lael from q=[0,0,1,0,0] to q’=[0.02,0.02,0.92,0.02,0.02].I am a complete beginner to DL，wish your help.

**Comment by xingyizhou** [comment]
It is [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/sample/ctdet.py#L86). However directly changing the label will not work as you desired. Our loss is not standard cross-entropy but a complex focal loss. I will encourage you to fully understand the loss first before starting modification the target.

**Comment by wen0618** [comment]
> It is [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/sample/ctdet.py#L86). However directly changing the label will not work as you desired. Our loss is not standard cross-entropy but a complex focal loss. I will encourage you to fully understand the loss first before starting modification the target.

Thank you very much!I will try it.

**Comment by yueyueyaya** [comment]
> Hi,I want to try label smoothing method in CenterNet.But I can not find the code you set the target label.I want to try set target lael from q=[0,0,1,0,0] to q’=[0.02,0.02,0.92,0.02,0.02].I am a complete beginner to DL，wish your help.

Hi, I'd like to ask how the label smoothing is doing and how the final effect is. I'm looking forward to your reply

**Comment by soans1994** [comment]
@xingyizhou @wen0618 

Hello,
I am generating custom dataset. can you please help me understand how to create height width labels for multi class. I know how to create Gaussian heatmap. For example if I have 20 classes and if output size is 128x128, I will create empty numpy array of size 128x128x20 and append every class heatmap into 3rd channel.

but for height width according to your paper, it is 128,128,2. I know 2 channel for height and width. Does it mean maximum object limit is 128x128=16284. Can you please explain how to append the data and which axis. I am confused how it can work for multi classes.

Thank you
