### ISSUE TITLE
kitti test: Couldn't read: 006042.txt of ground truth.

### ISSUE THREAD

**Issue by lhyfst** [xingyizhou/CenterNet#55]
When I run test.py on kitti, I encountered this error.
```
d3dop |################################| [3768/3769]|Tot: 0:02:40 |ETA: 0:00:01 |tot 0.038s (0.042s) |load 0.000s (0.000s) |pre 0.001s (0.001s) |net 0.033s (0.033s) |dec 0.001s (0.002s) |post 0.004s (0.006s) |merge 0.000s (0.000s) 
Thank you for participating in our evaluation!
Loading detections...
number of files for evaluation: 3769
ERROR: Couldn't read: 006042.txt of ground truth. Please write me an email!
An error occured while processing your results.
```

I know in [prclibo's test code](https://github.com/prclibo/kitti_eval), I may encounter this error because the test file cannot access the original labels files always due to wrong label file path.
However, in this case, we use `convert_kitti_to_coco.py` to convert kitti form label files to coco form label files and do not need to access original kitti label files. So I don't know what went wrong.
Do you know the reason? Thanks!

**Comment by xingyizhou** [comment]
Hi, 
  We do access to the original kitti labels for testing (See [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/dataset/kitti.py#L86)). Can you provide your script? Also, make sure you are running `evaluate_object_3d_offline.cpp`, not `evaluate_object_3d.cpp`.

**Comment by lhyfst** [comment]
The solution is quite simple. 
`cd data/kitti`
`mv label_2 label_val` <br>
Or,
https://github.com/xingyizhou/CenterNet/blob/b328816ecf16c65ee43ba14c6edd2a6e8dcdacff/src/lib/datasets/dataset/kitti.py#L87
change `label_val` to `label_2`

**Comment by chensonglu** [comment]
@lhyfst it works, thanks
