### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by GuoChuan1314** [xingyizhou/CenterNet#550]
I want to train the data of voc2017.I try change the program,but I failed.I changed as below:
in main.py：
opt.task = 'ctdet'
opt.dataset = 'coco'
in coco.py give json file：
    self.annot_path='/media/lab/persondata/GuoChuan/Detection_Local/CenterNet_ROOT/src/lib/data/coco/annotations/instances_val2017.json'
in lib/datastes/sample/ctdet.py:
   img_id='/media/lab/persondata/GuoChuan/Detection_Local/data/data_object_image_2/training/image_2'
   file_name = self.coco.loadImgs(ids=[img_id])[0]['image_2']
    img_path='/media/lab/persondata/GuoChuan/Detection_Local/data/data_object_image_2/training/image_2/000310.png'

the error:
KeyError: 'Traceback (most recent call last):\n  File "/home/lab/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/lab/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/media/lab/persondata/GuoChuan/Detection_Local/CenterNet_ROOT/src/lib/datasets/sample/ctdet.py", line 34, in __getitem__\n    file_name = self.coco.loadImgs(ids=[img_id])[0][\'image_2\']\n  File "/home/lab/.local/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 229, in loadImgs\n    return [self.imgs[id] for id in ids]\n  File "/home/lab/.local/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 229, in <listcomp>\n    return [self.imgs[id] for id in ids]\nKeyError: \'/media/lab/persondata/GuoChuan/Detection_Local/data/data_object_image_2/training/image_2\'\n'

**Comment by xingyizhou** [comment]
Can you make sure you haven't modified any code and the dataset is processed successfully?

**Comment by xingyizhou** [comment]
Closing for now for no response. Feel free to reopen.
