### ISSUE TITLE
model does not fully load the pre-trained weight when I train the hgnet on coco

### ISSUE THREAD

**Issue by Outlande** [xingyizhou/CenterNet#551]
When I train the hgnet with  
"python main.py ctdet --exp_id coco_hg --arch hourglass --batch_size 24 --master_batch 4 --lr 2.5e-4 --load_model ../models/ExtremeNet_500000.pth --gpus 0,1,2,3,4
--num_epochs 50 --lr_step 40"

It print
"No param hm.0.0.conv.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
"
Is that normal?
![1481749097](https://user-images.githubusercontent.com/48147430/71556252-e979d180-2a70-11ea-8b26-2d2dced6247e.jpg)

**Comment by xingyizhou** [comment]
Thanks for pointing it out. Yes it is normal. It is dropping the layers in ExtremeNet, which are not used in CenterNet.

**Comment by Outlande** [comment]
> Thanks for pointing it out. Yes it is normal. It is dropping the layers in ExtremeNet, which are not used in CenterNet.
Ok, Thanks for you reply
