### ISSUE TITLE
Support for PyTorch 1.0+

### ISSUE THREAD

**Issue by MARMOTatZJU** [xingyizhou/CenterNet#553]
Is it possible to run CenterNet with PyTorch>=1.0.0? Has anyone tried this?

**Comment by xingyizhou** [comment]
Testing is completely possible. Just upgrade your pytorch and replace the DCNv2 repo. However I observed more randomness (~0.7AP jittering) in training and that's why I released it in 0.4.1.

**Comment by MARMOTatZJU** [comment]
Thanks for your reply. 
BTW, I've encountered a similar issue at my side with training (it was in Visual Tracking). Maybe check the parameter initialization part and fix it with hard-coded initializer (e.g. fixed std for gaussian_init_). This is what I did with my issue and this worked for me.

**Comment by xingyizhou** [comment]
Thanks for your suggestion!

**Comment by kHarshit** [comment]
> Testing is completely possible. Just upgrade your pytorch and replace the DCNv2 repo. However I observed more randomness (~0.7AP jittering) in training and that's why I released it in 0.4.1.

Replacing DCNv2 with what? Do you mean removing it completely? @xingyizhou

**Comment by vesor** [comment]
> Testing is completely possible. Just upgrade your pytorch and replace the DCNv2 repo. However I observed more randomness (~0.7AP jittering) in training and that's why I released it in 0.4.1.

@xingyizhou, Could you create a branch which use pytorch 1.0+? That would help a lot. Thanks!
