### ISSUE TITLE
 How to save the results (e.g. bbox, score, iou ...) ?

### ISSUE THREAD

**Issue by David-19940718** [xingyizhou/CenterNet#554]
Hello, I want to save the results like a bounding box, predict class with its score.
How can I get this info? When I run the demo.py, I just got the predicted picture.
I don't need to compute the AP, I just want to test my own picture and get the corresponding information. 
Who can tell me how to deal. Thank you very much.
@philkr @cclauss @Gcaya @DequanWang

**Comment by xingyizhou** [comment]
Please refer to the readme:

To use this CenterNet in your own project, you can 

~~~
import sys
CENTERNET_PATH = /path/to/CenterNet/src/lib/
sys.path.insert(0, CENTERNET_PATH)

from detectors.detector_factory import detector_factory
from opts import opts

MODEL_PATH = /path/to/model
TASK = 'ctdet' # or 'multi_pose' for human pose estimation
opt = opts().init('{} --load_model {}'.format(TASK, MODEL_PATH).split(' '))
detector = detector_factory[opt.task](opt)

img = image/or/path/to/your/image/
ret = detector.run(img)['results']
~~~
`ret` will be a python dict: `{category_id : [[x1, y1, x2, y2, score], ...], }`

**Comment by David-19940718** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xingyi Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月5日(星期天) 晚上8:37
收件人:&nbsp;"xingyizhou/CenterNet"<CenterNet@noreply.github.com&gt;;
抄送:&nbsp;"王伟"<940565369@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xingyizhou/CenterNet]  How to save the results (e.g. bbox, score, iou ...) ? (#554)




Please refer to the readme:
 
To use this CenterNet in your own project, you can
 import sys CENTERNET_PATH = /path/to/CenterNet/src/lib/ sys.path.insert(0, CENTERNET_PATH) from detectors.detector_factory import detector_factory from opts import opts MODEL_PATH = /path/to/model TASK = 'ctdet' # or 'multi_pose' for human pose estimation opt = opts().init('{} --load_model {}'.format(TASK, MODEL_PATH).split(' ')) detector = detector_factory[opt.task](opt) img = image/or/path/to/your/image/ ret = detector.run(img)['results']  
ret will be a python dict: {category_id : [[x1, y1, x2, y2, score], ...], }
