### ISSUE TITLE
Small objects

### ISSUE THREAD

**Issue by zieitokk** [xingyizhou/CenterNet#560]
Hi Xingyi, I have a question about small objects. Since the output size of centernet is 128x128 and for each entry in this 128x128 feature map may represent a center of an object, do this mean that all detected objects should be larger than `actual_width / 128, actual_height / 128` ?

**Comment by tingnit** [comment]
Input size / output size is 512 / 128 = 4, so just larger than (actual_width / 4, actual_height / 4)

**Comment by xingyizhou** [comment]
It is not required.

**Comment by zieitokk** [comment]
> It is not required.

Thank you for your reply!

**Comment by zieitokk** [comment]
> Input size / output size is 512 / 128 = 4, so just larger than (actual_width / 4, actual_height / 4)

Thank you!
