### ISSUE TITLE
Attribute error:"Debugger" object has no attribute 'names'

### ISSUE THREAD

**Issue by mrkind** [xingyizhou/CenterNet#561]
when running test.py I encountered the error shown in the title.The commands and other details are shown in the picture below.
![testerror](https://user-images.githubusercontent.com/14086114/71659057-1257da80-2d81-11ea-8cb7-00aac115bfa1.png)

The same model_best.pth(and the trained model_last.pth) also results in  error while running demo.py as shown in the following picture.

![demoerror](https://user-images.githubusercontent.com/14086114/71659089-387d7a80-2d81-11ea-85e1-622a9db4d5d7.png)

How could these errors occur.Previously I did not encounter these errors when following the steps in https://blog.csdn.net/weixin_41765699/article/details/100118353

**Comment by xingyizhou** [comment]
You will need to add the category names in debugger.py if you are using a custom dataset.

**Comment by mrkind** [comment]
strange enough! I have added the category names in line 461 of debugger.py
,namely  'huawei_class_name=["kd","sz","sj"]'

but error persists

**Comment by mrkind** [comment]
That is,errror persists when running demo.py(no images with bbox drawn are generated),but  when running test.py,the error is eliminated since I get the mAP result.
Why no error occurred when running test.py,and the same error as the second picture above occurred when running demo.py?How to modify test.py so that mAP results and pictures with bboxes are both generated after running it?

**Comment by mrkind** [comment]
Thank you author,I have partly resolved this issue!
