### ISSUE TITLE
Develop SemSeg Head

### ISSUE THREAD

**Issue by faheuer** [xingyizhou/CenterNet#565]
Hi, I am considering adding a Semseg head to CenterNet detection. Plan is to predict segmentation maps and detections with a shared backbone, for example for COCO. Has anybody played around with this or can the author give some thoughts on this?

I intend to add another head with a single conv layer to the ctdet branch (next to wh, reg, hm) and then have the network predict centerpoints + segmentation maps. For the backbone I want to use DLA since it is architectually close some SemSeg backbones.

**Comment by xingyizhou** [comment]
I don't have good suggestion on that. I have seen a similar idea [here](https://github.com/CaoWGG/Mask-CenterNet).

**Comment by faheuer** [comment]
Thank you, I will look into that!
