### ISSUE TITLE
How to get bounding box coordinates? 

### ISSUE THREAD

**Issue by mrkind** [xingyizhou/CenterNet#567]
How to return them in python code or output them to files?

**Comment by xingyizhou** [comment]
Please refer to the readme:

To use this CenterNet in your own project, you can 

~~~
import sys
CENTERNET_PATH = /path/to/CenterNet/src/lib/
sys.path.insert(0, CENTERNET_PATH)

from detectors.detector_factory import detector_factory
from opts import opts

MODEL_PATH = /path/to/model
TASK = 'ctdet' # or 'multi_pose' for human pose estimation
opt = opts().init('{} --load_model {}'.format(TASK, MODEL_PATH).split(' '))
detector = detector_factory[opt.task](opt)

img = image/or/path/to/your/image/
ret = detector.run(img)['results']
~~~
`ret` will be a python dict: `{category_id : [[x1, y1, x2, y2, score], ...], }`

**Comment by KhanhCon** [comment]
Any got weird results like me?

`Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /content/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded CenterNet/models/ctdet_coco_dla_2x.pth, epoch 230
{1: array([[ 1.63218033e+02, -1.70807528e+00,  4.80712646e+02,
         5.10384033e+02,  7.74947643e-01],
       [ 7.47832642e+02,  1.06753671e+00,  8.30699951e+02,
         1.26424660e+02,  5.42822421e-01],
       [ 8.50738342e+02,  2.93608022e+00,  8.95824341e+02,
         1.35330093e+02,  5.06913841e-01],
       [ 4.87997925e+02,  5.89458704e-01,  5.95515869e+02,
         1.99313461e+02,  4.15315330e-01],
       [ 4.19605957e+02, -3.08564365e-01,  5.93378113e+02,
         1.98090942e+02,  2.64821321e-01],
       [ 7.33037476e+02,  2.06416702e+00,  7.72190918e+02,
         3.78472214e+01,  2.32965603e-01],
       [ 8.17574097e+02, -6.36692882e-01,  8.47689697e+02,
         3.25882149e+01,  2.12188557e-01],
       [ 7.29465576e+02,  4.11134863e+00,  7.63459717e+02,
         1.19802094e+02,  2.10129231e-01],
       [ 8.05843445e+02, -5.46536803e-01,  8.29924927e+02,
         3.13762264e+01,  1.75266847e-01],
       [ 7.68957642e+02,  1.60173607e+00,  7.82594055e+02,
         2.66974030e+01,  1.39217943e-01],
       [ 5.63746338e+02, -5.37694037e-01,  7.32949463e+02,
         2.26000488e+02,  1.25280306e-01],
       [ 8.54076538e+02,  1.11813641e+00,  8.92479614e+02,
         5.00415344e+01,  1.04170397e-01],
       [ 4.97256897e+02,  1.02324176e+00,  7.41312683e+02,
         2.21023331e+02,  1.03984214e-01],
       [ 7.73302551e+02, -2.32894331e-01,  8.05447021e+02,
         2.92665386e+01,  9.03661102e-02],
       [ 8.79856934e+02,  1.23098396e+02,  8.97970215e+02,
         1.43926620e+02,  8.72496068e-02],
       [ 8.29137024e+02,  7.11136627e+01,  8.63413391e+02,
         1.27261665e+02,  8.54314566e-02],
       [ 8.93983215e+02,  1.59545794e+01,  8.98634583e+02,
         2.93818146e+02,  6.91315979e-02],
       [ 2.33690155e+02, -1.01466501e+00,  3.21115936e+02,
         5.62791748e+01,  6.32409751e-02],
       [ 8.42967285e+02, -7.15116978e-01,  8.61254150e+02,
         2.84152412e+01,  5.95615245e-02],
       [ 8.49741394e+02,  1.08382683e+02,  8.97016235e+02,
         1.74128540e+02,  5.74230440e-02],
       [ 4.21007446e+02,  9.23540890e-01,  4.77351685e+02,
         5.01126823e+01,  5.68330437e-02],
       [ 3.08659332e+02,  5.96073925e-01,  4.78266205e+02,
         7.05042801e+01,  5.41975200e-02],
       [ 5.26836920e+00,  1.78893951e+02,  1.01164612e+02,
         2.16402313e+02,  4.74741310e-02]], dtype=float32), 2: array([], shape=(0, 5), dtype=float32), 3: array([], shape=(0, 5), dtype=float32), 4: array([], shape=(0, 5), dtype=float32), 5: array([], shape=(0, 5), dtype=float32), 6: array([], shape=(0, 5), dtype=float32), 7: array([[-3.10451674e+00,  7.78055573e+00,  1.10149872e+02,
         5.57701477e+02,  6.48031831e-02],
       [-2.79901505e+00,  5.54240990e+00,  1.08086044e+02,
         3.47530609e+02,  6.26476705e-02],
       [ 7.94056058e-01,  1.59450083e+01,  1.05936867e+02,
         4.35765289e+02,  6.15837201e-02]], dtype=float32), 8: array([[ 1.25075614e+00,  1.75613899e+01,  1.05539772e+02,
         4.19860901e+02,  5.34679815e-02],
       [-4.59407234e+00,  1.60265410e+00,  1.10221565e+02,
         3.64338501e+02,  5.10231480e-02]], dtype=float32), 9: array([], shape=(0, 5), dtype=float32), 10: array([], shape=(0, 5), dtype=float32), 11: array([], shape=(0, 5), dtype=float32), 12: array([[5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        4.6725657e-02]], dtype=float32), 13: array([], shape=(0, 5), dtype=float32), 14: array([[7.30581299e+02, 2.48386459e+01, 7.61699097e+02, 1.14731621e+02,
        6.02072664e-02],
       [8.00763428e+02, 1.82757931e+01, 8.49999573e+02, 9.16362915e+01,
        5.74141182e-02],
       [8.06666077e+02, 1.95599976e+01, 8.55151367e+02, 1.17969086e+02,
        5.43001331e-02],
       [8.18201782e+02, 1.66033264e+02, 9.02027954e+02, 5.68379944e+02,
        5.31192720e-02]], dtype=float32), 15: array([], shape=(0, 5), dtype=float32), 16: array([], shape=(0, 5), dtype=float32), 17: array([[ 3.35499695e+02,  1.87629425e+02,  9.03149170e+02,
         6.00414368e+02,  9.31395888e-01],
       [-1.56740248e+00,  9.00170975e+01,  3.06471313e+02,
         5.88779968e+02,  8.66762578e-01],
       [-1.13590097e+00,  9.01787796e+01,  2.04753006e+02,
         5.87017456e+02,  1.07340544e-01],
       [ 5.09336948e+00,  9.78721466e+01,  1.98389328e+02,
         2.25551270e+02,  6.25257790e-02],
       [ 7.48724243e+02,  4.65186554e+02,  9.00679077e+02,
         5.95536316e+02,  5.63660599e-02],
       [-9.32023942e-01,  7.10184402e+01,  2.03149017e+02,
         4.36948761e+02,  5.30035272e-02]], dtype=float32), 18: array([], shape=(0, 5), dtype=float32), 19: array([], shape=(0, 5), dtype=float32), 20: array([], shape=(0, 5), dtype=float32), 21: array([], shape=(0, 5), dtype=float32), 22: array([], shape=(0, 5), dtype=float32), 23: array([], shape=(0, 5), dtype=float32), 24: array([], shape=(0, 5), dtype=float32), 25: array([[ 3.0865933e+02,  5.9607393e-01,  4.7826620e+02,  7.0504280e+01,
         9.8432377e-02],
       [ 3.0840924e+02,  1.4013666e-01,  4.2291409e+02,  6.9639168e+01,
         9.5380478e-02],
       [ 2.3369016e+02, -1.0146650e+00,  3.2111594e+02,  5.6279175e+01,
         9.4270810e-02],
       [ 4.2100745e+02,  9.2354089e-01,  4.7735168e+02,  5.0112682e+01,
         8.8476866e-02],
       [ 8.2879553e+02,  9.5013481e+01,  8.6162158e+02,  1.3071823e+02,
         8.4367141e-02],
       [ 7.4543054e+02,  3.3140614e+01,  7.9008765e+02,  1.2087768e+02,
         4.9167711e-02],
       [ 5.0933695e+00,  9.7872147e+01,  1.9838933e+02,  2.2555127e+02,
         4.9108587e-02]], dtype=float32), 26: array([], shape=(0, 5), dtype=float32), 27: array([[ 3.08409241e+02,  1.40136659e-01,  4.22914093e+02,
         6.96391678e+01,  2.05334067e-01],
       [ 3.08659332e+02,  5.96073925e-01,  4.78266205e+02,
         7.05042801e+01,  1.72135770e-01],
       [ 2.33690155e+02, -1.01466501e+00,  3.21115936e+02,
         5.62791748e+01,  1.28044099e-01],
       [ 6.45099731e+02,  2.56924103e+02,  8.91661377e+02,
         4.64148712e+02,  1.27555251e-01],
       [ 4.21007446e+02,  9.23540890e-01,  4.77351685e+02,
         5.01126823e+01,  1.05824955e-01],
       [ 8.28795532e+02,  9.50134811e+01,  8.61621582e+02,
         1.30718231e+02,  9.82085392e-02],
       [ 8.02351624e+02,  2.32423401e+01,  8.48451660e+02,
         7.49814072e+01,  7.97634423e-02],
       [ 2.32764801e+02, -6.78584754e-01,  3.24540161e+02,
         1.97378235e+02,  7.02389404e-02],
       [ 8.79856934e+02,  1.23098396e+02,  8.97970215e+02,
         1.43926620e+02,  5.31700924e-02],
       [ 8.05585266e+02,  7.04174805e+01,  8.43031921e+02,
         1.26866234e+02,  5.00681885e-02]], dtype=float32), 28: array([[4.2545248e+02, 1.8504684e+00, 4.4415390e+02, 4.2703377e+01,
        1.0748083e-01],
       [5.8330121e+02, 2.6671671e+02, 6.2927441e+02, 3.6907651e+02,
        8.0633447e-02],
       [5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        7.1252614e-02],
       [5.9308673e+02, 2.6649155e+02, 6.3246100e+02, 3.2354355e+02,
        6.7686327e-02]], dtype=float32), 29: array([[ 3.08659332e+02,  5.96073925e-01,  4.78266205e+02,
         7.05042801e+01,  1.19488947e-01],
       [ 3.08409241e+02,  1.40136659e-01,  4.22914093e+02,
         6.96391678e+01,  9.26436931e-02],
       [ 1.34133741e-01,  9.93738327e+01,  1.93554901e+02,
         2.37343048e+02,  6.11214153e-02],
       [ 7.30581299e+02,  2.48386459e+01,  7.61699097e+02,
         1.14731621e+02,  5.73213920e-02],
       [-4.59407234e+00,  1.60265410e+00,  1.10221565e+02,
         3.64338501e+02,  4.75337841e-02]], dtype=float32), 30: array([[5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        7.1640626e-02]], dtype=float32), 31: array([[5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        4.8702296e-02]], dtype=float32), 32: array([], shape=(0, 5), dtype=float32), 33: array([], shape=(0, 5), dtype=float32), 34: array([], shape=(0, 5), dtype=float32), 35: array([[5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        7.1211874e-02]], dtype=float32), 36: array([], shape=(0, 5), dtype=float32), 37: array([[-5.83412266e+00, -1.75301403e-01,  1.11817604e+02,
         3.80699066e+02,  5.35740182e-02]], dtype=float32), 38: array([], shape=(0, 5), dtype=float32), 39: array([], shape=(0, 5), dtype=float32), 40: array([[5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        9.3329787e-02],
       [5.9257397e+02, 2.6197079e+02, 6.3436902e+02, 3.2036377e+02,
        8.2231209e-02],
       [8.0764856e+02, 8.0579529e+01, 8.4063263e+02, 1.2939128e+02,
        6.5355852e-02],
       [5.8330121e+02, 2.6671671e+02, 6.2927441e+02, 3.6907651e+02,
        5.0465465e-02]], dtype=float32), 41: array([], shape=(0, 5), dtype=float32), 42: array([], shape=(0, 5), dtype=float32), 43: array([], shape=(0, 5), dtype=float32), 44: array([[5.8353076e+02, 2.7081406e+02, 6.2740961e+02, 3.7794751e+02,
        6.7332000e-02],
       [5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        6.6985503e-02]], dtype=float32), 45: array([], shape=(0, 5), dtype=float32), 46: array([[3.5387366e+02, 4.4887411e+02, 4.2015201e+02, 4.9794244e+02,
        7.1098380e-02]], dtype=float32), 47: array([], shape=(0, 5), dtype=float32), 48: array([], shape=(0, 5), dtype=float32), 49: array([], shape=(0, 5), dtype=float32), 50: array([], shape=(0, 5), dtype=float32), 51: array([], shape=(0, 5), dtype=float32), 52: array([], shape=(0, 5), dtype=float32), 53: array([], shape=(0, 5), dtype=float32), 54: array([], shape=(0, 5), dtype=float32), 55: array([], shape=(0, 5), dtype=float32), 56: array([], shape=(0, 5), dtype=float32), 57: array([[7.3107941e+02, 3.4058132e+01, 7.6248230e+02, 1.1744470e+02,
        1.2919097e-01],
       [8.0235162e+02, 2.3242340e+01, 8.4845166e+02, 7.4981407e+01,
        9.2840873e-02]], dtype=float32), 58: array([], shape=(0, 5), dtype=float32), 59: array([], shape=(0, 5), dtype=float32), 60: array([], shape=(0, 5), dtype=float32), 61: array([[-1.7248718e+00,  2.9390774e+00,  9.2159210e+01,  4.9510777e+01,
         5.3862657e-02],
       [ 8.0235162e+02,  2.3242340e+01,  8.4845166e+02,  7.4981407e+01,
         4.9735282e-02],
       [ 8.5090302e+02,  1.3943959e+02,  8.9714801e+02,  1.7096794e+02,
         4.6249542e-02]], dtype=float32), 62: array([], shape=(0, 5), dtype=float32), 63: array([], shape=(0, 5), dtype=float32), 64: array([], shape=(0, 5), dtype=float32), 65: array([], shape=(0, 5), dtype=float32), 66: array([[5.26836920e+00, 1.78893951e+02, 1.01164612e+02, 2.16402313e+02,
        1.10684045e-01]], dtype=float32), 67: array([], shape=(0, 5), dtype=float32), 68: array([[5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        1.8952040e-01],
       [5.9308673e+02, 2.6649155e+02, 6.3246100e+02, 3.2354355e+02,
        8.6674981e-02],
       [8.0699701e+02, 2.6599222e+02, 8.7017139e+02, 2.9954770e+02,
        6.1825395e-02]], dtype=float32), 69: array([], shape=(0, 5), dtype=float32), 70: array([[-1.72487175e+00,  2.93907738e+00,  9.21592102e+01,
         4.95107765e+01,  1.04404911e-01],
       [-1.04091191e+00,  2.45391388e+01,  1.08005646e+02,
         4.54824097e+02,  5.45067042e-02],
       [-3.89414811e+00,  9.20433998e+00,  1.10627899e+02,
         5.69670776e+02,  4.74837981e-02]], dtype=float32), 71: array([], shape=(0, 5), dtype=float32), 72: array([[-1.7248718e+00,  2.9390774e+00,  9.2159210e+01,  4.9510777e+01,
         2.0830423e-01],
       [ 1.3112297e+00,  4.0324383e+00,  3.1855856e+01,  4.6344879e+01,
         7.1091115e-02]], dtype=float32), 73: array([[-4.59407234e+00,  1.60265410e+00,  1.10221565e+02,
         3.64338501e+02,  6.56525567e-02]], dtype=float32), 74: array([[6.4509973e+02, 2.5692410e+02, 8.9166138e+02, 4.6414871e+02,
        3.0295208e-01],
       [5.9257397e+02, 2.6197079e+02, 6.3436902e+02, 3.2036377e+02,
        6.7578025e-02],
       [6.8959875e+02, 2.7588312e+02, 8.5979651e+02, 3.7204791e+02,
        6.7203984e-02],
       [5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        5.7844747e-02]], dtype=float32), 75: array([[5.9257397e+02, 2.6197079e+02, 6.3436902e+02, 3.2036377e+02,
        7.6363139e-02],
       [5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        6.9498688e-02]], dtype=float32), 76: array([], shape=(0, 5), dtype=float32), 77: array([[5.8330121e+02, 2.6671671e+02, 6.2927441e+02, 3.6907651e+02,
        4.7672987e-02]], dtype=float32), 78: array([], shape=(0, 5), dtype=float32), 79: array([[5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        7.0282564e-02]], dtype=float32), 80: array([[5.2683692e+00, 1.7889395e+02, 1.0116461e+02, 2.1640231e+02,
        1.3928451e-01]], dtype=float32)}`
