### ISSUE TITLE
The result of demo not good?

### ISSUE THREAD

**Issue by EasonEdison** [xingyizhou/CenterNet#568]
![{UG7QGTC91BX8TNFC ~WR42](https://user-images.githubusercontent.com/31425634/71760042-2d962780-2ef2-11ea-9502-ba1fcbb7dc69.png)
![S }7ARF~I8`SYMVIJPDL@3S](https://user-images.githubusercontent.com/31425634/71760112-481cd080-2ef3-11ea-8236-b01d39a34883.png)

I use separately ddd_3dop.pth and ddd_sub.pth,but results both are not good, code is:
```
python demo.py ddd --demo ../images/17790319373_bd19b24cfc_k.jpg --load_model ../models/ddd_sub.pth --debug 2
```
Did I do something wrong? or is it supposed to be?

**Comment by xingyizhou** [comment]
This is expected. The model trained on KITTI will not generalized to in-the-wild data.
