### ISSUE TITLE
how to customize output files'names

### ISSUE THREAD

**Issue by mrkind** [xingyizhou/CenterNet#569]
By adding the following line at the end of ctdet.py

debugger.save_all_imgs(path='/home/czb/CenterNet-master/output/', genID=True)

I got output png files named "1ctdet.png","2ctdet.png",...

But my input files'names are for instance "abc.bmp","uvw.bmp"

I want to modify output png files'names to "abc_suffix.png","uvw_suffix.png".How to achieve that?

**Comment by xingyizhou** [comment]
This will be hard in the current code. You will need to provide the file name in the data loader.

**Comment by mrkind** [comment]
Thank you author,solved!
