### ISSUE TITLE
Training results are a bit poor

### ISSUE THREAD

**Issue by pipi2020** [xingyizhou/CenterNet#571]
@xingyizhou Dear author, hello, I'm glad to see such a great job on object detection tasks. I also trained my own data using your method. After 70 epochs, I tested my dataset with the best model I saved. But the results are not ideal. What I want is to detect the area between the finger seams, but there are a lot of error boxes. I do n’t know what happened, where should I look for my errors?
The test results are as follows： 
![image](https://user-images.githubusercontent.com/43240670/71799093-4e47b400-308f-11ea-97d1-d26ff886d2d8.png)

**Comment by pipi2020** [comment]
i only follow the blog to change the code for my dataste
[http://www.ishenping.com/ArtInfo/3732493.html](url)

**Comment by xingyizhou** [comment]
This looks like the model is not correctly loaded. Can you make sure you haven't seen any abnormal outputs when running the test?

**Comment by pipi2020** [comment]
yes，i have solved it by loading the model you have trained ,and i continue to train it .it work




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xingyi Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 中午11:23
收件人:&nbsp;"xingyizhou/CenterNet"<CenterNet@noreply.github.com&gt;;
抄送:&nbsp;"高健"<787117010@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xingyizhou/CenterNet] Training results are a bit poor (#571)




This looks like the model is not correctly loaded. Can you make sure you haven't seen any abnormal outputs when running the test?
