### ISSUE TITLE
Question about the GT heatmap generation

### ISSUE THREAD

**Issue by DemonsRhythm** [xingyizhou/CenterNet#577]
Hello, When I read the code `sample/ctdet.py`, I find that the `draw_gaussian` function return the heatmap that has not changed. So the Ground Truth heatmaps returned by `sample/ctdet.py`  are just the initial value `np.zeros((num_classes, output_h, output_w), dtype=np.float32)`. I find it the same as code in `CornerNet`. 
```
def draw_umich_gaussian(heatmap, center, radius, k=1):
  diameter = 2 * radius + 1
  gaussian = gaussian2D((diameter, diameter), sigma=diameter / 6)
  
  x, y = int(center[0]), int(center[1])

  height, width = heatmap.shape[0:2]
    
  left, right = min(x, radius), min(width - x, radius + 1)
  top, bottom = min(y, radius), min(height - y, radius + 1)

  masked_heatmap  = heatmap[y - top:y + bottom, x - left:x + right]
  masked_gaussian = gaussian[radius - top:radius + bottom, radius - left:radius + right]
  if min(masked_gaussian.shape) > 0 and min(masked_heatmap.shape) > 0: # TODO debug
    np.maximum(masked_heatmap, masked_gaussian * k, out=masked_heatmap)

  return heatmap
```
Could you plz answer this question? Thanks a lot.

**Comment by y0un5** [comment]
The code is little bit confusing, but `heatmap` is actually changed. When I saw this function for the first time, I had the same thought as yours, but after run the function I could see that `heatmap` is changed. 

`masked_heatmap` refers to some part of `heatmap` and `masked_heatmap` is changed in the following code. So, `heatmap` is changed too.

```python
np.maximum(masked_heatmap, masked_gaussian * k, out=masked_heatmap)
```

**Comment by DemonsRhythm** [comment]
> The code is little bit confusing, but `heatmap` is actually changed. When I saw this function for the first time, I had the same thought as yours, but after run the function I could see that `heatmap` is changed.
> 
> `masked_heatmap` refers to some part of `heatmap` and `masked_heatmap` is changed in the following code. So, `heatmap` is changed too.
> 
> ```python
> np.maximum(masked_heatmap, masked_gaussian * k, out=masked_heatmap)
> ```

Thanks for your reply. I understand the function as it use the feature of Python that arrays are passed by reference in functions. So the parameter `heatmap` share the same address with `hm` in `ctdet.py`, and also `masked_heatmap` refers to the same address of elements in `heatmap`. So when `masked_heatmap` changes, corresponding elements in `heatmap` will change indeed.
