### ISSUE TITLE
Testing error on pascal voc 2007 dataset

### ISSUE THREAD

**Issue by XzlXcc** [xingyizhou/CenterNet#58]
When I use the following code to test on pascal voc 2007 dataset: 

`python test.py ctdet --exp_id dla --dataset pascal --load_model ../models/ctdet_pascal_dla_384.pth --flip_test`

I encountered an error when getting the mAP after testing on each image: 
`......`
`dla |############################### | [4947/4952]|Tot: 0:01:28 |ETA: 0:00:01 |tot 0.017s (0.017s) |load 0.000s (0.000s) |pre 0.000s (0.000s) |net 0.014s (0.014`
`dla |############################### | [4948/4952]|Tot: 0:01:28 |ETA: 0:00:01 |tot 0.018s (0.017s) |load 0.000s (0.000s) |pre 0.000s (0.000s) |net 0.015s (0.014`
`dla |############################### | [4949/4952]|Tot: 0:01:28 |ETA: 0:00:01 |tot 0.017s (0.017s) |load 0.000s (0.000s) |pre 0.000s (0.000s) |net 0.014s (0.014`
`dla |############################### | [4950/4952]|Tot: 0:01:28 |ETA: 0:00:01 |tot 0.016s (0.017s) |load 0.000s (0.000s) |pre 0.000s (0.000s) |net 0.014s (0.014`
`dla |################################| [4951/4952]|Tot: 0:01:28 |ETA: 0:00:01 |tot 0.016s (0.017s) |load 0.000s (0.000s) |pre 0.000s (0.000s) |net 0.014s (0.014s) |dec 0.001s (0.001s) |post 0.001s (0.001s) |merge 0.000s (0.000s)`
**sh: 1: Syntax error: "(" unexpected**

How to solve it? Thanks a lot.

**Comment by xingyizhou** [comment]
I haven't met this. Please make sure your code is intact. You can manually evaluate pascal by
`python reval /path/to/your/exp/results.json` in `src/tools`.

**Comment by XzlXcc** [comment]
OK, I got the solution. There is a file contains "()" so I met that problem. Anyway thanks a lot. 


------------------ Original ------------------

**Comment by XzlXcc** [comment]
I am OK with the train and test on COCO and VOC dataset, but I got another question during my reading the code. I am confused with how to predict the width and height after getting the center points of each category. Could you show me which file does this work, and its basic steps? Thanks a lot.

**Comment by xingyizhou** [comment]
https://github.com/xingyizhou/CenterNet/blob/master/src/lib/models/decode.py#L464

**Comment by XzlXcc** [comment]
> https://github.com/xingyizhou/CenterNet/blob/master/src/lib/models/decode.py#L464

I find that this function is not called during training, just predict width and height during testing period. Am I right?
