### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Eyren** [xingyizhou/CenterNet#583]
hi,my image is 512*512
`Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/zmy/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/zmy/CenterNet/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/zmy/miniconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/zmy/miniconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/zmy/miniconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zmy/miniconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/zmy/CenterNet/src/lib/datasets/sample/ctdet.py", line 39, in __getitem__
    height, width = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'
`

Then i checked some answer about this problem.I change the code in ctdet.py,i want to print the img to see if cv2.imread can read my picture.
![image](https://user-images.githubusercontent.com/46129572/72202528-87bb5d80-349b-11ea-85a0-c009baf53dca.png)

it can print out the images array
![image](https://user-images.githubusercontent.com/46129572/72202541-a9b4e000-349b-11ea-8f09-48dbcd5907e8.png)
I think this showed cv2.imread is worked fine?
So,what i can do now?

**Comment by wwetnaroh** [comment]
the same problem。 have you solved it?

**Comment by Eyren** [comment]
> the same problem。 have you solved it?

Yeah,I kind of finding the problem.It seems like some of my images are broken.Cause when i print(type(img)),some of images were<class NoneType>
Then i came to check my annotations file,the filename can't corresponding the image.I think you should check the name of your annotations and images .

**Comment by wwetnaroh** [comment]
> > the same problem。 have you solved it?
> 
> Yeah,I kind of finding the problem.It seems like some of my images are broken.Cause when i print(type(img)),some of images were
> Then i came to check my annotations file,the filename can't corresponding the image.I think you should check the name of your annotations and images .

what is the path of your image?  I use print(img_path)but find the image path is in /home/gxt/CenterNet/src/lib/../../data/ead/images/000813.jpg but not in CenterNet/data/ead/images folder

**Comment by Eyren** [comment]
my path is /home/zmy/CenterNet/data/images
Actually my path is correct,my problem is my annotations has Chinese words in it.....so the annotations can't be read correctly.

**Comment by wwetnaroh** [comment]
> my path is /home/zmy/CenterNet/data/images
> Actually my path is correct,my problem is my annotations has Chinese words in it.....so the annotations can't be read correctly.

Thanks a lot, bro

**Comment by 1356789-rr** [comment]
> > > the same problem。 have you solved it?
> > 
> > 
> > Yeah,I kind of finding the problem.It seems like some of my images are broken.Cause when i print(type(img)),some of images were
> > Then i came to check my annotations file,the filename can't corresponding the image.I think you should check the name of your annotations and images .
> 
> what is the path of your image? I use print(img_path)but find the image path is in /home/gxt/CenterNet/src/lib/../../data/ead/images/000813.jpg but not in CenterNet/data/ead/images folder

@wwetnaroh  I have the same problem。 have you solved it?
