### ISSUE TITLE
successfully trained,but can't test my images

### ISSUE THREAD

**Issue by Eyren** [xingyizhou/CenterNet#584]
My training data
`ctdet/coco_dla |##                              | train: [140][0/13]|Tot: 0:00:01 |ETA: 0:00:00 |loss 1.8252 |hm_loss 1.3708 |wh_loss 3.9439 |off_loss 0.0599 |Dctdet/coco_dla |####                            | train: [140][1/13]|Tot: 0:00:02 |ETA: 0:00:13 |loss 2.5078 |hm_loss 1.8484 |wh_loss 5.8866 |off_loss 0.0707 |Dctdet/coco_dla |#######                         | train: [140][2/13]|Tot: 0:00:03 |ETA: 0:00:12 |loss 2.5040 |hm_loss 1.7788 |wh_loss 6.4590 |off_loss 0.0793 |Dctdet/coco_dla |#########                       | train: [140][3/13]|Tot: 0:00:04 |ETA: 0:00:11 |loss 2.4010 |hm_loss 1.7046 |wh_loss 6.1381 |off_loss 0.0826 |Dctdet/coco_dla |############                    | train: [140][4/13]|Tot: 0:00:05 |ETA: 0:00:10 |loss 2.4445 |hm_loss 1.7290 |wh_loss 6.2453 |off_loss 0.0910 |Dctdet/coco_dla |##############                  | train: [140][5/13]|Tot: 0:00:06 |ETA: 0:00:09 |loss 2.5059 |hm_loss 1.7492 |wh_loss 6.6092 |off_loss 0.0958 |Dctdet/coco_dla |#################               | train: [140][6/13]|Tot: 0:00:07 |ETA: 0:00:08 |loss 2.5515 |hm_loss 1.7671 |wh_loss 6.8841 |off_loss 0.0959 |Dctdet/coco_dla |###################             | train: [140][7/13]|Tot: 0:00:08 |ETA: 0:00:07 |loss 2.5712 |hm_loss 1.7616 |wh_loss 7.1701 |off_loss 0.0926 |Dctdet/coco_dla |######################          | train: [140][8/13]|Tot: 0:00:09 |ETA: 0:00:06 |loss 2.6877 |hm_loss 1.8467 |wh_loss 7.4508 |off_loss 0.0960 |Dctdet/coco_dla |########################        | train: [140][9/13]|Tot: 0:00:10 |ETA: 0:00:05 |loss 2.6406 |hm_loss 1.8192 |wh_loss 7.2809 |off_loss 0.0934 |Dctdet/coco_dla |###########################     | train: [140][10/13]|Tot: 0:00:11 |ETA: 0:00:04 |loss 2.7000 |hm_loss 1.8243 |wh_loss 7.7994 |off_loss 0.0957 |ctdet/coco_dla |#############################   | train: [140][11/13]|Tot: 0:00:12 |ETA: 0:00:03 |loss 2.6547 |hm_loss 1.8170 |wh_loss 7.3758 |off_loss 0.1001 |ctdet/coco_dla |################################| train: [140][12/13]|Tot: 0:00:13 |ETA: 0:00:02 |loss 2.6393 |hm_loss 1.8094 |wh_loss 7.2929 |off_loss 0.1006 |Data 0.227s(0.219s) |Net 1.015s
`
It seems no problem at all.But in my exp/ctdet .It's only have three olg folder.
 when i test the model_best.path.It shows
`loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded val 68 samples
Creating model...
loaded /home/zmy/CenterNet/models/model_best.pth, epoch 95
coco_dla |                                | [0/68]|Tot: 0:00:01 |ETA: 0:00:00 |tcoco_dla |                                | [1/68]|Tot: 0:00:01 |ETA: 0:01:13 |tcoco_dla |#                               | [2/68]|Tot: 0:00:01 |ETA: 0:00:37 |tcoco_dla |#                               | [3/68]|Tot: 0:00:01 |ETA: 0:00:25 |tcoco_dla |##                              | [4/68]|Tot: 0:00:01 |ETA: 0:00:19 |tcoco_dla |##                              | [5/68]|Tot: 0:00:01 |ETA: 0:00:15 |tcoco_dla |###                             | [6/68]|Tot: 0:00:01 |ETA: 0:00:13 |tcoco_dla |###                             | [7/68]|Tot: 0:00:01 |ETA: 0:00:11 |tcoco_dla |####                            | [8/68]|Tot: 0:00:01 |ETA: 0:00:10 |tcoco_dla |####                            | [9/68]|Tot: 0:00:01 |ETA: 0:00:09 |tcoco_dla |#####                           | [10/68]|Tot: 0:00:01 |ETA: 0:00:08 |coco_dla |#####                           | [11/68]|Tot: 0:00:01 |ETA: 0:00:08 |coco_dla |######                          | [12/68]|Tot: 0:00:01 |ETA: 0:00:08 |coco_dla |######                          | [13/68]|Tot: 0:00:01 |ETA: 0:00:08 |coco_dla |#######                         | [14/68]|Tot: 0:00:01 |ETA: 0:00:08 |coco_dla |#######                         | [15/68]|Tot: 0:00:01 |ETA: 0:00:07 |coco_dla |########                        | [16/68]|Tot: 0:00:01 |ETA: 0:00:07 |coco_dla |########                        | [17/68]|Tot: 0:00:01 |ETA: 0:00:07 |coco_dla |########                        | [18/68]|Tot: 0:00:01 |ETA: 0:00:07 |coco_dla |#########                       | [19/68]|Tot: 0:00:01 |ETA: 0:00:07 |coco_dla |#########                       | [20/68]|Tot: 0:00:01 |ETA: 0:00:07 |coco_dla |##########                      | [21/68]|Tot: 0:00:01 |ETA: 0:00:07 |coco_dla |##########                      | [22/68]|Tot: 0:00:01 |ETA: 0:00:07 |coco_dla |###########                     | [23/68]|Tot: 0:00:01 |ETA: 0:00:06 |coco_dla |###########                     | [24/68]|Tot: 0:00:01 |ETA: 0:00:06 |coco_dla |############                    | [25/68]|Tot: 0:00:01 |ETA: 0:00:06 |coco_dla |############                    | [26/68]|Tot: 0:00:01 |ETA: 0:00:06 |coco_dla |#############                   | [27/68]|Tot: 0:00:01 |ETA: 0:00:06 |coco_dla |#############                   | [28/68]|Tot: 0:00:01 |ETA: 0:00:06 |coco_dla |##############                  | [29/68]|Tot: 0:00:01 |ETA: 0:00:06 |coco_dla |##############                  | [30/68]|Tot: 0:00:01 |ETA: 0:00:06 |coco_dla |###############                 | [31/68]|Tot: 0:00:01 |ETA: 0:00:05 |coco_dla |###############                 | [32/68]|Tot: 0:00:01 |ETA: 0:00:05 |coco_dla |################                | [33/68]|Tot: 0:00:01 |ETA: 0:00:05 |coco_dla |################                | [34/68]|Tot: 0:00:01 |ETA: 0:00:05 |coco_dla |################                | [35/68]|Tot: 0:00:01 |ETA: 0:00:05 |coco_dla |#################               | [36/68]|Tot: 0:00:02 |ETA: 0:00:05 |coco_dla |#################               | [37/68]|Tot: 0:00:02 |ETA: 0:00:05 |coco_dla |##################              | [38/68]|Tot: 0:00:02 |ETA: 0:00:04 |coco_dla |##################              | [39/68]|Tot: 0:00:02 |ETA: 0:00:04 |coco_dla |###################             | [40/68]|Tot: 0:00:02 |ETA: 0:00:04 |coco_dla |###################             | [41/68]|Tot: 0:00:02 |ETA: 0:00:04 |coco_dla |####################            | [42/68]|Tot: 0:00:02 |ETA: 0:00:04 |coco_dla |####################            | [43/68]|Tot: 0:00:02 |ETA: 0:00:04 |coco_dla |#####################           | [44/68]|Tot: 0:00:02 |ETA: 0:00:04 |coco_dla |#####################           | [45/68]|Tot: 0:00:02 |ETA: 0:00:04 |coco_dla |######################          | [46/68]|Tot: 0:00:02 |ETA: 0:00:03 |coco_dla |######################          | [47/68]|Tot: 0:00:02 |ETA: 0:00:03 |coco_dla |#######################         | [48/68]|Tot: 0:00:02 |ETA: 0:00:03 |coco_dla |#######################         | [49/68]|Tot: 0:00:02 |ETA: 0:00:03 |coco_dla |########################        | [50/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |########################        | [51/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |########################        | [52/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |#########################       | [53/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |#########################       | [54/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |##########################      | [55/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |##########################      | [56/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |###########################     | [57/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |###########################     | [58/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |############################    | [59/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |############################    | [60/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |#############################   | [61/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |#############################   | [62/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |##############################  | [63/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |##############################  | [64/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |############################### | [65/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |############################### | [66/68]|Tot: 0:00:02 |ETA: 0:00:01 |coco_dla |################################| [67/68]|Tot: 0:00:02 |ETA: 0:00:01 |tot 0.041 |load 0.002 |pre 0.009 |net 0.028 |dec 0.001 |post 0.001 |merge 0.000 
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.28s).
Accumulating evaluation results...
DONE (t=0.03s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
`
Does someone has the same issue?Please help me about this.Thanks.

**Comment by xingyizhou** [comment]
Please make sure you have set up the testing annotations correctly. I will appreciate it if you can organize the log when you post an issue next time.

**Comment by Eyren** [comment]
> Please make sure you have set up the testing annotations correctly. I will appreciate it if you can organize the log when you post an issue next time.

Thanks for your reply,i'll check again.

**Comment by ujsyehao** [comment]
＠Eyren, Do you solve the problem？

**Comment by Eyren** [comment]
> ＠Eyren, Do you solve the problem？

I change the dataset and try again,the map  changed.And i check the train and val images,it tested perfectly,but when i use the test images,it still couldn't show the results.I don't know how to solve it...

**Comment by ujsyehao** [comment]
@Eyren Can you post your val.json and the script? I use my own val dataset and get mAP = -1.

**Comment by ujsyehao** [comment]
@Eyren I have solved the problem, my script has some errors.

**Comment by yiiiruu** [comment]
@ujsyehao Hello,I have the same problem , how did you solve it ? thx!
