### ISSUE TITLE
Can this method can be reffered as anchor-free?

### ISSUE THREAD

**Issue by YijianLiu** [xingyizhou/CenterNet#586]
After reading and doing experiments on your CenterNet, I think CenterNet is quite different from other anchor-based methods, can we refer it as real anchor-free?

**Comment by SuriyaNitt** [comment]
Yes.

**Comment by xingyizhou** [comment]
Thanks for your interest in our work. Feel free to refer it whatever you like. I don't think wheater anchor-free is important.
