### ISSUE TITLE
Problem when training

### ISSUE THREAD

**Issue by wwetnaroh** [xingyizhou/CenterNet#591]
when I run python main.py ctdet --exp_id food --batch_size 32 --lr 1.25e-4  --gpus 0, a problem occurs:
RuntimeError: The size of tensor a (38) must match the size of tensor b (37) at non-singleton dimension 3, which is related to CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 56, in forward
out += residual.

**Comment by czy112** [comment]
how to solve this?

**Comment by KeyuLuo** [comment]
i have the same problem! how to solve?
