### ISSUE TITLE
Centertrack

### ISSUE THREAD

**Issue by bhack** [xingyizhou/CenterNet#597]
Do you plan to add Centertrack to this repo?

**Comment by xingyizhou** [comment]
Thanks for your interest on CenterTrack. We plan to release it in 1-2 months.

**Comment by bhack** [comment]
Not strictly related to centertrack. But, on Cityscape, if you are interested this was heavly inspired by your Centernet https://arxiv.org/abs/2001.03343
https://github.com/Banconxuan/RTM3D
/cc @Banconxuan

**Comment by bhack** [comment]
Is there a Centertrack paper in the meantine?

**Comment by xingyizhou** [comment]
Thank you for checking this. There is. We will post the paper together with the code, hopefully within a month.

**Comment by xingyizhou** [comment]
It's online now: https://arxiv.org/abs/2004.01177.

**Comment by bhack** [comment]
Thanks
