### ISSUE TITLE
GPU: Training goes slower and slower

### ISSUE THREAD

**Issue by TWDH** [xingyizhou/CenterNet#604]
Hi, I am coming again.  I was trying to train the model faster so I bought an Asus 2080super.
Initially, the program was fine, and the Data time and Net time goes longer and longer. (It was ok for the original gtx1070)
I use Nvidia-smi to check the GPU power, it jumps from 70w - 240w up and down and "volatile GPU-Util" becomes very low as well, degrees and fans also decrease a lot. I am assuming the GPU doesn't really work hard.  Is it because of my hard-disk too slow(but the other gtx1070 was fine) or any other problem.

Examples:
ctdet/coco_dla |##                              | train: [54][991/14785]|Tot: 0:15:23 |ETA: 2:50:59 |loss 1.7357 |hm_loss 1.3041 |wh_loss 2.1866 |off_loss 0.212

ctdet/coco_dla |##########                      | train: [54][4784/14785]|Tot: 1:20:53 |ETA: 6:14:23 |loss 1.7448 |hm_loss 1.3093 |wh_loss 2.2258 |off_loss 0.2129 |Data 3.556s(0.517s) |Net 1.014s

**Comment by TWDH** [comment]
Sorry for interrupting, it seems it's a matter of CPU when I shut down two pycharm windows. It comes to the original speed. It's very interesting that CPU will do such harm to the program. Probably i7 8700k has some difficulty running with rtx2080s? whatever...

**Comment by kaixinbear** [comment]
Same problem like yours.I train the model on TiTian X ,and suddenly it becomes very slow.How did you fix that ?

**Comment by TWDH** [comment]
it seems just my personal issues because pycharm consumes a lot of cpu memory. After update skeleton in pycharm, my model works fine. Maybe check any app that take too much of your cpu?
