### ISSUE TITLE
how to train model on a few classes

### ISSUE THREAD

**Issue by Arfua** [xingyizhou/CenterNet#61]
I don't need all 80 classes from COCO. I need only 2 of them. And my own dataset consists of images of 2 classes. How to train ctdet in such a case if I really want to remove other classes from training process?

**Comment by xingyizhou** [comment]
Hi,
Basically there are three steps to add new dataset:

- Convert the dataset annotation to [COCO format](http://cocodataset.org/#format-data). Please refer to [src/tools/convert_kitti_to_coco.py](../src/tools/convert_kitti_to_coco.py) for an example to convert kitti format to coco format.
- Create a dataset intilization file in `src/lib/datasets/dataset`. In most cases you can just copy `src/lib/datasets/dataset/coco.py` to your dataset name and change the category information, and annotation path.
- Import your dataset at `src/lib/datasets/dataset_factory`.
