### ISSUE TITLE
Could you make some comments in topk function, it's hard for understanding

### ISSUE THREAD

**Issue by dongzhuoyao** [xingyizhou/CenterNet#62]
https://github.com/xingyizhou/CenterNet/blob/master/src/lib/models/decode.py#L103

**Comment by xingyizhou** [comment]
It functions the same as the [slow version](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/models/decode.py#L81). Basically it first extract top 100 for **each** 80 categories, than exact the top 100 of the 80 * 100 results. We observe it is faster than directly extracting top 100 of the 80 * 128 * 128 heatmaps in practice.
