### ISSUE TITLE
data augment

### ISSUE THREAD

**Issue by alicera** [xingyizhou/CenterNet#622]
in the opt.py  , the '--rotate'
where is your '--rotate'  code  ?
"
   # dataset
    self.parser.add_argument('--not_rand_crop', action='store_true',
                             help='not use the random crop data augmentation'
                                  'from CornerNet.')
    self.parser.add_argument('--shift', type=float, default=0.1,
                             help='when not using random crop'
                                  'apply shift augmentation.')
    self.parser.add_argument('--scale', type=float, default=0.4,
                             help='when not using random crop'
                                  'apply scale augmentation.')
    self.parser.add_argument('--rotate', type=float, default=0,
                             help='when not using random crop'
                                  'apply rotation augmentation.')
    self.parser.add_argument('--flip', type = float, default=0.5,
                             help='probability of applying flip augmentation.')
    self.parser.add_argument('--no_color_aug', action='store_true',
                             help='not use the color augmenation '
"

**Comment by vellano** [comment]
it is not used in thee code， and it is  always set to 0.
and the generated bbox h,w  has a bug with rotation augmentation.

**Comment by alicera** [comment]
thanks,
I have another problem .
the centernet  have object detect limit , like the small object  detect area  > 16x16 pixel . If the small object is 10x10 pixel ,the object will not be detected by centernet.

 how about the min limit and max limit

**Comment by vellano** [comment]
i dont see the code use to limit the obj size. Maybe your grandturth does not include the small obj?

**Comment by xingyizhou** [comment]
`rotate` is rotate data-augmentation. It is not used in all experiments in the paper. There should be no size limit of objects.
