### ISSUE TITLE
CenterNet training code is very CPU heavy

### ISSUE THREAD

**Issue by ProblemFactory** [xingyizhou/CenterNet#623]
I tried to use a lightweight backbone (MobileNet) with CenterNet, but the training speed is very slow with GPU utilization < 50% (even with batch size 12). It seems that the data augmentation takes too much time. Do you have any idea on how to improve this? For example, if I use torchvision instead of opencv, do you think the performance will improve?

**Comment by ujsyehao** [comment]
you can use batchsize 64

**Comment by ProblemFactory** [comment]
> you can use batchsize 64

My (single) GPU memory is fully utilized with batch size 12. The CPU (2 CPUs with 32 physical cores total) usage is 100% at then. I have also tried batch size 48 with 4 GPUs, the training time has no change.

**Comment by Dantju** [comment]
@ProblemFactory  can u  share the mobilenet code?

**Comment by xingyizhou** [comment]
I agree that the current data augmentation implementation is unnecessarily heavy and slow. It will be improved in a (not near) future version. By that feel free to simplify the affine transform to simple resize and crop/ pad.

**Comment by ujsyehao** [comment]
@xingyizhou Can I post a PR about replace affine transform with resize?

**Comment by xingyizhou** [comment]
@ujsyehao I will be very appreciated for the PR! It can be a great reference. However I will need to verify before merging it to master.
