### ISSUE TITLE
About big resolution when training

### ISSUE THREAD

**Issue by iamastar88** [xingyizhou/CenterNet#624]
Appreciate you for the good job. But i have question, why the input size for training cannot continue to increase?  I tried to increase the input size from 512 to 800 then to 1000, which basically  converged.  However, if I continue increasing the size, such 1600 * 1600 , it will not converged. It dose not appear in faster-rcnn, why? 
The object of my dataset is small, so i want to try to change the size, i wonder what causes it?

**Comment by xingyizhou** [comment]
Thank you for your experiments. I also observed larger resolution does not help much is CenterNet. One conjecture is that as discussed in the EfficientNet paper, increasing the input size also requires increasing the network capacity. My suggestion, in this case, would be to try dla60 for larger resolutions, but I haven't tried that.

**Comment by xingyizhou** [comment]
Closing this for now. Feel free to reopen if you have further questions.
