### ISSUE TITLE
Have ctdet_coco_dla_2x.pth been trained on coco val5k?

### ISSUE THREAD

**Issue by Libaishun** [xingyizhou/CenterNet#625]
I downloaded the pretrained weights ctdet_coco_dla_2x.pth and test on coco val5k, got mAP=0.464, what is the test dataset for mAP=37.4 as you stated in the performance for DLA-34?

**Comment by xingyizhou** [comment]
I am sure it is not trained on val5k and have confirmed the number is as reported in the paper. Can you be more specific about your 0.464 result? Make sure you are using the original instances_val2017.json and haven't modified the pycocotools.

**Comment by Libaishun** [comment]
My mistake, I am using MSCOCO2014
