### ISSUE TITLE
__background__ and negative sampling

### ISSUE THREAD

**Issue by jinmingteo** [xingyizhou/CenterNet#626]
Hi @xingyizhou, nice work! 

As i am trying to do a single classification class with my training dataset, I would like to ask if there is a need to have "__background__" in my num_classes at debugger.py and change my num_classes to 2 (1 for background).

Also, I was code tracing and it seems that there is no negative sampling generated from your code right? Or is there? Does that mean we have to generate our own negative sampling in our training dataset? 

Thank you for the great work!

**Comment by Libaishun** [comment]
heatmaps are independent in regression, each is a sigmoid classification, so you don't need a background class

**Comment by xingyizhou** [comment]
You are correct. We don't need a background class.
