### ISSUE TITLE
Has any one tried HRNet as backbone ?

### ISSUE THREAD

**Issue by Libaishun** [xingyizhou/CenterNet#628]
HRNet has achieve state of art performance in both segmentation and pose estimation, and also proved effective in FCOS object detection,  did anyone tried to use them as backbones for Centernet ?

**Comment by xingyizhou** [comment]
I have tried all popular backbones, but haven't made them work better than DLA on a 4x output stride. Other backbones can perform better than DLA in a FPN-style output (8x ~ 128x stride). Details will be provided in a future revision of the paper.
