### ISSUE TITLE
Mapping original center coordinate into heatmap coordinate using 'floor' in paper

### ISSUE THREAD

**Issue by Stick-To** [xingyizhou/CenterNet#63]
why not use 'round'? I think that 'round' is more precise

**Comment by xingyizhou** [comment]
It follows CornerNet. I tried round once on pascal voc and it doesn't help. Feel free to have a try on COCO yourself.

**Comment by Stick-To** [comment]
Is there a sigmoid for offset prediction?

**Comment by xingyizhou** [comment]
No

**Comment by Stick-To** [comment]
thinks

**Comment by Stick-To** [comment]
thanks
