### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by xuhzyy** [xingyizhou/CenterNet#631]
src/lib/datasets/sample/multi_pose.py line157-160:
   if rot != 0:
      hm = hm * 0 + 0.9999
      reg_mask *= 0
      kps_mask *= 0
你好，我对姿态估计数据预处理时的这几行代码有所疑问，请问当rot大于０时为什么要进行上述处理呢？

**Comment by xingyizhou** [comment]
Hi,
  When applying rotation augmentation, the 2D bounding box will change and thus the center points change. All center related outputs should be ignored.

**Comment by Zepyhrus** [comment]
@xingyizhou quick question from `datasets/dataset_factory.py` lien 31~34: 
```python
def get_dataset(dataset, task):
  class Dataset(dataset_factory[dataset], _sample_factory[task]):
    pass
  return Dataset
```

How does the `get_dataset` function works? From my understanding, it returns a empty (almost) class
