### ISSUE TITLE
Add batchnorm after 3x3 conv in centernet head

### ISSUE THREAD

**Issue by ujsyehao** [xingyizhou/CenterNet#635]
Hi, in your code, you don't use BN after 3x3 conv/
I verify the experiments on my own dataset.
(input resolution: 256x256)
not use BN: mAP(IOU@0.5) = 36.1
use BN: mAP(IOU@0.5) = 36.7

**Comment by xingyizhou** [comment]
Thank you for your report! I would say one layer is worth 0.6 mAP ... It will be more interesting if you have COCO results.

**Comment by ujsyehao** [comment]
@xingyizhou haha, I will try. but BN has effect.

**Comment by xingyizhou** [comment]
Thank you for the suggestion. However I didn't find BN helpful on COCO, but GN seems to be slightly helpful (+0.3mAP) in a short schedule.

**Comment by ujsyehao** [comment]
@xingyizhou okay, I see!
