### ISSUE TITLE
work on pytorch=1.1 cuda = 10.1(del your old envs)

### ISSUE THREAD

**Issue by LIUHAO121** [xingyizhou/CenterNet#636]
I fixed it.
cuda=10.0, python=3.6, anaconda=Anaconda3-5.3.1-Linux-x86_64.sh
1- git clone https://github.com/xingyizhou/CenterNet.git
2- conda create --name CenterNet python=3.6
3- conda activate CenterNet
4- pip install -r requirements.txt
5- conda install pytorch=1.1 torchvision(the pip channel use https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free)
6- cd CenterNet\src\lib\external
python setup.py build_ext --inplace
7- cd /CenterNet/src/lib/models/networks
     rm -r DCNv2
     git clone https://github.com/CharlesShang/DCNv2.git
     cd /CenterNet/src/lib/models/networks/DCNv2
     python setup.py build develop
8- down ctdet_coco_dla_2x.pth from this [https://drive.google.com/file/d/1pl_-ael8wERdUREEnaIfqOV_VF2bEVRT/view](url)  and put it in /Centernet/models
9-  cd CenterNet/src/, and run:
python demo.py ctdet --demo ../images/24274813513_0cfd2ce6d0_k.jpg --load_model ../models/ctdet_coco_dla_2x.pth
10- done!

_Originally posted by @David-19940718 in https://github.com/xingyizhou/CenterNet/issues/356#issuecomment-531550456_

**Comment by xingyizhou** [comment]
Thank you for your post! However I observed the run time is actually slower in torch 1.0+ than torch 0.4 and haven't figured out why ...

**Comment by David-19940718** [comment]
This may be due to cudnn support issues with different versions of pytorch.
you can try set:
torch.backends.cudnn.deterministic = False and torch.backends.cudnn.benchmark = True
it may get a higher training speed.

**Comment by xingyizhou** [comment]
@David-19940718 Thanks for the suggestions. However it doesn't help. Anyway pytorch 1.4 can get close to the 0.4.1 speed. Closing this for now. Feel free to reopen.

**Comment by Aaron20127** [comment]
I followed these steps, but it didn't work：

Fix size testing.
training chunk_sizes: [16, 16]
The output will be saved to  /home/icvhpc1/liwei/experiment/object_detection/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
Illegal instruction (core dumped)

**Comment by YangYangGirl** [comment]
![image](https://user-images.githubusercontent.com/32426369/80169143-48161d00-8617-11ea-9400-2b40dfcdd704.png)
![image](https://user-images.githubusercontent.com/32426369/80169188-61b76480-8617-11ea-9543-9501f805f875.png)
I was puzzled by the warning. Anyone knows?

**Comment by xiaohuojianchendiwen** [comment]
I want to install this environment in Jetson nano (B01), but I can't install it successfully with arm's Pytorch1.1 installation package. How can I solve this problem?
