### ISSUE TITLE
multi gpus training does not shorten the training time as expected

### ISSUE THREAD

**Issue by Libaishun** [xingyizhou/CenterNet#637]
when I train on single gpu with batch_size=32, num_wokers=4, per epoch on coco need 42 min,
while use 4 gpus, batch_size=128, num_workers=16, per epoch on coco need 24 min, the time is roughly halved, not quartered as expected !

**Comment by xingyizhou** [comment]
This is expected, but I don't have a good solution to that yet. Changing it from data-parallel to distributed data-parallel might help, but that requires tons of works.

**Comment by xingyizhou** [comment]
Closing this for now. Feel free to reopen if you have further questions.
