### ISSUE TITLE
Save the feature map as intermediate products

### ISSUE THREAD

**Issue by neoyang0620** [xingyizhou/CenterNet#639]
Hi,

I want to save the feature maps of each input frame as an intermediate product which will be used for further independent precessing. Do you know how could I achieve that? What's kind of format I should use? Tensor? 

Best,
Neo

**Comment by xingyizhou** [comment]
You can dump `x` [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/models/networks/pose_dla_dcn.py#L472).
