### ISSUE TITLE
[Need Help]error in modulated_deformable_col2im_cuda: invalid argument

### ISSUE THREAD

**Issue by zhaotf16** [xingyizhou/CenterNet#642]
When I train my own dataset, I meet a problem seeming relevant to DCNv2

It still outputs loss and training process but I don't think it's ok....

Error log:
Creating model...
Setting up data...
==> initializing proteasome val data.
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
Loaded val 16 samples
==> initializing proteasome train data.
loading annotations into memory...
Done (t=0.67s)
creating index...
index created!
Loaded train 164 samples
Starting training...
ctdet/coco_dla/data00/UserHome/zwang/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
/data00/UserHome/zwang/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/parallel/_functions.py:58: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument
error in modulated_deformable_col2im_cuda: invalid argument

**Comment by xingyizhou** [comment]
I have met this before. In my case, I compiled DCNv2 on RTX 2080 ti but ran it on GTX 1080 ti. Keeping the compiling machine and running machine the same GPU type might solve this issue.

**Comment by xingyizhou** [comment]
Closing this for now. Feel free to reopen if it doesn't work.

**Comment by zhaotf16** [comment]
Thanks, I solve it by reducing my input shape from (2048,2048) to (512, 512)
I dont know why it works but it does
