### ISSUE TITLE
num_workers > 0 don't work on windows

### ISSUE THREAD

**Issue by Libaishun** [xingyizhou/CenterNet#649]
When setting num_workers > 0 in train_data_loader, it goes to error like "Can't pickle local object 'get_dataset.<locals>.Dataset".  Setting num_workers = 0 can skip this error, however it slows down the training process very much, how to settle this problem ?

**Comment by xingyizhou** [comment]
I haven't tried to train on Windows and can not provide helpful suggestions ...
