### ISSUE TITLE
gen_coco_extreme_points.py doesn't exist

### ISSUE THREAD

**Issue by y0un5** [xingyizhou/CenterNet#65]
Dataset preparation document says that run `gen_coco_extreme_points.py` for ExtremeNet, but I can't find it in `$CenterNet_ROOT/tools/`. Could you check this, please?

https://github.com/xingyizhou/CenterNet/blob/master/readme/DATA.md#dataset-preparation

```
[Optional] If you want to train ExtremeNet, generate extreme point annotation from segmentation:

cd $CenterNet_ROOT/tools/
python gen_coco_extreme_points.py
```

**Comment by xingyizhou** [comment]
You can check the file [here](https://github.com/xingyizhou/ExtremeNet/blob/master/tools/gen_coco_extreme_points.py).

**Comment by y0un5** [comment]
Thanks! I've copied the file to CenterNet sub-directory and found it works well with minor changes(directory path in the file).
