### ISSUE TITLE
scale augmentation tends to zoom image to larger size

### ISSUE THREAD

**Issue by Libaishun** [xingyizhou/CenterNet#650]
I set scale=0.4, input_w=input_h=608, then the image size augmentation range from int(608/(1+0.4))=434 to int(608/(1-0.4))=1013 according to the code, with random augmentation,  
I found the augmentated size tend to be (1013, 1013) very often.
Would this be bad augmentation trick?

**Comment by xingyizhou** [comment]
Thanks for your experiments. I haven't played with the augmentation hyper-parameters. They are inherited from CornerNet or human pose estimation projects. You are welcomed to share/ discuss your results!
