### ISSUE TITLE
About size Loss form, Confused

### ISSUE THREAD

**Issue by tangchen2** [xingyizhou/CenterNet#651]
First really appreciate the Great work! While i have some questions about the size loss, hope you could help me @xingyizhou 
Size Loss used in CenterNet is just L1 Loss, in this case, won't the scale of the object affect the final loss? For example, a small object (w=20, h=20), the predict size is w_hat  = 30, h_hat = 30, then the L1 loss is |30-20| + |30-20| = 20. While a large object (w = 300, h = 300), the predict size is w_hat = 310, h_hat = 310 and its L1 loss is |310-300| + |310-300| = 20. These two objects contribute the same loss however i think the small boject is predicted worse and should be punished more. L1 loss can't handle this situation, right? 
Besides, the large range of w, h may result in unstable loss, whick makes it hard to train, am i right ? 
I am a little confused about the size loss form in paper, hope someone could explain this, thanks so much!

**Comment by xingyizhou** [comment]
Thank you for your interest. You are correct. We did not handle this explicitly. For the unstable problem, we do have a loss weight for it (0.1). I do have tried other fancier losses but haven't observed a better performance yet.

**Comment by tangchen2** [comment]
Thank you for your reply! I will considier the loss again, maybe try logloss in size loss and check the performance.
Close it!
