### ISSUE TITLE
How to get center coordinates or location

### ISSUE THREAD

**Issue by xenc0d3r** [xingyizhou/CenterNet#652]
Hello everyone,

Does anyone know which method returns the center point value in terms of pixels or mm ?
I would like to know the location of the detected object in the image. I made some research through code but couldn't find it, all I get is bounding boxed objects.

Thank you..

**Comment by xingyizhou** [comment]
A simple way is to calculate the center in pixel from the bounding box by (x, y) = ((bbox[0] + bbox[2]) / 2, (bbox[1] + bbox[3]) / 2).

**Comment by xenc0d3r** [comment]
@xingyizhou thank you for the reply, it works.
