### ISSUE TITLE
Why in multi_pose_dla_1x.sh load model from ctdet_coco_dla_2x.pth?

### ISSUE THREAD

**Issue by laisimiao** [xingyizhou/CenterNet#653]
Question1: Why in `multi_pose_dla_1x.sh` load model from `ctdet_coco_dla_2x.pth`?  I thought their parameters(name or shape) are not exact same between ctdet task and multi_pose task? Or just load part of params because  `ctdet_coco_dla_2x.pth`  was trained early to gain?
Question2: If I now train a multi_pose task, I'd better load model like `multi_pose_dla_1x.pth` in the model zoo, am I right?
thanks for your reply!

**Comment by xingyizhou** [comment]
Thank you for your questions.
1: Only the heads are different. However this is indeed a wrong decision we made in the project. Training multi_pose from scratch would be ~3mAP better than finetune from detection. We will update the results.
2. Yes.
