### ISSUE TITLE
problem of using Soft_nms, does it works in the source code? 

### ISSUE THREAD

**Issue by guizilaile23** [xingyizhou/CenterNet#655]
in the detector of ctdet, we set to use soft_nms in testing, but the soft_nms could not be debug, and I see nothing return，and the soft_nms only return indicators, does the soft_nms change the sequence of the predictions?
 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/18462654/77044936-44c9b900-69fb-11ea-941c-1d97d0e3b599.png">

**Comment by xingyizhou** [comment]
It should be inplace. Feel free to print `results[j]` before and after this line to see if it changes.

**Comment by guizilaile23** [comment]
Thanks, it's work well.

**Comment by Alien1007** [comment]
@guizilaile23 Have you found correct changes before and after soft-nms? It seems that we only return the keep index and do not change predictions in the source code of soft-nms.  And I got same shape of predictions before and after thie line and code.

**Comment by Alien1007** [comment]
@xingyizhou @guizilaile23 I have understood that. Soft_NMS indeed modify the score and rank of predictions in-place. However, we do not discard those predictions with very low confidence score. Therefore, CenterNet can involve many predictions with very low confidence score in the final JSON file, though those low-confidence predictions do not affect mAP.
