### ISSUE TITLE
Train models

### ISSUE THREAD

**Issue by Gouiaa** [xingyizhou/CenterNet#66]
@xingyizhou, Hello is it possible to train the models on 1 GPU ? I see all scripts used 8 or 2 GPU

**Comment by xingyizhou** [comment]
Yes you can. You will need to linearly scale the learning rate and expect a linear scale of the training time then. It is suggested to play with Pascal VOC first if you only have one GPU.

**Comment by Gouiaa** [comment]
@xingyizhou Thanks. Could you mention the piece of code where you applied the data augmentation for pose estimation?
