### ISSUE TITLE
what data augmentation you use when training resnet?

### ISSUE THREAD

**Issue by hheavenknowss** [xingyizhou/CenterNet#666]
hello, I've noticed in parper that:" We use random ﬂip, random scaling (between 0.6 to 1.3),cropping,and color jittering as data augmentation,and use Adam [28] to optimize the overall objective",but in the code, I found that could not use crop and the scaling same time, so plz tell me about what data augmentation do you use when you training res18, thanks.

**Comment by xingyizhou** [comment]
Crop and scales are included in the affine transform function.
