### ISSUE TITLE
How to do object detection and pose estimation in the same inference？

### ISSUE THREAD

**Issue by 0x45f** [xingyizhou/CenterNet#667]

**Comment by xingyizhou** [comment]
Unfortunately, currently we do not support this feature.

**Comment by xjsxujingsong** [comment]
With pose estimation, you can get boundingbox directly. right?

**Comment by xingyizhou** [comment]
Yes we can get bounding box for persons. I am assuming the question here is to get keypoints for person and bounding boxes for other 79 categories.

**Comment by 0x45f** [comment]
> Yes we can get bounding box for persons. I am assuming the question here is to get keypoints for person and bounding boxes for other 79 categories.

Yes，i want to get keypoints for person and bounding boxes for other 79 categories.
Thank you for your reply

**Comment by ShihuaiXu** [comment]
How can we modify the code and get keypoints for person and bounding boxes for other 79 categories? @xingyizhou

**Comment by ShihuaiXu** [comment]
Sir, have you found the solution? @0x45f

**Comment by 0x45f** [comment]
> Sir, have you found the solution? @0x45f

I dont find solution, sorry

**Comment by ShihuaiXu** [comment]
> > Sir, have you found the solution? @0x45f
> 
> I dont find solution, sorry

thank you very much
