### ISSUE TITLE
Train only on centers 

### ISSUE THREAD

**Issue by mchagneux** [xingyizhou/CenterNet#669]
How do I train with ctdet without regressing the bboxes ? I only need to detect the centers.

**Comment by xingyizhou** [comment]
You can add `--off_weight 0 --wh_weight 0` in your training.

**Comment by mchagneux** [comment]
Okay thanks a lot!

**Comment by mchagneux** [comment]
I get the following error: 

"loss_stats[l].mean().item(), batch['input'].size(0))
AttributeError: 'int' object has no attribute 'mean'" 

Are you sure the code is ready to handle this case ? I find it surprising that only using these arguments can work. The outputs are suppoed to be 4 uplets with bbox coordinates so shouldn't I change that beforehand ? 

Thanks in advance

**Comment by xuduo35** [comment]
try setting off_weight and wh_weight to 0.00001, it cannot be totally zero.
