### ISSUE TITLE
Why classes interchanged?

### ISSUE THREAD

**Issue by mrkind** [xingyizhou/CenterNet#671]
In Centernet object detection,I defined 6 classes a,b,c,d,e,f.After running demo.py using trained weights,I found a "rename" type misclassification error,namely  a objects are tagged d ,b objects are tagged e , c objects are tagged f. d objects are tagged a,e objects are tagged b, f objects are tagged c.

a<->d  b<->e c<->f  

How could this happen?

**Comment by xingyizhou** [comment]
I have no idea about that. Visualizing custom datasets requires modifying `debug.py`. You will need to define the class name here yourself.

**Comment by mrkind** [comment]
OK
