### ISSUE TITLE
Train Dataset :KeyError: 2?

### ISSUE THREAD

**Issue by zhousaYolo** [xingyizhou/CenterNet#672]
(pytorch) D:\PycharmProjects\CenterNet-master\src>python main.py ctdet --exp_id MyDeFineresult --batch_size 4 --lr 1.25e-4  --gpus -1
Using tensorboardX
Fix size testing.
training chunk_sizes: [4]
The output will be saved to  D:\PycharmProjects\CenterNet-master\src\lib\..\..\exp\ctdet\MyDeFineresult
heads {'hm': 1, 'wh': 2, 'reg': 2}
Namespace(K=100, aggr_weight=0.0, agnostic_ex=False, arch='dla_34', aug_ddd=0.5, aug_rot=0, batch_size=4, cat_spec_wh=False, center_thresh=0.1, chunk_sizes=[4], data_dir='D:\\PycharmProjects\\CenterNet-master\\src\\lib\\..\\..\\data', dataset='ped', debug=0, debug_dir='D:\\PycharmProjects\\CenterNet-master\\src\\lib\\..\\..\\exp\\ctdet\\MyDeFineresult\\debug', debugger_theme='white', demo='', dense_hp=False, dense_wh=False, dep_weight=1, dim_weight=1, down_ratio=4, eval_oracle_dep=False, eval_oracle_hm=False, eval_oracle_hmhp=False, eval_oracle_hp_offset=False, eval_oracle_kps=False, eval_oracle_offset=False, eval_oracle_wh=False, exp_dir='D:\\PycharmProjects\\CenterNet-master\\src\\lib\\..\\..\\exp\\ctdet', exp_id='MyDeFineresult', fix_res=True, flip=0.5, flip_test=False, gpus=[-1], gpus_str='-1', head_conv=256, heads={'hm': 1, 'wh': 2, 'reg': 2}, hide_data_time=False, hm_hp=True, hm_hp_weight=1, hm_weight=1, hp_weight=1, input_h=512, input_res=512, input_w=512, keep_res=False, kitti_split='3dop', load_model='', lr=0.000125, lr_step=[90, 120], master_batch_size=4, mean=array([[[0.5095014 , 0.42827773, 0.38516736]]], dtype=float32), metric='loss', mse_loss=False, nms=False, no_color_aug=False, norm_wh=False, not_cuda_benchmark=False, not_hm_hp=False, not_prefetch_test=False, not_rand_crop=False, not_reg_bbox=False, not_reg_hp_offset=False, not_reg_offset=False, num_classes=1, num_epochs=10, num_iters=-1, num_stacks=1, num_workers=0, off_weight=1, output_h=128, output_res=128, output_w=128, pad=31, peak_thresh=0.2, print_iter=0, rect_mask=False, reg_bbox=True, reg_hp_offset=True, reg_loss='l1', reg_offset=True, resume=False, root_dir='D:\\PycharmProjects\\CenterNet-master\\src\\lib\\..\\..', rot_weight=1, rotate=0, save_all=False, save_dir='D:\\PycharmProjects\\CenterNet-master\\src\\lib\\..\\..\\exp\\ctdet\\MyDeFineresult', scale=0.4, scores_thresh=0.1, seed=317, shift=0.1, std=array([[[0.26929525, 0.24785739, 0.24371529]]], dtype=float32), task='ctdet', test=False, test_scales=[1.0], trainval=False, val_intervals=5, vis_thresh=0.3, wh_weight=0.1)
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Creating model...
Setting up data...
==> initializing coco 2017 val data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded val 80 samples
==> initializing coco 2017 train data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded train 200 samples
Starting training...
ctdet/MyDeFineresultTraceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "D:\PycharmProjects\CenterNet-master\src\lib\trains\base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "D:\PycharmProjects\CenterNet-master\src\lib\trains\base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 560, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\PycharmProjects\CenterNet-master\src\lib\datasets\sample\ctdet.py", line 102, in __getitem__
    cls_id = int(self.cat_ids[ann['category_id']])
KeyError: 2

**Comment by xingyizhou** [comment]
You will need to set `self.cat_ids` for your own dataset. It maps the `category_id` in your json file to a contiguous index.
