### ISSUE TITLE
module 'DCNv2.dcn_v2' has no attribute 'dcn_v2_cuda_forward'

### ISSUE THREAD

**Issue by winter2897** [xingyizhou/CenterNet#674]
I tried to implement CenterNet on Google Colab and encountered this error! Can someone help me! I think I have compiled deformable convolutional.
Link Colab Notebook: https://drive.google.com/open?id=1lnG6cBJXftIUG3_c4yZjkN3X043_ubeO

**Comment by zhangyi-student** [comment]
I also want to reproduce it on Colab, and a similar problem appears. Can I have a look at your Colab code?
