### ISSUE TITLE
Train cadet_hg model with custom dataset

### ISSUE THREAD

**Issue by neoyang0620** [xingyizhou/CenterNet#677]
Hi,

When I want to train my own dataset with hourglass model, it gave warning like:

"Drop parameter hm_t.0.0.conv.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset."

I download the ExtremeNet_500000.pkl and use your script to preprocess it. Will it affect the final results?

**Comment by xingyizhou** [comment]
That's OK. The dropped parameters are from the extreme point heatmaps. They need to be dropped.
