### ISSUE TITLE
Question: Is CUDA mandatory to run CenterNet?

### ISSUE THREAD

**Issue by santo4ul** [xingyizhou/CenterNet#679]
Hi, Based on the instructions to build CenterNet, I see CUDA libs are required. 

Is it possible to run CenterNet on CPU, without installing any CUDA libs? 

Thank you.

**Comment by xingyizhou** [comment]
Unfortunately, CUDA is required.

**Comment by santo4ul** [comment]
Thanks @xingyizhou
