### ISSUE TITLE
why PD mAP is  low in multi_pose task?

### ISSUE THREAD

**Issue by Dantju** [xingyizhou/CenterNet#681]
@xingyizhou I train person detection on ctdet task,and get map 56%,and i also train multi_pose,the PD result is 49% in multi_pose task,compare to ctdet task,the detection result drop 7%, I want to know to how to train PE but PD result is not drop a lot.I try to  train mulit_pose task with set PE' loss weight to 0,but PD result also 49%,I confused

**Comment by xingyizhou** [comment]
I didn't observe that. In my experiments both got similar person box AP. Please make sure you haven't modified the code. If so, can you provide your command to run these experiments?

**Comment by Dantju** [comment]
@xingyizhou ,I test your DLA-34 multi pose model get PD 49.1% and PE 59.2%,I just train Person detection and get result 56%, what i modified is change  classed number from 80 to 1,can you update person detection model？
