### ISSUE TITLE
Why do the author modify DLA-34 and ResNet? What if using them as if?

### ISSUE THREAD

**Issue by sisrfeng** [xingyizhou/CenterNet#685]
Many thanks!

**Comment by xingyizhou** [comment]
Clearly because the modified versions worked better. The original versions require feature pyramid outputs to work better. I will update these results within (hopefully) a month.

**Comment by sisrfeng** [comment]
Hi，would you mind updating the results? Is the speed of your DLA with DCN  approximately the same as that of the original versions?

**Comment by sisrfeng** [comment]
Why do you think of DCN while modifing DLA? Is DCN so strong that it can benefit many architecture ?
thx!
