### ISSUE TITLE
Is it possible to do no classification, only bounding box regression?

### ISSUE THREAD

**Issue by MrunaliniN** [xingyizhou/CenterNet#689]
Hi,
Is it possible to do only object detection/bounding box regression without doing any classification? 
My project does not need to classify the object, but, just identify it. Setting the classes to 1 is one option, but does not give me the speed advantage I am looking for. Would setting head_conv to 0 or setting num_classes to 0 help? 
Kindly advice... looking for urgent help

**Comment by ammaddd** [comment]
"My project does not need to classify the object, but, just identify it." so this means you have a class that is the object. So technically you have 1 class. Set num_classes as 1. and in your data set just replace all the classes examples car,van etc to object so you will have 1 class now.

**Comment by MrunaliniN** [comment]
That is an option. Thanks. I am looking to totally remove the classification part though.

**Comment by ammaddd** [comment]
Buddy identification is classification. Lets say you need to identify all the stars in space. You don't need to classify what type of star is (just identify). Then it means you are doing classification (but in this case it is binary classification). You are actually classifying between background and stars. so from your question you need to "identify" an object means you need to classify an object as background vs object. If you see the src code when you pass argument as num classes =4 lets say ['car','van','truck','bus'] basically code adds another class which is background.

**Comment by xingyizhou** [comment]
I agree with @ammaddd .
