### ISSUE TITLE
How to continue training on checkpoints?

### ISSUE THREAD

**Issue by mrkind** [xingyizhou/CenterNet#690]
After obtaining a model file model_best.pth,how to continue training on model_best.pth?Further optimizing its parameters?

**Comment by ammaddd** [comment]
you can resume from last checkpoint by just passing argument --resume .Dont pass load_model when resuming

**Comment by mrkind** [comment]
THX，since i will resume from modelbest not modellast maybe i will use --resume and --load model simultaneously

**Comment by ammaddd** [comment]
> THX，since i will resume from modelbest not modellast maybe i will use --resume and --load model simultaneously

Technically just rename model_best as model_last. Don't load_model otherwise epochs numbering will be messy

**Comment by mrkind** [comment]
ok,a good idea!

**Comment by xingyizhou** [comment]
Thanks @ammaddd . Closing as the issue was solved.
