### ISSUE TITLE
Append surffix in saving detection results

### ISSUE THREAD

**Issue by mrkind** [xingyizhou/CenterNet#691]
By adding the following line at the end of  src/lib/detectors/ctdet.py
 
debugger.save_all_imgs(path='/media/deep1/My Passport/dy2test', genID=True)

Result pictures named 0ctdet.png , 1ctdet.png ,...  were saved .However I think it's better to make the names of the result pictures composed of the names of the original pictures with a suffix attached.

For instance original_picture_name1_r.png , original_picture_name2_r.png,...

How to achieve this?

**Comment by xingyizhou** [comment]
You can just add the name when calling cv2.imsave.
