### ISSUE TITLE
cuda 10.0 + pytorch=1.1

### ISSUE THREAD

**Issue by DangerousY** [xingyizhou/CenterNet#698]
When I follow #636 question, using cuda10.0 and pytorch1.1 to implement this.
I get some problems: such as 
RuntimeError: Not compiled with GPU support
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d 
....
frame #9: THPFunction_apply

**Comment by cocacola0** [comment]
What was the solution ?

**Comment by rajatsainju** [comment]
Anyone with the solution to this? @xingyizhou

**Comment by lhyfst** [comment]
It might because you compiled something(maybe DCN) in an environment without GPU, but run it in an environment with GPU.
