### ISSUE TITLE
focal loss

### ISSUE THREAD

**Issue by DangerousY** [xingyizhou/CenterNet#699]
When i use focal loss, not mse_loss, the map will only 22%. However, the MAP will arrive 86% when using mse_loss. And I set hm_gauss = 4. 
How to solve the problem, tks!
And did the code default only implement with MSELoss rather than FocalLoss ?
self.parser.add_argument('--mse_loss', action='store_true',
                             help='use mse loss or focal loss to train '
                                  'keypoint heatmaps.')
I change action = 'store_true' to action = 'store_false'; then set hm_gauss = 4; Then the accuracy is low.

**Comment by DangerousY** [comment]
And did the code default only implement with MSELoss rather than FocalLoss ?

**Comment by xingyizhou** [comment]
That's interesting. Not sure what dataset you are using, but focal loss works much better in COCO. It can be reasonable if you are only detecting one object category and every training image contains that category, where there is no significant "imbalance" problem in the loss.

**Comment by DangerousY** [comment]
My dataset has 4 classes, if I want to use focal loss. Does that mean I just change the —mse_loss’s action=‘store_true’ to ‘store_false’ in opts.py.  Thanks for your reply!

**Comment by DangerousY** [comment]
> That's interesting. Not sure what dataset you are using, but focal loss works much better in COCO. It can be reasonable if you are only detecting one object category and every training image contains that category, where there is no significant "imbalance" problem in the loss.

My dataset has 4 classes, if I want to use focal loss. Does that mean I just change the —mse_loss’s action=‘store_true’ to ‘store_false’ in opts.py. Thanks for your reply!

**Comment by xingyizhou** [comment]
I haven't used `store_false` so I am not sure about your question. The default option is using focal loss, you don't need to change anything. If you add `--mse_loss` in your command, it will turn to mse loss.

**Comment by DangerousY** [comment]
> 
> 
> I haven't used `store_false` so I am not sure about your question. The default option is using focal loss, you don't need to change anything. If you add `--mse_loss` in your command, it will turn to mse loss.

Ok, tky!
