### ISSUE TITLE
color augment

### ISSUE THREAD

**Issue by Apostatee** [xingyizhou/CenterNet#702]
Hi, After the color_aug method, the pixel value could be greater than 255 or less than 0, and you did not deal with it, I wonder it was done on purpose or it's just a tiny bug that you ignored?

**Comment by Apostatee** [comment]
`def blend_(alpha, image1, image2):
    image1 *= alpha
    image2 *= (1 - alpha)
    image1 += image2

def saturation_(data_rng, image, gs, gs_mean, var):
    alpha = 1. + data_rng.uniform(low=-var, high=var)
    blend_(alpha, image, gs[:, :, None])

def brightness_(data_rng, image, gs, gs_mean, var):
    alpha = 1. + data_rng.uniform(low=-var, high=var)
    image *= alpha`

**Comment by xingyizhou** [comment]
Thanks for pointing this out. It's a tiny bug I ignored. However I still want to ignore it since the color augmentation itself affects little on the performance.

**Comment by Apostatee** [comment]
Ok, Thanks

**Comment by sisrfeng** [comment]
> color augmentation

I use your coco_hourglass on my own picture whose contrast is stange. After changing the contrast, the picture looks less strange, and some FN become TP.    
Is the model you trained not robust to color jittering?

**Comment by sisrfeng** [comment]
> the pixel value could be greater than 255 or less than 0

 Have you fixed the bug?adding  a clip function can help?
