### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 576-577: invalid continuation byte

### ISSUE THREAD

**Issue by XinyingZheng** [xingyizhou/CenterNet#707]
who can tell me i can do what to correct  this error ,thanks very much!

**Comment by xingyizhou** [comment]
I have no idea. Can you show your command and the full log?

**Comment by XinyingZheng** [comment]
thank you very much,I have solved that error, because there are some Chinese comments of garish code in the program. However, I encountered a problem when compiling DCNv2 to run sh make.sh. Could you please help me check it.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xingyi Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 凌晨5:49
收件人:&nbsp;"xingyizhou/CenterNet"<CenterNet@noreply.github.com&gt;;
抄送:&nbsp;"1475646392"<1475646392@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xingyizhou/CenterNet] UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 576-577: invalid continuation byte (#707)





 
I have no idea. Can you show your command and the full log?

**Comment by XinyingZheng** [comment]
my code can run correctly now,thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xingyi Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 凌晨5:49
收件人:&nbsp;"xingyizhou/CenterNet"<CenterNet@noreply.github.com&gt;;
抄送:&nbsp;"1475646392"<1475646392@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xingyizhou/CenterNet] UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 576-577: invalid continuation byte (#707)





 
I have no idea. Can you show your command and the full log?
