### ISSUE TITLE
confidence score

### ISSUE THREAD

**Issue by xiexuliunian** [xingyizhou/CenterNet#709]
Thanks for your work!!!

Can you give me some advice for make the detec result confidence score more higher?
When I use retinaNet the score is usually over 0.95,but use centernet even the trained epoch reach 200,the detec confidence score is about 0.5-0.8......,May be too low

**Comment by xingyizhou** [comment]
That's a good point, however I have no good suggestions except manually multiplying the score by 2. One conjecture is that RetinaNet defines "hard" positive and negative, while we define "soft" ones. Anyway it should not matter for the evaluation, where only the ranking matters.

**Comment by xiexuliunian** [comment]
Thanks!!!
