### ISSUE TITLE
The missing annotation problem

### ISSUE THREAD

**Issue by pengsida** [xingyizhou/CenterNet#71]
Hi, Xingyi,

Thanks for your great work.
I notice that some images in Coco are not fully annotated.
![image](https://user-images.githubusercontent.com/11582122/57743830-4353a400-76f9-11e9-8684-339fe7ec6be7.png)

For such images, simply applying focal loss penalizes the true positive predictions, as suggested by OpenPose. However, I cannot find how your code deal with the problem.
Could you tell me if the problem affects a lot?

Another problem is that your bounding box for person class includes the crowd, which is not consistent with the semantic definition with a single person. The following heatmap corresponds to persons in the image above.
![image](https://user-images.githubusercontent.com/11582122/57743999-fb814c80-76f9-11e9-9906-d46c9c596535.png)

Have you noticed this problem and experimented how much it affects the performance.

Thanks for your great work again.

**Comment by xingyizhou** [comment]
Hi, I am not aware of the problem of missing annotation in COCO and can tell if this is a problem. Feel free to refer me the code if you found other implementations have ideas to handle this. I am aware of the crowd thing, we follow CornerNet to include them in training. I haven't tried excluding them.

**Comment by pengsida** [comment]
Like the implementation of OpenPose:
1. generate mask: https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/training/genCOCOMask.m
2. supervise only on annotated persons: https://github.com/tensorboy/pytorch_Realtime_Multi-Person_Pose_Estimation/blob/master/train_VGG19.py#L105

Section 2.1 in OpenPose refers this problem:
![image](https://user-images.githubusercontent.com/11582122/57831034-92c3ce00-77e6-11e9-960a-cea0beb632bc.png)

I don't have much experience on keypoint detection, while you are an expert on the literature. Have you noticed the problem when training human keypoints.

**Comment by pengsida** [comment]
Today I accidentally figure out this problem.
The data without annotation, or coarse annotation data, is marked as 'iscrowd=1' in coco.
![image](https://user-images.githubusercontent.com/11582122/58745327-33bab600-8482-11e9-8f93-3de5230d0533.png)

**Comment by sisrfeng** [comment]
> Today I accidentally figure out this problem.
> The data without annotation, or coarse annotation data, is marked as 'iscrowd=1' in coco.
> ![image](https://user-images.githubusercontent.com/11582122/58745327-33bab600-8482-11e9-8f93-3de5230d0533.png)

Hi，have you got the conclusion for the problem?
I find the same problem while visualizing the cars, bus, and trucks.
Some area, where there are many cars, is labeled as a car with "iscrowd" label. I think it will mislead the model if not filtering the large "car".
But in coco.py provided by Xingyi Zhou, "iscrowd" is not handled.

**Comment by pengsida** [comment]
I filtered the annotations with `iscrowd=1`.

**Comment by sisrfeng** [comment]
Some pictures with iscrowd=1 leave many objects unlabeled. I think using such picture will increase the FN. Do you filtered the pictures with iscrowd=1?

**Comment by pengsida** [comment]
Good point.
I did not filter the pictures with `iscrowd=1`.
I think that it is better to filter the pictures with `iscrowd=1`.
