### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by qianchenghao** [xingyizhou/CenterNet#711]
when i running the command 
python demo.py ctdet --demo /home/yohji.qian/CenterNet/images --load_model ../models/ctdet_coco_hg.pth
It runs well at first couple lines with：
----------------------------start
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/yohji.qian/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
and then：
No param ida_up.proj_2.conv.conv_offset_mask.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.up_2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.node_2.actf.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.node_2.actf.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have
correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.node_2.actf.0.running_mean.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.node_2.actf.0.running_var.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.node_2.actf.0.num_batches_tracked.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.node_2.conv.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have
correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.node_2.conv.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.node_2.conv.conv_offset_mask.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param ida_up.node_2.conv.conv_offset_mask.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param hm.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param hm.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param hm.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param hm.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param wh.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param wh.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param wh.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param wh.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param reg.0.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param reg.0.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param reg.2.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
No param reg.2.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
段错误

There is no more information and i don't what does the “段错误” came from.

Currently using the torch=1.2.0,torchvision=0.4.0,cuda=10.0.

**Comment by xingyizhou** [comment]
Can you try `--arch hourglass` first? However I don't know there the segment fault is from. Maybe try torch 0.4.1, where the model is trained with.

**Comment by qianchenghao** [comment]
I tried and not working.Then i switch from gcc 4.8.5 to gcc 4.9.2,finally works.

**Comment by qianchenghao** [comment]
> I tried and not working.Then i switch from gcc 4.8.5 to gcc 4.9.2,finally works.

I guess it's  gcc compatible with corresponding torch version when make DCNv2.
