### ISSUE TITLE
when i change aug_rot=0.5, it seems not work?

### ISSUE THREAD

**Issue by zhangcj13** [xingyizhou/CenterNet#712]
RuntimeWarning: divide by zero encountered in log
  wh[k] = np.log(1. * w / 4), np.log(1. * h / 4)

Does this augmention not supported in multi_pose training work?

**Comment by xingyizhou** [comment]
It doesn't work for me too, and is not included in the paper. I don't understand the runtimewarning, it seems the log is not from the original code.

**Comment by zhangcj13** [comment]
HI @xingyizhou 
this code is from chenjun2hao/CenterFace.pytorch. I check  it ,indeed, it is not from the original code .now i rotate the imgs in the first place before loading to training instead of this param. 
whatever, thank you for your reply.
