### ISSUE TITLE
where is the depth value of ddd?

### ISSUE THREAD

**Issue by GuoChuan1314** [xingyizhou/CenterNet#713]
I want to find the depth value of ddd in the program.But I can't find the value.Can you tell me where is it? which one code is it?Thank you very much.

**Comment by xingyizhou** [comment]
It's [here](https://github.com/xingyizhou/CenterNet/blob/master/src/lib/utils/post_process.py#L61).

**Comment by GuoChuan1314** [comment]
thank you very much.I've been working on your program for a long time, starting from scratch. I'm sorry to trouble you。

**Comment by xingyizhou** [comment]
Thank you for your interest in our project! Closing this now. Feel free to open an issue if you have further questions.
