### ISSUE TITLE
How can I get a cpu mode model without deformable convolution

### ISSUE THREAD

**Issue by macqueen09** [xingyizhou/CenterNet#714]
I know deformable convolution must in GPU mode. 
So , how can I train a CenterNet ( backbone res_18 )  **on GPU without deformable convolution**  , so I can run that model in a CPU laptop?
I just want run a light CenterNet in a laptop without GPU

**Comment by macqueen09** [comment]
sorry . I find if you use res_18 or dla34 , it hasn't a deformable convolution ， and then you can delate 'cuda' code in py file. such as ```torch.cuda.synchronize()``` in file ```src/lib/base_detector.py``` 
or ```from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn``` in  ```src/lib/models/model.py``` **and so on**.
after that I can run demo.py on res_18 detection . It cost 2.2 seconds per images (512x512)on my i7 8565U   CPU mode.

**Comment by macqueen09** [comment]
torch.cuda.synchronize() is use for waiting result . you can just use a ```print(" ",end='')``` instead to wait result without GPU.

**Comment by macqueen09** [comment]
Thanks a lot

**Comment by imchwan** [comment]
> sorry . I find if you use res_18 or dla34 , it hasn't a deformable convolution ， and then you can delate 'cuda' code in py file. such as `torch.cuda.synchronize()` in file `src/lib/base_detector.py`
> or `from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn` in `src/lib/models/model.py` **and so on**.
> after that I can run demo.py on res_18 detection . It cost 2.2 seconds per images (512x512)on my i7 8565U CPU mode.

@macqueen09 
How did you manage to remove deformable convolution networks(DCN) for dla34?

It looks like res_18 is using `from .networks.msra_resnet import get_pose_net`
and dla_34 is using `from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn`.
res_18 hasn't  DCN, however, dla34 does.

Did you use 'from .networks.dlav0 import get_pose_net as get_dlav0' instead?

**Comment by macqueen09** [comment]
@imchwan , sorry, I hasn't try on dlav0. But I find DCN has a CPU mode by official [https://github.com/CharlesShang/DCNv2](https://github.com/CharlesShang/DCNv2). we can use this replace DCN fold

**Comment by xiweiya** [comment]
hello,may i ask you a question? 
I want to confirm that resnet18 does not use deformable convolution and dla use deformable convolution? 
because the default code fc = DCN(self.inplanes.......)，so i want to confirm that point.
thanks a lot.
