### ISSUE TITLE
Paper：论文里Loss为什么用像素来回归呀

### ISSUE THREAD

**Issue by macqueen09** [xingyizhou/CenterNet#715]
Q1:4.2节中，In paper “4.2 We considered the pose as a k x 2-dimensional property of the center point , and parametrize each keypoint bu an offset to the center point . **we directly regress to the joint offsets(in pixels) with an L1 loss** ”
Why use pixels not a rate , that way vary unusual
问下姿态估计部分的归回，为什么要用像素来回归，这样好像就会缺少一些尺度不变性吧
Q2:4节中，Lsize损失函数也是使用的像素来回归，使用超参λ=0.1调整，很少见使用像素直接回归（当然，有可能是我见的少）

**Comment by xingyizhou** [comment]
I do have tried other alternatives (log, normalized to 0~1), and find they perform worse or the same as raw pixel. The raw pixel version is the simplest for me.

**Comment by macqueen09** [comment]
Thanks very much.
Deep Learning 还真是“实践出真知”
