### ISSUE TITLE
Paper:论文创新点中无需NMS的疑惑

### ISSUE THREAD

**Issue by macqueen09** [xingyizhou/CenterNet#716]
创新点中说无需NMS， 我不太懂，two-stage中，一个目标上面好多个IOU>0.7的anchor都是正样本，训练模型。模型inference时一个目标可能检测出多个BBox，因而需要NMS。
CenterNet中训练时一个目标只有一个正样本（中心点），测试时heatmap上有几个峰值就算是几个目标是吧。
也没那么精确一个目标就输出一个峰值吧。我在测试时也发现某些图片中一个目标会输出两个很接近的BBox ， inference时用不用NMS，是说明heatmap上一个目标就真能完全输出一个峰值嘛？
一个目标inference时不会出现多个峰值嘛？

**Comment by macqueen09** [comment]
怕描述不清楚，多加一些描述。一个目标inference时如果出现多个比较近的峰值，那预测出来肯定是多个接近的BBox是吧。此时就需要NMS了，是吧。
所以不用NMS的保证是一个目标基本能预测出仅一个峰值嘛？
论文中峰值指的是8邻域里的峰值是吧。3x3大小里中间像素最大，128x128大小的heatmap里一个目标是如何保证只预测数只有一个峰值的

**Comment by macqueen09** [comment]
Focal Loss的使用应该是使得周围像素被难以预测为峰值，减少了一个目标输出多个峰值的可能。不过还是没法保证完全丢弃NMS，模型是如何做到检测一个人，只输出一个峰值的呢？要知道像人这种非刚体，会有差异很大的姿态，甚至有的BBox中心点在肚子，当人斜着弯腰时有的中心点甚至落在背景上，如何保证无须NMS只预测出一个峰值

**Comment by xiaoLiuxiaoLiuxiaoLiu** [comment]
是这样的兄嘚。输出heatmap还要接一个3x3的maxpooling的操作进行训练,  然后你会发现topk的置信值虽然低了，但是推断的时候直接输出heatmap（不接maxpooling），基本只剩一个点了。

**Comment by xingyizhou** [comment]
It does happens that the model will predict multiple peaks for large objects. In this case NMS is helpful. We have a section in our paper showing applying NMS afterward will further increase the performance by ~0.5mAP.

**Comment by macqueen09** [comment]
Thank you for your reply .Your work is really exciting .  @xingyizhou 
那我大致得出这么一个结论，由于模型Loss设置得合理，采取Focal Loss类似的损失函数，对目标中心周围的像素点被预测为峰值有抑制作用，使得绝大部分检测结果无须NMS即为较好结果。

**Comment by xingyizhou** [comment]
I agree. Closing this for now. Feel free to reopen.

**Comment by sisrfeng** [comment]
NMS To verify that IoU based NMS is not needed for
CenterNet, we ran it as a post-processing step on our
predictions. For DLA-34 (flip-test), the AP improves from
39.2% to 39.7%. For Hourglass-104, the AP stays at
42.2%. Given the minor impact, we do not use it.

**Comment by macqueen09** [comment]
@sisrfeng Thank you for your answer. 
Yes, it is so from the result. 
What I was more concerned about before was why the NMS could be removed in principle.

**Comment by igo312** [comment]
It also confuses me actually. 
Using the maxpooling operation doesn't mean that only save the center pixel when it is larger than 8 neighbouring pixel.
In my mind,maxpooling will asign the maxmium value of the window  to the center. Therefore there will be multiple peaks in objects.

What I have done is  simply add maxpooling on heatmap then output. 

here's my result. the shape of output is `(152,152)`  and the ship should not be **the large object** as other says right?
the above is the heatmap before maxpooing, below is the heatmap after maxpooing
![1](https://user-images.githubusercontent.com/28484395/100514194-a4dd4580-31ad-11eb-954a-cfa952571780.png)

sorry for bothering you @xingyizhou, but hoping for your response

**Comment by NeuZhangQiang** [comment]
@xiaoLiuxiaoLiuxiaoLiu 不明白你这里的意思：输出heatmap还要接一个3x3的maxpooling的操作进行训练。
CenterNet的heatmap，不是直接计算FocalLoss么？你所谓的接一个3x3的maxpooling的操作进行训练，能否告诉我在代码的哪一部分吗？
另外，我对inference还是有点不清楚，文章里面说，找到极值点，然后取前100个。所以，一张图最后会出现100个框？假如一张图只有1个目标呢？那出来100个岂不是错的很离谱。

还是说，heatmap最后就只出现一个峰值，所以所谓的前100个峰值，也只有一个，是这样吗？

**Comment by zxk19981227** [comment]
我也遇到了这个问题，在CenterNet中遇到前100个峰全都有值的情况。
