### ISSUE TITLE
It there some problem with ctdet_coco_dla_2x.pth?

### ISSUE THREAD

**Issue by mengzhi2** [xingyizhou/CenterNet#717]
The result of ctdet_coco_dla_2x.pth is as following.
![0ctdet](https://user-images.githubusercontent.com/57434241/82778960-de936380-9e8d-11ea-99fe-f4901e68354b.png)

I tried another model, it worked. The installation seems have no problem.
So I re-downloaded this model, but problem still exists.

**Comment by xingyizhou** [comment]
This seems because the last layer of the model is not correctly loaded. Have you seen any "skip loading xxx" in the log? If so, please make sure you followed the instruction. Or show your command to run the code here if it still doesn't work.

**Comment by mengzhi2** [comment]
Thanks so much. Problem solved.
