### ISSUE TITLE
请问一下，可以把计算数据集均值、方差、特征值和特征向量的代码发给我学习一下吗？

### ISSUE THREAD

**Issue by songyuc** [xingyizhou/CenterNet#725]
尊敬的开发者，你好，
我在你的代码中看到，在做数据处理时，你使用了数据集的均值、方差、特征值和特征向量这些参数；
![图片](https://user-images.githubusercontent.com/27288110/83393263-115ad000-a429-11ea-9d3a-c6f5cc60339c.png)
由于我想把你的代码适配到我自己的数据集上，但是我不太会怎么获得这个数据集的参数，你有计算这些参数的代码可以给我学习一下吗？

期待你的回复！

**Comment by xingyizhou** [comment]
I don't know how to compute these too. They are from CornerNet. However I think just use mean = (0.5, 0.5, 0.5) and std = (1, 1, 1) should be fine.

**Comment by songyuc** [comment]
Hi, @xingyizhou, thanks for your reponse and guide!

**Comment by xiaqing10** [comment]
`
for idx in range(len(pathDir)):
    filename = pathDir[idx]
    img = imread(os.path.join(filepath, filename)) / 255.0
    R_channel = R_channel + np.sum((img[:, :, 0] - R_mean) ** 2)
    G_channel = G_channel + np.sum((img[:, :, 1] - G_mean) ** 2)
    B_channel = B_channel + np.sum((img[:, :, 2] - B_mean) ** 2)
 
R_var = np.sqrt(R_channel / num)
G_var = np.sqrt(G_channel / num)
B_var = np.sqrt(B_channel / num)
print("R_mean is %f, G_mean is %f, B_mean is %f" % (R_mean, G_mean, B_mean))
print("R_var is %f, G_var is %f, B_var is %f" % (R_var, G_var, B_var))`
