### ISSUE TITLE
Why train on affine transformed image rather than original image?

### ISSUE THREAD

**Issue by liuchang8am** [xingyizhou/CenterNet#73]
I'm refering to line 70 - 75 here:
https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/sample/ctdet.py#L70

**Comment by liuchang8am** [comment]
I see it's for data augmentation.

**Comment by 92ypli** [comment]
Same question?

**Comment by liuchang8am** [comment]
> Same question?

I think the affine transform can be omitted, given the unnecessary transformation when W != H.
