### ISSUE TITLE
I want a judgmental basis like gradcam's.

### ISSUE THREAD

**Issue by kotamumu** [xingyizhou/CenterNet#731]
Is the KEY POINT HEATMAP like GRAD-CAM in which the basis for the decision is visualized?
If not, could you tell me how to process it like GRADCAM?

**Comment by xingyizhou** [comment]
What is gradcam?

**Comment by kotamumu** [comment]
It's a way of using a gradient to show which places cnn has looked and made decisions.
Could centernet's keypoint heat map be such a decision?
I'm sorry. I'm a newbie and I think I'm asking a terrible question.

**Comment by DreamRiverForever** [comment]
> Is the KEY POINT HEATMAP like GRAD-CAM in which the basis for the decision is visualized?
> If not, could you tell me how to process it like GRADCAM?

Hello, have you implemented gradcam of centernet?

**Comment by engrjav** [comment]
@kotamumu  @DreamRiverForever  i am also looking for the same answer. Is center net heat map same as grad cam ? can you guide
