### ISSUE TITLE
train wrong

### ISSUE THREAD

**Issue by GuoChuan1314** [xingyizhou/CenterNet#733]
FileNotFoundError: [Errno 2] No such file or directory: '../../data/kitti//annotations/kitti_3dop_train.json'
Where is the kitti_3dop_train.json?Can you send me the data of kitti which is necessary in the program.My emal is guochuan218@163.com

**Comment by xingyizhou** [comment]
It is [here](https://github.com/xingyizhou/CenterNet/blob/master/readme/DATA.md).
