### ISSUE TITLE
num_classes num_joints 

### ISSUE THREAD

**Issue by lijain** [xingyizhou/CenterNet#736]
First of all, thank you for your sharing. I would like to ask about my prediction of multiple objectives. Each type of target has one center point and five corners. Don't know multi_ What parameters can I change in the pose code to predict? Thank you

**Comment by xingyizhou** [comment]
The "five" corner corresponds to `num_joints`. However I will suggest not use multi_pose but write your own `task`. You will also need to change the flip correspondence too.

**Comment by lijain** [comment]
OK, thank you for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xingyi Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 凌晨3:09
收件人:&nbsp;"xingyizhou/CenterNet"<CenterNet@noreply.github.com&gt;;
抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xingyizhou/CenterNet] num_classes num_joints  (#736)





 
The "five" corner corresponds to num_joints. However I will suggest not use multi_pose but write your own task. You will also need to change the flip correspondence too.
