### ISSUE TITLE
what's the benefit of hm_disturb\lost_disturb\fp_disturb?

### ISSUE THREAD

**Issue by lrjbdss** [xingyizhou/CenterNet#747]
没想明白,感觉hm_disturb只会让label不再精确,但这并不是好事呀,希望大佬能给解释下

**Comment by xingyizhou** [comment]
They are used to simulate the errors during test. If not doing that, the heatmap output may tend to just copy the input heatmap and ignore the image in training. This is not desired in testing when you don't have the ground truth.

**Comment by lrjbdss** [comment]
对哦,这个不是用来生成label,是生成pre_hm的.明白了,谢谢
