### ISSUE TITLE
Why doesn't  the author add --trainval in the test experiment? How can you make the split become test?

### ISSUE THREAD

**Issue by sisrfeng** [xingyizhou/CenterNet#761]
https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/experiments/ctdet_coco_dla_2x.sh#L7

In my experiment,  split  will be val when I run test.py without  --trainval .  After adding --trainval , the test.json is loaded.
Why do you use val while testing?

thx!

**Comment by xingyizhou** [comment]
Adding `--trainval` is to use train+val for training and test for testing. This is used only when you want to submit the results to the test server.

**Comment by sisrfeng** [comment]
Oh I see, coco test set is not provided.
My own dataset in coco format has test set, so I took it for guarantee.
感谢大佬拔冗回复silly question
