### ISSUE TITLE
Couldn't train multi_pose model

### ISSUE THREAD

**Issue by tungedng2710** [xingyizhou/CenterNet#799]
I have run main.py to train your multi_pose model by the following command:
`python main.py multi_pose --exp_id coco_dla --batch_size 8 --master_batch 15 --lr 1.25e-4  --gpus 0`
but it returns that error:
`AttributeError: type object 'Dataset' has no attribute 'flip_idx'`
(I have trained `ctdet` and didn't have any problems)

**Comment by xingyizhou** [comment]
Hi,
  You will need to use `--dataset coco_hp` for human pose estimation. By default, it uses the COCO detection dataset.

**Comment by tungedng2710** [comment]
Thanks a lot!
