### ISSUE TITLE
memory is increaing when training

### ISSUE THREAD

**Issue by 20143698lhy** [xingyizhou/CenterNet#80]
memory is increaing when training,
![image](https://user-images.githubusercontent.com/31585212/57918164-c6772480-78c8-11e9-8080-73d84ca60a38.png)

I output the memory, but i can't find out where is the increaing memory, can you help me ?
thanks!

**Comment by xingyizhou** [comment]
We also observed the memory is increasing slightly during training, but we didn't find why. It might be related to the GPU type. You can decrease your batch size slightly if it doesn't work.
