### ISSUE TITLE
Is the actual batch size 29 or 24 for Hourglass?

### ISSUE THREAD

**Issue by sisrfeng** [xingyizhou/CenterNet#811]
> For Hourglass-104, we follow ExtremeNet [61] and use batch-size 29 (on 5 GPUs, with master GPU batch-size 4).
> 
> ExtremeNet:
> finetuned from a pre-trained CornerNet model with randomly initialized head layers on 5 GPUs for 250k
> iterations with a batch size of 24.

Is the actual batch size 29 or 24?  
Any typo?
Thx!

**Comment by sisrfeng** [comment]
in CenterNet/experiments/ctdet_coco_hg.sh:
cd src
# train
python main.py ctdet --exp_id coco_hg --arch hourglass --batch_size 24 --master_batch 4 --lr 2.5e-4 --load_model ../models/ExtremeNet_500000.pth --gpus 0,1,2,3,4

I think `use batch-size 29` is a typo.  
--batch_size 24

**Comment by xingyizhou** [comment]
Thanks for pointing out the issue. You are correct, it should be 24.
