### ISSUE TITLE
soft_nms

### ISSUE THREAD

**Issue by wshj2020** [xingyizhou/CenterNet#814]
Hi Mr. Zhou, I have a problem in test, did you use the softnms in the test. from my point, the function returns a array of index,but anywhere else did not use it .

**Comment by thomasstats** [comment]
One of the main points of this whole thin gis to not use NMS

**Comment by wshj2020** [comment]
Soft_nms returned index, where used the index ?

**Comment by ShawnNew** [comment]
There is a maxpooling-like operation (peak of keypoint) to alternate nms when decoding hm output.

**Comment by wshj2020** [comment]
I have got it, thank you ~

**Comment by xingyizhou** [comment]
We didn't use soft nms in CenterNet. The codebase also supports running ExtremeNet, which used soft nms.

**Comment by wwwht** [comment]
I found if not used nms or softnms, It exists many overlap bbox in inference. how to fix this problem.
