### ISSUE TITLE
Why the bias of cls conv is not set to -2.19 in msra_resnet

### ISSUE THREAD

**Issue by urbaneman** [xingyizhou/CenterNet#826]
Hi, @xingyizhou ,thanks for your great work.

I noticed that many of the detection networks were set up cls conv is set to -2.19, and the -2.19 is the same value with reference to focal loss & cornnet. 

` fc[-1].bias.data.fill_(-2.19)`

https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/src/lib/models/networks/resnet_dcn.py#L166

but not set up in `msra_resnet.py`: 

https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/src/lib/models/networks/msra_resnet.py#L150

What is the reason for incorrect bais initialization? Is the effect unsatisfactory?

Waiting for your reply, thanks, again.

**Comment by xingyizhou** [comment]
Hi,
  This follows CornerNet, which is from -log(0.1 / (1-0.1)). This makes the initialization sigmoid(-2.19) = 0.1. Actually this is not a principled hyper-parameter at all. You will find a slight improvement if you use -4.6 (initial value 0.01).

**Comment by urbaneman** [comment]
> Hi,
> This follows CornerNet, which is from -log(0.1 / (1-0.1)). This makes the initialization sigmoid(-2.19) = 0.1. Actually this is not a principled hyper-parameter at all. You will find a slight improvement if you use -4.6 (initial value 0.01).

Copy. It's seem like a trick, not a principled hyper-parameter. Thanks for your great works, again.
Btw, I close this issue. Thanks.
