### ISSUE TITLE
 No lr drop in ctdet_coco_hg.sh:    learning rate 2.5e-4 for 50 epochs with 10× learning rate dropped at the 40 epoch.

### ISSUE THREAD

**Issue by sisrfeng** [xingyizhou/CenterNet#829]
For Hourglass-104, we follow ExtremeNet [61] and use batch-size 24 (on 5 GPUs, with master GPU batch-size 4) and learning rate 2.5e-4 for 50 epochs
with 10× learning rate dropped at the 40 epoch.

https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/experiments/ctdet_coco_hg.sh#L3

opts.py: 
--lr_step', type=str, default='90,120'

Any mistake?

Thx!

**Comment by xingyizhou** [comment]
Thanks! You are correct, this should be `--num_epoch 50 --lr_step 40`
