### ISSUE TITLE
Transfer learning using model zoo models

### ISSUE THREAD

**Issue by deandiakov** [xingyizhou/CenterNet#83]
When training models on our own dataset, is there a way to use the base models you have provided as a checkpoint for transfer learning, or do they have to all be trained from scratch with massive datasets?

**Comment by xingyizhou** [comment]
You can directly `--load_model /path/to/a/pretrained/model`.

**Comment by deandiakov** [comment]
> You can directly `--load_model /path/to/a/pretrained/model`.

Thank you. On a further note, is there a specific way to run demo.py after training our own custom model? I'm doing basic object detection, and I provide the demo with the model generated from our experiment folder, and I point it to our custom dataset, but the inferences that are generated seem to be completely random and still using labels from the original COCO dataset. When I run the training through the debugger, I can see that even after an epoch, the predictions it provides on my evaluation set are already pretty decent and correctly labeled. This is what leads me to believe I'm running the demo incorrectly somehow.

**Comment by PeterVennerstrom** [comment]
In debugger.py line 44 it picks up coco names if you're using the coco dataset.  (it defines the coco names around line 445)

I added my own names and added an extra elif statement.  This required renaming my custom dataset to something besides coco.  

I also had to adjust def init in opts.py line 338 to match my class number and the new dataset name.

**Comment by deandiakov** [comment]
> In debugger.py line 44 it picks up coco names if you're using the coco dataset. (it defines the coco names around line 445)
> 
> I added my own names and added an extra elif statement. This required renaming my custom dataset to something besides coco.
> 
> I also had to adjust def init in opts.py line 338 to match my class number and the new dataset name.

Yep, ctdet was still defaulting to coco and 80 classes in opts.py, changing that solved my issue. Thanks!

**Comment by chensonglu** [comment]
@PeterVennerstrom great!!!
