### ISSUE TITLE
confusion about expanding reg_kps and hm_kps to BJKK2 in lib.models.decode.multi_pose_decode

### ISSUE THREAD

**Issue by SophiaSarah** [xingyizhou/CenterNet#831]
When I read the code in decode.py multi_pose_decode, I'm confused about the expandsion of reg_kps and hm_kps. 
![image](https://user-images.githubusercontent.com/26705571/95575395-3b6c7080-0a61-11eb-9d88-767a8e8ab522.png)
![image](https://user-images.githubusercontent.com/26705571/95575381-31e30880-0a61-11eb-8b81-650b80e4323a.png)

Will the results of calculating min_dist (BJK) differ using BJKK2 from BJK2? The expanding operartion only replicates the top k predictions, and dist will only be calculated between one by one according the order of sort not the conbination of top k of hm_kps and top k of kps. Am I right or have I missed something?

**Comment by xingyizhou** [comment]
Hi,
  Sorry, I didn't understand the question. The matching is between each pair of regression points and heatmap peaks (K * K). What do you mean by "Will the results of calculating min_dist (BJK) differ using BJKK2 from BJK2?"?

**Comment by SophiaSarah** [comment]
> Hi,
> Sorry, I didn't understand the question. The matching is between each pair of regression points and heatmap peaks (K * K). What do you mean by "Will the results of calculating min_dist (BJK) differ using BJKK2 from BJK2?"?

Thank you for replying. I think I get what you mean. Thanks again.
