### ISSUE TITLE
Question about losses.py

### ISSUE THREAD

**Issue by white2018** [xingyizhou/CenterNet#84]
@xingyizhou Excellent work!

I have a question in losses.py.  

def _neg_loss(pred, gt):
  ''' Modified focal loss. Exactly the same as CornerNet.
      Runs faster and costs a little bit more memory
    Arguments:
      pred (batch x c x h x w)
      gt_regr (batch x c x h x w)
  '''
  pos_inds = gt.eq(1).float()
  neg_inds = gt.lt(1).float()

I can see the pos_inds means all the center-points in ground-truth heatmap. However, neg_inds represents all the other points in the gt heatmap. 

My question is whether the points which are equal to zero should be excluded from neg_inds? 

BTW, is there any problem about the following heatmap?
![image](https://user-images.githubusercontent.com/26728432/57969292-1973d900-79a8-11e9-8cc6-2d1c0e58940a.png)

Looking forward to reply!
Thanks a lot

**Comment by xingyizhou** [comment]
1. The zeros in heatmap are **included** in the neg_inds.
2. The shape looks good. Why is the tv heatmap not isotropic?

**Comment by white2018** [comment]
> 1. The zeros in heatmap are **included** in the neg_inds.
> 2. The shape looks good. Why is the tv heatmap not isotropic?

Regarding the second question, the right side image is the overlapped consequence of origin image and heatmap, which I suppose leads to be not isotropic.
