### ISSUE TITLE
Coco Folder Structure

### ISSUE THREAD

**Issue by PeterVennerstrom** [xingyizhou/CenterNet#85]
/src/lib/datasets/dataset/coco.py 

The paths in the code are missing the folder 'images' which is included in the instructions.  

e.g. line 24 in coco.py:

self.img_dir = os.path.join(self.data_dir, '{}2017'.format(split))

self.img_dir = os.path.join(self.data_dir, 'images', '{}2017'.format(split))

Great work! Thanks

**Comment by xingyizhou** [comment]
Thanks! We will fix readme soon.
