### ISSUE TITLE
eval unnormal result

### ISSUE THREAD

**Issue by huang45** [xingyizhou/CenterNet#86]
hi, I trained my own dataset by converting to coco format. It works well by following:  
`python demo.py ctdet --demo /home/data/coco/images/val2017/ --load_model ../models/model_last.pth  `
but when I tried to do the evaluation:
`python test.py ctdet --exp_id coco_dla_2x --keep_res --load_model ../models/model_last.pth `
I got wrong result:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

I found some lines in the result. Is it normal to get a minus bbox?
{"image_id": 51, "category_id": 15, "bbox": [1588.14, 92.34, **-0.59**, 42.57], "score": 0.98}, 

Appreciate if someone could help by this.

**Comment by xingyizhou** [comment]
It is possible to generate a minus coordinate, if the offset prediction is negative, even though it has never been supervised as negative. According to your testing commend, you haven't specified `--dataset`, so it will evaluate on COCO by default. You can also add `--debug 2` when running `test.py` to visualize the results.

**Comment by huang45** [comment]
Yes it is. I fixed this by modifying test.py and coco.py according to my own format.  
thanks for your reply.
