### ISSUE TITLE
about dense_reg

### ISSUE THREAD

**Issue by dongzhuoyao** [xingyizhou/CenterNet#87]
Hi, Xingyi:

 I am trying to transfer your code to my task.

I see that you also consider dense_reg(you only use reg in your paper though).

Could you tell me is there any result difference between reg and dense_reg?

I tried to **directly** use reg for wh(no sigmoid for prediction, no rescale for ground truth), but the "wh reg" didn't converge....

**Comment by xingyizhou** [comment]
I only tried it on pascal voc, and it doesn't work, with <40 mAP for weights 0.01 or 1.

**Comment by dongzhuoyao** [comment]
Thanks
