### ISSUE TITLE
Are offset inference is easy and accurate?

### ISSUE THREAD

**Issue by hellojialee** [xingyizhou/CenterNet#871]
Hi, I added offset refinement in my own project but found that the offset failed to bring about precision improvement. It seems that the offset branch is not easy to work well. Could someone give me a hint? Thanks!

**Comment by antoinekeller** [comment]
Hi, I have the same issue for my project where I am trying to detect sports balls. It seems that the offset loss is way too small in comparison to the modified focal loss for the main heatmap, and it doesnt bring any improvements in terms of localization accuracy. Any idea on how to solve this?

**Comment by hellojialee** [comment]
In my attempt, it is not easy and accurate. I have tried to merge the nearby offsets according to scores but no improvement achieved. Here is my code to try:
https://github.com/hellojialee/OffsetGuided/blob/a710d632bca58aec55cf04ce9d71176b17318f50/decoder/offset.py#L8
