### ISSUE TITLE
about optimum resolution

### ISSUE THREAD

**Issue by westpilgrim** [xingyizhou/CenterNet#88]
I found the default resolution of the dla multi pose model input is 512 * 512, but my training image is 1600 * 1300 ,if I use the default resolution ,I am afraid there may be accuracy drop when I use this model to test on another dataset(with different resolution), because the aspect ratio changed .if I use the training dataset resolution ,my gpu memory is not so large ,so how to deal with this problem?does aspect ratio change affect final test accuracy?

**Comment by xingyizhou** [comment]
The network never changes the aspect ratio. It will resize the longer side to 512 and pad 0 to the shorter side. Both sides of the resolution need to be dividable by 32 (for dla/ resnet, and 128 for hourglass). You will need to select a good resolution your self.

**Comment by westpilgrim** [comment]
ok

**Comment by suyeH** [comment]
> Both sides of the resolution need to be dividable by 32 (for dla/ resnet, and 128 for hourglass).
Hi, I am confused about this, why  the resolution need to be dividable by 32? The backbone network down-sampled the input image by a factor 4, so I believe that dividable by 4 is enough, why 32 necessary?

**Comment by suyeH** [comment]
> Both sides of the resolution need to be dividable by 32 (for dla/ resnet, and 128 for hourglass).

Hi, I am confused about this, why  the resolution need to be dividable by 32? The backbone network down-sampled the input image by a factor 4, so I believe that dividable by 4 is enough, why 32 necessary?
