### ISSUE TITLE
cv2 error at demo.py

### ISSUE THREAD

**Issue by sounansu** [xingyizhou/CenterNet#89]
Hi. I try to inference by ctdet_coco_dla_2x.pth
<pre>
python demo.py ctdet --demo 20150207_0.mp4 --load_mode ../models/ctdet_coco_dla_2x.pth

tot 0.057s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.058s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.058s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.058s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.058s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.056s |load 0.000s |pre 0.007s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.056s |load 0.000s |pre 0.007s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.007s |net 0.019s |dec 0.001s |post 0.030s |merge 0.000s |
tot 0.055s |load 0.000s |pre 0.006s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.058s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.058s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.007s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.058s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.056s |load 0.000s |pre 0.007s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.056s |load 0.000s |pre 0.007s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.056s |load 0.000s |pre 0.007s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.058s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.058s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.056s |load 0.000s |pre 0.007s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.056s |load 0.000s |pre 0.007s |net 0.019s |dec 0.001s |post 0.029s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.008s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
tot 0.057s |load 0.000s |pre 0.009s |net 0.019s |dec 0.001s |post 0.028s |merge 0.000s |
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 29, in demo
    cv2.imshow('input', img)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/highgui/src/window.cpp:352: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
</pre>

I use remote Ubuntu machine and Xserver running at windows10 machine.

And. I want to save image to movie file.
Has anyone ever tried it?

**Comment by xingyizhou** [comment]
It seems there is a problem with your video. Does it work for other videos? You can search `opencv save video` for saving images to movie file.

**Comment by sounansu** [comment]
> Does it work for other videos?

Yes,Yes.
I will try 
> You can search opencv save video for saving images to movie file.

Thank You!
