### ISSUE TITLE
Evaluation result AP=0; During the training process, train_loss decreases and val_loss increases

### ISSUE THREAD

**Issue by jueqiang** [xingyizhou/CenterNet#910]
I trained my own dataset using CenterNet. During the training process, train_loss decreases, and val_loss increases. I have referred to the solutions in #148 but the issue still exists. I also find issues during the testing process, the evaluation result AP=0. Can someone give me some suggestions on how to solve these issues?
python main.py ctdet --exp_id coco_dla_4_26_4 --batch_size 16 --lr 1e-4  --gpus 0,1
python test.py --exp_id coco_dla_4_26_4 --not_prefetch_test ctdet --load_model ../exp/ctdet/coco_dla_4_26_4/model_best.pth

**Comment by toastedbaguatte** [comment]
Hey hello, I noticed that you have closed this issue as completed. May I ask, were you able to solve the issue? Thank you!
