### ISSUE TITLE
how to solve dont care in my dataset,which cannot be converted to coco style?

### ISSUE THREAD

**Issue by qiuhaining** [xingyizhou/CenterNet#92]

**Comment by xingyizhou** [comment]
What I did for the ignored samples in KITTI (https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/sample/ddd.py#L114) is to set the ignored positive location to `1 - eps` so that it is not supervised as positive, but gives very little penalty when predicted as positive.
