### ISSUE TITLE
poor performance using ctdet_coco_resdcn18.sh

### ISSUE THREAD

**Issue by qiuhaining** [xingyizhou/CenterNet#93]
![image](https://user-images.githubusercontent.com/23293902/58390049-bc3fed80-8061-11e9-98c0-a864b752b7be.png)

**Comment by joyyang1215** [comment]
There are no object popped out when using ctdet_coco_resdcn18 pre-trained weights.

**Comment by kimyoon-young** [comment]
> There are no object popped out when using ctdet_coco_resdcn18 pre-trained weights.
Hi. In my case, I added --arch argument with 'resdcn_18' because a default architecture is 'dla_34'

python demo.py ctdet --demo webcam --load_model ../models/ctdet_coco_dla_2x.pth **--arch resdcn_18'**

**Comment by joyyang1215** [comment]
OK, thanks. It works.
