### ISSUE TITLE
test.py UnboundLocalError

### ISSUE THREAD

**Issue by JehanJay** [xingyizhou/CenterNet#932]
I am getting this Unbound local error when running the test.py. I couldn't find any errors in the scripts.
![Screenshot from 2021-07-22 10-46-54](https://user-images.githubusercontent.com/41586782/126612912-d48452bd-aefe-497d-8923-b0d8fed7c920.png)
@xingyizhou any idea what this is?

**Comment by nnuk** [comment]
Hi, 

Exactly the same issue. How did you solve that? 
Thanks.
