### ISSUE TITLE
cuda runtime error (30): unknown error 

### ISSUE THREAD

**Issue by maverick-fyp** [xingyizhou/CenterNet#933]
issue raised when GPU runs at 100% and RAM 7580/7980

**Comment by maverick-fyp** [comment]
solved by the below:
https://discuss.pytorch.org/t/resolved-cuda-runtime-error-30/1116
https://github.com/tensorflow/tensorflow/issues/5777#issuecomment-301058363
command:
sudo rmmod nvidia_uvm
sudo rmmod nvidia                             #(this cannot run idk why)
sudo modprobe nvidia
sudo modprobe nvidia_uvm                 #(this cannot run idk why)
training   "--resume" finally can work at last

**Comment by yktangac** [comment]
I have the same issue with demo.py
