### ISSUE TITLE
【Two situations】When compiling DCNv2: (1) "collect2: fatal error: cannot find 'ld' compilation terminated." (2) unable to execute 'x86_64-conda_cos6-linux-gnu-gcc': No such file or directory.

### ISSUE THREAD

**Issue by Haonan-Qin** [xingyizhou/CenterNet#94]
I tried to run the code in two different environment but failed.
BTW, my linux environment is offline.

【1】The environment is:
(0) Ubuntu 16.04
(1) Anaconda python 3.6.2 (GCC 7.2.0)
(2) PyTorch 0.4.1
(3) gcc -v --> 5.4.0
(4) CUDA 9.0.176
【ERROR】：
building '_dcn_v2' extension
creating home
creating ...
creating .../CenterNet-master/src/lib/models/networks/DCNv2/src
x86_64-conda_cos6-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -DWITH_CUDA -I/home/qinhaonan/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/qinhaonan/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/qinhaonan/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/opt/anaconda3/include/python3.6m -c _dcn_v2.c -o ./_dcn_v2.o -std=c99 -fopenmp -std=c99
x86_64-conda_cos6-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -DWITH_CUDA -I/home/qinhaonan/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/qinhaonan/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/qinhaonan/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/opt/anaconda3/include/python3.6m -c /home/qinhaonan/Algorithm/CenterNet/CenterNet_01/CenterNet-master/src/lib/models/networks/DCNv2/src/dcn_v2.c -o ./home/qinhaonan/Algorithm/CenterNet/CenterNet_01/CenterNet-master/src/lib/models/networks/DCNv2/src/dcn_v2.o -std=c99 -fopenmp -std=c99
x86_64-conda_cos6-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -DWITH_CUDA -I/home/qinhaonan/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/qinhaonan/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/qinhaonan/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/opt/anaconda3/include/python3.6m -c /home/qinhaonan/Algorithm/CenterNet/CenterNet_01/CenterNet-master/src/lib/models/networks/DCNv2/src/dcn_v2_cuda.c -o ./home/qinhaonan/Algorithm/CenterNet/CenterNet_01/CenterNet-master/src/lib/models/networks/DCNv2/src/dcn_v2_cuda.o -std=c99 -fopenmp -std=c99
x86_64-conda_cos6-linux-gnu-gcc -pthread -shared -Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now -Wl,-rpath,/opt/anaconda3/lib -L/opt/anaconda3/lib -Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now -Wl,-rpath,/opt/anaconda3/lib -L/opt/anaconda3/lib ./_dcn_v2.o ./home/qinhaonan/Algorithm/CenterNet/CenterNet_01/CenterNet-master/src/lib/models/networks/DCNv2/src/dcn_v2.o ./home/qinhaonan/Algorithm/CenterNet/CenterNet_01/CenterNet-master/src/lib/models/networks/DCNv2/src/dcn_v2_cuda.o /home/qinhaonan/Algorithm/CenterNet/CenterNet_01/CenterNet-master/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu.o /home/qinhaonan/Algorithm/CenterNet/CenterNet_01/CenterNet-master/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.cu.o -L/opt/anaconda3/lib -lpython3.6m -o ./_dcn_v2.so
collect2: fatal error: cannot find 'ld'
compilation terminated.
...
distutils.errors.DistutilsExecError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
...
distutils.errors.LinkError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
...
cffi.error.VerificationError: LinkError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
...

【2】The environment is:
(0) Ubuntu 16.04
(1) Anaconda python 3.6.2 (GCC 7.2.0)
(2) PyTorch 0.4.0
(3) gcc -v --> 4.8.5
(4) CUDA 8.0.61
【ERROR】：
...
./make.sh:行5: nvcc: 未找到命令
./make.sh:行6: nvcc: 未找到命令
./make.sh:行9: nvcc: 未找到命令
./make.sh:行10: nvcc: 未找到命令
...
running build_ext
building '_dcn_v2' extension
...
creating ...CerterNet/CenterNet-master/src/lib/models/networks/DCNv2/src
x86_64-conda_cos6-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fPIC -DWITH_CUDA -I/apps/jhinno/users/IMGLAB/4003/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/apps/jhinno/users/IMGLAB/4003/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/apps/jhinno/users/IMGLAB/4003/.local/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/opt/anaconda3/include/python3.6m -c _dcn_v2.c -o ./_dcn_v2.o -fopenmp -std=c99
unable to execute 'x86_64-conda_cos6-linux-gnu-gcc': No such file or directory
...
distutils.errors.DistutilsExecError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
...
distutils.errors.CompileError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
...
cffi.error.VerificationError: CompileError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
...

**Comment by xingyizhou** [comment]
It seems a cuda installation issue. Please make sure you have installed cuda and pytorch correctly, i.e., can run the nmist example in pytorch examples.

**Comment by zlheos** [comment]
modify enviroment ~/.bashrc
add 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export PATH=$PATH:/usr/local/cuda-10.0/bin
export CUDA_HOME=$CUDA_HOME:/usr/local/cuda
