### ISSUE TITLE
AP is 0 when Iam trying to use CenterNet on transfer learning

### ISSUE THREAD

**Issue by melanih** [xingyizhou/CenterNet#959]
Hello, I hope anyone can help me 😥. This is for my thesis. So, I'am trying to train CenterNet Hourglass with visdrone dataset, and I already train this model for 10 epochs (just trying whether this models ran well or not). This is my code when training the model
`!python main.py ctdet --exp_id coco_hg --arch hourglass --batch_size 8 --master_batch 4 --lr 2.5e-4 --load_model ../models/ExtremeNet_500000.pth --gpus 1 --num_epochs 10 --lr_step 40`

And this is the result :
`ctdet/coco_hg |################################| train: [1][807/808]|Tot: 0:16:37 |ETA: 0:00:02 |loss 1.7558 |hm_loss 1.4503 |wh_loss 1.0548 |off_loss 0.2000 |Data 0.001s(0.003s) |Net 1.235s
ctdet/coco_hg |################################| train: [2][807/808]|Tot: 0:16:33 |ETA: 0:00:02 |loss 1.3881 |hm_loss 1.1306 |wh_loss 0.7342 |off_loss 0.1841 |Data 0.002s(0.003s) |Net 1.229s
ctdet/coco_hg |################################| train: [3][807/808]|Tot: 0:16:33 |ETA: 0:00:02 |loss 1.3076 |hm_loss 1.0604 |wh_loss 0.6780 |off_loss 0.1794 |Data 0.001s(0.003s) |Net 1.230s
ctdet/coco_hg |################################| train: [4][807/808]|Tot: 0:16:33 |ETA: 0:00:02 |loss 1.2595 |hm_loss 1.0194 |wh_loss 0.6388 |off_loss 0.1762 |Data 0.001s(0.002s) |Net 1.230s
ctdet/coco_hg |################################| train: [5][807/808]|Tot: 0:16:33 |ETA: 0:00:02 |loss 1.2208 |hm_loss 0.9846 |wh_loss 0.6159 |off_loss 0.1746 |Data 0.001s(0.002s) |Net 1.230s
ctdet/coco_hg |################################| val: [5][547/548]|Tot: 0:00:44 |ETA: 0:00:01 |loss 1.2102 |hm_loss 0.9709 |wh_loss 0.6758 |off_loss 0.1717 |Data 0.001s(0.006s) |Net 0.081s
ctdet/coco_hg |################################| train: [6][807/808]|Tot: 0:16:33 |ETA: 0:00:02 |loss 1.1949 |hm_loss 0.9635 |wh_loss 0.5937 |off_loss 0.1720 |Data 0.001s(0.003s) |Net 1.230s
ctdet/coco_hg |################################| train: [7][807/808]|Tot: 0:16:33 |ETA: 0:00:02 |loss 1.1679 |hm_loss 0.9390 |wh_loss 0.5817 |off_loss 0.1707 |Data 0.001s(0.002s) |Net 1.229s
ctdet/coco_hg |################################| train: [8][807/808]|Tot: 0:16:33 |ETA: 0:00:02 |loss 1.1482 |hm_loss 0.9213 |wh_loss 0.5725 |off_loss 0.1696 |Data 0.001s(0.002s) |Net 1.229s
ctdet/coco_hg |################################| train: [9][807/808]|Tot: 0:16:32 |ETA: 0:00:02 |loss 1.1266 |hm_loss 0.9023 |wh_loss 0.5589 |off_loss 0.1684 |Data 0.001s(0.003s) |Net 1.229s
ctdet/coco_hg |################################| train: [10][807/808]|Tot: 0:16:33 |ETA: 0:00:02 |loss 1.1084 |hm_loss 0.8868 |wh_loss 0.5457 |off_loss 0.1670 |Data 0.001s(0.003s) |Net 1.229s
ctdet/coco_hg |################################| val: [10][547/548]|Tot: 0:00:39 |ETA: 0:00:01 |loss 1.1456 |hm_loss 0.9164 |wh_loss 0.6262 |off_loss 0.1665 |Data 0.000s(0.001s) |Net 0.073s`

The losses is still really high. Then, I have been change the configuration such us: 

- visdrone.py (adding new configuration, copy paste from coco.py) 
- dataset_factory.py
- debugger.py (to add the dataset class name and the number of my classes)
- opts.py (also changes the number of classes and the name of dataset we are using)

and then I'm trying to evalulate with this code 
`!python test.py ctdet --exp_id coco_hg --keep_res --load_model ../exp/ctdet/coco_hg/model_best.pth`

and got the result like this:
 `Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000`

Iam Using PyTorch 1.4.0 for information and did the reasearch on google colab.
Ur reply is really important for me, Thank you! 🥺

**Comment by ifanshida** [comment]
I also tried to see if I could run the code in collab. But I met the following：

input：
%cd /content/CenterNet/src/lib/models/networks/DCNv2
!./make.sh

output：
/content/CenterNet/src/lib/models/networks/DCNv2
/content/CenterNet/src/lib/models/networks/DCNv2
Traceback (most recent call last):
  File "build.py", line 21, in <module>
    raise ValueError('CUDA is not available')
ValueError: CUDA is not available
Traceback (most recent call last):
  File "build_double.py", line 21, in <module>
    raise ValueError('CUDA is not available')
ValueError: CUDA is not available

I'm just getting started, so I don't know how to modify the code. Can you give me some guidance? Thank you very much !

**Comment by melanih** [comment]
@ifanshida are you sure you are using gpu on your colab?

**Comment by ifanshida** [comment]
Thank you very much for your reply!
As you said, the problem arises here. I built a new notebook, but I forgot to open GPU.
Are you doing 2D target detection? I want to use this network for 3D target detection. If you can, would it be convenient for you to send me a screenshot of the process executed on the collab?
Thank you again!

**Comment by Piyal93** [comment]
AP shows zero when you have more classes than that specified in the JSON file. Can you maybe post a pic while running the test script??

**Comment by melanih** [comment]
coco_hg |################################| [547/548]|Tot: 0:00:40 |ETA: 0:00:01 |tot 0.072s (0.071s) |load 0.000s (0.000s) |pre 0.001s (0.001s) |net 0.068s (0.064s) |dec 0.001s (0.002s) |post 0.002s (0.004s) |merge 0.000s (0.000s) 
Loading and preparing results...
DONE (t=0.32s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=5.51s).
Accumulating evaluation results...
DONE (t=0.62s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

**Comment by alanMachineLeraning** [comment]
how to solve this problem?

**Comment by Piyal93** [comment]
Check the hyper-parameters before running the test script and also if the image path is given properly.
