### ISSUE TITLE
Log files not generating per epoch. Generated ones are empty!! How to fix it??

### ISSUE THREAD

**Issue by Dipankar1997161** [xingyizhou/CenterNet#979]
hey! 
I would get to the question right away.

How can I get log files after every epoch?? I started my training at time A (it's still running )and only at that time the LOg file was generated. After that, no more log files are generated in my "exp" folder.

Also, the generated ones are empty log.txt. 
When using Tensorboard, no graph is plotted either :{

DO I HAVE TO MANUALLY KEEP A TRACK OF THE loss???

Anyone can provide me with a way to produce log file for every epoch?? would be great

**Comment by melaniihariono** [comment]
Can you tell me, how you plot the log :) are you plotting it manually?

**Comment by melaniihariono** [comment]
Oke, thank you!

**Comment by melaniihariono** [comment]
Hello @Dipankar1997161, would you mind to send me your email :( I wanna ask you about GPU problem :( 
if you don't mind..  
Thank you

**Comment by Dipankar1997161** [comment]
@melaniihariono  
Sure, here is my email : dnandi29@gmail.com
